### ISSUE TITLE
앱을 한시간 이후(날씨정보가 갱신됨)에 앱 재 실행시에 화면 갱신이 안됨.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1002]
앱을 한시간 이후(날씨정보가 갱신됨)에 앱을 다시 실행하면 데이터를 가지고 오는 것 같지만 화면이 갱신되지 않음.

reload를 한번 더 눌러주면 그때 화면이 갱신됨.

**Comment by kimalec** [comment]
크롬에서 재현이 됨. applyWeatherData()한 이후에 데이터가 업데이트 되어서 발생하는 증상이 아닌가 함.

**Comment by skywlrl** [comment]
#982 이슈에서 처리됨
