### ISSUE TITLE
시간별 차트에서 현재 온도에 맞게 라인 꺾기

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1022]
현재는 실제온도와 상관없이 현재 시간위치에 점을 찍어 어느정도 위치인지 표시해주고 있다.
실제 데이터를 반영해서, 1,2시, 4,5시 등에서도 정확한 온도를 표시해보자.

**Comment by skywlrl** [comment]
[app.js.zip](https://github.com/WizardFactory/TodayWeather/files/347953/app.js.zip)
테스트 코드가 들어간 app.js 파일이고 작업해야 하는 내용을 "//[modify_" 로 시작하는 주석으로 적어놓았습니다.

**Comment by kimalec** [comment]
#1034 적용하면서 차트 사이 이동이 3칸에서 6칸으로 늘었음. (재조정이 필요할지도..)

**Comment by kimalec** [comment]
간격을 단순하게 0시~3시 사이에 한 포인트만 사용하는 것으로 결정. 
0시1분부터~2시59분까지는 중간에 표시한다.
