### ISSUE TITLE
android image 수정.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1041]
app review에서 아래 사항에 대하여 수정 사항 받았음.

가이드 이미지, 그래픽 이미지(1024*500) 에서 핸드폰 프레임을 안드로이드용으로 변경.
아이콘 이미지를 이모지형태로 변경.

**Comment by kimalec** [comment]
가이드 이미지 5.5인치 안드로이드(파랑바탕 있는거, 없는거), 7인치 안드로이드(태블릿) 파랑바탕있는거.
그래픽 이미지(1024*500)  안드로이드용.

**Comment by kkkiiikkii** [comment]
[160729_가이드 화면(안드로이드).zip](https://github.com/WizardFactory/TodayWeather/files/392224/160729_.zip)
[160729_앱 실행화면 이미지(안드로이드).zip](https://github.com/WizardFactory/TodayWeather/files/392225/160729_.zip)

**Comment by kkkiiikkii** [comment]
![160729_ -01](https://cloud.githubusercontent.com/assets/12652131/17274447/c08b0238-571c-11e6-9273-66945c5b0672.jpg)

**Comment by kimalec** [comment]
튜터리얼뿐만 아니라, 안드로이드용 화면에서 새로운 아이콘이 들어간 이미지로 변경 필요.

**Comment by kimalec** [comment]
안드로이드폰용 스크린샷
[ssnote5screenshot.zip](https://github.com/WizardFactory/TodayWeather/files/429343/ssnote5screenshot.zip)

안드로이드태블릿용 스크린샷은 업데이트 예정.

**Comment by kimalec** [comment]
안드로이드태블릿용 스크린샷
[android_tablet_screenshot.zip](https://github.com/WizardFactory/TodayWeather/files/433887/android_tablet_screenshot.zip)

**Comment by kkkiiikkii** [comment]
[160825_가이드화면 수정(안드로이드).zip](https://github.com/WizardFactory/TodayWeather/files/440662/160825_.zip)
[160825_앱 실행화면 이미지(안드로이드).zip](https://github.com/WizardFactory/TodayWeather/files/440663/160825_.zip)

**Comment by kimalec** [comment]
앱 실행화면 이미지는 큰 사이즈로 첨부해봐주세요. 사이즈 조정을 다른 툴로 해보겠음.

**Comment by kkkiiikkii** [comment]
![160825_ 2-01](https://cloud.githubusercontent.com/assets/12652131/18032214/946ec9ae-6d39-11e6-86dd-9d50438e35ee.jpg)

**Comment by kimalec** [comment]
google play console graphic image 1024x500

![android_1024_500](https://cloud.githubusercontent.com/assets/6895272/18032238/852c1b94-6d3a-11e6-8f99-e7389233da93.jpg)

**Comment by kimalec** [comment]
- [ ]  앱의 제목/로고가 포함되어야 합니다.
- [ ] 큰 글꼴을 사용
- [ ] 로고가 잘 보이도록 프레임의 정중앙에 배치
- [ ] 포함하지 말아야 할 것 : 모든 종류의 단말기 이미지, 앱 스크린샷
