### ISSUE TITLE
새로운 아이콘 제작

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1083]
1.0에 맞추어 새로운 아이콘을 만들자.

**Comment by kimalec** [comment]
http://actualapple.com/ios-vs-android-10-7-0-nougat-comparison-of-interfaces/

android nougat app
<img width="320" src="https://cloud.githubusercontent.com/assets/6895272/18027765/8440f54e-6ca7-11e6-9f88-d4f29f0a7e08.png">

ios10 map icons
<img width="320" alt="2016-08-27 22 26 19" src="https://cloud.githubusercontent.com/assets/6895272/18027773/d02c61f0-6ca7-11e6-815b-19ce30fe0d7c.png">

**Comment by kkkiiikkii** [comment]
![default](https://cloud.githubusercontent.com/assets/12652131/18186147/250628ea-70dc-11e6-8572-b21b49ad57c1.png)

**Comment by kkkiiikkii** [comment]
![default](https://cloud.githubusercontent.com/assets/12652131/18188995/b1e46672-70f1-11e6-979b-6403623cd0bd.png)

**Comment by kkkiiikkii** [comment]
<img width="1148" alt="160909_ 2" src="https://cloud.githubusercontent.com/assets/12652131/18411906/883c0fb4-77bd-11e6-8282-2edfa2d024c8.png">

**Comment by kkkiiikkii** [comment]
![160915_ 2-01](https://cloud.githubusercontent.com/assets/12652131/18606518/87cf6c9e-7ced-11e6-9717-0b72ca70e0b0.jpg)
![160915_ 2-01](https://cloud.githubusercontent.com/assets/12652131/18606517/87ccacc0-7ced-11e6-8ea7-a1a107159ee0.png)
![160915_ 2-02](https://cloud.githubusercontent.com/assets/12652131/18606519/87dadeee-7ced-11e6-90fa-f6c00ef0d6a4.jpg)
![160915_ 2-02](https://cloud.githubusercontent.com/assets/12652131/18606520/87dc5814-7ced-11e6-9874-4d4a66eaf27c.png)

**Comment by kkkiiikkii** [comment]
![160915_ -01](https://cloud.githubusercontent.com/assets/12652131/18607138/f0a7fc98-7cfe-11e6-8303-9012024b701b.png)
![160915_ -02](https://cloud.githubusercontent.com/assets/12652131/18607139/f0e40454-7cfe-11e6-9e0d-067889180662.png)

**Comment by kimalec** [comment]
인기차트에서 앱아이콘 모양
<img width="324" alt="2016-09-19 01 11 09" src="https://cloud.githubusercontent.com/assets/6895272/18620266/ab239ea6-7e49-11e6-9d04-43498ee59f59.png">
<img width="324" alt="2016-09-19 01 11 51" src="https://cloud.githubusercontent.com/assets/6895272/18620269/ab657ab0-7e49-11e6-973b-6d1d32887d5f.png">
<img width="326" alt="2016-09-19 01 12 09" src="https://cloud.githubusercontent.com/assets/6895272/18620268/ab6561e2-7e49-11e6-9c54-68595325e804.png">
<img width="324" alt="2016-09-19 01 12 23" src="https://cloud.githubusercontent.com/assets/6895272/18620270/ab65b462-7e49-11e6-93c9-6d3caa97a14e.png">
<img width="324" alt="2016-09-19 01 12 36" src="https://cloud.githubusercontent.com/assets/6895272/18620271/ab65b3f4-7e49-11e6-810a-c5d80af0dbf5.png">
<img width="325" alt="2016-09-19 01 12 53" src="https://cloud.githubusercontent.com/assets/6895272/18620272/ab666650-7e49-11e6-80bb-673936e71973.png">
<img width="324" alt="2016-09-19 01 25 55" src="https://cloud.githubusercontent.com/assets/6895272/18620267/ab47a90e-7e49-11e6-9663-1062f5ab6b3d.png">
<img width="324" alt="2016-09-19 01 25 55" src="https://cloud.githubusercontent.com/assets/6895272/18620274/ae99c25e-7e49-11e6-909b-981f743d7c9f.png">

**Comment by kimalec** [comment]
원형아이콘과, 옅은 파랑 라운드 아이콘 A/B Test합니다.
<img width="308" alt="2016-09-19 13 27 24" src="https://cloud.githubusercontent.com/assets/6895272/18622621/d466fe3e-7e6c-11e6-884c-6c03a04f19b3.png">

**Comment by kimalec** [comment]
아직 수집 데이터가 부족한 상황이긴 하지만, 판도가 바뀌지는 않을 것으로 보여 옅은 파랑 라운드 박스 디자인으로 적용하도록 하겠습니다.
<img width="706" alt="2016-09-25 13 25 19" src="https://cloud.githubusercontent.com/assets/6895272/18813013/95f4b0b8-8323-11e6-8543-d053b8184961.png">

**Comment by kimalec** [comment]
일주일정도 되면 결과 나오네요. 옅은파랑 승!
<img width="687" alt="2016-09-26 10 17 42" src="https://cloud.githubusercontent.com/assets/6895272/18819851/9ace44dc-83d2-11e6-93d9-37d0d39be687.png">

**Comment by kimalec** [comment]
- [ ] itunes connect에 1024x1024 app launcher icon upload

**Comment by kkkiiikkii** [comment]
![161002_ -03](https://cloud.githubusercontent.com/assets/12652131/19019339/b775c42e-88bf-11e6-9efa-cf3fab406226.png)
![161002_ -03](https://cloud.githubusercontent.com/assets/12652131/19019338/b774db5e-88bf-11e6-9415-c7a5e3fe1106.jpg)

**Comment by kkkiiikkii** [comment]
![161002_ -03](https://cloud.githubusercontent.com/assets/12652131/19019370/a6d01844-88c0-11e6-9f30-b9aebb821e3f.jpg)
![161002_ -03](https://cloud.githubusercontent.com/assets/12652131/19019369/a6ceac3e-88c0-11e6-9ca2-8c633432791b.png)
