### ISSUE TITLE
권한이 없는 경우와 위치 정보를 못 가지고 오는 경우 분리.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1085]
현재는 getCurrentPosition이 실패하는 경우 하나의 팝업으로 처리하지만, error.code를 분리하여

권한이 없는 경우(1) 와 정보를 못 가지고 온 경우(3)을 분리하여, 안내메세지를 분리하자.

**Comment by kimalec** [comment]
초기 설정 중에 꼬이는 문제가 발생함. - 권한 문제인 경우 설정 페이지로 이동 필요함.

**Comment by skywlrl** [comment]
https://github.com/dpa99c/cordova-diagnostic-plugin
https://github.com/dpa99c/cordova-plugin-request-location-accuracy

**Comment by skywlrl** [comment]
#1135 이슈의 아래 두 Comment 관련 작업 포함해서 진행 예정
https://github.com/WizardFactory/TodayWeather/issues/1135#issuecomment-251986201
https://github.com/WizardFactory/TodayWeather/issues/1135#issuecomment-251998050

**Comment by kimalec** [comment]
위치 정보 관련한 것, 주소정보(daum, google api), 날씨 정보 들에 대한 이벤트 카테고리가 모두 data로 되어 있어서 분류하기 쉽게 분리하는게 좋겠어요.

**Comment by skywlrl** [comment]
[시나리오]
1. 처음 실행으로 현 위치 검색을 시도 한 경우
  1) 위치 서비스 On -> 위치 정보를 가져와서 날씨 정보 요청
  2) 위치 서비스 Off -> 위치 서비스 On을 하라고  Error Popup 표시(또는 설정 화면 연결)
2. 재실행으로 현재 위치 검색을 시도 한 경우
  1) 위치 서비스 On -> 위치 정보를 가져와서 날씨 정보 요청
  2) 위치 서비스 Off -> 마지막 검색한 위치에 대한 날씨 정보 요청

**Comment by skywlrl** [comment]
[Android]
- 권한 팝업이 뜰 때 pause 이벤트 발생
- 권한 팝업이 닫힐 때 resume 이벤트 발생
- 설정 창이 뜨고 닫힐 때는 pause, resume 처리되지 않음(App 내에서 설정 Activity가 실행된 것과 동일)
[iOS]
- 권한 팝업이 뜨고 닫힐 때 pause, resume 발생하지 않음

* Android, iOS 둘 다 현재 위치를 background로 요청하고 있음 -> 코드 분리 필요

**Comment by skywlrl** [comment]
* cordova.plugins.locationAccuracy.request 를 사용하지 않는 이유(위치 서비스 설정 화면으로 이동 기능)
https://github.com/dpa99c/cordova-plugin-request-location-accuracy
-> ios에서 취소를 누르면 다시 뜨지 않는 문제가 있음. 체크가 되지 않아 팝업이 떴는지 뜨지 않았는지 알 수 없음.
-> iOS "Cancel" button caveat 참고

**Comment by kimalec** [comment]
- [ ] 현재위치로 날씨 업데이트 이후, 사용자가 임의로 location permission을 disable한 경우, 앱실행시 권한요청이 오지만 거기서 거절후 검색으로 가면 현재위치날씨가 보이지 않아 disable할 수 없음
- [ ] 현재위치 삭제후 날씨탭으로 이동시 현재위치로 시작하기 하면 삭제한 날씨 정보가 나옴.
