### ISSUE TITLE
today extension 에서 과거 데이터가 미리 나오게 개선.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1098]
현재는 시작할때 데이터 가지고 온 이후에 보이는데, 먼저 저장된 데이터로 정보를 보여주고, 갱신하는 형태로 수정.

**Comment by seankim2** [comment]
* viewDidLoad에서 과거 데이터가 있다면(저장된 데이터) unarchive후 UI를 갱신
* 새로운 데이터를 받을 때 UI에 뿌리기 전에 archive
* 데이터가 많지 않으므로 NSKeyedArchiver, NSKeyedUnarchiver 클래스를 이용.
* 기존 weather results(processWeatherResults()) jsonDictionary를 직접 저장
  * 저장시 addr1, addr2, addr3를 비교후 해당 Array index(여러 도시가 존재할시)에 저장이 필요
* unarchive시에도 요청할 도시의 데이터를 아카이빙에서 find후 UI를 갱신해야함

**Comment by seankim2** [comment]
GItHub에 pull request 하기 (기억이 가물가물...)
* 내 repo에서 clone 한다.
 * git clone https://github.com/seankim2/TodayWeather.git
* WizardFactory의 TodayWeather 원격저장소를 로컬에 추가한다.
 * git remote add WizardFactory https://github.com/WizardFactory/TodayWeather.git
* WizardFactory 원격저장소의 내용을 가져온다.	
 * git fetch WizardFactory
* WizardFactory 의 가져온 내용을 로컬 master branch에 merge한다.
 * git merge WizardFacotry/master
* fork된 내 repo에 push 한다.
 * git push origin master
* GitHub에서 Pull Request를 한다.

**Comment by seankim2** [comment]
* gulp sass error 발생 
```

KwangHo-Kim-ui-MacBook-Pro:client mis2010$ gulp sass
[23:24:20] Using gulpfile ~/workjs/TodayWeather/TodayWeather/client/gulpfile.js
[23:24:20] Starting 'sass'...
buffer.js:287
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:287:9)
    at Function.Buffer.from (buffer.js:133:10)
    at new Buffer (buffer.js:112:17)
    at /Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/gulp-minify-css/index.js:91:25
    at CleanCSS.<anonymous> (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/gulp-minify-css/index.js:36:7)
    at CleanCSS.minify (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/clean-css/lib/clean.js:396:14)
    at Object.ImportInliner.process.whenDone (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/clean-css/lib/clean.js:69:25)
    at Inliner.processNext (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/clean-css/lib/imports/inliner.js:83:22)
    at Object.Inliner.process (/Users/mis2010/workjs/TodayWeather/TodayWeather/client/node_modules/clean-css/lib/imports/inliner.js:76:12)
```

* gulp sass error 파행법
 * rm hooks/after_prepare/011_update_config.js 
 * rm -rf plugins/ platforms/
 * ionic state reset
 * npm install;bower install;
 * ionic build ios
 * ionic platform add ios
 * ionic build ios
 * gulp sass
 * ionic serve
 * cd platforms/
 * cp -af ios/ ../../

**Comment by seankim2** [comment]
* platforms 아래의 ios는 widget을 포함하고 있지 않음
* TodayWeather Top 폴더 아래의 ios는 plugin을 포함하고 있으나 www를 포함하고 있지 않아 error가 발생됨
* 어떻게 해야하나??
 * 프로젝트 파일등 모든 파일을 덮어쓰면 widget 관련 내용을 로드 하지 못하됨
 * platforms 아래의 ios가 release 되는 부분인 거 같으니 error가 안되게 fix해야 될 거임

**Comment by seankim2** [comment]
@kimalec TodayWeather/ios/TodayWeather.xcodeproj를 commit해주세여.
처음 clone 한 사람들은 ionic 빌드후에 www 폴더만 복사하면 될 것 같아보이는데...
아니면 ionic 빌드시에 widget이 포함되어야 될 거 같네여...
의견주세여

**Comment by kimalec** [comment]
최신 버전에서 gulp build하면 적절하게 될겁니다. 
다음주에 간단히 미팅하면서 설명드릴께요.

**Comment by seankim2** [comment]
* CityInfo를 기존에 setCityInfo function에서 저장하고 있기에, CityInfo object에 날씨정보를 추가해서 사용
* currentCity의 index에 따라 unarchive된 CityInfo의 weatherInfo를 끄집어 내어 뿌린다.
* setCityInfo내에서 unarchive된 weather dictionary를 processWeatherResults를 통해 draw.
* 새로 얻어진 데이터는 makeJSONWithData 내에서 mCurrentCityIdx를 이용하여 저장이 필요함.
 * 그렇게 하기 위해서는 현재 currentcity의 index인 mCurrentCityIdx도 가지고 있어야함

**Comment by seankim2** [comment]
* load된 userdefault를 이용하여 weather data를 draw하는 부분 구현
* 현재 데이터를 userdefault에 save하는 루틴을 구현하였지만 data 저장 방식을 string이 아닌 nsdata 형식으로 저장하여 init시 error발생
 * 로딩시 알맞는 방식으로 weather data를 변환하여 저장 하거나
 * 아니면 userdefault가 아닌 별개의 file로 관리해야 될 거 같음

**Comment by seankim2** [comment]
* 로딩에 알맞는 방식인 UTF8로 인코딩된 NSString으로 변환 후 Userdefault에 저장 후 error 발생 안됨

> NSString* nssCityList = [[NSString alloc] initWithData:nsdCityList encoding:NSUTF8StringEncoding];

* 이전 데이터가 정상적으로 draw된 후 현재 데이터로 변환되는 걸 볼 수 있으나, 간헐적으로 재 시작시에 저장된 데이터가 아닌 그 이전데이터가 보이는 모습이 보였다가 다시 현재 정보로 갱신되는 상황이 발생되는 거 같음 .. 아닌가... 맥북에 연결후 컴파일 상태로 확인해서 그렇게 보이는 걸지도....
 * 바로바로 갱신이 안되니 테스트의 시간이 걸림. 
 * 맥북에 연결된 상태가 아닌 기기 상태에서 직접 테스트 해봐야겠음
 * 여러개의 도시를 최대 추가 후 테스트가 필요함

**Comment by seankim2** [comment]
* 10개이상 도시를 등록 후 테스트 중 통합대기가 '(null)'로 표시되는 경우가 발생
 * 데이터를 draw시에 데이터가 null 이 아닌 경우만 draw 하게 변경
* 대부분 정상적으로 과거 데이터를 뿌린 후, 현재 data를 draw하나, 간헐적으로 이전 도시의 데이터가 들어오는 경우가 발생됨
 * Async로 데이터를 서버로 부터 데이터를 갱신하는 이유임
 * flag를 두어 요청을 한 도시의 데이터 갱신 및 저장이 끝난 후에 다음 도시에 대한 요청이 가능하도록 수정해야함

**Comment by seankim2** [comment]
* 어떤 도시의 데이터는 상당히 늦게 들어오는 경우가 있음.
 * 그래서 다음 도시들을 처리하는 도중에 이전에 요청된 데이터가 들어와서 처리되는 경우가 생김
* flag를 사용하고, 로딩 indication나 데이터로딩중을 의미하는 문구를 두어 사용자가 인지하게 해야함

**Comment by seankim2** [comment]
* 테스트 중 영하온도에 대한 처리 이슈 수정함
* indicator를 추가하여 사용자에게 오래 걸리는 request에 대해 인지를 시킴
 * 간헐적으로 5초 이상 걸리는 request도 있음(??)

**Comment by seankim2** [comment]
* commit 전 테스트 코드 삭제
* comment 및 소스코드 정리
