### ISSUE TITLE
today extension 업데이트 되지 않는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1099]
한번씩 today extension에 날씨 정보가 안나오는 경우가 있음.

**Comment by kimalec** [comment]
#1112 와 관련 있을듯함.

**Comment by seankim2** [comment]
* 다음키의 limitation으로 인한 이슈 였음
* 아래와 같이 multi key를 사용할 수 있게끔 수정하였음.
** https://github.com/WizardFactory/TodayWeather/pull/1629
