### ISSUE TITLE
FrontEnd와 BackEnd간에 REST API 설계

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#11]

**Comment by kimalec** [comment]
[Richardson 성숙도 모델(Richardson Maturity Model)](http://jinson.tistory.com/190) 입니다.  이번 설계는 level 2 로 진행하겠습니다.

**Comment by kimalec** [comment]
#10 진행후에 논의

**Comment by kimalec** [comment]
현재시간과, 지역정보(시,구,동)를 전달하면, 서버에서 현재시간 기준으로 과거 15개, 미래 15개의 3시간 단위 데이터, 오늘 최고/최대 전달.

상세한 api url과 json object 모양은 @pokers 가 업데이트 해주세요.

**Comment by pokers** [comment]
상세 설계 및 구현 내용은 #59 에서 처리합니다.
