### ISSUE TITLE
GA의 충돌 및 예외 항목에서 검출되는 문제

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1103]
- 안드로이드에서만 발생함
- [x] NullPointerException (@AdMobPlugin:getAdViewSize:185) {main}
  
  -> #791에서 수정
- [x] NullPointerException (@IabHelper:queryPurchases:849) {Thread-913}
  
  -> https://github.com/AlexDisler/cordova-plugin-inapppurchase/issues/52 이슈와 동일하나 해결방법이 없음

**Comment by skywlrl** [comment]
안드로이드 0.9.8 버전에서 추가로 발생함(위젯 추가에 의해 발생한 것으로 보임)
* IllegalArgumentException (@LoadedApk:forgetServiceDispatcher:1156) {main}
* IllegalArgumentException (@WidgetUpdateService:registerLocationUpdates:156) {main}
* NoSuchMethodError (@InAppBrowser$5:run:576) {main}

**Comment by kimalec** [comment]
NoSuchMethodError (@InAppBrowser$5:run:576) {main} -> 이거는 리뷰쓰기 해야 동작하는 부분인듯하네요. ㅠㅠ 리뷰쓰러 갔다가 죽는다면 완전 슬프군요 ㅋ

**Comment by kimalec** [comment]
https://github.com/AlexDisler/cordova-plugin-inapppurchase 는 5개월째 업데이트 되지 않고 있음.
이전에 검토했던 https://github.com/j3k0/cordova-plugin-purchase 재확인 예정.

**Comment by kimalec** [comment]
#1210 에서 plugin 업데이트 되었으므로 본 이슈 close하고 crash마다 개별관리하겠음.
