### ISSUE TITLE
iOS widget 충돌 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1112]
0.9.8에서 iOS용 widget이 들어가면서 충돌 리포트 오고 있음.
<img width="273" alt="2016-09-13 06 15 47" src="https://cloud.githubusercontent.com/assets/6895272/18453310/93a53476-7979-11e6-9884-83c7162602ef.png">

**Comment by kimalec** [comment]
json으로 받은 데이터를 변환할때, json값이 없는 경우에 죽을 수 있음. wsd 의 경우 데이터가 없는 경우가 많음.

**Comment by kimalec** [comment]
itunesconnect에서 충돌보고서 확인하기

**Comment by seankim2** [comment]
* 충돌보고서 찾기 및 사용
 * [https://developer.apple.com/support/debugging/kr/]
* 충돌보고서 보기( apple 가이드)
 * [https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide_ko/Chapters/ImprovingCustomersExperience.html#//apple_ref/doc/uid/TP40016320-CH27-SW3]
* iOS Crash Reporting Tools 소개
 * [http://khanrc.tistory.com/entry/iOS-Crash-Reporting-Tools-%EC%86%8C%EA%B0%9C]
* 충돌보고서 내역이 없으니 생성될 때 까지 code review로 대체해보자

**Comment by kimalec** [comment]
organizer 에서 바로 볼 수 있네요. 

두건은 widget이고, 한건은 todayweather app이네요.

<img width="320" alt="2016-10-19 13 39 22" src="https://cloud.githubusercontent.com/assets/6895272/19505900/a81fa95a-9601-11e6-9045-98280c6e6ba7.png">

**Comment by seankim2** [comment]
* CLConnection 에러에 관한 stackoverflow
 * [http://stackoverflow.com/questions/32698342/crash-on-clconnectionsendmessageinternal]
* 백그라운드에서 stopUpdatingLocation을 하지 않아 생기는 이슈로 보임

**Comment by seankim2** [comment]
* widget에서는 메인 어플리케이션에 있는 백그라운드로 갔을 시 호출되는 function 이 없다.
* widget은 os에 의해서 start후에 stop 되고 kill 되는 구조이다.
* 따라서 view가 사라지는 시점인 viewDidDisappear 함수에서 stopUpdatingLocation을 하면 될 것으로 보인다.
```
- (void)viewDidDisappear:(BOOL)animated
{
    [super viewDidDisappear:animated];
    NSLog(@"view did disappear");

    NSLog(@"stopUpdatingLocation !!!");
    [locationManager stopUpdatingLocation];
}
```

**Comment by seankim2** [comment]
* 20일 충돌 6건...
  * organizer>crashes에는 0.9.17, 0.9.20, 0.9.21에서 나타나고 있지 않음
  * 좀 더 기다려야 report가 올라올 것으로 예상되거나, 0.9.15에서 생성된 crash(stopUpdatingLocation 부재로 인한) 일 수 있음

**Comment by kimalec** [comment]
@seankim2 확인 감사합니다. 최신버전에서 발생하지 않으면 검토할 필요 없을 것 같습니다.

**Comment by seankim2** [comment]
* crashes에 history 확인
** saveWeatherInfo function 내의 setObject function에서 crash
*** 서버로 부터 값을 못 얻어올때를 대비하여 setObject에 대한 nil(null) 체크 추가함

**Comment by seankim2** [comment]
* processPrevData function 내부에서 나는 widget crash
  * objectAtIndex funcion 호출시에 나는 에러
    * mCityDictList 가 null 일 경우 체크
    * idx가 mCityDictList array 배열과 같거나 클경우는 return 처리 해야함.

**Comment by seankim2** [comment]
* CLConnection 에러에 대해서는 stopUpdatingLocation 처리 이외에도 추가적은 처리가 더 필요해 보임

**Comment by kimalec** [comment]
21일 어제 충돌이 많이 발생했었습니다.
어제 데이터 오류가 있었던거 같은데, 검토때 체크해봐주세요.

![2016-12-22 21 29 18](https://cloud.githubusercontent.com/assets/6895272/21425994/ca937c80-c88f-11e6-9fe1-a9d02e3a0a4e.png)

**Comment by seankim2** [comment]
* 21일에 나타난 에러가 24개로 위 그래프와는 차이가 있음
  * 24개 모두 processWeatherResults 함수 내에 나는 에러임
  * 그런데 21일에만 왜 갑자기 에러가 확 늘어난 것일까?
     * new 소프트웨어인 iOS 10.2 문제일까?
     * 데이터를 parsing해서 display하는 부분인데, 서버 데이터가 변경되어 생기는 문제일까?
  * ShowMore 기능에서는 현재 코드가 processWeatherResultsShowMore로 함수 변경 될 것임
  * 함수 내에 취약코드가 있는지 한번더 확인 필요
  * 아직 집계가 다 안된 것인지 내일 한번 더 확인이 필요함

**Comment by seankim2** [comment]
* 다시 확인해 보니 10.0.3 (14A551) 에서 나타난 에러임
* 10.2에서 나타난 에러는 아님

**Comment by kimalec** [comment]
21일에 서버에서 데이터오류가 있었습니다. 데이터 오류 문제라면 추가 디버깅은 안해도 됩니다.

**Comment by seankim2** [comment]
* 수정된 processWeatherResultsShowMore 함수내 null 체크 강화
  * 각 파싱 될 데이터들에 강제로 nil 값 입력 후 에러 유무 확인

**Comment by seankim2** [comment]
* CLLocation sendMessageInternal crash 관련 구글링 후 아래와 같은 이슈 가능성도 있음
```
When the application entered the foreground, the CLLocationManager was re-initialized, without first stopping the old instance. Two bits of code:
```
* 따라서 CLLocationManager instance alloc시 nil일시에는 init을 하지 않도록 수정
