### ISSUE TITLE
loading time 개선 2차

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1130]
앱 초기 로딩 속도가 너무 느립니다. 더 가볍게 할 수 없나요. 
data get 시에 6252ms 걸리는 경우가 있음.
그 당시 서버에서 데이터 전송은 200ms에 전달했음.
#805

**Comment by kimalec** [comment]
현재위치 정보를 늦게 받아서 발생하는 문제는 아님.
부팅후에 자동 업데이트 하는 것으로 좀 더 늦게 시작하는 것을 고려해봐야 할듯함.

**Comment by kimalec** [comment]
- [ ] SplashScreen 내려가는 시점 조절

**Comment by kimalec** [comment]
ios에서는 수동hide보다 오히려 자동 hide가 더 빠른듯함.

**Comment by kimalec** [comment]
4.4 에서 로딩중에 아래와 같은 메세지나오고 있음.
관련하여 검토 중
```
09-29 15:24:41.200 27680-27680/net.wizardfactory.todayweather D/JsMessageQueue: Set native->JS mode to OnlineEventsBridgeMode
09-29 15:24:46.380 27680-27680/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(1185)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1185)
```

**Comment by kimalec** [comment]
android의 경우 delay 없이 자동으로 splash hide하면 처음부터 나타지 않음.
deviceready에서 hide하면 페이지 로딩상태와 상관없이 splash가 사라지고, main page가 보이게 됨.
ios의 경우 auto hide가 약간 더 빠른 느낌이 있고, 데이터 전송여부에 따라 차이를 보이는듯함.

**Comment by kimalec** [comment]
속도최적화를 위해서 deviceready가 되기 전에 여러가지 작업을 하도록 하였는데, 이것이 오히려 deviceready를 방해하는 상황이 되었음.
js쪽 모든 작업을 device ready 이후로 변경하니 평균 7.47 걸리는 것이 4.29만에 끝남.
기존 코드에서 device ready에 맞게 동작하게 수정하면 될것으로 보임.

기존에 ready까지 5초 timeout발생하던 것이 2.2초에 ready가 종료됨. 
```
09-29 17:16:46.102 14641-14641/net.wizardfactory.todayweather D/JsMessageQueue: Set native->JS mode to OnlineEventsBridgeMode
09-29 17:16:48.452 14641-14641/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(1493)] "device ready services.js!!!", source: file:///android_asset/www/js/services.js (1493)
```

**Comment by kimalec** [comment]
@skywlrl 소스 각각에서 ready에 callback을 걸어서 필요한 상황을 초기화하다 보니, 순서를 보장하지 못하는 문제가 있어요. 한군데에서 스케줄하여 순차적으로 실행시켜주어야 할꺼 같은데, 이부분 같이 고민해주세요.

**Comment by kimalec** [comment]
A7의 경우 android 6.0.1로 위와 같은 plugin 병목현상은 없음.
다만 자체성능이 낮은듯함.
위에 수정 사항으로 splashscreen 사라지기까지, 4.28에서 4.03으로 약간 줄었지만, 데이터까지 완전 로딩하는데까지는 8.37에서 8.60초로 조금 늘어났음.
5회만 테스트 한 것으로 차이 없다고 볼 수 있음.

**Comment by kimalec** [comment]
$stateChangeStart event 를 platform ready로 들어오니 "도시를 추가해주세요" 에러 문구가 나옴.
TabCtrl의 doTabForecast도 ready후로 변경해도 "도시를 추가해주세요"라는 문구가 나오는걸봐서는 loadCities가 늦어서 발생하는 것으로 보임.

$stateChangeStart event 는 구조 개선하면서 수정해야 할 것 같음.

좀 복잡아지는데 최적의 성능을 낼려면, 레이아웃은 같은 것은 ready전부터 시작하고, 데이터 관련은 후에 하던지 아니면 모두 ready 이후에 하던지 알아보고 구조 개선해야 할 것으로 보임.

**Comment by skywlrl** [comment]
$stateChangeStart event 를 platform ready로 감싸지 말고 아래 코드와 같이 확인 부탁드립니다.
```
.run(function($ionicPlatform, Util, $rootScope, $location, WeatherInfo) {
     $ionicPlatform.ready(function() {
          $location.path('/tab/forecast'); // 첫 페이지 로드 요청
     }
}
$rootScope.$on('$stateChangeStart', (event, toState, toParams, fromState, fromParams) {
     if (!deviceReady) {
          event.preventDefault(); // 페이지 전환 막음
     } else {
          // 기존 처리 코드
     }
)
```

**Comment by kimalec** [comment]
iPhone 6+에서도 오랜 시간 이후에 실행하면 6초이상 걸림.  실제 문제인지 핸드폰 문제인지 좀 더 확인 필요.

**Comment by kimalec** [comment]
@skywlrl 
첫페이지 로드가 config의 otherWise에 의해서 이동하는데, app.js의 run 경로설정이 의미가 없지 않을까요? (아래코드 참고)
app.js line 1121
```js
        // if none of the above states are matched, use this as the fallback
        $urlRouterProvider.otherwise('tab/forecast');
```
또 push notification click시와 deep link의 경우 url를 직접 설정하기 때문에 문제되지 않을까 싶어요.

**Comment by kimalec** [comment]
추후 device ready이후 controller, services, 등이 순서보장하여 초기화 하는 부분 필요. - 베타 및 릴리즈후 이슈 봐서 진행.

**Comment by kimalec** [comment]
noplugin (3.2, 3.6, 3.3, 3.3, 3.2) - 가이드 페이지
noplugin has index 0 (4.7,  5.2, 4.1, 4.5, 4.4) - 현재위치 잡아서 데이터 저장후
whitelist, console(4.3, 4.2, 3.9, 3.6, 4.1) - 현재위치와 정상적으로 데이터 가지고 오는 경우.

[plugin_loading_time.log.zip](https://github.com/WizardFactory/TodayWeather/files/535497/plugin_loading_time.log.zip)

**Comment by skywlrl** [comment]
#987에 추가한 아래 Comment는 여기서 검토하기로 함
http://stackoverflow.com/questions/27300583/how-to-deviceready-in-right-way-in-ionic-application

**Comment by kimalec** [comment]
http://www.slideshare.net/infect2/angularjs-ionic-cordova-syrup-store-app - dom 관련 최적화 확인

**Comment by kimalec** [comment]
#1219 적용후 속도
S3 - 2.8, 2.9, 2.8, 2,9, 2.8
```
10-24 10:21:31.586 11930-11930/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-24 10:21:34.381 11930-11930/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
```
10-24 10:22:58.551 14031-14031/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-24 10:23:01.461 14031-14031/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
```
10-24 10:24:07.336 15908-15908/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-24 10:24:10.166 15908-15908/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
```
10-24 10:25:20.976 17697-17697/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-24 10:25:23.266 17697-17697/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
```
10-24 10:26:23.341 19366-19366/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-24 10:26:26.101 19366-19366/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```

**Comment by kimalec** [comment]
- [ ] #1219 적용하면 다른 곳에서 device ready에 대한 고려가 필요없을 것 같은데 확인 필요.

**Comment by kimalec** [comment]
- [ ] device ready 뒤로 뺀것도 다시 돌려도 될거 같음 스테이트 정리하면서 필요한 건 돌릴예정.

**Comment by kimalec** [comment]
- [ ] ionic serve 로 실행시에 동작하지 않음.

**Comment by skywlrl** [comment]
ionic serve 로 실행시에 동작하지 않는 문제는 디버깅할 때만 필요하기 때문에 <body>에서 ng-app을 추가해서 사용하기로 함
