### ISSUE TITLE
현재 위치가 아닌 도시의 날씨 데이터를 가져오지 못하는 문제

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1135]
**안드로이드 리뷰**
> 현재위치사용안하는데앱에들어가서지역변경하면계속현재위치를확인할수없다고 재시도나중에라고나와요

**GA에서 확인 정보**
> GA의 고객 ID : 24e0d515-50b0-458f-8e5b-8e491e2461f2
> 9월 23일 에러 이벤트 정보
- 이벤트 카테고리 : data error
- 이벤트 액션 : get
- 이벤트 라벨 : 창원시,웅동2동(1)
- 이벤트 수 : 1
- 이벤트 값 : 32

**Comment by skywlrl** [comment]
설치 후 '창원시,웅동2동'을 추가하여 재현되는 것을 보았으나 다시 재현 시 발행안함

**Comment by skywlrl** [comment]
현재 위치가 아닌 경우에 데이터 로드가 실패하면 "위치 정보 업데이트를 실패하였습니다."라고 에러 팝업이 뜨고 있음
-> 날씨 정보가 아닌 현재 위치를 가져오는데 실패한 것으로 인식됨

**Comment by kimalec** [comment]
"위치 정보 업데이트를 실패하였습니다." 는 에러 문구 오류 인듯합니다. "날씨 정보 업데이트를 실패하였습니다"라고 표시 해야 할 듯하네요.

controllers.js 754 line 입니다.

**Comment by kimalec** [comment]
문구 조정

**위치정보를 못 가지고 오는 경우(getCurrentPosition)** 

1. Position retrieval timed out.(iOS) - 현재위치를 찾을 수 없습니다.
1. Location services are disabled.(iOS) - 위치정보를 설정해주세요.
1. 작업을 완료할 수 없습니다.(kCLErrorDomain 오류 0.)) - 내용확인예정.
1. Timeout expired - 현재위치를 찾을 수 없습니다.
1. application does not have sufficient geolocation permissions. - 위치정보에 대한 접근권한이 없습니다.

**다음, 구글에서 주소 정보를 못 가지고 오는 경우 (getAddressFromGeolocation)**

1. null - 위치에 대한 정보를 못 가지고 왔습니다.
1. Fail to get address name - 내용확인예정.
1. Fail to find dong address - 오류발생확인
1. ZERO_RESULTS - 내용확인예정

**서버로부터 날씨 정보를 못 가지고 온 경우 (getWeatherInfo)**

1. Fail to get weatherInfo - 날씨정보 업데이트를 실패하였습니다. 내용 세분화 필요.

#1140 #1167 - 관련이슈

**Comment by kimalec** [comment]
**작업을 완료할 수 없습니다.(kCLErrorDomain 오류 0.))**
잘 파악 안됨.
https://analytics.google.com/analytics/web/#report/app-visitors-user-activity/a70746703w108020734p112546834/%3F_.useg%3DuserUpY3Ix8OQ5ORMjKfvQpu3w%26_r.userId%3Dd2ea842f-3329-434a-84ca-c4540fc69fd7%26_r.userListReportStates%3D%3F_.useg%3DuserUpY3Ix8OQ5ORMjKfvQpu3w%26_r.userListReportId%3Dapp-visitors-legacy-user-id/

**Fail to get address name, Fail to find dong address**
해외에서 현재위치날씨 조회하면 발생함.

**ZERO_RESULTS**
10/3 9:1 
[galog](https://analytics.google.com/analytics/web/#report/app-visitors-user-activity/a70746703w108020733p112546833/%3F_.useg%3DuserwW3smw0nQuWDVakmWfUtRA%2Cuser-uI4VB8HSNSxID0EqBmiUQ%26_r.userId%3Dddbb1d90-7c12-4cc2-ae30-45ff7fb17c71%26_r.userListReportStates%3D%3F_.useg%3DuserwW3smw0nQuWDVakmWfUtRA%2Cuser-uI4VB8HSNSxID0EqBmiUQ%2526_r.activeSegmentId%3Duser-uI4VB8HSNSxID0EqBmiUQ%26_r.userListReportId%3Dapp-visitors-legacy-user-id%26activity-userActivityTable.activityTypeFilter%3DAPPVIEW%2CGOAL%2CECOMMERCE%2CEVENT%26activity-userActivityTable.sorting%3Ddescending%26activity-userActivityTable.rowShow%3D500/)

**Comment by kimalec** [comment]
@skywlrl 
- [ ] 문구 수정에 대한 의견 주세요. 문구 정리되면 PR하겠습니다.

**Comment by skywlrl** [comment]
**다음, 구글에서 주소 정보를 못 가지고 오는 경우 (getAddressFromGeolocation)**
위치에 대한 정보를 못 가지고 왔습니다. -> 현재 위치 정보를 가져오지 못하였습니다.

**서버로부터 날씨 정보를 못 가지고 온 경우 (getWeatherInfo)**
날씨정보 업데이트를 실패하였습니다. -> 날씨 정보를 가져오지 못하였습니다.

**Comment by skywlrl** [comment]
[재현 경로]
Push 메시지를 통해 App이 실행된 경우 fav 값이 설정되어 전달되는데 해당 값이 숫자가 아닌 스트링으로 처리되어 좌, 우 버튼 클릭으로 도시 변경 시 CityIndex가 잘못된 값으로 설정되어 발생함
1. 추가된 즐겨찾는 도시가 3개
2. 첫번째 도시의 Push 발생. fav="1"로 App 실행
3. 이전 도시로 Swipe 시에 fav=3이 아닌 fav=0으로 도시 정보를 가져오고 있음
