### ISSUE TITLE
서버에서 응답이 200ms인데 Client에서 6000ms만에 응답 받는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1140]
해당 케이스 오전 12시 8분
https://analytics.google.com/analytics/web/#report/app-visitors-user-activity/a70746703w108020733p112546833/%3F_u.date00%3D20160917%26_u.date01%3D20160926%26_r.userId%3D109f733b-1bd7-48d9-8200-5fb1bd49fc49%26_r.userListReportStates%3D%3F_u.date00%3D20160917%2526_u.date01%3D20160917%2526explorer-table.plotKeys%3D%5B%5D%2526explorer-table.rowStart%3D0%2526explorer-table.rowCount%3D5000%26_r.userListReportId%3Dapp-visitors-legacy-user-id%26activity-userActivityTable.activityTypeFilter%3DAPPVIEW%2CGOAL%2CECOMMERCE%2CEVENT%26activity-userActivityTable.sorting%3Ddescending%26activity-userActivityTable.rowStart%3D0%26activity-userActivityTable.rowShow%3D500/

#1130 과 관련 있음.

**Comment by kimalec** [comment]
군산시,나운2동(20:03)
**부산시,당리동(18:49)**
200ms에 응답함.
```
» 27 Sep 2016 18:49:09.951 2016-09-27T09:49:09.844Z info > {"method":"get AllDataFromDb","region":"부산광역시","city":"사하구","town":"당리동"}
» 27 Sep 2016 18:49:10.092 2016-09-27T09:49:10.049Z info ## /v000705/town/부산광역시/사하구/당리동
```
광명시,광명1동(21:15)

**Comment by kimalec** [comment]
**광명시,광명1동(21:15)**
100ms에 응답함.
```
» 27 Sep 2016 21:15:19.748 2016-09-27T12:15:19.673Z info > {"method":"get AllDataFromDb","region":"경기도","city":"광명시","town":"광명1동"}
» 27 Sep 2016 21:15:19.847 2016-09-27T12:15:19.808Z info ## /v000705/town/경기도/광명시/광명1동
```

**Comment by kimalec** [comment]
**군산시,나운2동(20:03)**
서버로 요청 안들어왔음.

- [ ] cloudfont log확인

**Comment by kimalec** [comment]
@skywlrl data get이 보통 얼마만에 받는지 알 수 있을까요? 적당히 짤라서 재시도 하는 방법으로 해야 할꺼 같아서요 예를 들어 1초 타임아웃으로 3번 재시도 하는 벙법

**Comment by kimalec** [comment]
- [ ] cloudfont log확인 : cloudfront에 logging을 안하고 있었음. (비용때문에 off해둔것으로 기억함)

**res의 전송 결과 확인방법**
 res.on('error', ...) 로 볼 수 있을 것 같습니다. Tcp reset등의 이유라면 위 이벤트로 볼 수 있을 것 같네요?!

**Comment by skywlrl** [comment]
최근 30일 기준으로 success time / error time 입니다.
1. weather info : 1.29초 / 3.86초
2. daum address :  0.33초 / 1.77초
3. position : 2.02초 / 5.97초
4. native position : 1.17초 / 5.14초
5. google address	: 0.98초 / 1.25초

**Comment by kimalec** [comment]
express res는 http모듈의 responseServer모듈에 기반을 두고 있습니다.잘 전송되면 finish이벤트를 발생시키고요,말씀하신 timeout도 같은 모듈의 setTimeout도 있습니다. 문서에도 있지만 setTimeout으로 callback을 받을 수 있어서 이 둘을 사용하시면 되겠네요:D

https://nodejs.org/api/http.html#http_class_http_serverresponse

**Comment by kimalec** [comment]
setTimeOut은 server에서 강제 종료하는 것이므로 위험해보이고, event를 체크해야 하는데, close와 finish가 있음.
close의 경우 데이터 준비중에 끊어지는 경우를 event를 받아서 중도 중단 같은 것을 할 수 있으나, 데이터 전후에 제대로 받았는지는 체크하기 힘듬. 그 이유는 finish는 우리가 보낼 데이터를 다 네트워크에 올리면 발생하는 event인데 그 이후에는 response에 대한 event를 받을 수 없음. 

결론 : client에서 좀 더 디테일하게 error상태를 체크해야함.

**Comment by kimalec** [comment]
$http 사용법이 잘 못 되었음.

http://stackoverflow.com/questions/24612855/angular-js-http-error-no-status-return-json

**Comment by kimalec** [comment]
retrycount를 가지고 2초마다 추가로 GET을 던짐.
개선 포인트 - 이미 던져진 retryGet에게 취소 통보 방법 -> 데이터가 2초안에 들어오지 않는 이상 retry는 retrycount만큼 하게 되어 있음.

**Comment by skywlrl** [comment]
**[Http Request 취소 방법]**
http://stackoverflow.com/questions/13928057/how-to-cancel-an-http-request-in-angularjs

**Comment by kimalec** [comment]
앞에 두번 실패하고, 뒤에 3번 성공하는 경우가 있음.
```
services.js:598 retry=5 get http
service.twads.js:52 create banner view
service.twads.js:103 set show ads show=true
service.twads.js:124 set ad mob show =true
service.twads.js:132 show/hide about ad mob show=true
services.js:1476 trackEvent success = Track Event: app
app.js:181 scope watch
services.js:598 retry=4 get http
service.twads.js:195 on banner receive msg={"isTrusted":false,"adType":"banner"}
services.js:598 retry=3 get http
services.js:598 retry=2 get http
services.js:598 retry=1 get http
services.js:610 -1:0
services.js:611 clear timeout = 23
controllers.js:632 finish update weather data
services.js:1502 trackTiming success = Track Timing: data error
services.js:1476 trackEvent success = Track Event: data error
services.js:610 -1:0
services.js:611 clear timeout = 40
services.js:601 status=200
services.js:603 clear timeout = 45
services.js:601 status=200
services.js:603 clear timeout = 50
services.js:601 status=200
services.js:603 clear timeout = 55
```
status codes less than -1 are normalized to zero. -1 usually means the request was aborted, e.g. using a config.timeout.

-1의 경우 무시하고 기달리자.
2초x5 retry말고, 3초x4 retry하자(2초의 경우 서버까지 넘어가는 경우가 있는 것 같음.)
"clear timeout"을 "clear timeoutId"로 변경하자.

**Comment by kimalec** [comment]
서버쪽 로그상에 보면, 데이터를 전송해준 이후에도 cloudfront넘어서 들어오는 경우가 있음.
-1인경우 무시 하는 것과 문구 수정만 진행.

**Comment by kimalec** [comment]
착각했음. -1은 timeOut일때 발생하는데, 첫 http timeout이 10초이고 이시간이 지나면 종료되는 것이 맞음.

**Comment by skywlrl** [comment]
* google mobile 페이지에서 현재 위치 가져오는 코드가 있는 js 파일 첨부
[google.js.zip](https://github.com/WizardFactory/TodayWeather/files/575700/google.js.zip)
> - navigator.geolocation.getCurrentPosition 요청 시 {timeout:3E4,maximumAge:15E3} 속성으로 주고 있음
> - 실패한 경우 google.nav.search을 호출하는데 어떤 기능인지 모르겠음
