### ISSUE TITLE
3시간단위 예보에서 최고/최저 기온이 0으로 오는 문제.

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#118]
3시간 단위 예보에서 최고/최저 기온은 하루 8번의 예보중 한번만 데이터가 넘어오고 나머지는 0이 오는데,
저장시 최고/최저 기온이 0이 아닌 의미있는 값을 저장하게 수정필요.

**Comment by kimalec** [comment]
현재 데이터를 보면, 아침 6시 즉 최저온도일때, mnx가 있고, 15시 최고온도일때만 max값이 있음.

**Comment by kimalec** [comment]
short에 들어오는 tmn과 tmx값은 유지하고, temp icon을 계산은 주간날씨 정보와 상세날씨 정보 가지고 올때, 추가 개선하겠습니다.

**Comment by kimalec** [comment]
값이 없는 경우에는 0이 아닌 실제 구분 가능한 값을 넣어야 할 것으로 보임.

**Comment by nammaste6** [comment]
안녕하세요. 공공데이터포털 운영팀입니다.

일 최저기온(TMN), 일 최대기온(TMX)은 예보시각(fcstTime)에 따라
일 최저(0600), 일 최대(1500) 자료에만 데이터 확인이 가능합니다.
이외의 값에 대해서는 해당 데이터를 사용하지 않아도 됩니다.

**Comment by kimalec** [comment]
기존대로, tmx, tmn의 기본값을 0으로 채우고, 최저일때 최고인 그 시간에 값을 넣도록 하자.
provider로부터 -50이 들어오면 예외처리한다.( 예외처리는 구현하면서 적정한 방향으로 결정.

**Comment by kimalec** [comment]
공공데이터포털 운영팀 가이드대로, 일 최저(0600), 일 최대(1500) 자료만 사용하도록 합시다. 그러면 수정사항이 없으므로, 이슈 클로즈 합니다.

다만, 현재온도나, t3h가 더 낮게 오는 경우가 있는데, 그 경우에 한해서 router에서 데이터 재보정해서 전달하도록 합시다.
#266 에 관련 보정 추가
