### ISSUE TITLE
도시 검색 문구 변경

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1187]
도시 검색 탭 + 도시 검색 화면에서 PlaceHolder 변경

**Comment by kimalec** [comment]
- [ ] 제목 영역 확인해봐주세요.
<img width="402" alt="2016-10-17 12 54 08" src="https://cloud.githubusercontent.com/assets/6895272/19424961/d0e55dca-9468-11e6-8832-f0a943cf363c.png">
