### ISSUE TITLE
Frontend에서 현재위치 정보로 주소(시,동) 구하기.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#12]
iOS, Andorid에서 GPS/WIFI를 활용한 위치 정보를 가지고, 주소 찾기.

**Comment by kimalec** [comment]
참고 : http://sshbug.tistory.com/38

**Comment by kimalec** [comment]
[모바일웹에서 기상청 날씨(실황) api 가져와서 파싱해서 노출까지 자바스크립트로 만들기](http://werty.co.kr/blog/3011)

**Comment by skywlrl** [comment]
[wunderground API Key]
* http://www.wunderground.com/
* wzdtester 계정으로 생성
* Key ID : aa55af08bd576de9
[ionic weather app]
* Source : https://github.com/skota/ionic-weather-app
** wunderground 사용안하는 것으로 보임
** ionic plugin add cordova-plugin-whitelist 설치
* Google Play : https://play.google.com/store/apps/details?id=com.ionicframework.weather -> 실행 안됨

**Comment by skywlrl** [comment]
**[위도/경도를 주소로 변환하는 방법]**
1. Android Geocoder 이용
http://areumwing.blogspot.kr/2012/05/blog-post.html
http://kwangoms.tistory.com/27
2. Google Geocoding API -> **해당 방법으로 작업 진행 예정**
https://developers.google.com/maps/documentation/javascript/geocoding?hl=ko
http://chongmoa.com/5349
3. 다음 지도 API
https://developers.daum.net/services/apis/local/geo/coord2addr

**Comment by skywlrl** [comment]
**[현재 위치 정보(위도, 경도)를 가져오는 방법] => 2번 방법으로 진행** 

1) cordova + org.apache.cordova.geolocation
* Apache Cordova Documentation : http://cordova.apache.org/docs/en/2.5.0/index.html
* org.apache.cordova.geolocation 설치 + 예제 (iOS8에서 발생한 버그 해결 방법 포함)
  * http://strangemilk.com/building-ios-app-ionic-part-1/
  * https://blog.nraboy.com/2014/10/implement-google-maps-using-ionicframework/

2) ngCordova + cordova-plugin-geolocation
 * ngCordova 설치 : http://ngcordova.com/docs/install/
  * cordova plugin을 wrapping 한 angular의 module을 제공함
  * ngCordova 설치 시 ionic에 포함되어 있는 angular library가 중복으로 설치됨 => bower로 설치하지 않고 소스 올려놓도록 함
  * Cordova Plugin을 설치하면 Apache Cordova plugin의 git에서 소스를 다운 받음(최신 버전 유지)
 * Geolocation Plugin 설치 + 예제 : http://ngcordova.com/docs/plugins/geolocation/

3) ngCordovaIonic
 * https://libraries.io/bower/ng-cordova-ionic
 * Wrappers for ngCordova services with Ionic fallbacks (사용 빈도가 낮아 고려하지 않음)

**Comment by kimalec** [comment]
package.json에서 cordovaPlugins에  ngCordova를 추가하면, ionic에 포함된거랑 library가 중복된다는 거죠?

**Comment by skywlrl** [comment]
ngCordova는 bower로만 설치 가능하고 설치하면 angular js 포함해서 angular 라이브러리가 같이 설치되는데 이미 ionic에 포함되어 있는 것들이에요. 설치된거 그대로 두면 빌드할 때 다 들어가버려서 좀 이상한 거 같고, ngCordova만 남기고 다른 설치된 거 지워도 문제 없이  동작하길래 bower로 설치된 ngCordova 코드를  ionic처럼 github에 올려놨어요. bower.json을 자동으로 만들어주는게 없는 거 같아요

**Comment by kimalec** [comment]
ionic, cordova, package.json, bower.json .. 아직 어렵군요. 일단, merge하고 더 좋은 방법이 생기면 개선하도록 합시다. 하다보면 알게되겠죠~

**Comment by kimalec** [comment]
google geocode의 경우에는 주소 정보가 여러개가 오는데, 서울 경우에는 도로명 주소와 지번주소가 같이 온다.
그 중에서 지번 주소 중에 동이 상세하게 나와 있는 경우(잠실동과 잠실본동)를 골라야 한다. 

```js
       /**
         * It's supporting only korean lang
         * @param results
         * @returns {string}
         */
        function findDongAddressFromGoogleGeoCodeResults(results) {
            var dongAdress = "";
            var length = 0;
            results.forEach(function (result) {
                var lastChar = result.formatted_address.slice(-1);
                if (lastChar === '동')  {
                    if(length < result.formatted_address.length) {
                        dongAdress = result.formatted_address;
                        length = result.formatted_address.length;
                    }
                }
            });

            return dongAdress;
        }
```
