### ISSUE TITLE
위젯 설정 기능을 앱 대신 위젯에서 제공하기

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1205]
- [x] 위젯 추가 시에 투명도 설정, 업데이트 주기, 도시 선택, 배경색, 글자색
* 색상 선택 Preference : https://github.com/kizitonwose/colorpreference
- [x] 위젯에 설정 기능 추가(투명도 설정, 업데이트 주기, 도시, 배경색, 글자색 변경 기능
- [x] 글자 크기 설정 #1663 에서 진행.
- [x] 앱의 설정에서 위젯 설정 기능 제거

**Comment by skywlrl** [comment]
빌드 시 수정 작업
1. 아래 두 파일 plugin 설치 후 복사
values/apppreferences.xml
xml/appreferences.xml 
2. build.gradle에 코드 추가
```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
dependencies {
    ...
    compile 'com.github.kizitonwose.colorpreference:core:1.0.2'
    // SUB-PROJECT DEPENDENCIES END
}

**Comment by kimalec** [comment]
cordova-plugin-app-preferences/bin/lib/android.js 에서 apppreferences.xml 를 만드는 것은 맞네요. 
다만 왜 만드는지 좀 더 봐야 할듯합니다.

**Comment by kimalec** [comment]
code에 두개가 없네요. 확인해봐주세요.
values/apppreferences.xml
xml/appreferences.xml
