### ISSUE TITLE
상단 메인 배경용 눈,비 Animation 적용

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#121]
main icon에 svg animation을 적용하자.

**Comment by kimalec** [comment]
http://forum.ionicframework.com/t/best-practice-for-svg-animation/14953

http://devdactic.com/ionic-with-movejs/

**Comment by kimalec** [comment]
http://codyhouse.co/gem/animate-svg-icons-with-css-and-snap/

http://webdesign.tutsplus.com/tutorials/how-to-animate-festive-svg-icons-with-css--webdesign-17658

http://designmodo.com/svg-animation/

https://css-tricks.com/using-svg/

http://articles.dappergentlemen.com/2015/01/13/svg-spinner/

**Comment by skywlrl** [comment]
http://patrickgarvin.com/blog/?p=1834
http://design.tutsplus.com/tutorials/svg-files-from-illustrator-to-the-web--vector-20899

**Comment by skywlrl** [comment]
[Animated gif 샘플 파일]
![animated](https://cloud.githubusercontent.com/assets/8368939/10414693/a0945552-701c-11e5-9c74-94a888b9321b.gif)

**Comment by kimalec** [comment]
big icon animation

![big_icon_animation](https://cloud.githubusercontent.com/assets/6895272/10415644/dacf5c6c-7035-11e5-8d74-ac5a6d7ee6a4.gif)

**Comment by kimalec** [comment]
아이콘 애니메이션보다는 배경애니메이션으로 갈 것으로 보임. 아직 미정임.

**Comment by kimalec** [comment]
airbnb처럼 배경 동영상을 넣는 방식도 괜찮을듯함.

**Comment by kimalec** [comment]
메인 상단화면에 사용할 눈, 비 에 대한 애니메이션 추가

**Comment by kimalec** [comment]
기본적인 비오는 SVG 제작해주세요.

**Comment by kimalec** [comment]
현재 진행 예정이 없어 close합니다.

**Comment by kimalec** [comment]
Bodymovin으로 animation 만들 수 있음 (html+css+js)  
https://github.com/bodymovin/bodymovin

**Comment by kimalec** [comment]
적절 아이콘 구매로 전환
