### ISSUE TITLE
흰색 배경화면용 날씨 아이콘

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1222]
#410 에서 만들어진 아이콘들을 흰배경에 사용가능하게 개선.

<img width="360" alt="2016-10-24 10 12 29" src="https://cloud.githubusercontent.com/assets/6895272/19631110/67703ff8-99d2-11e6-9d3c-f514c34e5120.png">

아래와 같이 테두리 라인 있으면 어떨까 싶음.
<img width="78" alt="2016-10-24 10 01 52" src="https://cloud.githubusercontent.com/assets/6895272/19631087/f5b5b348-99d1-11e6-8c9a-f0988e2fb522.png">
참고
http://search.daum.net/search?w=tot&m=&q=서울시%20날씨&nzq=날씨&topq=&DA=NSJ
http://m.weather.naver.com

**Comment by kkkiiikkii** [comment]
![161029_ -01](https://cloud.githubusercontent.com/assets/12652131/19826286/71c318ca-9dc1-11e6-9379-007f4f1f7c75.png)
![161029_ -02](https://cloud.githubusercontent.com/assets/12652131/19826287/71c65008-9dc1-11e6-828b-8ae1ca927697.png)
![161029_ -03](https://cloud.githubusercontent.com/assets/12652131/19826288/71c84160-9dc1-11e6-8228-5e6e7da5eaba.png)

**Comment by kkkiiikkii** [comment]
[161028_날씨아이콘 흰배경용1.zip](https://github.com/WizardFactory/TodayWeather/files/559711/161028_.1.zip)
[161028_날씨아이콘 흰배경용2.zip](https://github.com/WizardFactory/TodayWeather/files/559712/161028_.2.zip)

**Comment by kimalec** [comment]
아이콘을 두가지 관리해야 하니, 검은색 아웃라인 하는 것은 어떨지 고려

**Comment by kimalec** [comment]
같이 쓸 방법 모색이 필요함.
짙은 색깔이나, 검은색으로 아웃라인 넣는거 검토
