### ISSUE TITLE
가이드 페이지 말고 동작 화면에 대한 가이드 툴팁 또는 팝업 지원

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1262]
http://www.jeffpickhardt.com/guiders
http://uxmovement.com/resources/build-a-user-friendly-web-application/

**Comment by kimalec** [comment]
지역검색에서 뭘해야 할지 모르는 경우가 꾀 있어 보임. 가이드 페이지 제거 여부와 상관없이 처음 지역검색에 오는 경우 입력창을 auto focus 하던지 툴팁을 띄워서 눈에 띄게 할 필요가 있어 보임.

**Comment by kimalec** [comment]
https://github.com/720kb/angular-tooltips

**Comment by kimalec** [comment]
#1526 starting page 적용
