### ISSUE TITLE
[iOS] Today Extension(Widget) 더 보기 기능 추가

### ISSUE THREAD

**Issue by seankim2** [WizardFactory/TodayWeather#1268]
* '더보기' 버튼 추가
  * 더 보기 버튼 클릭시 새로운 영역이 추가(일별/시간별 날씨 영역
* 토글 기능으로 일별날씨(어제포함)와 시간별날씨를 Display

**Comment by seankim2** [comment]
* merge 를 했으나 ios쪽은 동일함
```
KwangHo-Kim-ui-MacBook-Pro:TodayWeather mis2010$ git merge WizardFactory/master
Updating c374a6d..11c2a72
Fast-forward
 client/config-androidsdk14.xml              |  17 +++++++++++++++++
 client/config-androidsdk19.xml              |  17 +++++++++++++++++
 client/gulpfile.js                          |  17 ++++++++++++++---
 client/{ionic.project => ionic.config.json} |   0
 client/package.json                         |   2 +-
 client/www/index.html                       |   2 +-
 client/www/js/app.js                        |  78 ++++++++++++++++++++++--------------------------------------------------------
 client/www/js/controller.purchase.js        |  25 ++++++++++++++++++++++---
 client/www/js/controllers.js                | 120 +++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------------------
 client/www/js/service.twads.js              |   9 +++------
 client/www/js/services.js                   | 127 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------
 11 files changed, 243 insertions(+), 171 deletions(-)
 rename client/{ionic.project => ionic.config.json} (100%)
```
* @kimalec TodayWeather.xcodeproj 이전 수정내용을 commit 한다고 지난 번에 얘기한거 같은데,
필요없는 작업이었나여? 일단 현재 상태에서 작업 진행할게여

**Comment by seankim2** [comment]
* 아래 set 및 callback을 통해 더보기<->간략히 보기 토글 기능이 동작됨
```
- (void)viewDidLoad
{
 ...
    
    // Add the iOS 10 Show More ability
    [self.extensionContext setWidgetLargestAvailableDisplayMode:NCWidgetDisplayModeExpanded];
}

- (void)widgetActiveDisplayModeDidChange:(NCWidgetDisplayMode)activeDisplayMode withMaximumSize:(CGSize)maxSize {
    if (activeDisplayMode == NCWidgetDisplayModeCompact){
        // Changed to compact mode
        self.preferredContentSize = maxSize;
    }
    else{
        // Changed to expanded mode
        self.preferredContentSize = CGSizeMake(self.view.frame.size.width, self.view.frame.size.height + WIDGET_PADDING);
    }
}
```

**Comment by seankim2** [comment]
* 하위 호환이 되는 함수인지 9.x 시뮬레이터를 통해 크래쉬 유무를 체크해야함
  *  @property (nonatomic, assign) NCWidgetDisplayMode widgetLargestAvailableDisplayMode **NS_AVAILABLE_IOS(10_0)**;

**Comment by kimalec** [comment]
@seankim2 저번에 PR할때 TodayWeather.xcodeproj는 포함하지 않았기 때문에 따로 신경쓰지 않아도 될꺼 같아요.

**Comment by seankim2** [comment]
* 9.3 OSversion iPhone 6S 에서 crash 이슈 발생
  * 아래 함수를 통해10.0이상 version에서만 show more 기능 동작하도록 수정
```
...
    NSOperatingSystemVersion nsOSVer = [[NSProcessInfo processInfo] operatingSystemVersion];
    NSLog(@"version : %ld.%ld.%ld", nsOSVer.majorVersion, nsOSVer.minorVersion, nsOSVer.patchVersion);
    
    if(nsOSVer.majorVersion >= 10)
    {
        // Add the iOS 10 Show More ability
        [self.extensionContext setWidgetLargestAvailableDisplayMode:NCWidgetDisplayModeExpanded];
    }
    else
    {
        NSLog(@"This OSVersion can't use Show More feature!!!");
    }
...
```

**Comment by seankim2** [comment]
* Toggle(일별/시간별) 하는 방식 (Android 방식)
  * ![img_1683](https://cloud.githubusercontent.com/assets/8072056/20237913/8652b1d0-a922-11e6-8e87-af87f4385fbf.JPG) ![img_1684](https://cloud.githubusercontent.com/assets/8072056/20237918/c09b0a54-a922-11e6-95b4-18ff07c0f80d.JPG)
* 한번에 일별/시간별 보여주는 방식 (원기날씨)
  * ![img_1685](https://cloud.githubusercontent.com/assets/8072056/20237925/f7dc2c64-a922-11e6-85be-039d86db6abd.PNG) ![img_1686](https://cloud.githubusercontent.com/assets/8072056/20237926/f7e16404-a922-11e6-956c-0a80189e7111.PNG)
* 일별(어제포함)/시간별 날씨는 6일/6시간내의 날씨를 보여주는 걸로 ... 
  * ![img_1682](https://cloud.githubusercontent.com/assets/8072056/20237939/56c38358-a923-11e6-863c-095722cefb6f.PNG)

**Comment by seankim2** [comment]
* 안드로이드 방식(토글)으로 6개 날씨 objects를 만든다.
* 각 object 는 아래의 UIView sub object를 가지도록 만든다.
  * label : 날짜 또는 시간 텍스트
  * image : 날짜 또는 시간 이미지
  * label : 온도 ( 날짜 -> 최대 / 최소,  시간 -> 현재 온도)
* 투명 버튼을 씌운뒤에 버튼 클릭시 Toggle(일별/시간별)하도록 만든다.

**Comment by seankim2** [comment]
* ShowMore View를 따로 생성
  * 이미지 및 label 생성
* 더보기/간략히 보기 에 따라 view hidden을 true/false로 ...
* 추가해야할 일 
  * 일별/시간별 데이터 받아와서 뿌리기
  * 테스트/이미지 정렬 ( 각 phone size에 받게 처리해야함)
  * 일별/시간별 토글시 처리 (데이터를 저장한다면 어떤 시점에 저장을 할 것인가?..  고민이 필요함)

**Comment by seankim2** [comment]
* 토글 버튼 생성 후 텍스트 변경 테스트
* city List가 없는 경우에도 이전에 Expand이면 계속 그 상태로 유지되는 이슈가 있음
  * cityList가 nil일시에는 Display Mode를 NCWidgetDisplayModeCompact로 유지

**Comment by seankim2** [comment]
* city List가 없는 경우 widget에 일별/시간별 toggle버튼이 덮어져 있어 도시목록으로 들어갈 수 없는 이슈
  * toggle 버튼을 show more view 내부에 위치시키도록 변경
* git update 이후 메인 앱에서 아래 이슈가 발생
  * 이슈 내용
```
2016-11-15 23:16:59.121529 TodayWeather[8834:2096587] ERROR: Plugin 'Device' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2016-11-15 23:16:59.121755 TodayWeather[8834:2096587] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["Device883359951","Device","getDeviceInfo",[]]
2016-11-15 23:16:59.182436 TodayWeather[8834:2096587] ERROR: Plugin 'NetworkStatus' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2016-11-15 23:16:59.182583 TodayWeather[8834:2096587] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["NetworkStatus883359952","NetworkStatus","getConnectionInfo",[]]
2016-11-15 23:16:59.182662 TodayWeather[8834:2096587] ERROR: Plugin 'StatusBar' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2016-11-15 23:16:59.182719 TodayWeather[8834:2096587] -[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["StatusBar883359953","StatusBar","_ready",[]]
```
  * 아래 명령으로 ios쪽 CDV를 recompile후에 정상 동작됨
```
# ionic state reset
# npm install
# bower install
# ionic io init
# gulp sass
# ionic run ios
```

**Comment by seankim2** [comment]
* 기존 URL로 가져온 데이터에는 일별/시간별 데이터는 없는 듯 보임
  * 해당 데이터를 가져올 수 있는 URL이 필요함

**Comment by kimalec** [comment]
아래 API가 모두 가지고 소스입니다. 이걸쓰게 되면 parse부분 많이 수정해야 할 수도 있을것 같네요. ㅠㅠ
https://todayweather-wizardfactory.rhcloud.com/v000705/town/경상북도/칠곡군/지천면

**Comment by seankim2** [comment]
* 위 URL을 통해 얻어진 데이터를 http://json.parser.online.fr/ 를 통하여 직관적으로 데이터를 일단 눈으로 parsing 
  * "current" 를 통해 현재 날씨 정보를 대체함
  * "short" Value를 통해 **시간별** 날씨를 가져와야함
    * shortPubDate(현재 시간 보다) 이후( 3시간 간격으로 데이터를 뿌려야함)
  * "midData"/"dailyData" 를 통해 **일별** 날씨를 가져오면 될듯.
* server/models/modelCurrent.js 등 model 내부에 있는 js 파일 내용으로 키가 어떤 것을 의미하는 지 파악

**Comment by seankim2** [comment]
* "current"를 통해 현재날씨 정보를 display
* icon은 없는 듯 ... 어떤 key에서  아이콘에 대한 정보를 얻는가?
* 아이콘을 위해 한번더 request 를 해야하는가??

**Comment by seankim2** [comment]
* 날짜를 표시하기 위해 NSString의 아래 함수를 이용하여 Display
```
    nssYear             = [nssDate substringToIndex:4];
    nssMonth            = [nssDate substringWithRange:NSMakeRange(5, 2)];
    nssDay              = [nssDate substringFromIndex:6];
    nssHour             = [nssTime substringToIndex:2];
    nssMinute           = [nssTime substringFromIndex:2];
    nssDateTime         = [NSString stringWithFormat:@"%@.%@.%@ %@:%@", nssYear, nssMonth, nssDay, nssHour, nssMinute];
```

**Comment by seankim2** [comment]
* TodayViewController 파일의 내용이 너무 길어 가독성이 떨어짐
  * 새로운 function들을 추가하기 위해 TodayWeatherUtil파일을 생성
* dailyData Array에 어제 날짜에 대한 정확한 index를 가져올수 없다면 비교를 위한 어제날짜를 계산해야함.... 
  * 날짜를 비교하기 위해 어제날짜를 가져오기 위한 util function을 생성
```
- (NSString *) getYYYYMMDDFromUTCTime:(unsigned int)UTCTime;

+ (NSDate *) getYesterday;
+ (NSArray *) getDaysArray:(NSDictionary *)jsonDict date:(int)curDate;
+ (NSArray *) getByTimeArray:(NSDictionary *)jsonDict date:(int)curDate time:(int)curTime;
```
* +, - method의 사용법을 잘 이용하자....
  * + 는 static method라고 간단히 이해하자...
  * 클래스 method와 instance method는 아래에서 이해를...
     * http://adolys.tistory.com/entry/%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EB%A9%94%EC%86%8C%EB%93%9CInstance-Method%EC%99%80-%ED%81%B4%EB%9E%98%EC%8A%A4-%EB%A9%94%EC%86%8C%EB%93%9CClass-Method

**Comment by kimalec** [comment]
기존 API에 아이콘속성을 추가할 생각입니다. 준비해서 코멘트하겠습니다.

**Comment by seankim2** [comment]
* 어제 날짜를 뽑아온 뒤 NSDate->NSString->int로 변경 후 dailyData Array의 date와 비교후 6개의 데이터를 뽑아옴
```
2016-11-22 23:57:33.807677 widget[2456:485282] yesterdayDate : 20161121
2016-11-22 23:57:33.808673 widget[2456:485282] date : 20161121
2016-11-22 23:57:33.808836 widget[2456:485282] date : 20161122
2016-11-22 23:57:33.808869 widget[2456:485282] date : 20161123
2016-11-22 23:57:33.808893 widget[2456:485282] date : 20161124
2016-11-22 23:57:33.808916 widget[2456:485282] date : 20161125
2016-11-22 23:57:33.809082 widget[2456:485282] date : 20161126
2016-11-22 23:57:33.813185 widget[2456:485282] arrDaysData : (
        {
        date = 20161121;
        fsn = 19;
        fsnGrade = 0;
        fsnStr = "\Uad00\Uc2ec";
        lgt = 0;
        lgtAm = 0;
        lgtPm = 0;
        pop = 20;
        pty = 0;
        ptyAm = 0;
        ptyPm = 0;
        r06 = 0;
        reh = 52;
        rn1 = 0;
        s06 = 0;
        sky = 4;
        skyAm = 4;
        skyPm = 4;
        t1d = "9.5";
        taMax = 14;
        taMin = 5;
        ultrv = 2;
        ultrvGrade = 0;
        ultrvStr = "\Ub0ae\Uc74c";
        wfAm = "\Ud750\Ub9bc";
        wfPm = "\Ud750\Ub9bc";
        wsd = "1.1";
        wsdGrade = 1;
        wsdStr = "\Uc57d\Ud568";
    },
        {
        date = 20161122;
        dustForecast =         {
            PM10Grade = 1;
            PM10Str = "\Ubcf4\Ud1b5";
            PM25Grade = 1;
            PM25Str = "\Ubcf4\Ud1b5";
            sido = "\Uacbd\Uae30\Ubd81\Ubd80";
        };
        fsn = 25;
        fsnGrade = 0;
        fsnStr = "\Uad00\Uc2ec";
        lgt = 0;
        lgtAm = 0;
        lgtPm
...
2016-11-22 23:57:33.813501 widget[2456:485123] =======>  date : 2016.12.22 23:00
```

**Comment by seankim2** [comment]
* Showmore에 필요한 date Label, temperature label, imageview에 IBOutlet으로 연결
* dateLabel에 미리 처리된 6개의 array값을 통하여 display
* button의 텍스트 삭제

**Comment by seankim2** [comment]
* 일별 온도 표시 추가
* 날짜 parsing 오류 수정
* 버튼 동작 오류 수정 ( View들의 순서가 중요함)
* ShowMore 관련 함수들을 위해 TodayWeatherShowMore.m, h 파일 추가

**Comment by seankim2** [comment]
* TodayWeatherShowMore funcion에서 TodayViewController의 UI Objects들을 controller하기위해 singleton 생성후 display
  * TodayViewController.m
```
+ (TodayViewController *)sharedInstance {
    static TodayViewController *todayVC = nil;
    
    if(todayVC == nil)
    {
        todayVC = [[TodayViewController alloc] initWithNibName:@"TodayViewController"			bundle:nil];

    }
    
    return todayVC;
}

- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
{
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self)
    {
    }
    return self;
}
```
  * TodayWeatherShowMore.m
```
TodayViewController *TVC = [TodayViewController sharedInstance];
...
TVC->time1Label.text = [NSString stringWithFormat:@"%@ / %@", nssMonth, nssDay];
TVC->temp1Label.text = nssTempMaxMin;
...
```

**Comment by seankim2** [comment]
* singleton sharedInstance function 오류수정
* getByTimeArray를 위한 util 함수 작성
* makeTimeIntervalWithDate, getCurTime function에 대한 TimeInterval을 적정하게 가져와서 비교해야함

**Comment by seankim2** [comment]
* TImeInterval을 한번더 변환하지 않고 NSDate자체로 비교
* processByTimeData를 통해 시간별데이터를 display하는 function 생성
  * 정상적으로 array구성을 못하고 있음. 디버깅이 필요.
* 't3h' 가 시간별 array의 온도값인가? 확인이 필요함

**Comment by kimalec** [comment]
short(시간별 array)에서 t3h가 온도입니다.

**Comment by seankim2** [comment]
* 얻어온 json을 set하는 함수가 call되지 않은 이슈 해결
* time이 24:00으로 오기때문에 NSDateFormatter로 변환하기 어려움
  * string을 붙여서 int로 변환후 체크하는 부분이 더 쉬운 알고리즘인듯...
* 날짜와 시간을 합친 String은 int로 다 변환하지 못하기에 long long으로 변환해야함
* 정상적으로 시간별화면이 출력됨
* 텍스트 간격 조정 이쁘게... (autolayout  기능이 추가되어야함)

**Comment by seankim2** [comment]
* 추가 해야할 일
  * 아이폰 해상도에 따른 autolayout (현재는 5S에 절대좌표)
  * 아이콘 display
  * 볼드체로 했을 때 이슈 확인
  * UI 더 이쁘게 또는 직관적이게 조정 (상의 필요)

**Comment by seankim2** [comment]
* 각 text들 autolayout 처리
* 메인 view 클릭시 메인앱으로 이동
* 시간별 화면에서 시간 버그 수정해야함(첫 시간은 현재 시간 보다 이후여야 함)
* 일별은 어제/오늘/내일 날짜3개로 표시

**Comment by seankim2** [comment]
* timeLabel과 TempLabel auoresizing 처리
  * 실제 아이폰6에서 확인해봐야함(동환PM 폰)
* 일별 array의 0,1,2 인덱스를 어제/오늘/내일로 변경표시

**Comment by seankim2** [comment]
* 일별/시간별 변경 버튼 autoresizing으로 변경
* 메인앱이동 버튼 생성
  * 메인앱으로 이동은 가능
  * @kimalec 오프라인에서 얘기한 도시 index를 가진 full URL이 필요함.

**Comment by kimalec** [comment]
#987 딥링크 만들기

@skywlrl 위젯에서 특정 favorite로 갈때  써야하는 주소 알려주세요. todayweather://tab/forecast?fav=1 이런식으로 하면 될까요?

**Comment by skywlrl** [comment]
todayweather://net.wizardfactory.todayweather?fav= 이렇게 쓰면 될거 같아요

**Comment by seankim2** [comment]
* main app으로의 이동URL 적용
  * index는 mCurrentCity.index사용
* 시간별 기준 시각을 shortPubDate가 아닌 current의 data, time 조합으로 비교
  * 시간별 화면의 이전 시간이 보이는 이슈 해결

**Comment by seankim2** [comment]
* getTodayArray 함수 생성 후 오늘 최고/최저 온도를 미세먼지 아래 표시
* 더보기/간략히 보기시 최고/최저 온도를 hidden toggle 시킴
* 더보기/간략히 보기시 폰트 사이즈 변경

**Comment by seankim2** [comment]
* 추가 변경사항
** 비가 온다면 강수량 표시
** 습도 표시 제거
** 업데이트 텍스트 : '업데이트 HH:MM' 로 변경
** 기존 통합대기에서 통합대기/미세먼지/초미세먼지를 판단
*** 다 똑같으면 통합대기만 표시
*** 높은 순으로 ( 낮음/보통/나쁨)
*** khaiGrade/pm10Grade/pm25Grade
** 아래의 모습으로
![screenshot_20161208-203959](https://cloud.githubusercontent.com/assets/8072056/21013839/d403c2a8-bd9e-11e6-9379-f40edfd46997.png)

**Comment by seankim2** [comment]
@skywlrl 'todayweather://net.wizardfactory.todayweather?fav='이 동작안하는 거 같은데, fav에 index 넣는 거 많나요?

**Comment by seankim2** [comment]
* 업데이트 텍스트를 '업데이트 HH:MM' 로 변경함
  * 관련 변수 및 함수들 제거
* Today Extentions의 Compact size는 110으로 고정
  * 사용하지 않는 label 및 텍스트 제거
  * label, image 순서 정리

**Comment by seankim2** [comment]
* 습도 표시 제거 완료
  * 현재 온도 표시 텍스트 크기 변경
* 최고/최저 온도 hidden toggle-> 항상 표시
  * 더보기 화면의 크기 215로 증가 ( 최고/최저온도 겹치지 않게)
* 강수량 레이블 최고/최저 lable 왼쪽에
* compact mode시 각 labels 정렬

**Comment by seankim2** [comment]
* 아이폰 업데이트 10.1.1 인한 xcode 오류
** xcode version 8.1로 업데이트

**Comment by seankim2** [comment]
* 시간별/일별 아이콘 이미지 위치 조정
* Show More View내의 main app 이동 버튼 제거
  * 간략히 보기에 버튼으로 대체
* 통합대기/미세먼지/초미세먼지 Grade계산후 표시
  * Grade가 동일하면 통합대기 값을 표시, 동일할때 우선순위는 통합대기 > 미세먼지 > 초미세먼지

**Comment by seankim2** [comment]
* 아이폰 5S에서는 정상적이나 아이폰 7 simulator에서 아래와 같이 화면 표시됨
![iphone7_widget](https://cloud.githubusercontent.com/assets/8072056/21186409/e6fe856a-c257-11e6-9436-a3cf0d3a4257.png)
* label 들의 위치가 fixed된 듯. autoresizng이 안된듯... 다시 해야됨

**Comment by seankim2** [comment]
* 스토리보드를 이용한 autolayout 
  * http://ddirty.tistory.com/58

**Comment by seankim2** [comment]
* Autolayout 강좌
  * http://meetkei.com/?p=3414
  * http://meetkei.com/?p=3460
  * http://meetkei.com/?p=3545
* 기존 autoresizing이 제대로 안먹던 이유는 각 label을 가로 autoresizing을 했더라도 그 lable을 담고 있는 view를  autoresizing하지 않아 동작되지 않음 문제 였음
* view 를 autoresizing 후 정상적으로 align됨
![autoresizing](https://cloud.githubusercontent.com/assets/8072056/21288087/751358fa-c4bd-11e6-9511-e94697bbbe83.png)

**Comment by seankim2** [comment]
*  todayweather://cityindex
  * 1) todayweather://1  ?
  * 2) todayweather://cityindex=1
* @skywlrl 1번처럼 URL을 open하는 게 맞져??
* 위 두가지로 해도 동일함 
* 소스 업데이트(angular js 쪽??)가 필요한 사항인가? (한달전 소스로 widget 개발중임)...

**Comment by kimalec** [comment]
client 폴더에서 아래와 같이 plugin 새로 설치한후 빌드하고 확인해봐주세요.

```bash
cordova plugin rm ionic-plugin-deeplinks
cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=todayweather --variable DEEPLINK_SCHEME=http --variable DEEPLINK_HOST=net.wizardfactory.todayweather --variable ANDROID_PATH_PREFIX=/
ionic build ios
```

**Comment by seankim2** [comment]
* cordova plugin rm ionic-plugin-deeplinks 시 아래와 같은 에러 발생
```
Error: Plugin "ionic-plugin-deeplinks" is not present in the project. See `cordova plugin list`.


┌──────────────────────────────────────────┐
│ Update available: 6.4.0 (current: 6.3.1) │
│ Run npm install -g cordova to update.    │
└──────────────────────────────────────────┘
```

**Comment by seankim2** [comment]
* 위에 무시하고, 아래 명령 실행 
```
cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=todayweather --variable DEEPLINK_SCHEME=http --variable DEEPLINK_HOST=net.wizardfactory.todayweather --variable ANDROID_PATH_PREFIX=/
ionic build ios
```
* mainapp으로 동작하고 기존 동작과는 달리 한번 더 이동을 하지만 동일한 city로 옮겨짐

**Comment by seankim2** [comment]
* 다시 plugin rm을 하면 위 에러가 발생하지 않지만 여전히 동일한 city로 옮겨짐
* 그리고 메인 앱 이동시 아래 이미지 에러가 한번 발생함
![img_1835 png](https://cloud.githubusercontent.com/assets/8072056/21356908/a16ac946-c716-11e6-8c72-dd43cd538dde.jpeg)

**Comment by seankim2** [comment]
* fake 이미지 삽입후 showmore의 이미지 아이콘 위치 조정
![img_1857 png](https://cloud.githubusercontent.com/assets/8072056/21394294/663ef91c-c7db-11e6-8245-04ffd0103434.jpeg)
* 추후 real icon data가 오면 변경필요

**Comment by seankim2** [comment]
* iPhone5s device, iphone6s emul, iphone 7 Plus emul 해상도에서 이미지 및 레이블 정렬 확인
* iphone 7 Plus emul 에서 이미지 가로로 늘려지는 이슈 해결
  * show more 이미지의 autosizing은 원본 그대로 유지 되도록 처리
* 9.3 버젼에서는 show more view가 겹쳐지는 이슈 발생 ( 10.대 버젼부터 show more가 생김)
  * 9. 대 버전 이하는 show more view를 hidden처리

**Comment by seankim2** [comment]
* 강수와 최고/최저온도 하나의 label로 합침
  * 강수가 없을시에는 최고/최저 온도만 표시
* 최신 iOS 10.2로 업그레이드후 에서 테스트
  * 문제없음
* 오늘 날씨 표시 오류 수정 (최고/최저 -> 최저/최고)
  * showMore view 최저/최고로 표시

**Comment by seankim2** [comment]
* 필요없는 변수 제거 및 디버깅 로그 일부 주석 처리
* 사용하지 않는 func제거 및 각 func에 comment
* 위젯 남은 작업 
  * 아이콘 처리
  * 위젯에서 메인 앱 이동시 버그 수정

**Comment by seankim2** [comment]
* git merge후 ionic state reset시 아래 에러 발생 
```
cordova plugin add cordova-plugin-google-analytics
cordova plugin add phonegap-plugin-push --variable SENDER_ID="" 

/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:543
        throw 'Error executing "' + pluginCommand + '":\n' + output;
        ^
Error executing "cordova plugin add phonegap-plugin-push --variable SENDER_ID="" ":
Unmet project requirements for latest version of phonegap-plugin-push:
    cordova-ios (4.2.1 in project, >=4.3.0 required)
    cordova-android (5.2.2 in project, >=6.0.0 required)
    cordova (6.3.1 in project, >=6.4.0 required)
Fetching highest version of phonegap-plugin-push that this project supports: 1.8.4 (latest is 1.9.2)
Fetching plugin "phonegap-plugin-push@1.8.4" via npm
Error: Variable(s) missing (use: --variable SENDER_ID=value).
```
* 위 에러를 위해 cordova update 함.
* value가 null로 들어오는 경우에 대한 exception 처리 추가
```
if( nssT1h != [NSNull null])
```

**Comment by seankim2** [comment]
* '더보기' 버튼을 눌렀을 때 더보기 View가 위에서 내려오는 동안 기존 view와 살짝 겹쳐보이는 증상이 있음
**  원기 날씨는 제자리에서 fadeIn-Out 되는 것 같음
* transitView function을 이용해서 시도해보자.
```
- (void) transitView:(UIView *)curView
          transition:(UIViewAnimationTransition)transiton
            duration:(NSTimeInterval)duration
{
    [UIView	beginAnimations:nil context:nil];
    
    if(transiton != UIViewAnimationTransitionNone)
    {
        [UIView setAnimationDuration:duration];
    }
    
    [UIView setAnimationWillStartSelector:@selector(animationDidStart:)];
    [UIView setAnimationDidStopSelector:@selector(animationDidStop:finished:)];
    
    [UIView setAnimationCurve:UIViewAnimationCurveEaseInOut];
    [UIView setAnimationTransition:transiton
                           forView:curView
                             cache:YES];
    
    if(transiton == UIViewAnimationTransitionNone)
    {
        [UIView	animateWithDuration:duration
                              delay:(0.0f)
                            options:(UIViewAnimationOptionAllowUserInteraction)
                         animations:^{
                             curView.transform		= CGAffineTransformMakeScale(1.1, 1.1);
                             curView.transform		= CGAffineTransformMakeScale(0.9, 0.9);
                         }
                         completion:^(BOOL finished){
                             curView.transform		= CGAffineTransformIdentity;
                         }
         ];	
    }
    
    [UIView	commitAnimations];
}
```
* 더 보기 버튼이 눌려졌을 때 위 function이 호출되면서 자연스러움을 연출해보자...

**Comment by seankim2** [comment]
* transView를 이용하여 widgetActiveDisplayModeDidChange함수내에서 호출
** 윗 기본 정보view와 겹치지 않고 자연스럽게 표현됨
```
- (void)widgetActiveDisplayModeDidChange:(NCWidgetDisplayMode)activeDisplayMode withMaximumSize:(CGSize)maxSize
{
    if (activeDisplayMode == NCWidgetDisplayModeCompact){
        // Changed to compact mode
        self.preferredContentSize   = maxSize;
        [todayWSM transitView:showMoreView
                   transition:UIViewAnimationTransitionFlipFromLeft
                     duration:0.75f];
        showMoreView.hidden         = true;
        NSLog(@"NCWidgetDisplayModeCompact height : %f", self.preferredContentSize.height);
        
    }
    else
    {
        // Changed to expanded mode
        self.preferredContentSize   = CGSizeMake(self.view.frame.size.width, WIDGET_PADDING);
        [todayWSM transitView:showMoreView
                   transition:UIViewAnimationTransitionFlipFromRight
                     duration:0.75f];
        showMoreView.hidden         = false;
        NSLog(@"expanded height : %f", self.preferredContentSize.height);
    }
}
```

**Comment by kimalec** [comment]
![img_1666](https://cloud.githubusercontent.com/assets/6895272/22624352/f196915a-ebbc-11e6-8693-9d1ac0c8337e.PNG)
초미세먼지 매우나쁨의 경우 글 줄임 발생 영역을 좀 늘려주세요

**Comment by seankim2** [comment]
* 대기영역 auto-sizing으로 변경
* 강수, 최고/최저 온도 영역 auto-sizing 및 위치, 사이즈 조정

**Comment by seankim2** [comment]
* 간헐적으로 localization 파일을 수정했음에도 적용이 안될시에는 프로젝트를 clean하고, 앱을 삭제후 다시 설치 해야되는 경우가 발생하니 디버깅시 유의해야함
![image uploaded from ios-1](https://cloud.githubusercontent.com/assets/8072056/22625831/704950b2-ebe2-11e6-9830-5501f1f56f39.jpg)

**Comment by seankim2** [comment]
* widget이 로드될때 '11/18 토'이라고 나오는 Defalut Text와 온도 label의 text를 모두 삭제 처리

**Comment by seankim2** [comment]
* 통합대기/최고, 최저 온도,강수확률 레이블 color gray->default(black) 으로 변경
* 날짜별 온도 label 도 gray->black 으로 변경
