### ISSUE TITLE
iOS 위젯에서 화면 겹치는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1288]
iOS 위젯에서 화면 겹치는 문제가 발생함.
현재까지 확인된 바로는 볼드체를 사용하는 경우에 발생함.

<img width="630" alt="2016-11-25 12 35 03" src="https://cloud.githubusercontent.com/assets/6895272/20613888/c6eb17bc-b30b-11e6-82be-3e867ec213cd.png">

**Comment by seankim2** [comment]
* 새로운 위젯(더보기) 기능을 추가한 후 bold체로 설정후 테스트가 필요해 보임

**Comment by kimalec** [comment]
#1268 에서 수정되었음.
