### ISSUE TITLE
과거2일과 예보데이터만 전달하는 command 생성.

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#1290]
서버에 gathering하기 전 서비스 오픈을 위해서

클라이언트에서 데이터 요청이 왔을때 DSF, WU를 이용해서 과거 2틀의 데이터(DSF이용)와 미래 예보 데이터(WU이용)를 클라이언트에 보내주는  API생성.

**Comment by kimalec** [comment]
app.js에서
```js
var controllerCollector = require('./controllers/worldWeather/controllerCollector');
global.collector = new controllerCollector();
//collector.doCollect();
```
doCollect는 실행하지말고
쿼리는 http://localhost:3000/ww/010000/current/2?gcode=44.0,30.00

**Comment by kimalec** [comment]
아래 두 라인 주석제거.
```js
app.use('/ww', require('./routes/worldweather/routeWeather'));
app.use('/req', require('./routes/worldweather/routeRequester'));
```
- [ ] url 조정 필요 -> http://localhost:3000/v010000/ww/current/2?gcode=44.0,30.00
- [ ] cache를 위해 url 조정 혹은 cloudFront 조정 필요 -> http://localhost:3000/v010000/ww/current/2/44.0/30.00 or https://docs.aws.amazon.com/ko_kr/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesQueryString

**Comment by kimalec** [comment]
- [ ] 동일한 시간의 어제 날씨정도가 필요함 (특히 온도)
- [ ] cloud가 없는 경우는 precType만으로 하늘 상태를 구분하는 것이 맞는지 확인

**Comment by kimalec** [comment]
- [ ] DSF의 온도 변환이 이상함 저장된 값은 화씨(F)인것으로 보이는데, 썹씨(C)->화씨(F) 변환식으로 화씨(F)에 넣고 있음.
- [ ] 썹씨(C) 소수점까지 표시해야 함.

**Comment by kimalec** [comment]
- [ ] 시간이 정상적인 3시간 간격으로 오지 않은 경우가 있음.
- [ ] temp_f만 있고, temp_c가 없는 경우가 있음.
test url : http://localhost:3000/ww/010000/current/2?gcode=40.625,-73.875

**Comment by kimalec** [comment]
#1295 합치지 않고 사용했었음. 합친후에 재확인해야 함.

**Comment by kimalec** [comment]
timely 재확인 결과
temp_f만 있고, temp_c가 없는 경우는 없는듯함.

- [ ] 시간이 정상적인 3시간 간격으로 오지 않은 경우가 있음.
- [ ] 특정 시간이 온도가 이상하게 큼.

**Comment by kimalec** [comment]
http://localhost:3000/ww/010000/current/2?gcode=40.625,-73.875
- current에 temp_c가 precType 가 없음.
- timely에서 temp_c, cloud가 없는 경우가 있음.
- timely에서 cloud가 소수점으로 나오는데, 이 경우는 percent로 변경안한 것으로 보임. "date":"2016-12-10T03:00:00.000Z" 부터 8개
- yesterday의 data 만드는 것 문의
```
Error temp_c of hourly is undefined {"date":"2016-12-11T03:00:00.000Z","desc":"Clear skies","temp_f":32,"ftemp_c":-4,"ftemp_f":24.8,"humid":54,"windSpd_ms":3.61,"windSpd_mh":8.08,"windDir":320,"cloud":25,"vis":16,"press":1031.2}
Error temp_c of hourly is undefined {"date":"2016-12-11T15:00:00.000Z","temp_f":32,"ftemp_c":-2.9,"ftemp_f":26.7,"cloud":100,"windSpd_ms":2.4,"windSpd_mh":5,"windDir":227,"humid":52,"precType":0,"vis":20,"press":1034}
Error cloud of hourly is undefined {"date":"2016-12-13T06:00:00.000Z","temp_c":1.7,"temp_f":35.1,"ftemp_c":-2.5,"ftemp_f":27.5,"windSpd_ms":4.5,"windSpd_mh":10,"windDir":291,"humid":79,"precType":0,"vis":20,"press":1017}
Error cloud of hourly is undefined {"date":"2016-12-15T06:00:00.000Z","temp_c":-3.7,"temp_f":25.3,"ftemp_c":-11.6,"ftemp_f":11.1,"windSpd_ms":9,"windSpd_mh":20,"windDir":287,"humid":54,"precType":0,"vis":17.2,"press":1015}
```

**Comment by kimalec** [comment]
- [ ] #929  - localTime 과 daylight offset과 timezone offset값을 전달하는 형태에 대한 논의

**Comment by kimalec** [comment]
http://api.weatherunlocked.com/api/forecast/40.71,-74.00 (뉴욕)
데이터가 이상함 - day가 2016-10-12일 20:00시부터 데이터가 나옴. UTC로는 11/12/2016 0시 임.

**Comment by kimalec** [comment]
- [ ] daily에 day object의 date 간격이 변경되는 경우가 있음.
```
"daily": [{
        "date": "2016-12-12T05:00:00.000Z",
        "localTime": "2016.12.12 00:00"
    }, {
        "date": "2016-12-13T05:00:00.000Z",
        "localTime": "2016.12.13 00:00"
    }, {
        "date": "2016-12-14T00:00:00.000Z",
        "localTime": "2016.12.13 19:00"
    }
```

**Comment by kimalec** [comment]
darksky에서 과거 데이터 요청하면, daily의 경우 당일 하루치만 옴.

**Comment by kimalec** [comment]
- [ ] timely에서 3시간 간격을 구할때, UTC기준이 아니라, localTime 기준으로 0, 3, 6, 9 로 가야 함.

**Comment by kimalec** [comment]
- [ ] 새로운 날씨정보를 가지고 올때, 최신뿐만 아니라 오늘의 0시부터의 과거 날씨도 가지고 와야 함 ( 예: 18시에 요청하면 0시부터 17시까지의 날씨 정보를 위해서 오늘 0시부터의 날씨 정보가 필요함)

**Comment by kimalec** [comment]
- [ ] 과거 데이터와, 예보 데이터 구분하거나, 시간이 지나면 예보 데이터를 실제 측정된 과거데이터를 덮어 씌워져야 함.

**Comment by kimalec** [comment]
- [ ] current와 yesterday를 array로 변경 -> thistime 으로 함.

**Comment by kimalec** [comment]
- [ ] precipAccumulation 가 강수합계이므로, 추가 필요함. daily에서는 precipAccumulation가 일강수량으로 쓰고, hourly에서는 3시간 간격으로 precipIntensity를 합산해야 함. hourly에 있는 precipAccumulation은 일 누적 강수량으로 보임.

참고 16년 12월 24일 16시 27분에 서울 날씨 https://api.darksky.net/forecast/[key]/37.571891,126.977629

**Comment by kimalec** [comment]
- [ ] daily에 sunrise만 있고, sunset이 없음.

**Comment by pokers** [comment]
precipAccumulation는 적설량.

> precipAccumulation optional, only on hourly and daily
The amount of snowfall accumulation expected to occur, in inches. (If no snowfall is expected, this property will not be defined.)

**Comment by pokers** [comment]
precipIntensity 는 내리는 모든것을 포함하는것.

> precipIntensity optional
The intensity (in inches of liquid water per hour) of precipitation occurring at the given time. This value is conditional on probability (that is, assuming any precipitation occurs at all) for minutely data points, and unconditional otherwise.

**Comment by kimalec** [comment]
- [ ] date format을 "yyyy.mm.dd HH:MM"으로 했으면 함. 이런 포맷은 new Date에 인자값으로 넣어주면 바로 Date object로 변환됨.
- [ ] daily의 date가 0시로 떨어지지 않음.

**Comment by kimalec** [comment]
- [ ] timeTime에 press가 없음.

**Comment by kimalec** [comment]
- [ ] cloud값이 0 아니면 1 인듯함, cloud값은 0~100%값임.
- [ ] daily에 cloud값이 rain인 경우도 없음

**Comment by pokers** [comment]
pubDate 는 데이터를 가지고오는 시간을 저장

**Comment by pokers** [comment]
DSF의 데이터의 정확도 및 사용할 데이터 선택의 문제
 
1. 뉴욕 좌표를 이용해서 쿼리 하는 경우 현재 12/27일 08시라고 가정
 - 쿼리시 시간을 넣지 않을 경우
   1. current데이터가 DSF의 웹에서 서비스 되는 날씨 데이터와 차이가 있다.
   2. 12/27일 12시의 예보 데이터도 DSF의 웹에서 서비스되는 날씨데이터와 차이가 있다.
- 쿼리시 시간을 12/27일 00시라고 입력해서 데이터를 받은 경우
   1. 과거 데이터와 금일 예보 데이터의 일부가 같이 들어온다.
   2. 시간을 입력하지 않았을때의 예보 데이터와 비교해보면 데이터에 차이가 있다.
   3. 이 데이터 중 현재 시간인 12/27일 08시의 데이터를 보면 DSF의 웹에서 표기되는 데이터와 거의 일치한다.
   4. 12/17일 12시의 예보 데이터또한 DSF의 웹에서 표기되는 데이터와 거의 일치한다.
   
어느 것을 사용해야할지.... 
DSF의 웹에서 서비스되고 있는 날씨는 쿼리시 시간을 입력해서 얻은 데이터와 동일하게 제공되고 있다.
이 데이터가 실제 날씨와 일치한지에 대한 확인도 필요...

**Comment by kimalec** [comment]
- [ ] DSF의 1시간단위 날씨를 3시간 단위로 변경할때, 합산(강수량), 평균(cloud), 최대값(강수확률)등 속성값에 맞는 방법으로 합산이 필요함.

**Comment by kimalec** [comment]
- [ ] checkValidDate 이 제대로 동작하지 않는 듯함 checkValidDate를 통과했는데, 어제 날씨가 없음.

**Comment by kimalec** [comment]
@pokers windSpd_mh 가 m per h or mile per h?

**Comment by kimalec** [comment]
개발진행 순서

1. API 재사용
1. 재사용 시나리오 정립
1. 1시간 단위 데이터를 3시간 단위로 변경 룰 생성
