### ISSUE TITLE
chart용 js lib조사

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#13]
시간별 온도표시용 chart lib조사

**Comment by nammaste6** [comment]
http://www.jsgraphs.com/

거의 대부분의 차트라이브러리가 정리가 되어있는 사이트입니다.

가격이 free이고 저희가 사용할 라인차트 기준으로 
ChartJS - http://www.chartjs.org/
FlotJS - http://www.flotcharts.org/
Plottable - http://plottablejs.org/
D3js - http://d3js.org
Ember Charts - http://addepar.github.io/#/ember-charts/

등이 있습니다.

**Comment by nammaste6** [comment]
cordova로 개발시 jqplot이 안보이는 현상 해결 방법
http://stackoverflow.com/questions/11288773/not-able-to-draw-graph-using-jqplot-in-android-phonegap-app

**Comment by skywlrl** [comment]
의존성이 없는 ChartJS를 우선으로 고려하기로 함
ChartJS의 예제로 Android, iOS에서 동작 테스트 필요함

**Comment by skywlrl** [comment]
**[AngularJS를 기반으로 Chart를 지원하는 js]**

1. angular-charts(AngularJS + d3.js)
 * http://chinmaymk.github.io/angular-charts/
 * https://github.com/chinmaymk/angular-charts/
2. angular-chart(AngularJS + Chart.js)
 * http://jtblin.github.io/angular-chart.js/

**[ionic + angular-chart.js 테스트]**
> 테스트 결과 : Android Phone, iOS Simulator 둘 다 정상 표시됨

1. ionic todo 소스 받기 & 실행

 > $ ionic start todo
$ cd todo
$ ionic platform add android
$ ionic build android
$ ionic emulate android / $ ionic run android
2. angular-chart.js 설치
> $ bower install angular-chart.js --save

3. Line Chart 예제 코드 추가
 * app.js 
 ```
angular.module('starter', ['ionic', 'chart.js', 'starter.controllers', 'starter.services'])
```
 * index.html
 ```
<link href="lib/angular-chart.js/dist/angular-chart.css" rel="stylesheet">
<script src="lib/Chart.js/Chart.js"></script>
<script src="lib/angular-chart.js/dist/angular-chart.js"></script>
```
 * tab-dash.html
 ```
<canvas id="line" class="chart chart-line" data="data" labels="labels" legend="true" series="series" click="onClick">
```
 * controller.js
 ```
.controller('DashCtrl', function($scope) {
      $scope.labels = ["January", "February", "March", "April", "May", "June", "July"];
      $scope.series = ['Series A', 'Series B'];
      $scope.data = [
          [65, 59, 80, 81, 56, 55, 40],
          [28, 48, 40, 19, 86, 27, 90]
      ];
      $scope.onClick = function (points, evt) {
          console.log(points, evt);
      };
})
```

4. Whitelist External Resources 처리 : https://blog.nraboy.com/2015/05/whitelist-external-resources-for-use-in-ionic-framework/
 > $ cordova plugin add cordova-plugin-whitelist

 * index.html
 ```
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">
```

**Comment by kimalec** [comment]
chart ui에 대한 추가 가이드라인

<img width="360" alt="default" src="https://cloud.githubusercontent.com/assets/6895272/9566086/9888e4e4-4f2f-11e5-8702-791fe21308f1.png">

**Comment by skywlrl** [comment]
[d3.js]
* d3 자료
 - http://d3js.org/
 - https://github.com/zziuni/d3/wiki
 - http://mobicon.tistory.com/275
 - http://christopheviau.com/d3_tutorial/
* 예제
 - http://www.danielepennati.com/d3/linea2.html
 - http://bl.ocks.org/jonSadka/482005612916b3f5e408
 - https://gist.github.com/ESeufert/3394672
* angularJS + d3 예제
 - http://www.ng-newsletter.com/posts/directives.html

**Comment by skywlrl** [comment]
AngularJS를 기반으로 Chart를 지원하는 js의 경우에는 지원하는 api가 한정적이므로
디자인 시안에 맞추기 어려워 d3.js로 직접 차트를 추가함.
조사를 위한 이슈이므로 d3.js + angular.js를 기반으로 차트를 추가하는 것으로 close 하고,
차트 디자인은 #78 이슈에서 진행.
