### ISSUE TITLE
iOS Native 부분 다국어 지원

### ISSUE THREAD

**Issue by seankim2** [WizardFactory/TodayWeather#1332]
* iOS의 Widget 및 Native 부분 다국어를 지원한다.
* 관련 이슈들
  * multi languages for main app #1287
  * 다국어 지원 #613
  * android widget에서 단위, 다국어, 세계날씨 지원 #1311

**Comment by seankim2** [comment]
* iOS localization(지역화) 완전 정복 -> http://trend21c.tistory.com/1689 부분을 참조
  * 앱 이름 지역화
  * storyboard부분은 따로 각각의 해당언어의 storyboard를 만들어서 다국어를 입력하고,
  * 팝업이나 소스상에서의 지원은 string files를 통한 localization

**Comment by seankim2** [comment]
* Project에서 localizations내에 create할 파일을 찾지 못함
  * locaization이 필요한 파일들을 먼저 localize한 뒤에 ( http://stackoverflow.com/questions/34266169/0-localized-files-seen-in-xcode-for-native-development-language )
  * Main에서 InfoPlist.string 파일 하나
  * widget에서 MainInterface.stroyboard, Info.plist 두파일을 locaize 버튼을 이용하여 Base, Englist로 만듦
* 다시 Project파일을 선택하여 Localizatins에서 +버튼을 이용하여 Korean을 추가

**Comment by seankim2** [comment]
* Localizations에 Japanese 추가
* 중국어 두가지 추가
  * Chinese (Simplified) - 간체
  * Chinese (Traditional) - 번체

**Comment by seankim2** [comment]
* Localizations에 독일어 추가

**Comment by seankim2** [comment]
* Info.plist localization후에 아래 빌드 에러 발생
```
the file “Info.plist” couldn’t be opened because there is no such file.
```
  * TodaWeather.xcodeproj -> Build Settings -> Info.plist File path 수정 후 빌드 성공
```
widget/info.plist -> widget/Base.lproj/Info.plist
```
  * 다국어 테스트시 정상적으로 App Name이 다국어 지원되는 지 확인 필요

**Comment by seankim2** [comment]
* 이전 프로젝트 확인 결과 "Info.plist"는 Localization이 필요없음
  * Info.plist에 Localization 할 내용인 Bundle display name은 infoPlist.strings에서 아래와 같이 가능함
```
"CFBundleDisplayName" = "App display name";
"CFBundleName" = "App bundle name";
```

**Comment by seankim2** [comment]
* Bundle Display Name 다국어 입력
  * client/locales/***.json 내용 참조
* 앱타이틀 다국어 적용 변경됨 확인

**Comment by seankim2** [comment]
* Widget에도 타이틀이 있기 때문에, 다시 widget내부에 info.plist를 localization화
  * Bundle Display Name 다국어화
* '업데이트' 다국어
  * 업데이트 단독 없음
  * "LOC_REFRESH_INTERVAL" : "업데이트 주기" 를 일단 이용
  * @kimalec  LOC_REFRESH_INTERVAL를 사용해도 되나여? 아니면 추가해주세요...

**Comment by seankim2** [comment]
* 다국어가 추가 필요하거나 문의 항목
  * 업데이트 ( '업데이트 주기' ??)
  * 오늘날씨앱을 실행하여 도시목록을 생성하여 주세요.
  * 통합대기 ( '통합대기지수'??, '대기지수'??)
  * 강수 20%의 강수 ('강수량'?? - LOC_PRECIPITATION??, LOC_RAINFALL??)

**Comment by seankim2** [comment]
* tomorrow의 중국어 간체,번체가 번역되어 있지 않음
  * "LOC_TOMORROW":"Tomorrow",
* 소스파일에서의 로컬라이제이션을 위해 localizable.strings와 LocalizationDefine.h를 생성

**Comment by kimalec** [comment]
android/res/values 참고해주세요~

**Comment by seankim2** [comment]
* TOMORROW는 明天 로 변경
* 업데이트는 android/res/values-xx/string.xml 참고
* '오늘날씨앱을 실행하여 도시목록을 생성하여 주세요' 번역본 없음
* 통합대기는 대기질로 사용???
* '강수' 없음

**Comment by seankim2** [comment]
* Update 다국어 변경 확인
* 통합대기/미세먼지/초미세먼지 아래로 일단 대체
```
"LOC_AQI"                           = "대기질";
"LOC_PM10"                          = "미세";
"LOC_PM25"                          = "초미세";
```

**Comment by seankim2** [comment]
* 강수는 강수확률
* 오늘날씨앱을 실행하여 도시목록을 생성하여 주세요 는 번역필요

**Comment by seankim2** [comment]
* 강수문구 강수확률로 대체
  * 영문과 독어는 너무 김. 줄일필요있음
* 오늘날씨는 기존 번역본 대체 ( 확인 후 버튼 사이즈 조정이나 label text size 조정 필요)
* 오늘날씨앱을 실행하여 도시목록을 생성하여 주세요 문구는 일단 구글 번역으로 대체구현 ( size 및 확인 필요)
  * 추가 번역본이 오면 업데이트해야함

**Comment by seankim2** [comment]
* 오늘날씨 버튼의 길이가 다국어로 인해 말줄임표로 표시됨
  * sizeToFit function을 사용하여 버튼의 size를 조정

**Comment by seankim2** [comment]
* 대기질->통합대기로 변경

**Comment by seankim2** [comment]
* 추가적으로 해야할 item
  * 각 언어별 draw시 문제점 확인
  * 번역되지 않은 문구 확인

**Comment by seankim2** [comment]
* 다국어 확인
  * 다국어 지원이외 국가(ex.. 베트남) 영어로 표시되는 지 확인
  * 6개국어(영어/한국어/일본어/독어/간체/번체) 확인

**Comment by seankim2** [comment]
* 오늘날씨 버튼 sizeToFit으로 보기에 아름답지 않음.
  * [twAppBtn sizeToFit]; 제거
  * 긴 다국어를 위해 버튼 사이즈를 늘림

**Comment by seankim2** [comment]
* 다국어 최신버젼으로 바꾼 뒤 확인 필요
* 도시정보없을때 '오늘날씨'버튼 위치 조정 필요 (위 텍스트와 붙어 있음)

**Comment by seankim2** [comment]
* 'LOC_PLEASE_EXECUTE_MAIN_APP' 에 대한 다국어 확인
  * 에뮬레이터가 훨씬 language 전환이 빠름
  * 여전히 제목은 안바뀜(테스트 플라이트로 확인해봐야 될 것 같음)
  * 설명 문구인 위 Label의 위치를 조정하여 좀 더 이쁘게 나오게 수정

**Comment by seankim2** [comment]
* LOC_UPDATE(업데이트) 최신버젼에 없음. 기존 유지
* LOC_YESTERDAY/LOC_TODAY/LOC_TOMORROW 다국어 최신버젼과 동일
* LOC_AQI/LOC_PM10/LOC_PM25 최신버젼 변경 및 확인
* LOC_PROBABILITY_OF_PRECIPITATION 최신버젼 변경 및 확인
* 앱과 widget을 삭제 후 확인하니 정상적으로 제목까지 변경됨

**Comment by seankim2** [comment]
* 시간별 데이터도 섭씨/화씨 일때 구분해서 소수점/소수점없음 으로 표시
* 2개이상의 Favorite이 있을 때 다음 도시선택후에 시간별 데이터 변경안되는 이슈 수정
  * setCurJsonDict 함수에서 한 번 alloc된 이후에 대한 처리가 제대로 처리되지 않았음
  * 아래와 같이 수정
```
@@ -848,11 +848,15 @@ 
-- (void) setCurJsonDict:(NSDictionary *)dict
+- (void) setCurJsonDict:(NSMutableDictionary *)dict
 {
     if(curJsonDict == nil)
     {
-        curJsonDict = [[NSDictionary alloc] initWithDictionary:dict];
+        curJsonDict = [[NSMutableDictionary alloc] initWithDictionary:dict];
+    }
+    else
+    {
+        [curJsonDict setDictionary:dict];
     }
 }
```

**Comment by seankim2** [comment]
* "최고/최저 온도 / 강수확률 / 통합 대기 텍스트 위치 ", "KR/Global", Phone Size등을 고려하여 Lable 위치 조정
  * label frame 위치 조정 부분 삭제
  * stroyboard에서 autoresizing 조정

**Comment by seankim2** [comment]
* "Localized resources can be mixed" 중국어 간체 추가

**Comment by seankim2** [comment]
* Global에서 nssTopPop이 Null이 되는 경우에 대해서도 강수확률 0%로 처리
```
nssTodPop           = [todayDict objectForKey:@"precProb"];
```
