### ISSUE TITLE
iOS Native 부분 world weather parser

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1334]
세계날씨지원을 위해 새로운 API에 따른 parser만들어야함.

**Comment by kimalec** [comment]
url : https://tw-wzdfac.rhcloud.com/ww/010000/current/2?gcode=40.71,-73.99
NSDefault로 전달되는 도시정보에 country, name이 추가되었습니다.
지역 정보 표시할때, name 우선으로 해주시면 됩니다.
country에 KR이 포함된 경우에는 기존 API를 사용하고, 그 외에는 새로운 API 주소를 사용하면 됩니다.
gcode값은 도시정보에 포함되어 있습니다.

현재위치에 대한 파싱 방법은 
services.js에 있는 getGeoInfoFromGeolocation를 참고해주세요.
구글에서 country와, name을 뽑고, country가 KR인 경우 daum api를 통해서 주소를 한글로 만듭니다.
그리고 한글로 만들어진 주소로 기존 API를 사용하면 됩니다. KR이 아닌경우 새로운 API로 요청하면 됩니다.

NSDefault에 units라는 이름으로 단위가 정보가 저장됩니다. 화씨의 경우 화씨에 맞게 변환하여 뿌려주시면 됩니다.

**Comment by kimalec** [comment]
지난 미팅에서 country 대신에 source를 사용하는 것에 대하여 이야기 했었는데, source가 지정한 위치의 날씨 정보를 제공하지 못하는 경우에 대한 예외처리가 필요하므로 우선 country로 진행하고, 그 다음 source 선택 가능하게 개선할때 예외처리 도 같이 들어가야 할 것으로 보임. 

결론 : source를 사용하지 말고, country로 구현해주세요.

**Comment by seankim2** [comment]
* 'https://tw-wzdfac.rhcloud.com/ww/010000/current/2?gcode=' string define 설정
* NSDefault 값 country, name이 Log상으로 확인 안됨, merge후 다시 확인이 필요

**Comment by seankim2** [comment]
* git pull 이후 ionic 재빌드를 하였지만 여전히 NSDefault에는 country는 나오지 않고 있음
* controller.js내부에 country가 사용되는 것 같음
```
...
  city.location = geoInfo.location;
            city.country = geoInfo.country; //"KR"
...

```
* main app에서 NSDefault에 country가 제대로 저장되는 지 먼저 확인이 필요해 보임

**Comment by seankim2** [comment]
* 필요한 파일들이 없어서 메인앱이 제대로 실행되지 않았음
  * 아래 command 가 추가적으로 필요함 
```
# bower install
# gulp sass
# ionic prepare ios  <- js파일만 업데이트
```
* 문제 발생시 gulpfile.js 를 참조해라.

**Comment by seankim2** [comment]
* main app에서 저장 데이터
```
TodayWeather[4645:1056883] save preference plist={"cityList":[{"currentPosition":false,"address":"대한민국 경기도 하남시 미사2동","country":"KR"},{"name":"서울특별시","currentPosition":false,"address":"대한민국 서울특별시","country":"KR"}]}
```
* widget에서 User Default print 한 값
```
2017-02-10 00:21:53.410058 widget[4670:1061803] current position : false address 대한민국 경기도 하남시 미사2동, name : (null), country : KR
2017-02-10 00:21:53.410222 widget[4670:1061803] current position : false address 대한민국 서울특별시, name : 서울특별시, country : KR
```
* name이 있으면 name을 사용하여 지역정보 표시하고, name이 없으면 예전방식으로 표시
* country가 있으면 country 없으면 KR로 인식하고 사용

**Comment by seankim2** [comment]
* CityInfo Class에 name, country를 NSString으로 처리
* 기존 KR에 대한 주소처리 부분 Util 함수로 처리 해야함
* KR이 아닌 country 구분 처리하는 루틴 구성해야함

**Comment by seankim2** [comment]
* address 처리를 위한 KR과 Global 함수 구분
*  도시 정보에서 location 정보로 위/경도 정보 획득
```
2017-02-12 23:18:11.682407 widget[1147:209631] location: {
    lat = "40.7127837";
    long = "-74.0059413";
}
2017-02-12 23:18:11.682616 widget[1147:209631] lat: 40.7127837, long:-74.0059413
```

**Comment by seankim2** [comment]
* CityInfo에 location 추가
* Global URL을 사용하기 위한 processGlobalAddress function 생성
* Global URL을 통해 날씨정보를 얻어옴
```
2017-02-14 00:04:44.292178 widget[2116:474067] [processGlobalAddress] nssURL : https://tw-wzdfac.rhcloud.com/ww/010000/current/2?gcode=40.7127837,-74.0059413
...
2017-02-14 00:04:48.749371 widget[2116:475034] jsonDict : {
    daily =     (
                {
            cloud = 70;
            date = "2017.02.12 00:00";
            desc = "Mixed precipitation until evening.";
            "ftempMax_c" = "3.6";
            "ftempMax_f" = "38.5";
            "ftempMin_c" = "-4.1";
            "ftempMin_f" = "24.5";
            humid = 89;

```

**Comment by seankim2** [comment]
* global weather data 를 draw하기 위한 function 파생
* address를 표시하기 위해 name이 있을시에는 name을 사용하고, 없을시에는 address를 parsing해서 사용해야함
  * Global data에는 KR과 달리 weather data에 address 정보가 없음

**Comment by seankim2** [comment]
* Global 현재위치 WeatherData Draw 시나리오
  * 현재 위치를 가져온다, (위도 / 경도)
  * 구글 api를 사용해서 현재 address를 가져온다.
    * country가 KR이면 기존처럼
    * 아니면 sub_locality_1을 찾는다. 없으면 locality를 사용
  * sub_locality_1으로 다시 위/경도를 가져온다.
  * 소스점 2자리까지 잘라낸다.
  * 서버에 요청하여 파싱하고, draw한다.
  * sub_locality 1이 name이 된다. 
* 소스를 확인한다. (services.js에 있는 getGeoInfoFromGeolocation를 참고)

**Comment by seankim2** [comment]
* saveWeatherInfo시에 KR과 Global시에 대한 처리 추가
  * KR에는 없고, Global에는 있는 데이터들에 대한 처리 추가
  * 저장되는 데이터의 NSDictionary는 아래와 같음
```
NSMutableDictionary* nsdTmpDict = [NSMutableDictionary dictionaryWithObjectsAndKeys:
                                       nssAddress, @"address",
                                       [nsdCurCity valueForKey:@"currentPosition"], @"currentPosition",
                                       nssCountry, @"country",
                                       nsnIdx, @"index",
                                       nsdLocation, @"location",
                                       nssName, @"name",
                                       @"", @"weatherData",
                                       nil];
```

**Comment by seankim2** [comment]
* address와 name에 대한 처리 후 name 정상 표시
  * name이 없을시에는 adress의 첫번째 주소를 표시한다
* 업데이트에서 현재날짜와 관련된 변수 및 처리 모두 제거
* 업데이트 시간은 thisTime Dictionary의 첫번째 Array에 date 항목을 파싱해서 얻어야함
```
"thisTime":[
{
"date":"2017.02.15 09:00",
...
```

**Comment by seankim2** [comment]
* processWeatherResultsXXX 필요없는 주석처리 부분 제거
** 함수복잡도 개선
* 데이터가 없는 부분 (null)로 표시되는 부분 공백으로 표시
* 업데이트 시간 thisTime의 첫번째 array의 date항목으로 표시함
* 다른 데이터들은 KR weatherData와는 다르게 되어 있음
** KR데이터들은 해당 weatherData를 그대로 출력만 하면 되는 상황
** @kimalec Globale weather data draw는 service.js 와 같이 구현 해야 하는 것인가요? 예를 들면 해당 내용들을 _parseWorldCurrentWeather의 내용과 같이 참조해서 처리해야하는 것인가요?
```
date: _convertDateToYYYYMMDD(new Date(current.date)),
               stnDateTime: current.date,
               summary: current.desc,
               t1h: current.temp_c,
               sensorytem: current.ftemp_c,
               reh: current.humid,
               wsd: current.windSpd_ms,
               wdd: _convertWindDirToWdd(current.windDir),
               skyIcon: _parseWorldSkyState(current.precType, current.cloud, isNight),
               visibility: current.vis,
               hPa: current.press,
               rn1: current.precip,
               today: todayInfo,
               yesterday: yesterday
```

**Comment by kimalec** [comment]
네 맞아요. _parseWorldWeather를 참고해서 해외용 parser 따로 만들어야 해요.

**Comment by seankim2** [comment]
* 이전에 말한 NSDefault에서 units는 보이지 않음
  * 화씨가 따로 들어오기때문에 섭씨<->화씨의 계산은 필요치 않아 보임
  * @kimalec 그렇다면 화씨를 뿌려야 할지? 섭씨의 온도를 뿌려야 할지 어떻게 결정하나요???
* precType으로 _parseWorldSkyState 함수내에서 날씨아이콘을 결정하는 것으로 보임
  * cloud와 isNight도 같이 확인해야함

**Comment by seankim2** [comment]
* controller.units.js의 _initUnits func를 통해 getTemperatureUnit을 만듦
  * KR이 default
  * JP/US/DE/CN/TW에 따라 C/F를 구분함
* @kimalec 위와 같이 TeperatureUnit을 구분해도 되나요?

**Comment by kimalec** [comment]
나라별 분리는 앱내에서 하도록 되어 있습니다. 그냥 공유된  units정보로 값변환만 하면 되어요~

**Comment by seankim2** [comment]
* units는 NSDefault에 공유된 데이터로 진행해야함.
  * units의 temperatureUnit를 사용해야함
  * 현재는 값을 확인할 수 없음. 추가적으로 디버깅이 필요함
* 강수확률은  precProb를 사용, 
* 통합대기는 Global에서 사용하지 않으므로 제거
  * 따라서 Global에서는 다르게 적용해야 함 ( 통합대기란인 2번째 라인에 현재최저/최고 온도을 표시, 강수확률은 그대로 3번째 라인에 표시)

**Comment by seankim2** [comment]
* 강수확률에 대한 처리
  * 강수확률이 없을시에는 3번째 라인에 어떤값도 표시하지 않음
* 글로벌 함수에서 사용하는 통합대기 변수 및 처리 모두 제거
  * 추후 추가시 KR 참조하여 처리
* 최고/최저온도만 2번째라인에 표시되는 상황에서 보기에 아름답지 않음...
  * 통합대기 레이블은 삭제하고, 강수/최고/최저온도 레이블을 가운데에 위치시키고, size를 조정할 필요있음

**Comment by seankim2** [comment]
* 통합대기 및 강수/최고/최저온도 레이블 처리
  * Global 통합대기 레이블 hidden을 true로 설정
  * 강수/최고/최저온도 레이블 2번째/3번째 라인 가운데 위치
  * 폰트 사이즈 및 label size/위치 조정
* Global weather data를 위한 today dictionary 처리
  * getTodayDictionaryInGlobal 함수 생성

**Comment by seankim2** [comment]
* getTodayDictionaryInGlobal 함수를 통해 daily에서 오늘의 dictionary를 추출
  * 최고/최저 온도 출력됨을 확인함
* 강수확률 precProb key로 추출
  * New York 내일 날씨에서 확인 가능함

**Comment by seankim2** [comment]
* 강수확률 정상적으로 처리됨을 확인함
* processLocationStr를 통해 소수점 2자리로 표현해서 NSDefaults에 저장하여 Query 하도록 처리
* 소수점 2자리로 변환되었다면 Skip하는 조건 추가

**Comment by seankim2** [comment]
* Latitude 소수점 2자리 parsing 과정에서 아래 에러 발생
```
-[__NSCFNumber componentsSeparatedByString:]: unrecognized selector sent to instance 0x17002c340
2017-02-25 13:37:08.830599 widget[3433:1271925] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber componentsSeparatedByString:]: unrecognized selector sent to instance 0x17002c340'
*** First throw call stack:
(0x1936491b8 0x19208055c 0x193650268 0x19364d270 0x19354680c 0x1000708f0 0x10007279c 0x10007250c 0x193c4b368 0x193c632a0 0x194137fb0 0x19407caa8 0x19406d0a4 0x19413a35c 0x1924d21bc 0x1924e03dc 0x1924d59a4 0x1924e234c 0x1924e20ac 0x1926db2a0 0x1926dad8c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
* NSDefault에서 받은 것은 NSNumber로 치환되기에 componentsSeparatedByString를 사용하기 위해서는 String으로 변환해야함

**Comment by seankim2** [comment]
* 소수점 두자리로 정상적으로 처리 됨을 확인함
```
[requestAsyncByURLSession] url : https://tw-wzdfac.rhcloud.com/ww/010000/current/2?gcode=40.71,-74.00
```
* NSDefault에 저장하던 부분을 기존대로 저장 하고, URL요청하는 부분에서 소수점 2자리로 수정하는 것으로 수정

**Comment by seankim2** [comment]
* 날짜별 데이터 draw를 위해 get/set current country함수 생성
* 기존 어제/오늘/내일... daily array를 조건 별로 분기하여 처리
* Global은 daily항목의 첫 array부터 6개 추출하여 어제/오늘/내일/... 수집
* country에 따라 C/F를 구분하여 온도 표시 추가

**Comment by seankim2** [comment]
* 현재 날씨 최저/최고 온도가 어제날짜 온도로 표시됨
  * 현재날씨 두번째 index로 변경함. 두번째 array가 오늘 현재 날씨임.
* 현재 최저/최고 온도가 반대로 표시되는 이슈 수정
* skyIcon 정상적으로 파싱되고, 표시됨을 확인함
* 날짜별 날씨 아이콘/날짜/최고/최저온도 정상적으로 draw됨을 확인함

**Comment by seankim2** [comment]
* 시간별 데이터를 Global drawing 하는 processByTimeData 함수 수정
* getByTimeArray 함수 Global 시간별 데이터를 처리할 수 있도록 수정
  * date를 비교할 수 있도록 string 분리 및 merge 처리

**Comment by seankim2** [comment]
* thisTime Array 이 하나만 오는 경우가 있음
  * 하나인경우에 대한 에러 처리
* 시간별 날씨 처리함
* 온도 표시는 소수점 1자리까지 처리

**Comment by seankim2** [comment]
* 추가적으로 해야할 일
  * 현재 장소처리
  * null일때 공백 표시 처리
  * 글로벌시에 강수확률/ 최고/최저 표시를 나누어서 (통합대기란에 강수확률/ 아래칸에는 최고/최저온도 표시)

**Comment by seankim2** [comment]
* 현재 위치를 가져오는 부분에서 KR과 그외지역을 구분
* current position 은 true인데 현재위치를 못찾는 경우에 대한 예외처리

**Comment by seankim2** [comment]
* 오늘 최고/최저온도 소수점 자리 없이 표시로 변경
* 위도/경도를 사용하여 Google로 부터 위치정보 얻는 getAddressFromGoogle function 생성 
  * global address를 파싱하는 함수 생성

**Comment by seankim2** [comment]
* services.js 의  getGeoInfoFromGoogle의 분석 중 sublocality가 없음... 한참찾았음 ㅠㅠ 이전 소스였음 ㅋ 
* 다시 업데이트 후 getGeoInfoFromGoogle와 유사하게 objective-c 형식으로 변형하여야함
* updated된 소스상에서는 sublocality 정보를 얻는 로직 찾음

**Comment by seankim2** [comment]
* 기존 현재위치를 을 얻는 로직에서 미리 NSDefaults에서 얻어진 country로 KR과 Global에 대한 처리를 분기하였음
  * 하지만 현재위치는 위젯에서도 변할 수 있기에 Google API로 먼저 country를 분기하여 처리해야함
  * 따라서 기존 Daum을 통해 처리하지 않고, 먼저 구글을 통해 파싱 후 KR과 글로벌을 분기하여
    * KR이면 그때 기존대로 Daum을 통해 처리
    * Global이면 새로운 함수를 처리하도록 구현해야함

**Comment by seankim2** [comment]
* 현재 위치를 얻는 부분에서 수정에 따른 아래 에러 발생됨
```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 2 beyond bounds [0 .. 1]'
*** First throw call stack:
(0x18b9311b8 0x18a36855c 0x18b80c7f4 0x1000bc834 0x1000bbe90 0x1000bbc68 0x18bf33368 0x18bf4b2a0 0x18c41ffb0 0x18c364aa8 0x18c3550a4 0x18c42235c 0x18a7ba1bc 0x18a7c83dc 0x18a7bd9a4 0x18a7ca34c 0x18a7ca0ac 0x18a9c32a0 0x18a9c2d8c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
* address_components count 만큼만 type을 처리하도록 수정

**Comment by seankim2** [comment]
* KR이 나올시에는 주소 parsing하는 로직을 사용하면 기존 함수로 처리하기엔 잘못된 Address가 나옴
  * '선동 하남시 KR'로 request 하게됨
* 따라서 country만 parsing하여 기존처럼 Daum API사용하여 처리함. 정상적으로 표기됨
  * 경기도/하남시/미사동 으로 request 할 수 있음

**Comment by seankim2** [comment]
* locationManager(위/경도 get function)에서 국가별 분리 로직 삭제
* Global 테스트를 위해 뉴욕 위/경도 를 강제로 assign 후 테스트 진행
```
#if 1 //GLOBAL_TEST
    // FIXME - for emulator - delete me
    double lat = 40.7127837;
    double longi = -74.0059413;
    
    //https://maps.googleapis.com/maps/api/geocode/json?latlng=40.7127837,-74.0059413
    
    NSString *nssURL = [NSString stringWithFormat:@"%@%g,%g", STR_GOOGLE_COORD2ADDR_URL, lat, longi];
#else
    NSString *nssURL = [NSString stringWithFormat:@"%@%g,%g", STR_GOOGLE_COORD2ADDR_URL, latitude, longitude];
#endif
```
* 뉴욕 위/경도로 주소를 뽑아냈지만 url을 만들어 내는 과정에서 null로 처리됨...  한글 URL을 헥사로 입력해야되나... 디버깅이 필요...
```
017-03-09 23:24:35.249271 widget[452:48531] [requestAsyncByURLSession] url : https://maps.googleapis.com/maps/api/geocode/json?latlng=40.7128,-74.0059, type : 2
2017-03-09 23:24:35.347619 widget[452:48614] [parseGlobalAddress] Get locations by using name!!! nssAddress :  맨해튼 뉴욕 US
2017-03-09 23:24:35.347763 widget[452:48614] [getGeocodeFromGoogle] url : https://maps.googleapis.com/maps/api/geocode/json?address= 맨해튼 뉴욕 US
2017-03-09 23:24:35.347857 widget[452:48614] [requestAsyncByURLSession] url : (null), type : 3
2017-03-09 23:24:35.406786 widget[452:48614] Failed to fetch (null): Error Domain=NSURLErrorDomain Code=-1002 "지원되지 않는 URL" UserInfo={NSLocalizedDescription=지원되지 않는 URL, NSUnderlyingError=0x174053ef0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}
```

**Comment by seankim2** [comment]
* characterSet을 이용하여  address를 URL에 맞게 encode
```
NSCharacterSet *set = [NSCharacterSet URLHostAllowedCharacterSet];
NSString *nssEncAddress = [nssAddress stringByAddingPercentEncodingWithAllowedCharacters:set];
NSString *nssURL = [NSString stringWithFormat:@"%@%@", STR_GOOGLE_ADDR2COORD_URL, nssEncAddress];
```
* unsupported URL 에러는 지나갔으나 parsing하는 부분에서 또 다른 에러 발생
```
[requestAsyncByURLSession] url : https://maps.googleapis.com/maps/api/geocode/json?address=%20%EB%A7%A8%ED%95%B4%ED%8A%BC%20%EB%89%B4%EC%9A%95%20US, type : 3
2017-03-10 23:32:44.935892 widget[1403:301595] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayI objectAtIndex:]: index 2 beyond bounds [0 .. 1]'
*** First throw call stack:
(0x1895711b8 0x187fa855c 0x18944c7f4 0x1000d5888 0x1000d3d40 0x1000d3aec 0x189b73368 0x189b8b2a0 0x18a05ffb0 0x189fa4aa8 0x189f950a4 0x18a06235c 0x1883fa1bc 0x1884083dc 0x1883fd9a4 0x18840a34c 0x18840a0ac 0x1886032a0 0x188602d8c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by seankim2** [comment]
* 아래 결과를 parsing하는 과정에서 생긴 에러임. 
```
https://maps.googleapis.com/maps/api/geocode/json?address=%20%EB%A7%A8%ED%95%B4%ED%8A%BC%20%EB%89%B4%EC%9A%95%20US
```
  * nil 체크를 통한 exception 처리
* reuslts를 parsing하는 과정에서 추가 에러 발생
```
 -[__NSSingleObjectArrayI objectForKey:]: unrecognized selector sent to instance 0x1700051e0
2017-03-12 22:13:30.393363 widget[2539:699907] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSSingleObjectArrayI objectForKey:]: unrecognized selector sent to instance 0x1700051e0'
*** First throw call stack:
(0x1895711b8 0x187fa855c 0x189578268 0x189575270 0x18946e80c 0x10008241c 0x100080be4 0x100080990 0x189b73368 0x189b8b2a0 0x18a05ffb0 0x189fa4aa8 0x189f950a4 0x18a06235c 0x1883fa1bc 0x1884083dc 0x1883fd9a4 0x18840a34c 0x18840a0ac 0x1886032a0 0x188602d8c)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by seankim2** [comment]
* 구글 결과에서 '[' 는 배열이므로 NSDictionary가 아닌 NSArray로 처리해야함
* 에러 없이 정보들을 draw했으나, 현재 city information이 제대로 업데이트 되지 않아서 US 이지만 KR로 단위등이 draw됨
* name, address, country, location이 메모리에 update되는 로직을 추가 해야함

**Comment by seankim2** [comment]
* parseGlobalAddress에서는 현재 name, address, country를 mCityDictList array에 현재 정보를 갱신
* parseGlobalGeocode에서는 현재 location을 update 함으로 써 현재 위치 정보들을 갱신
* 정상적으로 address와 현재 온도, 최고, 최저온도를 표시함
* 날짜별/시간별 데이터는 정상적이지 않음
  * 특히 시간별 데이터는 crash가 발생됨
```
*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSSingleObjectArrayI objectAtIndex:]: index 1 beyond bounds [0 .. 0]'
*** First throw call stack:
(0x1895711b8 0x187fa855c 0x189562420 0x1000726e4 0x10006e630 0x100077b14 0x1883fa1fc 0x1883fa1bc 0x1883fed68 0x18951e810 0x18951c3fc 0x18944a2b8 0x18aefe198 0x18f4917fc 0x18f48c534 0x18864fcc8 0x188651944 0x18a1963c4 0x191c42128 0x191c41c90 0x191c4214c 0x18a17c0d4 0x18842d5b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by seankim2** [comment]
* temperature unit을 얻기 위한 함수인 getCurCountry에서 멤버 변수인 curCountry를 제대로 업데이트 하지 않아  US인데도 불구 하고 섭씨 온도로 표시 되었음. 
* update시에 해당 멤버값도 갱신되도록 수정하여 정상적으로 표시됨.

**Comment by seankim2** [comment]
* thisTime array가 하나만 들어오는 경우가 있기에 아래와 같이 count 계산후 처리가 필요
```
if([arrThisTime count] == 2)
            currentDict         = [arrThisTime objectAtIndex:1];        // Use second index; That is current weahter.
else
            currentDict         = [arrThisTime objectAtIndex:0];        // process about thisTime
```

**Comment by kimalec** [comment]
thisTime array문제는 버그이긴한데, 위와 같이 해두어도 문제는 없을 것 같습니다.

**Comment by seankim2** [comment]
* 값이 없을시 (null)로 표시되는 부분 모두 공백으로 표시
  * 업데이트 시간
  * 도시 이름 ( 화살표 포함)
  * 통합대기값 (KR 일때)

**Comment by seankim2** [comment]
* requestURL 은 "https://todayweather.wizardfactory.net/v000705/town"(address가 하나도 없음)  이고, 데이터는 null인 경우가 발생됨
* current position 하나와 일반도시 지정후 도시를 변경하면 재현됨
  * 로그는 아래와 같음
```
et city : current position false, address 대한민국경기도고양시일산동구마두동 index 1, name : 마두동, country : KR
2017-03-15 22:56:57.813038 widget[1239:284450] All air state is same!!! khaiGrade(0), pm10Grade(0), pm25Grade(0)
2017-03-15 22:56:57.813865 widget[1239:284450] yesterdayDate : 20170314
2017-03-15 22:56:57.814036 widget[1239:284450] Expected string is : (
    "\Ub300\Ud55c\Ubbfc\Uad6d\Uacbd\Uae30\Ub3c4\Uace0\Uc591\Uc2dc\Uc77c\Uc0b0\Ub3d9\Uad6c\Ub9c8\Ub450\Ub3d9"
)
2017-03-15 22:56:57.814160 widget[1239:284450] [requestAsyncByURLSession] url : https://todayweather.wizardfactory.net/v000705/town, type : 4
2017-03-15 22:56:57.814386 widget[1239:284450] nssURL : https://todayweather.wizardfactory.net/v000705/town
```

**Comment by seankim2** [comment]
* 메인 앱으로 들어갔다가 UserDefault를 다시 update후에는 정상적으로 뿌려짐
* 로그는 아래와 같음
```
 set city : current position false, address 대한민국 경기도 고양시 일산동구 마두동 index 1, name : 마두동, country : KR
2017-03-15 23:06:43.473765 widget[1239:284450] nsdWeatherInfo is NULL!!!
2017-03-15 23:06:43.473943 widget[1239:284450] Expected string is : (
    "\Ub300\Ud55c\Ubbfc\Uad6d",
    "\Uacbd\Uae30\Ub3c4",
    "\Uace0\Uc591\Uc2dc",
    "\Uc77c\Uc0b0\Ub3d9\Uad6c",
    "\Ub9c8\Ub450\Ub3d9"
)
2017-03-15 23:06:43.474085 widget[1239:284450] [requestAsyncByURLSession] url : https://todayweather.wizardfactory.net/v000705/town/%EA%B2%BD%EA%B8%B0%EB%8F%84/%EA%B3%A0%EC%96%91%EC%8B%9C%EC%9D%BC%EC%82%B0%EB%8F%99%EA%B5%AC/%EB%A7%88%EB%91%90%EB%8F%99, type : 4
2017-03-15 23:06:43.474276 widget[1239:284450] nssURL : https://todayweather.wizardfactory.net/v000705/town/%EA%B2%BD%EA%B8%B0%EB%8F%84/%EA%B3%A0%EC%96%91%EC%8B%9C%EC%9D%BC%EC%82%B0%EB%8F%99%EA%B5%AC/%EB%A7%88%EB%91%90%EB%8F%99
```

**Comment by seankim2** [comment]
* 주소에서 (null)값이 그대로 보임
  * 주소값에 nil 체크 뿐만아니라 실제 string이 '(null)'로 들어가는 경우도 empty처리해야함
  * nextCity 버튼도 hidden시켜야함
* 현재온도도 값이 없을시에는 0으로 표시하는 것이 아니라 empty로 draw해야함
* KR 일때 통합대기가 '(null)'로 표시되는 부분도 처리

**Comment by seankim2** [comment]
* 메인앱에서 정상적으로 '대한민국 경기도 고양시 일산동구 마두동' 으로 값이 들어왔지만, save 할때는 '대한민국경기도고양시일산동구마두동'로 붙어져 들어옴
```
2017-03-18 22:29:49.791631 widget[363:30229] set city : current position false, address 대한민국 경기도 고양시 일산동구 마두동 index 1, name : 마두동, country : KR
...
2017-03-18 22:29:49.793301 widget[363:30229] Expected string is : (
    "\Ub300\Ud55c\Ubbfc\Uad6d",
    "\Uacbd\Uae30\Ub3c4",
    "\Uace0\Uc591\Uc2dc",
    "\Uc77c\Uc0b0\Ub3d9\Uad6c",
    "\Ub9c8\Ub450\Ub3d9"
)
2017-03-18 22:29:49.793554 widget[363:30229] [requestAsyncByURLSession] url : https://todayweather.wizardfactory.net/v000705/town/%EA%B2%BD%EA%B8%B0%EB%8F%84/%EA%B3%A0%EC%96%91%EC%8B%9C%EC%9D%BC%EC%82%B0%EB%8F%99%EA%B5%AC/%EB%A7%88%EB%91%90%EB%8F%99, type : 4
2017-03-18 22:29:49.793869 widget[363:30229] nssURL : https://todayweather.wizardfactory.net/v000705/town/%EA%B2%BD%EA%B8%B0%EB%8F%84/%EA%B3%A0%EC%96%91%EC%8B%9C%EC%9D%BC%EC%82%B0%EB%8F%99%EA%B5%AC/%EB%A7%88%EB%91%90%EB%8F%99
2017-03-18 22:29:49.795988 widget[363:30229] save first city of list
2017-03-18 22:29:50.735340 widget[363:31240] [saveWeatherInfo] nssAddress: 대한민국경기도고양시일산동구마두동
```
* 그 이후부터는 공백(' ')으로 parsing 해야하는 데 못하기 때문에 weather정보를 제대로 못얻어옴

**Comment by seankim2** [comment]
* KR에 대해서는 Global과 동일하게 address를 처리해서는 안됨.
```
if(bIsKR == TRUE)
        {
            NSLog(@"KR is not modified address(%@)!!!", nssAddress);
        }
        else
        {
            NSLog(@"[saveWeatherInfo] the other country not KR nssAddress(%@)!!!", nssAddress);
            nssAddress = [nssAddress stringByReplacingOccurrencesOfString:@" " withString:@""];

            if(nssAddress != nil)
            {
                NSArray *chunks = [nssAddress componentsSeparatedByString: @","];
                nssAddress = [chunks objectAtIndex:0];  // New York or 맨해튼;
            }
            else
            {
                nssAddress = [NSString stringWithFormat:@"AddressEmpty"];
            }
        }
...
```
* 위와 같이 수정 후 정상동작함

**Comment by seankim2** [comment]
* 강수확률의 글자수가 다국어로 전환시 많기에 기존에 한 label에 최고/최저온도에 표시하던 것을 나누어 처리
* 강수확률이 있을시
  * 통합대기label에 강수확률, 최고/최저온도에는 단지 최고/최저만 표시
```
todayMaxMinTempLabel.frame  = CGRectMake(160, 50, 140, 25);
```
* 강수 확률이 없을시
  * 최고/최저 온도 Label을 가운데 위치 시키면서, 통합대기 Label은 hidden
```
curDustLabel.frame          = CGRectMake(160, 40, 138, 21);
...                
todayMaxMinTempLabel.frame  = CGRectMake(160, 65, 138, 21);
```

**Comment by seankim2** [comment]
* 강수확률이 없을시 KR 최고/최저 온도 표시-> 최저/최고로 변경

**Comment by seankim2** [comment]
* KR아닌 다국어로 변경했을 때 통합대기 value가 'Moderate'로 나오는 이슈 있음.

**Comment by seankim2** [comment]
* KR은 섭씨이므로 소수점 표시
* Global은 섭씨/화씨에 따라 소수점/정수 표시로 변경
* KR일때 강수확률과 최고/최저 온도 위치 변경

**Comment by seankim2** [comment]
**관련 이슈로 코멘트 이동 및 기존 코멘트 삭제** 
* 시간별 데이터도 섭씨/화씨 일때 구분해서 소수점/소수점없음 으로 표시
* 2개이상의 Favorite이 있을 때 다음 도시선택후에 시간별 데이터 변경안되는 이슈 수정
  * setCurJsonDict 함수에서 한 번 alloc된 이후에 대한 처리가 제대로 처리되지 않았음
  * 아래와 같이 수정
```
@@ -848,11 +848,15 @@ 
-- (void) setCurJsonDict:(NSDictionary *)dict
+- (void) setCurJsonDict:(NSMutableDictionary *)dict
 {
     if(curJsonDict == nil)
     {
-        curJsonDict = [[NSDictionary alloc] initWithDictionary:dict];
+        curJsonDict = [[NSMutableDictionary alloc] initWithDictionary:dict];
+    }
+    else
+    {
+        [curJsonDict setDictionary:dict];
     }
 }
```
* "최고/최저 온도 / 강수확률 / 통합 대기 텍스트 위치 ", "KR/Global", Phone Size등을 고려하여 Lable 위치 조정
  * label frame 위치 조정 부분 삭제
  * stroyboard에서 autoresizing 조정

**Comment by kimalec** [comment]
KR이라도 화씨일수 있습니다. 단위는 나라와 상관없이 동작해요.

**Comment by seankim2** [comment]
* 섭씨<->화씨 convert 함수 생성
*  NSDefaults의 units에 따라 섭씨/화씨를 결정
* 한국/일본/미국, 섭씨/화씨 테스트 완료.
