### ISSUE TITLE
iOS Widget 상세보기에서 온도 짤리는 문제

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1347]
<img width="359" alt="2017-01-20 10 41 51" src="https://cloud.githubusercontent.com/assets/6895272/22132431/56d835ae-defd-11e6-80a3-98e30d2e1c84.png">

**Comment by seankim2** [comment]
* 이슈를 해결하는 방안
  * 전체적인 font size를 줄여서. '...'이 나오지 않게 한다. 기준은 -888 / -888
  * width iphone5(320) 이하는 5일의 날씨정보, iphone6(375), 6+(414)는 6일의 날씨정보
  * 최고/최저온도를 위 아래로 표시한다.
* 추가로 전체적인 font size는 늘려야함 ( 아이폰 기본날씨앱 Size 정도)

**Comment by seankim2** [comment]
* Autosize로 ...표시 없이 데이터가 정상적으로 나오게 한다. 
  * 단, size가 줄어든다.
* 최대한 size가 변경없게 하기 위해 iphone5(width 320) 이하는 5개만 표시하게 함
  * showDailyWeatherAsWidth 함수 생성
  * 추가적으로 5days의 정렬이 필요함

**Comment by seankim2** [comment]
* width 320 이하는 5개만 표시하도록 조정
  * 마지막 날씨는 hidden후 소스 코드상으로 조정
![image uploaded from ios](https://cloud.githubusercontent.com/assets/8072056/22404247/2d5d6eea-e670-11e6-9225-eae39470d8df.jpg)
