### ISSUE TITLE
홍보용 동영상 제작.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#139]
서비스 설명용으로 사용할 홍보용 동영상 제작.

**Comment by kimalec** [comment]
동영상 촬영장소

https://www.ckl.or.kr:446/www/main/userMain/main.do

**Comment by kimalec** [comment]
#101 에 연계된 이슈.

**Comment by kimalec** [comment]
시나리오 구상 및 참고할만한 동영상 search 필요.

**Comment by kimalec** [comment]
https://youtu.be/YatmXO98VjY - yahoo weather introduction
https://youtu.be/YmcHp-rjkqs - kweather
https://youtu.be/SSzn0WSJlX0 - Weather Clock Widget
https://youtu.be/2VyhIipHI14 - 날씨
https://youtu.be/4nZglAtvC0E - weather live

**Comment by kimalec** [comment]
시나리오 초안
![kakaotalk_20151001_140847391](https://cloud.githubusercontent.com/assets/6895272/10213938/272910de-684e-11e5-80b0-24fdae94fa18.jpg)
1)
![kakaotalk_20151001_143657734](https://cloud.githubusercontent.com/assets/6895272/10213945/39d0e1da-684e-11e5-973a-f69da07e3636.jpg)
2)
![kakaotalk_20151001_143659321](https://cloud.githubusercontent.com/assets/6895272/10213946/3d04e4a0-684e-11e5-9e19-c00878857739.jpg)
3)
![kakaotalk_20151001_143701123](https://cloud.githubusercontent.com/assets/6895272/10213947/413a889a-684e-11e5-878e-fbdd0d416b32.jpg)
4)
![kakaotalk_20151001_143702793](https://cloud.githubusercontent.com/assets/6895272/10213949/459659dc-684e-11e5-9e8c-d628cdd13305.jpg)

1번에서 2번씬으로 넘어가는 부분이 매끄럽지 못 하여 구상중.
@kimalec은 어제:20도 + 오늘:15도 = 어제:반팔 + 오늘:긴팔 이런 느낌도 생각했는데 이게 좋을지 @joljel 의 기존 생각하는 방향이 더 좋은지 ...

**Comment by joljel** [comment]
![11](https://cloud.githubusercontent.com/assets/14917457/10218010/c116a182-686e-11e5-8a60-0464ee3b8aa8.jpg)
![12](https://cloud.githubusercontent.com/assets/14917457/10218018/cdef4a58-686e-11e5-8690-931878977e77.jpg)
![13](https://cloud.githubusercontent.com/assets/14917457/10218021/d145b994-686e-11e5-834a-16b4b41b8e48.jpg)
![14](https://cloud.githubusercontent.com/assets/14917457/10218022/d4de8a2c-686e-11e5-9b22-5ef7c9b4aac6.jpg)
![15](https://cloud.githubusercontent.com/assets/14917457/10218024/d72a1080-686e-11e5-9e71-ba8731d237e9.jpg)
2차 수정 1안)

**Comment by joljel** [comment]
![21](https://cloud.githubusercontent.com/assets/14917457/10218031/e3edb128-686e-11e5-8ad4-c008b5160e36.jpg)
![22](https://cloud.githubusercontent.com/assets/14917457/10218034/e70cb5ca-686e-11e5-9ea2-125896b81fdc.jpg)
![23](https://cloud.githubusercontent.com/assets/14917457/10218037/e9703634-686e-11e5-8d1e-c812746cb685.jpg)
![24](https://cloud.githubusercontent.com/assets/14917457/10218039/eb719b12-686e-11e5-8d18-0db2905e2cc8.jpg)
![25](https://cloud.githubusercontent.com/assets/14917457/10218042/ed93aed0-686e-11e5-85ef-64e182027f15.jpg)

2차수정 2안)
-1안과 2안의 차이는 1,2번째 이미지 차이.

결론: 어제와 오늘이라는 시간개념이 좀더 명확해야 하며, 날씨와 온도를 둘다 보여주기 보다는 온도에 좀더 중점을 둬도 괜찮겠다는 의견.

**Comment by kimalec** [comment]
1차 완료하였으나, 약간 보정해야 publishing 예정

첫번째컷 움직이는 타이밍이랑 음 중간에 살짝 화면이 튀는 부분 수정 예정.

**Comment by kimalec** [comment]
https://www.youtube.com/watch?v=FdERlh0V0-8
