### ISSUE TITLE
short time에서 t3h가 0으로 오는 경우.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#145]
https://d2ibo8bwl7ifj5.cloudfront.net/town/경기도/성남시분당구/서현1동
으로 요청한 결과 아래와 같이, 20150923 의 0300, 0600,0900의 t3h가 0으로 오는 경우가 있음.
#138 과 같이 invaild data의 경우 0으로 오는 것으로 보임.

invaild value에 대한 처리 방법이 설정되면, client측에서도 반영하여 적용 필요함.

{"regionName":"경기도","cityName":"성남시분당구","townName":"서현1동","short":[{"date":"20150919","time":"0300","pop":20,"pty":0,"r06":0,"reh":82,"s06":0,"sky":1,"t3h":16,"tmn":0,"tmx":0},{"date":"20150919","time":"0600","pop":20,"pty":0,"r06":0,"reh":86,"s06":0,"sky":3,"t3h":15,"tmn":14,"tmx":0},{"date":"20150919","time":"0900","pop":10,"pty":0,"r06":0,"reh":59,"s06":0,"sky":1,"t3h":21,"tmn":0,"tmx":0},{"date":"20150919","time":"1200","pop":10,"pty":0,"r06":0,"reh":46,"s06":0,"sky":2,"t3h":25,"tmn":0,"tmx":0},{"date":"20150919","time":"1500","pop":10,"pty":0,"r06":0,"reh":38,"s06":0,"sky":2,"t3h":27,"tmn":0,"tmx":28},{"date":"20150919","time":"1800","pop":10,"pty":0,"r06":0,"reh":49,"s06":0,"sky":1,"t3h":24,"tmn":0,"tmx":0},{"date":"20150919","time":"2100","pop":0,"pty":0,"r06":0,"reh":70,"s06":0,"sky":1,"t3h":20,"tmn":0,"tmx":0},{"date":"20150920","time":"0000","pop":0,"pty":0,"r06":0,"reh":78,"s06":0,"sky":1,"t3h":18,"tmn":0,"tmx":0},{"date":"20150920","time":"0300","pop":0,"pty":0,"r06":0,"reh":83,"s06":0,"sky":1,"t3h":17,"tmn":0,"tmx":0},{"date":"20150920","time":"0600","pop":0,"pty":0,"r06":0,"reh":87,"s06":0,"sky":1,"t3h":15,"tmn":14,"tmx":0},{"date":"20150920","time":"0900","pop":0,"pty":0,"r06":0,"reh":68,"s06":0,"sky":2,"t3h":20,"tmn":0,"tmx":0},{"date":"20150920","time":"1200","pop":10,"pty":0,"r06":0,"reh":51,"s06":0,"sky":2,"t3h":25,"tmn":0,"tmx":0},{"date":"20150920","time":"1500","pop":10,"pty":0,"r06":0,"reh":42,"s06":0,"sky":2,"t3h":27,"tmn":0,"tmx":28},{"date":"20150920","time":"1800","pop":10,"pty":0,"r06":0,"reh":51,"s06":0,"sky":3,"t3h":25,"tmn":0,"tmx":0},{"date":"20150920","time":"2100","pop":10,"pty":0,"r06":0,"reh":72,"s06":0,"sky":1,"t3h":20,"tmn":0,"tmx":0},{"date":"20150921","time":"0000","pop":10,"pty":0,"r06":0,"reh":84,"s06":0,"sky":1,"t3h":17,"tmn":0,"tmx":0},{"date":"20150921","time":"0300","pop":0,"pty":0,"r06":0,"reh":89,"s06":0,"sky":1,"t3h":15,"tmn":0,"tmx":0},{"date":"20150921","time":"0600","pop":0,"pty":0,"r06":0,"reh":90,"s06":0,"sky":1,"t3h":14,"tmn":14,"tmx":0},{"date":"20150921","time":"0900","pop":0,"pty":0,"r06":0,"reh":71,"s06":0,"sky":1,"t3h":21,"tmn":0,"tmx":0},{"date":"20150921","time":"1200","pop":0,"pty":0,"r06":0,"reh":48,"s06":0,"sky":1,"t3h":26,"tmn":0,"tmx":0},{"date":"20150921","time":"1500","pop":0,"pty":0,"r06":0,"reh":43,"s06":0,"sky":1,"t3h":27,"tmn":0,"tmx":28},{"date":"20150921","time":"1800","pop":0,"pty":0,"r06":0,"reh":54,"s06":0,"sky":1,"t3h":26,"tmn":0,"tmx":0},{"date":"20150921","time":"2100","pop":0,"pty":0,"r06":0,"reh":76,"s06":0,"sky":1,"t3h":20,"tmn":0,"tmx":0},{"date":"20150922","time":"0000","pop":0,"pty":0,"r06":0,"reh":85,"s06":0,"sky":1,"t3h":18,"tmn":0,"tmx":0},{"date":"20150922","time":"0300","pop":0,"pty":0,"r06":0,"reh":90,"s06":0,"sky":1,"t3h":16,"tmn":0,"tmx":0},{"date":"20150922","time":"0600","pop":0,"pty":0,"r06":0,"reh":91,"s06":0,"sky":1,"t3h":16,"tmn":15,"tmx":0},{"date":"20150922","time":"0900","pop":0,"pty":0,"r06":0,"reh":62,"s06":0,"sky":1,"t3h":22,"tmn":0,"tmx":0},{"date":"20150922","time":"1200","pop":0,"pty":0,"r06":0,"reh":46,"s06":0,"sky":1,"t3h":27,"tmn":0,"tmx":0},{"date":"20150922","time":"1500","pop":0,"pty":0,"r06":0,"reh":41,"s06":0,"sky":1,"t3h":28,"tmn":0,"tmx":28},{"date":"20150922","time":"1800","pop":0,"pty":0,"r06":0,"reh":53,"s06":0,"sky":1,"t3h":26,"tmn":0,"tmx":0},{"date":"20150922","time":"2100","pop":10,"pty":0,"r06":0,"reh":76,"s06":0,"sky":2,"t3h":21,"tmn":0,"tmx":0},{"date":"20150923","time":"0000","pop":10,"pty":0,"r06":0,"reh":85,"s06":0,"sky":2,"t3h":18,"tmn":0,"tmx":0},{"date":"20150923","time":"0300","pop":0,"pty":0,"r06":0,"reh":0,"s06":0,"sky":0,"t3h":0,"tmn":0,"tmx":0},{"date":"20150923","time":"0600","pop":0,"pty":0,"r06":0,"reh":0,"s06":0,"sky":0,"t3h":0,"tmn":0,"tmx":0},{"date":"20150923","time":"0900","pop":0,"pty":0,"r06":0,"reh":0,"s06":0,"sky":0,"t3h":0,"tmn":0,"tmx":0}],"current":{"date":"20150921","time":"0400","mx":62,"my":123,"t1h":15,"rn1":0,"sky":1,"uuu":0,"vvv":0,"reh":90,"pty":0,"lgt":0,"vec":117,"wsd":0}}

**Comment by kimalec** [comment]
어떤 경우에 -50으로 오는 경우도 있던데, data.go.kr에 아직 미정인 값을 -50으로 줄수 있는지 확인또는 0으로 오는 경우에 invaild한 것인지 어떻게 구분하는지 확인 필요해보임.

**Comment by nammaste6** [comment]
안녕하세요. 공공데이터포털 운영팀입니다.

T3H값이 누락되어 표시되는 장애관련하여 기상청에도 인지하고 있으며,
관련 정보는 현재 정상화를 위해 계획중으로 전달받았습니다.

관련하여 정상화 완료 시 재답변 드리겠습니다.

서비스 이용에 불편을 드려 죄송합니다.

**Comment by kimalec** [comment]
"누락되어 표시되는 장애" 라는 것이 "0"을 의미을 하나요? 아니면 "-50"을 의미하나요?

**Comment by kimalec** [comment]
아침 지금 시각으로 원기날씨앱의 경우 모레 24시까지 데이터가 모두 정확히 표시되고 있어요 우리는 지금 시간에 모레 3시부터 테이터가 0으로 9시까지 밖에 안오지 않을까 싶네요. 우리가 모르는 뭔가가 좀 더 있는거 같아요

**Comment by kimalec** [comment]
작년4월부터 늘어난 것으로 보임.
http://www.onkweather.com/bbs/board.php?bo_table=economy3&wr_id=701 - 기상청, 동네예보 기간 2일에서 3일로 확대 - 온케이웨더

**Comment by nammaste6** [comment]
0을 의미합니다

**Comment by kimalec** [comment]
공공데이터포털 운영팀입니다.

동네예보정조보회의 단기예보 호출 시 예보값이 0으로 출력되는 내용에 대해 기관에 
메일로 문의하였으며 기관에 답변 확인 후 재안내 하여 드릴 수 있도록 하겠습니다.

----

그 상황이 보이면, 시간 지나면 변경되는지 살펴볼께요.  혹시 사용중에 그런 증상이 보이면 신고(?)해주세요.

**Comment by kimalec** [comment]
https://d2ibo8bwl7ifj5.cloudfront.net/town/경기도/성남시수정구/양지동
http://todayweather1-wizardfactory.rhcloud.com/town/경기도/성남시수정구/양지동

위 두개의 링크의 경우에는 끝부분에 3개가 0으로 되어 있음.
{"date":"20151015","time":"1500","pop":0,"pty":0,"r06":0,"reh":0,"s06":0,"sky":0,"t3h":0,"tmn":0,"tmx":0},{"date":"20151015","time":"1800","pop":0,"pty":0,"r06":0,"reh":0,"s06":0,"sky":0,"t3h":0,"tmn":0,"tmx":0},{"date":"20151015","time":"2100","pop":0,"pty":0,"r06":0,"reh":0,"s06":0,"sky":0,"t3h":0,"tmn":0,"tmx":0}

반면에 아래 두개의 링크의 경우에는 정상적으로 데이타가 보임.

{"date":"20151015","time":"1500","pop":20,"pty":0,"r06":0,"reh":32,"s06":0,"sky":3,"t3h":22,"tmn":0,"tmx":22},{"date":"20151015","time":"1800","pop":20,"pty":0,"r06":0,"reh":47,"s06":0,"sky":3,"t3h":18,"tmn":0,"tmx":0},{"date":"20151015","time":"2100","pop":10,"pty":0,"r06":0,"reh":72,"s06":0,"sky":2,"t3h":14,"tmn":0,"tmx":0}],"shortest":{"date":"20151013","time":"1830","mx":63,"my":124,"pty":0,"rn1":0,"sky":1,"lgt":0},"current":


http://todayweather1-wizardfactory.rhcloud.com/town/경기도/성남시수정구/양지동
http://newsky2.kma.go.kr/service/SecndSrtpdFrcstInfoService/ForecastSpaceData?serviceKey=fE6avSm9apnXtX3vepLv0ubPaccc6dmaxQP%2F9y2JNNJ5t16jM7EYF2Jw9wnkKjUFwLqt2yl8u48yFb1ZqzWxWw%3D%3D&base_date=20151013&base_time=1700&nx=63&ny=124&pageNo=1&numOfRows=999

**Comment by kimalec** [comment]
provider로 부터 데이터를 받아, 디비에 저장하기 전에 reh와 pop, sky, pty, t3h가 모두 0인 경우 그 데이터는 버리도록 할 필요가 있습니다.
