### ISSUE TITLE
생활지수, 보건지수 지점정보(areaNo) 관리 및 쿼리 개선

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1512]
지수들은 한번 요청에 모두 데이터를 가지고 올 수 있음.
각 지점정보(areaNo)는 시간에 흐름에 따라 변경됨.

kmaIndexAreaInfo를 만들고, areaNo의 맞는 3개단계 이름, geolocation정보를 저장한다.
새로운 index정보가 들어오면, kmaIndexAreaInfo를 참고하여 areaNo의 3단계 이름을 찾고, geolocation을 찾아서 kmaLifeIndex, kmaHealthyIndex 정보에 같이 저장한다.
만약에 찾는 지점정보가 디비에 없으면 외부에서 찾아서(data.go.kr확인) 찾아서 3단계 이름, geolocation을 찾아 kmaIndexAreaInfo, kmaLifeIndex, kmaHealthyIndex에 저장한다.

client에서 요청이 들어오면 가장 가까운 위치에 정보를 제공한다.

#1511 #538 #1509

**Comment by kimalec** [comment]
법정동코드는 현재 API 제공하는 곳이 없어보임.
기상청 비공개? API는 존재하는데 데이터가 과거것임
참고 : http://uznam8x.tistory.com/8
17년 4월 20일 기준으로 2016-10-04일이 최신인데, 07-04일 데이터가 조회됨.

**Comment by kimalec** [comment]
행정표준코드 관리시스템 - 법정동 - 법정동 전체 코드 자료 에서 모두 받을 수 있음.

**Comment by kimalec** [comment]
이어도의 경우 법정도 전체코드자료에는 없지만, 5019099000 에 대한 보건지수는 오고 있음.

**Comment by kimalec** [comment]
운영하고 있는 디비 업데이트 해야 하나요?

**Comment by pokers** [comment]
업데이트 해야 해요.
$>node node ./utils/updateAreaNo.js

그리고, 아직 어느 DB 에도 없는 신규 areaNo에 대한 처리 (noti, db update)는 구현이 남아 있어서 어떻게 처리할지 고민중에 있고, 지금 pl된것만 해도 areano가 없는경우 geocode를 찾아서 가까운 areano 찾아주니까 운영상에 크게 문제 될건 없어 보이네요.

**Comment by kimalec** [comment]
지금 towns.js에 areaNo가 안 맞는 경우들이 종종 있는데, 이 경우 areaNo가 실제 데이터에 있으면 사용하고 없으면 위치 기반으로 찾는다는 이야기죠?

**Comment by pokers** [comment]
정리하자면
1. town.js에서 주소기준으로 areaNo 가져와서
2. 가져온 areaNo로 Health Day DB에서 데이터를 찾고,
3. 2번에서 Health Day DB내에 맞는 areaNo가 없으면,
4. modelAreaNo DB에서 주소기준으로 areaNo를 다시 가져와서
5. 4번에서 가져온 areaNo로 Health Day DB에서 데이터를 찾고,
6. 5번에서 Health Day DB에서 해당 areaNo로 찾을수 없으면,
7. 주소를 geocode로 받아서 geocode와 가장 가까운 areaNo를 modelAreaNo에서 찾고,
8. 찾은 areaNo를가지고 다시 Health Day DB에서 데이터를 찾는다.

**Comment by kimalec** [comment]
명령으로 업데이트 해봄
```
db.towns.update({"areaNo" : "4119957000"}, {$set: {"areaNo" : "4119086000"}});
```
