### ISSUE TITLE
[iOS][widget] 통합대기 Label이 사라지는 경우 발생

### ISSUE THREAD

**Issue by seankim2** [WizardFactory/TodayWeather#1521]
* 재현
  * widget에서 세계날씨와 KR을 동시에 favorite을 한경우
    * 세계날씨(예:키프러스)에 강수확률이 없는 경우 통합대기 Label에 강수확률을 draw한다.(label 정렬을 위해)
    *  그런데 hidden 된 상태로 계속 유지 되기에 한국의 날씨(수내동)으로 변경하자 기존에 나왔던 통합대기 label이 계속 hidden 상태로 유지 됨.

**Comment by seankim2** [comment]
* 해결책
  * 한국인 경우는 통합대기가 항상 표시되기에 static하게 통합대기 label을 hidden=false로 유지
  * 세계날씨인 경우 강수확률이 없을시에는 label을 hidden=true로 유지하고, 최고/최저온도를 가운데로 위치 이동하여 아름답게 만든다.

**Comment by seankim2** [comment]
* 통합대기 label을 가운데로 유지 해도 데이터가 별로 없기에 보기에 좋지 않음. 
** 세계날씨에서는 현재는 통합대기가 없지만, 추후 추가될 예정이기에, 통합대기레이블을 사용하여 강수 확률이 0이라도 0%로 표시하는 게 미관상 보기 좋음. 통합대기 지원전까지 현재상태로 유지
** 한국은 기존대로 강수 확률이 0이면, 최고/최저 온도가 있기때문에 외관상 문제없기에  강수확률을 제하고, 최고/최저온도만 표시

**Comment by kimalec** [comment]
- [ ] 한국인 경우에 항상 통합대기 표시하기 보다는 대기정보가 있는 경우에만 표시 하는게 어떨까요?

**Comment by seankim2** [comment]
* 대기정보가 없는 경우 그 레이블이 비워지면 보기가 안 좋은데... 음... 내일 회의시간에 의논해보도록 하지요. 의견에 보내진 대기정보 수치표시와 같이 의논해보도록 하져

**Comment by seankim2** [comment]
* 강수확률이 없는 경우에도 0%표시가 필요(빈공간이 있으면 보기에 안좋음)
* 통합대기가 생기는 경우에는 KR처럼 통합대기는 윗레이블에 표시하고, 아래에는 최고/최저, 강수확률(옵션)으로 처리

**Comment by seankim2** [comment]
* 강수확률이 없는 경우 0% 표시 구현
* Global 통합대기 지원시 label 위치 와 통합대기/최고/최저/강수확률 position 처리 예정
* 현재 이슈는 fix 되었으므로 close
