### ISSUE TITLE
중기 예보 정보를 Client에 전달 하는 REST API 부분 구현

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#154]
routeTownForecast.js 내부에 중기 예보 정보를 client에 전달해주는 REST API 구현.

**Comment by kimalec** [comment]
사용법은..

전국 날씨 요약 : http://todayweather1-wizardfactory.rhcloud.com/town/

광역시,도 날씨 요약: http://todayweather1-wizardfactory.rhcloud.com/town/{광역시,도}

시,군단위 주간 날씨 및 날씨 요약 : http://todayweather1-wizardfactory.rhcloud.com/town/{광역시,도}/{시,군}

동네별 전체 데이터 : http://todayweather1-wizardfactory.rhcloud.com/town/{광역시,도}/{시,군}/{동,읍,면}

http://todayweather1-wizardfactory.rhcloud.com/town/경기도/성남시분당구/수내3동 하면 기존 예보 데이터와, midData하부에 forecast(주간날씨 요약), land(날짜별 날씨), temp(날짜별 최고,최저 기온) 으로 채워져서 날라옵니다

중기예보 정보는 하루 2회 수집하고 오전 6시와 오후 6시입니다

**Comment by kimalec** [comment]
지금 cloudfront 거쳐서 요청하는데 상관없나요?

**Comment by kimalec** [comment]
현재 서비스는 클라우드프론트를 거처서 위의 주소가 아닌 http://todayweather2-wizardfactory.rhcloud.com/town/ 요놈이 호출 됨.

**Comment by kimalec** [comment]
지금 미래 3일부터 오는데, 과거 8일전부터 미래 10일까지 오는 형태로 보낼수 있게, 추가로 더 작업해야 하는거죠?

json format은 short와 비슷하면 좋은데 가능할지 모르겠네요.

추정 UI에서는 일별 예상 습도가 들어가는데, 일별 예상습도가 있는지 확인 부탁드려요.

**Comment by kimalec** [comment]
일별 예상습도와 강수확률은 없음. (UI 수정 필요)
