### ISSUE TITLE
검색 취소 기능

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1578]
현재위치로 검색하기 하거나, 사용자가 넣은 검색어를 한번에 취소할 수 있는 버튼 필요

- ~android의 경우 back button 적용~
  - [ ] start page 검색에 적용
  - [ ] locations page(favorite) 검색에 적용
- 검색어 오른쪽에 취소 버튼 추가
  - [ ] start page 검색에 적용
  - [ ] locations page(favorite) 검색에 적용

**Comment by skywlrl** [comment]
#1590 이슈에서 즐겨찾기에서 Edit 옆에 취소 버튼 추가됨
