### ISSUE TITLE
Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1597]
Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/Base.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/PlugIns/widget.appex/Base.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/PlugIns/widget.appex/de.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/PlugIns/widget.appex/ja.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/PlugIns/widget.appex/ko.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/PlugIns/widget.appex/zh-Hans.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/PlugIns/widget.appex/zh-Hant.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/de.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/ja.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/ko.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/zh-Hans.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

Unexpected CFBundleExecutable Key - The bundle at '/Payload/TodayWeather.app/zh-Hant.lproj/Info.plist' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

**Comment by seankim2** [comment]
* 다국어를 통해 자동으로 생성된 각 언어별 Info.plist에 포함된 CFBundleExecutable key로 인한 error로 추측됨
* 아래와 같이 해당 Key를 제거함으로 써 정상적으로 build 및 archive가 되었다고 함.
   * http://stackoverflow.com/questions/32096130/unexpected-cfbundleexecutable-key
   * http://vallista.tistory.com/entry/Unity3D-iOS-%EB%B9%8C%EB%93%9C-%EC%8B%9C-ERROR-ITMS90535-Unexpected-CFBundleExecutable-Key-The-Bundle-at-GooglePlusbundle-does-not-contain-a-bundle-this-Issues
   * http://stackoverflow.com/questions/42157006/unexpected-cfbundleexecutable-key-issue
* 해당 키 삭제후 테스트 필요

**Comment by seankim2** [comment]
* 현재 상태로 upload 후 에러발생
![2017-05-16 11 11 34](https://cloud.githubusercontent.com/assets/8072056/26111267/a0367eac-3a8f-11e7-868b-cd49ec154861.png)
* widget의 각 info.plist 및 TodayWeather-Info.plist 에서 Executable file 필드 삭제 
![2017-05-16 11 29 31](https://cloud.githubusercontent.com/assets/8072056/26111512/3eee8a12-3a90-11e7-9406-e2c6eb072881.png)
* version 0.9.45->0.9.46 변경 후에는 아래 에러 발생
![2017-05-16 11 33 05](https://cloud.githubusercontent.com/assets/8072056/26111515/4266f454-3a90-11e7-89eb-00ab6cb87bfc.png)

**Comment by seankim2** [comment]
* 같은 Version 의 Build 값이 같은 앱은 아이튠즈 커넥트에 등록 할 수 없다.
* 앱을 다시 등록 할 경우에 
  * Project > General > Identity > Build 를 수정해 주어야 한다. 
* Build의 버젼을 0.9.45.1로 변경
* Redundant Binary Upload 에러는 지나갔으나 ITMS-90207 에러 발생
![2017-05-16 11 52 01](https://cloud.githubusercontent.com/assets/8072056/26112398/bff0fb20-3a92-11e7-805a-2695b67b5685.png)

**Comment by seankim2** [comment]
* Widget의 Executable file만 삭제시 아래 에러 발생
![2017-05-17 12 03 39](https://cloud.githubusercontent.com/assets/8072056/26114101/61ef9702-3a97-11e7-8ee4-e120584f6dc6.png)
* Widget필드의 Bundle creator OS Type code 값을 ????->BNDL로 변경후 Archive upload completed 됨
![2017-05-17 12 23 44](https://cloud.githubusercontent.com/assets/8072056/26114169/8bb4d066-3a97-11e7-8c24-2d10b700b846.png)

**Comment by seankim2** [comment]
* 아래 Warning과의 연관성이 의심됨
```
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file
```
* 구글링후 아래와 같이 Copy Bundle Resources에서 Info.pList를 제거
  * https://developer.apple.com/library/content/qa/qa1649/_index.html
* warning 제거 후 정상적으로 upload 됨
