### ISSUE TITLE
[iOS][widget] 지역명 / 위젯타이틀 다국어 에러

### ISSUE THREAD

**Issue by seankim2** [WizardFactory/TodayWeather#1636]
![default](https://cloud.githubusercontent.com/assets/8072056/26826108/cc32d262-4af2-11e7-85c0-c9ffb2c816c0.jpg)
* 앱에서는 한글로 표시되지만, 위젯에서는 영문으로 표시됨
* 위젯 타이틀이 한글이 아닌 영문으로 표시됨

**Comment by kimalec** [comment]
앱의 경우 변수 네임이지만, 위젯의 경우 단순 영어 표기로 되어 있음.
<img width="549" alt="2017-08-08 06 55 12" src="https://user-images.githubusercontent.com/6895272/29047425-a41f608e-7c06-11e7-8a10-b426a8078c4f.png">
<img width="563" alt="2017-08-08 06 55 21" src="https://user-images.githubusercontent.com/6895272/29047472-c066ede8-7c06-11e7-979d-902df5d00cb7.png">

**Comment by seankim2** [comment]
* 최신버젼을 빌드만 한 상태에서 폰에 앱을 올려도 현재 '오늘날씨'로 표기됨.
* 위와 같이 Display Name을 TodayWeather에서 $(PRODUCT_NAME)으로 변경 후 해도 '오늘날씨'로 표기됨
* 아래 warning도 좀 의심스러움.
```
Warning: The Copy Bundle Resources build phase contains this target's Info.plist file 'widget/Base.lproj/Info.plist'.
```

**Comment by seankim2** [comment]
* Targets > widget > Build Phases > Copy Bundle Resources 에서 info.plist를 제거
  * 위 warning은 제거됨.
  * https://developer.apple.com/library/content/qa/qa1649/_index.html

**Comment by seankim2** [comment]
* Copy Bundle Resources에서 inf.plist제거 후 언어가 한글일때 'TodayWeather' 가 아닌 'WIDGET'으로 표시될 때도 있음...
* 앱내에서는 InfoPlist.strings를 사용하는데, widget에서는 그 파일이 생성되지 않음...
  * http://funnyrella.blogspot.kr/2013/12/74-application-localization.html
* Localizabel.strings에 CFBundleDisplayName을 사용해봤지만 상태는 동일함.
* Today Extention의 localization에 대해서 구글링을 더 해봐야함...

**Comment by seankim2** [comment]
* 앱에서와 마찬가지고 InfoPlist.strings를 추가하여 각 언어에 맞게 CFBundleDisplayName을 추가하니 정상적으로 표시됨
  * Info.plist의 Bundle Display Name에 각 언어별로 Display Name을 기재했었음
* 6개국어 확인 결과 정상적으로 변경됨을 확인함

**Comment by kimalec** [comment]
- [ ] 앱 아이콘 이름이 영어로 표시됨

**Comment by kimalec** [comment]
Target Mebership을 지정해주서야 함.
<img width="594" alt="2017-10-07 9 47 20" src="https://user-images.githubusercontent.com/6895272/31303247-2c0878f6-ab45-11e7-9af7-39837c8c14d7.png">

- [ ] 설정에 저장하게 수정적용 필요.
