### ISSUE TITLE
상세날씨, 생활지수 등 부가 정보들

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#166]
미세먼지 : 0
체감온도 : X
바람 방향 및 강도 : -
나들이 : X
자외선 : 0
빨래 : X
세차 : X
일출:일몰 : -
운동지수 : x
피부지수 : x
오존 : x
통합대기지수 : -

감기가능지수 : -
식중독지수: -
천식, 폐질환가증지수 : x
뇌졸증가능지수 : x

**Comment by kimalec** [comment]
추가 가능한 지수
감기가능지수 : -
식중독지수: -
천식, 폐질환가증지수 : x
뇌졸증가능지수 : x

**Comment by kkkiiikkii** [comment]
항시 : 미세먼지, 자외선, 빨래, 세차
이벤트 : 바람 및 강도, 감기지수, 식중독지수

**Comment by nammaste6** [comment]
자외선, 오존, 체감온도

**Comment by kimalec** [comment]
항시 : 미세먼지, 자외선, 바람 및 강도
이벤트 : 식중독, 감기, 나들이, 빨래, 세차

**Comment by skywlrl** [comment]
항시 : 체감온도, 일출:일몰, 바람 방향 및 강도
이벤트 : 미세먼지, 자외선, 오존

**Comment by pokers** [comment]
항시: 체감온도, 자외선, 미세먼지
이벤트: 오존, 식중독, 감기, 나들이

**Comment by kimalec** [comment]
항시 : 자외선(3,2) 미세먼지(3,1), 빨래(항시1,이벤트1),세차(항시1, 이벤트1), 체감온도(3표), 바람강도(2,1), 일출일몰(1) - 자외선, 미세먼지, 체감온도, 바람강도
이벤트:  감기(3), 식중독(3), 오존(2), 나들이(2), 빨래(1,1), 세차(1,1), 일출/일몰(1) - 감기, 식중독, 오존, 나들이, 빨래, 세차

**Comment by kimalec** [comment]
생활기상지수(기상청) - 동상가능지수, 식중독지수, 열지수, 동파가능지수, 부패지수, 자외선 지수, 체감온도, 대기확산지수, 불쾌지수

보건기상지수(기상청) - 뇌졸중가능지수, 감기지수, 꽃가루농도위험지수, 피부질환가능지수, 천식폐질환가능지수

**Comment by kimalec** [comment]
#10 바탕으로 추가

**Comment by kimalec** [comment]
식중독지수 - http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getFsnLifeList
6시, 18시에 오늘, 내일, 모레까지 발표됨.
위험(95), 경고(70), 주의(35), 관심(35)]
부패지수 -  http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getRotLifeList
6시 발표 3시간~66시간까지 높음(7), 보통(3~7), 낮음(~3)
체감온도 - http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getSensorytemLifeList
6시 발표 3시간~66시간까지 -45(위험), -25~45(경고), -10~-25(주의), 관심(~10)
불쾌지수 - http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/DsplsListRequest
3시 발표 3시간~66시간까지 80이상(매우높음), 75이상(높음), 68이상(보통), 60미만(낮음)
자외선지수 - http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/UltrvListRequest
7시 19시 발표 오늘,내일, 모레까지 위험(11이상), 매우높음(8이상), 높음(6이상), 보통(3이상), 낮음(0)

식중동(3월~11월), 부패(3~11월), 체감온도(11월~3월), 동상가능지수(12월 2월), 불쾌지수(6월~9월), 자외선 지수(3월~11월)

**Comment by kimalec** [comment]
보건지수, 생활기상지수 조회 개발용 계정 승인났습니다.

**Comment by kimalec** [comment]
http://203.247.66.146/contents/api_spec_kma2.html
openapi.kma.go.kr 이 203.247.66.146 안듯, domain연결안되지만, ip로 데이터를 가지고 올 수 있음.

식중독지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getFsnLifeList
부패지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getRotLifeList
체감온도	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getSensorytemLifeList
동상가능지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getFrostbiteLifeList
불쾌지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getDsplsLifeList
실효습도	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getHumidityLifeList
자외선지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getUltrvLifeList
황사영향지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getDustLifeList
대기오염소산지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getAirpollutionLifeList
감기지수	http://openapi.kma.go.kr/iros/RetrieveWhoIndexService/getInflWhoList

**Comment by kimalec** [comment]
http://kma.go.kr/HELP/basic/help_01_06.jsp - 각 지수에 대한 설명

**Comment by kimalec** [comment]
<img width="854" alt="default" src="https://cloud.githubusercontent.com/assets/6895272/10562363/77fe6db8-7593-11e5-908d-8d9829a24e59.png">

**Comment by kimalec** [comment]
바람 강도 뿐만 아니라,  방향까지 넣고, 숫자보다는 의미를 더 크게 하는게 좋을 것 같아요. 
사람들은 숫자보다는 의미를 더 잘 이해하니깐요.

**Comment by kkkiiikkii** [comment]
<img width="770" alt="2" src="https://cloud.githubusercontent.com/assets/12652131/10562643/9a33a7e6-75a1-11e5-92c6-891a7b6da961.png">

**Comment by kkkiiikkii** [comment]
수정버전~

**Comment by kimalec** [comment]
미세먼지 아이콘
![default](https://cloud.githubusercontent.com/assets/6895272/10708001/98ffdaaa-7a35-11e5-88df-63dce16255c7.png)
바람 아이콘
![default](https://cloud.githubusercontent.com/assets/6895272/10708000/98fd6db0-7a35-11e5-938f-27830c9f5979.png)
자외선 아이콘
![default](https://cloud.githubusercontent.com/assets/6895272/10708003/9900e5bc-7a35-11e5-9038-ea4c42cd6322.png)
체감온도 아이콘
![default](https://cloud.githubusercontent.com/assets/6895272/10708002/9900271c-7a35-11e5-9f3c-89934b0296ce.png)
----

**Comment by kimalec** [comment]
상세날씨 화면 가이드
![151018_ -01](https://cloud.githubusercontent.com/assets/6895272/10708083/491ed958-7a37-11e5-867a-c04c72542842.jpg)

**Comment by kimalec** [comment]
비오는 날 강수량을 표기 위한 우산 혹은 강수량(비온양)을 의미하는 아이콘 필요.

**Comment by kimalec** [comment]
비오는 날을 강수량 표시를 위한 우산 아이콘

![kakaotalk_photo_2015-11-22-09-30-03_2](https://cloud.githubusercontent.com/assets/6895272/11321294/a0603790-90fb-11e5-8c02-05083ee09bf1.png)
