### ISSUE TITLE
AQI 단위 변경 지원

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1699]
http://tw-test.wizardfactory.net/v000803/town/서울특별시?aqi=airkorea
단위종류
airkorea, airkorea_who, airnow

PM2.5, PM10, O3같은 개별 속성도 변경해야함.

참고 https://en.wikipedia.org/wiki/Air_quality_index

추후 메인 설정에서 단위 변경가능함.

기본 : 국내 airkorea_who, 국외 airnow

**Comment by pokers** [comment]
뭘 해야 하는지 명확하지가 않은데... 아래 두개가 필요하다는 얘기인가?

1. pm25, pm10,o3 등에 대한 각각의 grade와 string도 query로 오는 단위에 따라 계산해서 보정.
2. pm25, pm10등 대기 관련 수치들을 airkorea, airnow등에서 제공하는 수식으로 통합 air quality를 구해서 그에 따른 통합 grade 혹은 string 추가.

**Comment by kimalec** [comment]
맞아 그거임

**Comment by pokers** [comment]
AQI에서 제공하는 데이터는 아래의 설명과 동일한 것으로 보여짐..
* pm10, pm25는 24시간 평균.
* SO2, NO2, O3, CO 수치는 1시간 평균.
* 6개의 데이터 중 가장높은 수치를 기록한 것으로 AQI 수치를 나타냄.
![image](https://user-images.githubusercontent.com/10987524/28992825-f65e9b34-79e1-11e7-81a2-db0db657cb20.png)
[W020120410332725219541.pdf](https://github.com/WizardFactory/TodayWeather/files/1202105/W020120410332725219541.pdf)

**Comment by pokers** [comment]
AQI에서 제공하는 데이터의 단위를 모르겠음...ppb or ug/m3 ??

**Comment by pokers** [comment]
아래와 같이 MEP document의 일부를 보면 aqicn.org에서 제공해주는 데이터는 모두 ug/m3 으로 보여진다.

![image](https://user-images.githubusercontent.com/10987524/29000033-ae18cd32-7a99-11e7-9ac9-ed09126d18ca.png)

**Comment by pokers** [comment]
Airnow의 경우 아래 표와 같이 pm10, pm25를 제외하고 데이터의 계산은 bbp로 계산된다
![image](https://user-images.githubusercontent.com/10987524/29000034-e45f5bfe-7a99-11e7-8a75-5ca03df69052.png)

따라서, aqicn.org에서 받은 데이터는 ug/m3 에서 ppb로 변환 후 AQI수치를 계산해야 한다.

**Comment by pokers** [comment]
ug/m3에서 ppb로 변환을 하기 위해서는 각 데이터의 몰(분자량) 값을 계산하고, 아래 공식에 대입해서 구할 수 있다

ppb = ug/m3 * 22.4 / M

각 데이터의 몰값은 원소 주기율표를 참고해서 원소량을 구한 다음 모든 원소량의 합을 구하면 된다.

SO2 분자량 : 15.99 + 15.99 + 32.07 = 64.05
NO2 분자량 : 15.99 + 15.99 + 14.01 = 45.99
O3 분자량 : 15.99 + 15.99 + 15.99 = 47.97
CO 분자량 : 15.99 + 12.01 = 28

위에서 구한 몰값을 이용해서 각 데이터의 변환공식을 정리하면

ug/m3 - > ppb
SO2 : _x ug/m3_ * 22.4 / 64.05 = _y ppb_
NO2 : _x ug/m3_ * 22.4 / 45.99 = _y ppb_
O3 : _x ug/m3_ * 22.4 / 47.97 = _y ppb_
CO : _x ug/m3_ * 22.4 / 28 = _y ppb_

**Comment by pokers** [comment]
aqicn에서 오는 각각의 데이터를 역산해보니 모두 아래 공식으로 나온 결과 값임.
결국 아래 공식으로 역산을 해서 나온 실제 측정값을  airnow의 공식으로 다시 계산 후 airnow table에서 AQI값을 가져와야 한다.


![image](https://user-images.githubusercontent.com/10987524/29001477-78d045ec-7ac6-11e7-874c-4319a907e3c7.png)

**Comment by kimalec** [comment]
app에서는 airnow, aircn, airkorea, airkorea_who 중에서 선택하기 때문에 국내, 국외 상관없이 저렇게 4개 기준으로 전달될 수 있어야 할꺼 같은데 의견줘

**Comment by pokers** [comment]
국내는 기준이 airkorea, airkorea_who 만 있으면 되는거 아닌가?
airnow나 aircn를 국내에서 굳이 지원할 필요가?

**Comment by kimalec** [comment]
국내사용자는 대기 기본단위를 airkorea_who로 하고, 해외 사용자는 airnow로 할까하는데,
국내사용자가 대기단위를 airkorea_who로 뉴욕이나 상하이 날씨를 봤는데 기준을 airnow나 aircn으로 나오면 혼란스러울꺼 같아서, 반대도 그렇고, 단위니깐 설정에 따라 모두 동일해야 하지 않을까 싶음

**Comment by pokers** [comment]
국내좌표에서는 airnow, aqicn의 단위로 변경하는 메뉴자체가 없어야 하지 않을까?
내 생각에는 유저한테 국내에서 사용하지 않는 단위까지 보여줘서 혼란을 야기할 필요가 있을까 싶어서 그런건데..
반대로 해외 사용자한테서는 airkorea관련 메뉴가 없어야 하고.

**Comment by kimalec** [comment]
사용자는 폰의 나라명으로 구분하기 하는데, 그렇게해도 국내 사용자가 뉴욕이나 상하이 날씨를 볼때, airkorea_who 로 나와야지 아니면 비슷한 수치인데 다르게 grade되어서 이상하게 생각할꺼 같아

**Comment by pokers** [comment]
내가 생각하기에는 그나라에 맞는게 그냥 나오는게 좋을 것 같은데... 그사람이 우리폰으로 봤을때랑 그쪽 나라 일기예보로 
 봤을때랑 수치가 다르게 나오는게 더 이상할거 같아. 
예를 들어서 who로 설정이 되어 있다고는 하지만 그 default를 건드리는 사람은 거의 없을거고 default 셋팅 그대로 쓰는 사람이 우리엡을 이용한 뉴욕 날씨랑 뉴욕날씨를 제공하는 홈페이지에서 봤을때 다르게 표기 되는게 더 이상한거 아닌가 싶은데

**Comment by kimalec** [comment]
이야기 하다가 둔거 같은데, 설정 -> 단위 -> 항목에서 사용자가 airkorea, airkorea_who, us(미국환경보호국 기준, airnow) 중에서 선택하는 것으로 할꺼라서, 국내 국외상관없이 설정된 단위로 표시 하는게 맞을 꺼 같아.

**Comment by kimalec** [comment]
경기도/광주시/경안동?aqi=airnow
```
    "arpltn": {
        "stationName": "경안동",
        "pm25Grade": 2,
        "pm10Grade": 1,
        "no2Grade": 1,
        "o3Grade": 1,
        "coGrade": 1,
        "so2Grade": 1,
        "khaiGrade": 2,
        "khaiValue": 86,
        "pm25Value": 20,
        "pm10Value": 43,
        "no2Value": 0.052,
        "o3Value": 0.001,
        "coValue": 0.7,
        "so2Value": 0.007,
        "dataTime": "2017-11-19 21:00",
        "pm10Str": "좋음",
        "pm25Str": "보통",
        "o3Str": "좋음",
        "no2Str": "좋음",
        "coStr": "좋음",
        "so2Str": "좋음",
        "khaiStr": "보통"
    }
```
pm10이 43이지만, airnow에서 54까지 좋음이므로, 맞게 처리되는 것 확인하였음.

**Comment by kimalec** [comment]
- [ ] grade이 이상함. 
no2Grade, pm10Grade, pm25Grade가 너무 큼. 또한 다른 grade도 계산하는 것이라도 그 특징상 정수여야 할 것을 보임. 혹시 측정소 정보 알 수 있는지 확인 필요함.
```
    "coValue": 0.23,
    "no2Value": 59.4,
    "o3Value": 2.56,
    "pm10Value": 32,
    "pm25Value": 74.18367346938776,
    "so2Value": 4.5,
    "aqiGrade": 99,
    "coGrade": 2.3,
    "no2Grade": 29.7,
    "o3Grade": 0.8,
    "pm10Grade": 32,
    "pm25Grade": 99,
    "so2Grade": 1.5,
    "t": 3.33,
    "h": 100,
    "p": 1025,
    "aqiStr": "Moderate",
    "coStr": "Good",
    "no2Str": "Good",
    "o3Str": "Good",
    "pm10Str": "Good",
    "pm25Str": "Moderate",
    "so2Str": "Good"
```

**Comment by pokers** [comment]
특이 사항 없으면 close 처리 합니다.
