### ISSUE TITLE
ionic first code commit

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#17]
19일 논의한대로, client folder에 first code (maybe blank template) commit 해주세요.

.gitignore 도 추가해주세요.

**Comment by kimalec** [comment]
#5 와 연결

**Comment by kimalec** [comment]
app-base 정도의 경로가 일반적이고,  최소한으로는  template 내용정도만 추가해도 됨.
[ionic-app-base](https://github.com/driftyco/ionic-app-base)
[ionic-starter-blank](https://github.com/driftyco/ionic-starter-blank)

**Comment by skywlrl** [comment]
**[ionic 프로젝트 생성하기]**
```
$ ionic start WizardFactory
```
* 프로젝트명을 WizardFactory로 기본 코드 생성
* ionic.project와 config.xml에 프로젝트 명이 WizardFactory로 설정됨
* ionic.project의 app_id는 ionic.io에서 발급받아서 등록해야 함(현재 미등록 상태로 입력)
* http://saltfactory.tistory.com/239
```
$ ionic state reset
```
* package.json에 설정된 cordovaPlugins을 plugins 폴더에 설치
* ionic state clear, save, restrore 기능도 제공함
* http://www.raymondcamden.com/2015/04/20/ionic-adds-a-new-state-feature?utm_content=buffer20073&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by kimalec** [comment]
https://jasonbrown.io/continuously-deploy-your-ionic-app-using-circle-ci/ - ionic account로 app store를 통하지 않고 update를 가능한 것으로 보이네요.
