### ISSUE TITLE
android 빌드 에러 문제

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1703]
:processDebugResources
/Users/wizardfactory/WebstormProjects/TodayWeather/client/platforms/android/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3 : AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

**Comment by skywlrl** [comment]
package.json에서 
cordova.plugins.diagnostic@3.3.3 대신에 cordova.plugins.diagnostic@3.0.0으로 변경하면 정상 빌드됨

**Comment by skywlrl** [comment]
https://github.com/dpa99c/cordova-diagnostic-plugin/issues/203
3.0.0 버전을 사용하면 동작이 이상함.(즐겨찾기에서 현재 위치 검색 시 무한 재요청 문제 발생)
3.1.1 버전으로 빌드 및 정상 동작함.

**Comment by kimalec** [comment]
이 문제에 직면함. ㅠ.ㅠ
