### ISSUE TITLE
[iOS] app store에서 지원언어에서 영어 표시 안됨.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1723]
<img width="381" alt="2017-08-15 02 04 32" src="https://user-images.githubusercontent.com/6895272/29282538-20c8bea8-815e-11e7-8c93-8d2d9bb28ba4.png">

**Comment by seankim2** [comment]
* 메인 앱 및 widget에서 Base와 동일하게 English 추가함.
