### ISSUE TITLE
어제온도 표기 오류

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1729]
24.6도인데 25보다 높음.

```
{"date":"20170815","time":"0100","t1h":24.6,"rn1":0,"sky":4,"uuu":-0.4,"vvv":-1,"reh":81,"pty":0,"lgt":0,"vec":24,"wsd":1.2}
```
<img width="383" alt="2017-08-16 01 12 27" src="https://user-images.githubusercontent.com/6895272/29324700-035bfd36-8220-11e7-9f73-b055ab8c4c31.png">

**Comment by skywlrl** [comment]
**[분석 내용]**
데이터가 불충분하여 확인할 수 없으나 아래의 경우로 생각됨
1. 8월 16일 0시의 t3h가 24.5일 것으로 예상됨. 원은 24.5도에 그리고 텍스트는 반올림하여 25도로 표시
2. 어제의 현재온도인 24.6도는 반올림하여 25도 위치에 원 표시하고 텍스트는 표시하지 않음
**[수정 내용]**
* 어제의 현재온도의 경우에도 원본 값으로 표시하도록 반올림하는 코드 제거
* 최초에 현재 온도 표시 작업 시 추가된 코드로 오늘은 현재온도는 원본 값으로 표시하고 있음
