### ISSUE TITLE
[app][iOS][widget] iOS 11에서 오류가 발생하는 경우가 있음.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1758]
<img width="480" alt="2017-09-20 4 15 33" src="https://user-images.githubusercontent.com/6895272/30631459-3d29e33c-9e1f-11e7-88f6-d4b25274112f.png">

**Comment by kimalec** [comment]
더 보기 모드에서 진입하게 되면 강제로 간략히 보기 변경되면서 이슈가 발생함.

**Comment by seankim2** [comment]
* 재현 경로
  * 위젯에서 더 보기 모드(버튼은 간략히 보기 상태)로 만든 다음, 위젯을 벗어난 후, 다시 위젯 진입을 하면 위 에러가 발생됨.

**Comment by seankim2** [comment]
* 11.0 이전 버젼에서는 더 보기 모드에서 재진입시 간략히 모드로 바뀌지 않음.
* 따라서 로딩시 모드에 따라 일별/시간별 View를 hidden 시켜야할 것으로 보임.

**Comment by seankim2** [comment]
* 위젯 로딩시 무조건 showMoreView(일별/시간별 View)를 hidden 시켰음.
* NCWidgetDisplayModeCompact 모드일때는 hidden시키고, NCWidgetDisplayModeExpanded일때는 show 모드로 코드 변경
* cityList가 nil일때 Compact모드로 변경되는 데, ios 10,11에 대한 테스트가 필요함
* xcode upgrade가 필요함.

**Comment by seankim2** [comment]
* xcode를 upgrade하기 위해서는 MacOS업그레이도 필요함.

**Comment by seankim2** [comment]
* MacOS Sierra 10.12.6 으로  Update 완료
* Xcode 9.0 Update로 iOS 11.0 지원 가능
* 컴파일후 올려보니 정상적으로 CityList는 nil 이 아니고 확장모드이므로 showMoreView는 enable 되는 것이 정상임
* iOS 10.xx 대에서도 자동으로 크기가 줄어들지는 않았음.
* iOS 11.0에서 widget의 height가 왜 줄어들었는지 디버깅이 필요함

**Comment by seankim2** [comment]
* 시작시에는 기존 상태(더 보기 or 간략히 보기) 상태를 유지하기 위해 init시 setContentSize 제거
* showMoreView 를 Compact/Expanded에 따라 hidden YES/ NO로 수정함
* iOS10, iOS11, city list가 nil일 때 테스트 후 정상동작 확인

**Comment by kimalec** [comment]
citylist가 nil인 경우가 왜 생기는 거예요? citylist는 app으로 부터 받은 location list가 맞죠?

**Comment by seankim2** [comment]
city list가 nil일때는 처음 설치할때여. 메인앱으로 가는 버튼이 있는 화면. 
코드 조건이 city list가 nil일때 compact모드로 동작하는데, 위 이슈와 연관성이 있을 거라 생각했는데, 위 comment에서 보듯이 그건 아니구여.
테스트 조건이 iOS10/iOS11/처음 설치 일때 입니다. 그래서 cit list가 nil일때 테스트를 추가한거구여. 결론은 모든 경우에 정상동작하네여.
