### ISSUE TITLE
시작 화면 설정 기능

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1787]
즐겨찾기, 시간별 날씨, 일별 날씨 탭 중에서 선택할 수 있도록 설정에 추가
- 기본은 지금과 동일하게 시간별 날씨 탭

**Comment by kimalec** [comment]
- [ ] iOS 11에서 시작페이지, 업데이트 주기 변경중에 화면이 보이지 않는 문제
- [ ] 시작페이지, 업데이트 주기에서 항목 변경하고, 나올때 다른 버튼이 자꾸 눌리는 문제

<img width="435" alt="2017-10-20 3 54 33" src="https://user-images.githubusercontent.com/6895272/31788696-78a139c8-b54a-11e7-946d-6422b4b97e0e.png">

**Comment by kimalec** [comment]
release 0.9.61
