### ISSUE TITLE
"지역 이름을 입력하세요."에 대한 독일어 리소스의 길이를 짧게 변경

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#1790]
StartPage와 즐겨찾기의 PlaceHolder로 사용되는 "지역 이름을 입력하세요."가 독일어로 표기 시 길어서 잘리는 문제 발생함
> "LOC_ENTER_CITY": "Geben Sie den Bezirksnamen ein"

**Comment by kimalec** [comment]
Eingeben ein Ortsname ( Enter a place name )
