### ISSUE TITLE
ES6 적용 방법 검토

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#18]
node js 에 ES6 를 적용하는 방법 조사.

**Comment by pokers** [comment]
* ES6 적용 방법
  * babel이나 traceur을 사용해서 적용 하는 방법이 있다.
  * 둘다 transpile해주는 module라고 함
  * traceur
    * 참고 사이트를 찾아서 따라해봤으나 실행시 error이 발생한다.
    * require라는 키워드가 없다고 나옴...
    * https://www.airpair.com/javascript/posts/using-es6-harmony-with-nodejs
  * babel
    * 참고 사이를 보면 간단하게 npm으로 설치할 수 있다.(npm install --global babel)
    * node 실행시 cmd가 'node' 가 아닌 'babel-node' 로 실행해야 한다.
    * 실행 cmd 가 바뀌기 때문에 적용이 가능할지는 확인해봐야 한다.
    * http://www.2ality.com/2015/03/babel-on-node.html

* traceur vs babel
  * http://ilikekillnerds.com/2015/01/transpiling-wars-6to5-vs-traceur
  * 위의 사이트에서 간단하게 비교를 하고 있는데, 결론은 어느것을 사용하던 별반 차이 없다 라는 결론이다.

babel 설치 후 아래 코드를 실행하는데 문제 없는 것을 확인했다. 
(확실히 예전 C++기억을 더듬에 조금더 익숙하게 코딩을 할수가 있다..ㅜㅡ)
`````````````````````````````````javascript
export class jwtToken{
    constructor(body, secret){
        this.body = body;
        this.secret = secret;
    }

    encryption(){
        this.enc = jwt.encode(this.body, this.secret);
        return this;
    }

    decryption(){
        this.dec = jwt.decode(this.body, this.secret);
        return this;
    }
}

`````````````````````````````````

**Comment by pokers** [comment]
babel 사용시 run command가 바뀌기 때문에 아쉽지만 포기.

**Comment by kimalec** [comment]
첨언: run command(ex: node)는 PaaS에서 일반적으로 Cloud 운역쪽에서 제어하기 때문에 제약이 생길 수 있습니다.

**Comment by kimalec** [comment]
issue close하겠습니다. 혹시 더 필요한 사항이 있으면 reopen해주세요.
