### ISSUE TITLE
특정 버전 이상에서 차트내에서 상하 스크롤이 안되는 문제

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1838]
새로 빌드하는 경우에 WKWebview를 사용했던 것처럼 차트내에서 상하스크롤이 안됨

**Comment by kimalec** [comment]
https://forum.ionicframework.com/t/when-using-horizontal-scroll-ion-scroll-page-cant-be-scrolled-down-in-y-direction/3833/46

#68

**Comment by kimalec** [comment]
https://codepen.io/jcsmith1859/full/dIHyK/ -> iPad browser에서 정상동작하지만, 따라해도 해결되지 않음.
$ionicConfigProvider.platform.ios.scrolling.jsScrolling(true); -> native scroll를 off해도 동작하지 않음. -> 완전히 off된건지는 확실치 않음.

**Comment by kimalec** [comment]
sample code에서 아래 코드 동작확인함.
```
 <ion-content class="padding" overflow-scroll="true">
    <div style="overflow: auto;white-space: nowrap; overflow-x:scroll; overflow-y:hidden;">
      <div style="width: 2400px; background-color: #009689">
        <p>
          test
        </p>
        <p>
          test
        </p>
      </div>
    </div>
</ion-content>
```

**Comment by kimalec** [comment]
#1811 에서 들어간 아래 내용때문에 안되는 문제였음

.has-header.overflow-scroll일 때 -webkit-overflow-scrolling를 auto로 변경

**Comment by skywlrl** [comment]
iOS에서 시작페이지, 업데이트 주기 변경 후에 흰색 화면으로 나오는 문제 수정 작업으로 추가된 코드입니다. WKWebview에서 제거 후 정상동작하면 빼셔도 됩니다

**Comment by kimalec** [comment]
먼저 UIWebview에서 동작해야 하니 수정방법 궁리해봐야 할듯하네요.

**Comment by kimalec** [comment]
- [ ] 광고 그리는 방식 변경되어, webkit-overflow-scrolling: auto가 삭제 가능할지도 모름
