### ISSUE TITLE
timeZone정보에 기준 도시 정보 추가

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1857]
예 +9 seoul, +9 tokyo -> format이 있음 맞추어야 함

**Comment by pokers** [comment]
상세 설명 추가 부탁합니다.

현재 아래 형식으로 timezone를 client에 보내고 있는데 외에도 timezone name(ID)를 포함해서 데이터 구성후 client로 전달해야 하는 건가요? ex> {"min":60, "ms":3600000, "timezoneId":"Africa/Ndjamena"}
```
"timezone":{"min":60,"ms":3600000}
```

**Comment by kimalec** [comment]
넵 맞아요. 기존 포맷에 timezoneId추가하면 될 것 같습니다.
