### ISSUE TITLE
단기 예보 정보가 적게 들어오는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#187]
#145 에서 분리 

아침 지금 시각으로 원기날씨앱의 경우 모레 24시까지 데이터가 모두 정확히 표시되고 있어요 우리는 지금 시간에 모레 3시부터 테이터가 0으로 9시까지 밖에 안오지 않을까 싶네요. 우리가 모르는 뭔가가 좀 더 있는거 같아요

작년4월부터 늘어난 것으로 보임.
http://www.onkweather.com/bbs/board.php?bo_table=economy3&wr_id=701 - 기상청, 동네예보 기간 2일에서 3일로 확대 - 온케이웨더

**Comment by kimalec** [comment]
#134 와 연결되는 이슈임.

**Comment by nammaste6** [comment]
------------------------------------------------------------
T3H값이 누락되어 표시되는 장애관련하여 기상청에도 인지하고 있으며,
관련 정보는 현재 정상화를 위해 계획중으로 전달받았습니다.
------------------------------------------------------------
라는 답변은 문의주신 내용을 잘못 이해하여 답변드린 것으로 잘못된 답변을 안내 해 드린 점 사과드립니다.

해당 T3H값이 누락되어 출력되는 것에 대해서는 재발생 시 운영팀에 호출 URL이 포함된 내용을
문의하여 주시면 기관에 문의하여 답변을 요청할 수 있도록 하겠습니다.

또한 공공데이터포털에서 제공하는 무료 기상정보가 아닌 연계되지않고 기상청에서 자체적으로
제공하는 유료 데이터가 있는 것으로 운영팀에서 인지하고 있으며 해당 상세내용은
http://www.kma.go.kr/weather/main.jsp 기상청의 고객센터로 문의하셔야 할 것 같습니다.

감사합니다.

**Comment by kimalec** [comment]
양쪽 모두 문의해봅시다. 호출URL을 포함하여 data.go.kr에 문의하고, 

기상청에는 동일한 질문 + 유료데이터 내용과 가격 문의해봅시다.

**Comment by kimalec** [comment]
http://www.bloter.net/archives/224491 - 월10만원 ㅋ ㅡ.ㅠ

**Comment by kimalec** [comment]
사용하는 URL 
http://newsky2.kma.go.kr/service/SecndSrtpdFrcstInfoService/ForecastSpaceData?serviceKey=[SVC_KEY]&base_date=20151007&base_time=0800&nx=62&ny=125&pageNo=1&numOfRows=999&_type=json

**Comment by kimalec** [comment]
기상청에서 제공받기 힘들면, #200 에 있는 openweathermap api를 통하여 모레 하루것만, 아침에 한번 받아서 저장하는 것도 커버하는 방법일 듯합니다. 

분당 60, 하루에 5만 콜 할 수 있음.  - http://openweathermap.org/price

**Comment by kimalec** [comment]
아래 두가지 방법으로도 가지고 올 수 있음. gridx,gridy는 기존의 nx,ny와 동일한 것으로 보임.

http://www.kma.go.kr/wid/queryDFS.jsp?gridx=62&gridy=125
http://www.kma.go.kr/wid/queryDFSRSS.jsp?zone=1171063100

**Comment by pokers** [comment]
* rss 를 이용해서 전국 데이터(약 1700개) 가져오는 것 확인 완료.
* 중간에 IP가 차당당하지는 않음.
*추후 openshift에서 실행 하거나 3시간 마다 req를 했을때 차단당하는지는 확인해봐야 함.
