### ISSUE TITLE
AQI 단위 변경 추가 수정

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#1939]
#1699 에서 변경하고, 추가 확인 및 필요 데이터 요청
- [x] Value값 PM10, PM2.5는 정수로만, 나머지 PPM은 소수점3자리까지  표시
- [x] aqiValue 추가.
- [x] 측정소 정보 추가
- [x] 측정시간 정보 추가
- [x] 첨부된 그림에서 PPM값이 너무 큰게 아닌지 확인 요청

<img width="323" alt="2017-12-20 9 21 34" src="https://user-images.githubusercontent.com/6895272/34206952-d20de0a4-e5cb-11e7-8364-ce3950ce392d.png">

**Comment by kimalec** [comment]
뉴욕의 경우 초미세먼지 데이터만 존재함.
없는 데이터 delete object.property로 삭제 했으면 함.
<img width="323" alt="2017-12-21 2 29 25" src="https://user-images.githubusercontent.com/6895272/34241815-6050f61e-e65b-11e7-8ae7-5b86f9723b9b.png">

**Comment by pokers** [comment]
1. 모든 데이터는 소수점 아래 반올림하게 수정 --> 이유는 5번 내용 확인
2. aqiValue 추가 완료 --> pr 확인
3. 측정소 정보 제공되지 않음 --> 도시 이름은 제공되는경우가 있으니 필요하다면 추가 가능.
4. 측정시간 정보 --> 제공되는 경우가 있으니 작업 예정. 단, db model이 수정되기 때문에 적용 후 기존 db data삭제 필요.
5. 모든 데이터 value는 실측 단위가 아닌 aqi 단위로 환산된 수치임 --> 실측 단위 제공해주지 않음.

**Comment by pokers** [comment]
실측단위가 아니고 aqi로 환산된 단위만 제공해주고 있어요. 그래서 ppm이나 u/m3 같은 단위는 알수 없어요

**Comment by pokers** [comment]
aqicn에서 제공되는 데이터를 다시 좀 봐야 할것 같아요. 얘네들이 실제 측정 데이터를 주는게 아니고 실제 측정데이터를 바탕으로 aqi값으로 환산해서 제공해주는듯 하네요.

**Comment by pokers** [comment]
아.....착각했네요. 예전에 aqicn 에서 실측값을 안주고 aqi값으로 변환해서 넘겨 주고 있어서,
그 값을 실측값으로 변환하는 함수를 만들었었네요.
현재 aqi에서 넘겨주는 데이터는 모두 ug/m3 이고, 
필요하다면 ppm으로 변환해서 넘기도록 수정할께요.

**Comment by pokers** [comment]
grade계산시 각각의 단위에 맞게 실측치 단위도 변환후 계산하기 때문에 문제 없어요.
자세히 말하면 국내 데이터로 grade변환할 때에
aircn의 경우grade계산할때에 um3단위로 계산하기 때문에 실측치 단위인 ppm을 um3단위로 변환해서 grade를 계산하고,
airnow의 경우 grade계산할때 ppb단위로 계산하기 때문에 ppm을 ppb로 변환해서 grade를 계산해요.
 
외국앱들이 어떤지는 모르겠는데 wiki의 aqi페이지에서 US의 경우 um3, ppb, ppm 모두 혼용해서 사용하고 있어요.
그래서, 일단은 우리나라 단위처럼 pm10,pm25만 um3로 표기하고 나머지는 ppm으로 표기해서 통일화 하고 상황을 좀 봤면해요.
