### ISSUE TITLE
도시 관리 및 설정 UI

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#194]
사용자는 메인 화면에서 검색 버튼을 누르면 도시 관리 화면이 나옴.

사용자가 추가한 도시리스트와 현재온도, 최저/최고 온도, 하늘 상태 정보가 표시 된다.

특정도시를 왼쪽으로 swipe하면 삭제버튼이 나타난다.

사용자가 상단 input box에 도시명을 넣으면 그 도시명이 해당하는 리스트가 나온다.

<img width="1080" alt="default" src="https://cloud.githubusercontent.com/assets/6895272/10414644/573c0096-701a-11e5-9226-b6223f78bd3d.png">

**Comment by kimalec** [comment]
![default](https://cloud.githubusercontent.com/assets/6895272/10414712/d8ac6d48-701d-11e5-86aa-58c99c069bce.png)

UI설명
![151010_](https://cloud.githubusercontent.com/assets/6895272/10414745/d7d92d56-701e-11e5-8f75-d7e14719d2b9.jpg)

**Comment by kimalec** [comment]
몇몇 api에서 auto complete api를 제공하는 것을 봐서는 backend에서 제공하는 형태도 있음.

http://apidev.accuweather.com/developers/auto-complete

**Comment by skywlrl** [comment]
google map api에서 자동완성 기능 제공함(한글도 가능)
https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete
