### ISSUE TITLE
[iOS][watch] app icon이 안나옴

### ISSUE THREAD

**Issue by seankim2** [WizardFactory/TodayWeather#1985]
* watch app icon 이 나오지 않음
* image assets 에 추가가 필요함
![2017-12-31 10 02 07](https://user-images.githubusercontent.com/8072056/34461770-e7a4d9dc-ee76-11e7-8936-507a4a7db0d3.png)

**Comment by seankim2** [comment]
@kimalec 기존에 있는 1024pt를 줄여서 사용하면 될까요?

**Comment by kimalec** [comment]
넵 ~

**Comment by seankim2** [comment]
* images.xcassets내에 이미지를 다 채워도 앱 아이콘이 나타나지 않음.
  * 구글링이 필요해보임
* TodayWeather로 계속 display name이 나오는 이슈도 발견됨.

**Comment by seankim2** [comment]
* watch폴더의 Assets.xcassets의 app-icon assets는 삭제
* AppIcon내의 warning(size이슈) 제거
* Apple Watch Home Screen(All) 40pt를 40@2x로 교체후 정상적으로 와치에 이미지 표시됨.

**Comment by seankim2** [comment]
* 기존 PR( https://github.com/WizardFactory/TodayWeather/commit/f2c8de9e585bf8fc9dfed1ca16e24234f1e1abdd )에 추가 Push함
** https://github.com/WizardFactory/TodayWeather/commit/9798622ca53e7753476e85365d113041284a575a
