### ISSUE TITLE
Provider 에서 상세날씨, 생활지수 등 부가 정보 가지고 와서 서버에 저장하기.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#205]
항시 :  자외선, 미세먼지/강수량, 체감온도, 바람강도
이벤트(문자):  감기, 식중독, 오존, 나들이, 빨래, 세차

kma
자외선 지수 - (3월~11월), 7시 19시 발표 오늘,내일, 모레까지 위험(11이상), 매우높음(8이상), 높음(6이상), 보통(3이상), 낮음(0)
강수량  - 동네예보 실황, 강수형태, 1시간 강수량
체감온도 - (11월~3월), 6시 발표 3시간~66시간까지 -45(위험), -25~45(경고), -10~-25(주의), 관심(~10)
바람강도 - 동네예보, 실황, 풍속, 강수형태,
감기 - (9월~4월) 6시, 18시에 오늘, 내일, 모레까지 발표됨, 매우높음(3), 높음(2), 보통(1), 낮음(0)
식중독 - (3월~11월) 6시, 18시에 오늘, 내일, 모레까지 발표됨., 위험(95), 경고(70), 주의(35), 관심(35)
불쾌지수 - (6월~9월), 3시 발표 3시간~66시간까지 80이상(매우높음), 75이상(높음), 68이상(보통), 60미만(낮음)
 
airkorea
미세먼지
오존

아직 모르는 곳
나들이
빨래
세차

**Comment by kimalec** [comment]
식중독지수 - http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getFsnLifeList
6시, 18시에 오늘, 내일, 모레까지 발표됨.
위험(95), 경고(70), 주의(35), 관심(35)]
부패지수 -  http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getRotLifeList
6시 발표 3시간~66시간까지 높음(7), 보통(3~7), 낮음(~3)
체감온도 - http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getSensorytemLifeList
6시 발표 3시간~66시간까지 -45(위험), -25~45(경고), -10~-25(주의), 관심(~10)
불쾌지수 - http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/DsplsListRequest
3시 발표 3시간~66시간까지 80이상(매우높음), 75이상(높음), 68이상(보통), 60미만(낮음)
자외선지수 - http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/UltrvListRequest
7시 19시 발표 오늘,내일, 모레까지 위험(11이상), 매우높음(8이상), 높음(6이상), 보통(3이상), 낮음(0)

식중독(3월~11월), 부패(3~11월), 체감온도(11월~3월), 동상가능지수(12월 2월), 불쾌지수(6월~9월), 자외선 지수(3월~11월)

http://203.247.66.146/contents/api_spec_kma2.html
openapi.kma.go.kr 이 203.247.66.146 안듯, domain연결안되지만, ip로 데이터를 가지고 올 수 있음.

식중독지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getFsnLifeList
부패지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getRotLifeList
체감온도	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getSensorytemLifeList
동상가능지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getFrostbiteLifeList
불쾌지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getDsplsLifeList
실효습도	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getHumidityLifeList
자외선지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getUltrvLifeList
황사영향지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getDustLifeList
대기오염소산지수	http://openapi.kma.go.kr/iros/RetrieveLifeIndexService/getAirpollutionLifeList
감기지수	http://openapi.kma.go.kr/iros/RetrieveWhoIndexService/getInflWhoList

http://kma.go.kr/HELP/basic/help_01_06.jsp - 각 지수에 대한 설명

h2. airkorea
오존지수
http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty?sidoName=서울&pageNo=1&numOfRows=10&ServiceKey=서비스키
시도별 측정소목록에 대한 일반 항목과 CAI 최종 실시간 측정값과 지수 정보 조회 기능을 제공한다..
sidoName = 시도 이름 (서울, 부산, 대구, 인천, 광주, 대전, 울산, 경기, 강원, 충북, 충남, 전북, 전남, 경북, 경남, 제주)

response message
측정소 측정일시
pm10Value - 미세 농도
o3Grade - 오존 지

미세먼지 예보통보 조회
http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/getMinuDustFrcstDspth?searchDate=2013-12-18&ServiceKey=서비스키

**Comment by kimalec** [comment]
아래와 같이 3단계의 depth에서 상위 두가지를 저장하지 않고, 처리할 방법은 ??

```
1100000000	서울특별시			
1111000000	서울특별시	종로구		
1111051500	서울특별시	종로구	청운효자동	
```

**Comment by nammaste6** [comment]
[140813=생활.산업.보건기상지수 지점정보.xlsx](https://github.com/WizardFactory/TodayWeather/files/15559/140813.xlsx)

**Comment by kimalec** [comment]
document에 있는 address는 잘 못 되었음.

참고 : https://www.data.go.kr/subMain.jsp#/cHVici9wb3QvcW5hL2lyb3NRbmFNYW5hZ2UvSXJvc1NlbGVjdFFuYURldGFpbCRAXjA0Mm00NSRAXnFuYUlkPVFOQV8wMDAwMDAwMDAwMDA3NjQ4

식중독 지수 기준으로 아래와 같이 key와 AreaNo를 넣어야 함.
http://203.247.66.146/iros/RetrieveLifeIndexService/getFsnLifeList?serviceKey=[SERVICE_KEY]&AreaNo=[AREA_NO]

**Comment by kimalec** [comment]
time process 인 cbProcess에서 데이터 가지고와서 db schema 모양대로 파싱하는 것까지 했음.

남은 것 : 디비 업데이트, 다음 업데이트 시간으로 갱신.

**Comment by kimalec** [comment]
fsn(식중독지수)에 대하여 기본적인 동작 확인하였음.  활용계정용 키 확인하고 PR하겠음.

**Comment by kimalec** [comment]
같은 기관에서 받은 키는 동일한 것을 사용하는 것으로 보임. 새로 받은 키는 기존의 중기, 단기에서 사용한 것과 동일함.

**Comment by kimalec** [comment]
자외선, 체감온도, 식중독, 불쾌지수 만들었음.  나머지, 동상, 열, 동파, 확산 지수는 #256에서 진행 예정.
