### ISSUE TITLE
UI 2.0을 위한 의견 수립.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#209]
기존 UI 1.0에서 부족한 부분이나, 강화할 부분, 개선 할 부분에 대한 의견을 수집합니다.

형식은 자유입니다.
손그림으로 설명하여도 되고, 다른 앱 화면 캡쳐해서 올려도 되고, 한 줄 정도의 의견을 제시하여도 상관없습니다.

아무튼 많은 의견 부탁드립니다.

**Comment by kimalec** [comment]
시간차트에서 레드닷(현재온도)를 3h에 찍지 않고, 각 시간에 맞는 좀 더 정확한 시간에 찍자.
시간차트가 3시간 단위인데, 초단기예보로 시간단위 재조정이 가능하는가?
#168 그래프에서 최저온도 일때, 현재온도가 최저온도로 느껴지는 문제. 
6h의 경우, 최저온도에 의해서, 평균온도의 의미가 사라지는 문제.

**Comment by kimalec** [comment]
1. 흰색바탕으로 아이콘이나, 글자에 컬러 포인트 주는 형태가  기본 테마로는 괜찮치 않을까 생각됨.
2. 주간예보는 아래 달력 느낌도 좋음.
![2015-10-14 17 37 12](https://cloud.githubusercontent.com/assets/6895272/10568058/e8e455d2-764d-11e5-9946-440f5b4aac8d.png)

**Comment by kimalec** [comment]
일전에 잠깐 이야기 나왔던, 온도에 따른 차트 색 변화

<img width="200" alt="2015-10-19 10 49 26" src="https://cloud.githubusercontent.com/assets/6895272/10568149/284acc5a-764f-11e5-85dc-c5d237956406.png">

**Comment by kimalec** [comment]
참고: 통합대기, 미세먼지 관련 UI
![2015-10-17 14 55 18](https://cloud.githubusercontent.com/assets/6895272/10568172/6c69605e-764f-11e5-9c05-bc87e9bff8f0.png)

참고 : 주간날씨를 세로로 만든 UI
![2015-10-17 16 56 38](https://cloud.githubusercontent.com/assets/6895272/10568191/90cc358e-764f-11e5-8fa2-f4af137c1669.png)

의견
일출,일몰에 따른 배경색이 검은색에서 흰색으로 변경됨. 
최근 업데이트 성공 시각 정보 제공

**Comment by kimalec** [comment]
강수확률을 온도차트에 같이 넣은 케이스
<img width="291" alt="2015-10-19 11 25 44" src="https://cloud.githubusercontent.com/assets/6895272/10568499/38d283d8-7654-11e5-876d-4b1f36947ff4.png">
과거 데이터에 대하여 회색처리한 케이스
<img width="292" alt="2015-10-19 11 25 57" src="https://cloud.githubusercontent.com/assets/6895272/10568503/4e40cb3a-7654-11e5-8b0e-4d2e91ad629a.png">

**Comment by kimalec** [comment]
코딩용 폰트처럼 인식하기 좋은 폰트 검토.
http://slowalk.tistory.com/2242

**Comment by pokers** [comment]
* 개선했으면 하는점
  * 각 시간대별 온도를 알기 힘들다
  * 화면을 좌우 스크롤 했을때 보여지는 그래프가 언제인지 구분하기 힘들다.
  * 그래프상에서 시간구분이 힘들다

**Comment by nammaste6** [comment]
개선했으면 하는점
- 기상아이콘이 움직였음 좋겠다
- 바탕이 너무 단조롭다( 그리고 업데이트에 나타나는 하얀 헤더는 덜 완성된것 처럼 보여진다)

**Comment by kimalec** [comment]
어제차트를 그림자 느낌으로 표현하면 어떨까?

**Comment by skywlrl** [comment]
- 표도 차트도 날짜 구분이 안됨
- 바탕색도 글자색도 아이콘도 너무 심플해서 여백이 많은 것처럼 보임
- pull-to-refresh 기능을 pulldown 대신 다른 방식으로 제공
- 시간별 예보의 시작과 끝을 날짜 단위로 바꿨으면 좋겠음(현재 23시..어제 21시 부터 데이터가 표시됨. 어제 0시 또는 3시 부터 보였으면 함)

**Comment by kimalec** [comment]
달모양을 항상 초승달로 하지말고, 실제 달모양애 따라 만월부터 초승달까지 변화되면 좋겠음.

지금 이라는 툴팁 들어가는 칸에 sun rise, sun set 넣으면 어떨까 싶은데 툴팁이랑 겹칠수 있는 것과 자칫 복잡해볼 수 있음

**Comment by kimalec** [comment]
저번에 회의에서 결정된 사항에서 하루를 보는 느낌이 카드에 비해 부족한듯해요. 오늘 하루를 보는 느낌을 살릴 수 있으면 좋겠어요.

**Comment by kimalec** [comment]
App store, Facebook, twitter, youtube, google photos, airbnb, instragram 등등 대부분 흰색배경위에 컨텐츠를 올리고, 적당한 포인트는 주고 있음.

모바일 디바이스에서 컨텐츠를 잘 전달하기 위해서는 그 방법 외에는 어려워서 그런 것으로 보임.

TW도 흰색에 서너가지 컬러 포인트 주는 것과, 검은화면에 서너가지 컬러로 포인트 주는 것을 기본으로 하는 것으로 고려해봤으면 함. 추후에 테마에서는 다양한 배합을 적용할 예정임.

**Comment by kimalec** [comment]
https://cdn-images-1.medium.com/max/1600/1*itTTnLfQEtyWHBZMwO93aQ.gif 동작 액션이 좋아 보임. 단 적용케이스가 생각나지 않음.

https://cdn-images-1.medium.com/max/1600/1*3oHG81-eOJPOkPIz5CPOtw.gif - 이 상단 일출/일몰 느낌 좋음.

**Comment by kimalec** [comment]
시간별 날씨에서 차트를 일별로 분리
일별 날씨에서는 주별로 차트를 분리 

위와 같이 한단계 큰 분류에서 분리하는 것도 괜찮을꺼 같음.

**Comment by kimalec** [comment]
내용 영역은 현재, 일별(하루에 해당하는 내용: 미세먼지, 일 강수량, 일별 생활지수), 차트(시간별/일별) 로 세군데로 나누고, 일별은 차트위치(어제, 오늘, 내일)로 변경시 같이 바뀌는 방식 제안해요

**Comment by kimalec** [comment]
UI 2.0 초안 A
<img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11441457/8009a6b8-954f-11e5-9c50-bbe1222752ac.png"><img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11441458/800e6a7c-954f-11e5-883f-99e4cd615104.png"><img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11441456/7fbe8840-954f-11e5-8f1b-4a6eedb5481f.png">
UI 2.0 초안 B
<img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11441519/2bc6f60e-9550-11e5-8b6d-25ecce81345b.png"><img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11441562/a2153ea6-9550-11e5-9e80-11b5d605d40d.png"><img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11441533/4d6e1cf6-9550-11e5-83e0-ad3c899793f9.png">

**Comment by kimalec** [comment]
날씨상태종류
<img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11442626/44b22d8c-955a-11e5-8803-cda15441ab4a.png">
눈,비,번개의 경우 전체 혹은 부분 애니메이션 적용
<img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11442651/82650294-955a-11e5-8864-79c14b7aa0bc.png">
하단에 예보업데이트된 시간 표시
<img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11442983/e6fb3c8a-955c-11e5-837c-7f9e484ab6a2.jpg">
도시 갯수 및 바로 이동 아이콘
<img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11443017/0ad6889e-955d-11e5-9bd3-9e3ab4b3c72b.jpg">
스탠드 모드
애플와치처럼, 가로모드일 경우, 탁장 시계, 날씨 표기용으로 사용(노트3, 갤S4는 온습도계가 있음)
<img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11443067/5699dbf0-955d-11e5-86d0-227e5572d955.jpg">
당일 시간별로 낮,밤을 구분
<img width="200" src="https://cloud.githubusercontent.com/assets/6895272/11443170/088e95ee-955e-11e5-87e3-d8569c48f949.jpg">

시간별 날씨에서 차트를 일별로 분리 - 어제, 오늘, 내일, 일별
일별 날씨에서는 주별로 차트를 분리 - 시간별, 지난주, 이번주, 다음주
<img width="200" alt="2015-11-27 23 25 19" src="https://cloud.githubusercontent.com/assets/6895272/11443239/bfaa32d8-955e-11e5-9372-1b2eb7362557.png">
<img width="200" alt="2015-11-27 23 26 06" src="https://cloud.githubusercontent.com/assets/6895272/11443240/c00280c8-955e-11e5-9323-c0a732bbe242.png">
<img width="200" alt="2015-11-27 23 27 32" src="https://cloud.githubusercontent.com/assets/6895272/11443241/c0088c48-955e-11e5-88b9-3ceb07b4220f.png">
<img width="200" alt="2015-11-27 23 40 40" src="https://cloud.githubusercontent.com/assets/6895272/11443544/4e9870f2-9561-11e5-966c-24c73c9048d4.png">

아래는 기황정보 예시인데, 경보 경우에 사용하기 적합할듯함.
<img width="200" alt="2015-11-27 23 32 31" src="https://cloud.githubusercontent.com/assets/6895272/11443303/5276fe48-955f-11e5-95b3-a8f7e4dd3896.png">
<img width="200" alt="2015-11-27 23 32 45" src="https://cloud.githubusercontent.com/assets/6895272/11443305/54864d06-955f-11e5-8d5d-8e9a401c6d04.png">
<img width="200" alt="2015-11-27 23 32 55" src="https://cloud.githubusercontent.com/assets/6895272/11443307/5d4beefa-955f-11e5-909c-873e7153b044.png">

달 상태를 현실에 맞게 반영
<img width="122" alt="2015-11-27 23 35 25" src="https://cloud.githubusercontent.com/assets/6895272/11443343/b18f8d00-955f-11e5-8590-0560506d6362.png">

도시리스트를 카드로 보여주기
<img width="200" alt="2015-11-27 23 37 42" src="https://cloud.githubusercontent.com/assets/6895272/11443367/edebf0ae-955f-11e5-837a-f344d64ca747.png">

날씨 상태는 차트 영역내에 표시
<img width="240" alt="2015-11-27 23 47 32" src="https://cloud.githubusercontent.com/assets/6895272/11443556/6239a414-9561-11e5-83e5-0d38bbdd6844.png">

**Comment by kimalec** [comment]
구름낀 상태가 지금은 구름 -> 흐림 만 있으나, 구름 적음 -> 구름 많음 -> 흐림 까지 확장
눈, 비, 비/눈 의 경우 모두 "흐림 + 눈, 비, 비/눈"인데, 구름 적고, 구름 많고 까지 확장

**Comment by kimalec** [comment]
현재날씨 요약이 길어지는 경우에 대하여, 표현 방법 정리 필요.

<img width="360" alt="2015-12-01 09 00 25" src="https://cloud.githubusercontent.com/assets/6895272/11488897/aca95270-980d-11e5-9d58-cf479f528291.png">

**Comment by kimalec** [comment]
#377 시간별 날씨, 일별 날씨에서 차트 시작 위치 개선

**Comment by kkkiiikkii** [comment]
![151206_](https://cloud.githubusercontent.com/assets/12652131/11611574/5bfb93b0-9c18-11e5-8b2c-b1545cb2d029.png)
![151206_](https://cloud.githubusercontent.com/assets/12652131/11611575/5bfbe93c-9c18-11e5-92a0-e4eb72a54ee1.png)

**Comment by kkkiiikkii** [comment]
![151220_ _ -01](https://cloud.githubusercontent.com/assets/12652131/11916506/e883d09a-a71c-11e5-8ed6-040b2bb72f77.jpg)
![151220_ _ -02](https://cloud.githubusercontent.com/assets/12652131/11916504/e87407be-a71c-11e5-9eac-f0400fcad01b.jpg)
![151220_ _ -03](https://cloud.githubusercontent.com/assets/12652131/11916505/e874a296-a71c-11e5-9769-ac602925509b.jpg)

**Comment by kkkiiikkii** [comment]
![151220_ _ -01](https://cloud.githubusercontent.com/assets/12652131/12219661/29e434b6-b790-11e5-948c-e380e2d1394c.jpg)

**Comment by kimalec** [comment]
밤모드에 대하여, 블루라이트를 낮추어 적용하는 것을 고려해보자.
참고: http://everythingallright.tistory.com/380

**Comment by kimalec** [comment]
일별날씨, 주간날씨 외에 상세날씨(추후 제거하면 좋지만 논의 필요), 대기지수(지금은 없는데 확대여부), 도시검색, 설정, 지금 설정에 없지만 추가되어야할 알림, 공지게시판, 피드백 전달 등이 필요함.

**Comment by kimalec** [comment]
그래프에서 현재(정시) 시간을 셀로 추가 하기 위해서는, "그제, 어제, 오늘, 내일, 모레" 에 모두 넣어주어야 한다. 그렇지 않으면 24시간 비교에서 틀어지게 된다.

**Comment by kimalec** [comment]
요일별 날씨 background, foreground color 검토해주세요.

**Comment by kimalec** [comment]
참고용 : google play store의 main화면과 하단메뉴 비율

<img width="320" src="https://cloud.githubusercontent.com/assets/6895272/13942474/3637dd9c-f036-11e5-9bb0-fc918b833ae5.jpeg">

**Comment by kimalec** [comment]
날씨 UI에도 참고 할만하네요. 시계에 적용하는 것도 괜찮고, 점 색깔을 흰색/회색으로 찍어서 어제오늘 비교도 가능할것도 같아요.
<img width="336" alt="2016-05-03 18 11 21" src="https://cloud.githubusercontent.com/assets/6895272/14978989/8d047014-115a-11e6-9bd6-0198c2b55032.png">

**Comment by kimalec** [comment]
아이패드용 화면 가이드 이미지를 아래 것으로 업데이트해주세요.
구글 플레이 스토어에서 태블릿 이미지가 같이 나와서 차이가 없어 보여, 변경했으면 해서요.

[v090_ipad_image.zip](https://github.com/WizardFactory/TodayWeather/files/344840/v090_ipad_image.zip)

**Comment by kkkiiikkii** [comment]
[160626_가이드 화면(ipad 768*1024).zip](https://github.com/WizardFactory/TodayWeather/files/344896/160626_.ipad.768.1024.zip)

**Comment by kkkiiikkii** [comment]
[160626_가이드 화면(ipad pro 2048*2732).zip](https://github.com/WizardFactory/TodayWeather/files/344900/160626_.ipad.pro.2048.2732.zip)

**Comment by kkkiiikkii** [comment]
![-01](https://cloud.githubusercontent.com/assets/12652131/19311602/1293680e-90ca-11e6-92b8-3935b3592f47.png)
![2-01](https://cloud.githubusercontent.com/assets/12652131/19311603/1295bbfe-90ca-11e6-97c3-a5ba5f5af63a.png)

**Comment by kimalec** [comment]
현 이슈는 닫고, 디자인 재수정시에 진행.
