### ISSUE TITLE
create screen and icon

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#21]
browser에서 사용할 favicon 만들기

https://en.wikipedia.org/wiki/Favicon
https://github.com/audreyr/favicon-cheat-sheet

**Comment by skywlrl** [comment]
icon, splash의 png 이미지 요청
* icon 최소 크기 : 192x192 px(no rounded corners)
* splash 최소 크기 : 2208x2208 px
* 참고 : http://ionicframework.com/docs/cli/icon-splashscreen.html

**Comment by kimalec** [comment]
화면 해상도는 우선 4K(3840 x 2160) 기준으로 만들어서 봅시다.
참고
출처: ..
<img width="607" alt="2015-08-09 13 47 53" src="https://cloud.githubusercontent.com/assets/6895272/9153649/c0368640-3e9f-11e5-8d39-b3499e6f1df1.png">

**Comment by kimalec** [comment]
적용되어서 close합니다.

**Comment by kimalec** [comment]
하늘상태 구름조금, 구름많음, 흐림으로 아이콘 확장 필요.
하늘상태 비/눈 동시 아이콘 필요.

**Comment by kimalec** [comment]
구름조금,많음은 안하기로 했음.
