### ISSUE TITLE
비교하는 시간 값이 이상한 문제

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2154]
query path : /v000901/dsf/coord/39.475,-6.372?distanceUnit=km&temperatureUnit=C&airUnit=airkorea&windSpeedUnit=m/s&precipitationUnit=mm&pressureUnit=hPa

[log link](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/elasticbeanstalk/twService-env/var/log/nodejs/nodejs.log;stream=i-0f5c62ad2533e05aa;refid=33879422222204680381187370659613908800663100077798785059;reftime=1519205834630)

재현하기 위해서 재시도하면 발생하지 않음. log상에는  동일한 오류가 여러개 존재함

<img width="1015" alt="2018-02-21 7 41 28" src="https://user-images.githubusercontent.com/6895272/36475813-3fc1ebbe-173f-11e8-8d9d-c7a8eb03ba51.png">

**Comment by pokers** [comment]
timezone이 null일 경우 발생.
아래 pr로 수정됨
#2159
