### ISSUE TITLE
초미세먼지 시간별 예보 데이터 오류 확인

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#2202]
2018-03-02 14:31 아신시 도고면 15시가 60으로 노랑색 계열로 제공되었음

#716

**Comment by pokers** [comment]
오류일때의 이미지를 확인해보니 기존 한국 지도의 예보데이터 이미지가 아닌 동아시아 이미지가 업로드 되어 있음...

http://www.airkorea.or.kr/file/viewImage/?atch_id=78573
