### ISSUE TITLE
주간 차트에서 라인 겹치는 문제. ios에서만 발생함.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#223]
주간 차트에서 라인 겹치는 문제. ios에서만 발생함.
<img width="377" alt="2015-10-24 04 06 16" src="https://cloud.githubusercontent.com/assets/6895272/10702421/a044ffba-7a04-11e5-8ece-55ef44bd29aa.png">

**Comment by kimalec** [comment]
다시 재현되지 않고 있네요.

**Comment by skywlrl** [comment]
하늘시에서 18개의 데이터가 있고, 추가된 도시에 17개의 데이터가 있어서 하늘시에서 그려진 마지막 데이터가 추가된 도시로 변경되어도 삭제되지 않아서 겹쳐서 그려지는 문제임
