### ISSUE TITLE
날씨 알림을 위한 local notification 지원

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#234]
사용자가 설정한 시간에 날씨 정보를 업데이트 한 이후에 지정된 지역에 대한 알림을 표시하자.
#181 push notification 와 관련 있음.

**Comment by kimalec** [comment]
http://ngcordova.com/docs/plugins/localNotification/

http://devdactic.com/local-notifications-ionic/

**Comment by kimalec** [comment]
http://blog.emojipedia.org/ios-9-1-emoji-changelog/ 알림에 이모지 적용

**Comment by skywlrl** [comment]
Android에서 Local Notification을 Scheduled를 시키고 App을 종료하면 알림은 Trigger되지만 Update가 되지 않는 문제가 있음
* IOS에서는 Background로 App을 실행시켜 주는 것으로 보임 -> 정상 동작됨
* App에서 설정한 Trigger 이벤트는 App이 종료되면 호출되지 않아 Update되지 않고 이전 Trigger된 알람으로 표시됨 -> App이 실행 또는 Background 실행되면 정상 동작함
* https://github.com/katzer/cordova-plugin-local-notifications/issues/899 동일한 문제가 이슈로 등록되어 있지만 답변 없음 -> Android에서 Background로 App을 실행시켜 주는 방법에 대한 Link만 있음
* Background로 실행하거나 Nativa App에서 직접 Update 처리하는 방법을 검토해야 함

**Comment by kimalec** [comment]
https://github.com/Telerik-Verified-Plugins/LocalNotification 는 katzer에서 folk 된 project인데, 이것도 앱종료시에 업데이트 되지 않음.

text 값이 http인 경우에 서버로부터 직접 가지고 오는 형태로 해야 할 것으로 보임.

**Comment by kimalec** [comment]
sound같은 경우에는 처음 스케줄에 등록될때, 다운받아서 저장한다.

NotificationCompat.setContentText 에서 text가 http인 경우에 데이터를 가지고와서 업데이트 하면 될 것으로 보임.

**Comment by kimalec** [comment]
AssetUtil에 getTextFromUrl를 추가하고, Options의 getText시에 업데이트 하는 형태로 진행할 예정.
HTTP로 JSON or String을 가지고 오는 코드가 필요함.

**Comment by kimalec** [comment]
AssetUtil.java에서 아래와 같은 형태로 하여 서버에서 데이터 가지고 오는 것 동작확인했음.
Icon과 Title까지 변경하는 형태로 수정 예정.

```java
            URL url = new URL(path);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();

            StrictMode.ThreadPolicy policy =
                    new StrictMode.ThreadPolicy.Builder().permitAll().build();

            StrictMode.setThreadPolicy(policy);

            connection.setRequestProperty("Connection", "close");
            connection.setConnectTimeout(5000);
            connection.connect();

            StringBuffer sb = new StringBuffer();

            InputStream is = new BufferedInputStream(connection.getInputStream());
            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            String inputLine = "";
            while ((inputLine = br.readLine()) != null) {
                sb.append(inputLine);
            }

            text = sb.toString();
```

**Comment by kimalec** [comment]
현재위치의 경우에는 현재위치정보를 갱신해서 진행해야 함.

**Comment by kimalec** [comment]
알람의 경우 설치된 앱을 삭제했어요, 다시 설치하면 알람이 그대로 살아 있음. 처음 실행시 알람을 전부삭제할 필요가 있음.

**Comment by kimalec** [comment]
id가 중복해서 만들수도 있는데, 이렇게 하면 지울때, 문제가 발생함. 한번 다 지우고, 다시 실행해서 다시 지워야 함.

즉 동일 id 갯수만큼 재실행해서 지워야 함.

**Comment by kimalec** [comment]
#677 로 부터 id, city의 address, time을 받음.

schedule에 추가하거나 업데이트 할때, data property에 url과 currentPosition 여부를 전달하여, android native에서 참고하도록 할 예정.

**Comment by kimalec** [comment]
cordova version 문제인지, ios 최신버전 문제인지, ios에서 local notification update가 되지 않음. 안드로이드처럼 데이터 갱신이 되지 않음.

**Comment by kimalec** [comment]
iOS경우 앱종료된 상태에서 local notification의 text를 업데이트 하지 못하고, background fetch라는 기능으로 갱신할 수 있음.

https://github.com/christocracy/cordova-plugin-background-fetch

android도 앱 종료시켜 재 확인 필요함.

**Comment by kimalec** [comment]
background fetch에서 localnotification으로 title,text를 업데이트하게 되면 랜덤하게 스캐줄 자체가 늘어가는 문제가 있음.

**Comment by kimalec** [comment]
https://github.com/WizardFactory/TodayWeather/tree/677-local-notification-time-picker 백업만 해둠.

실행시, trigger, background fetch시에 notification을 update해야 하지만, 업데이트 시에 랜덤하게 증가하는 문제가 있음.
현재 이대로 사용하지 못하고, 추후 재검토를 위해 백업만해둘 예정임.

**Comment by kimalec** [comment]
widget 지원으로 지원하지 않음 다만 위젯 과 메인앱과 데이터를 같이 쓸 방안 모색이 필요할 수 있음.
