### ISSUE TITLE
TodayWeather User Flow Chart

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#235]
TodayWeather User Flow Chart 적성하여, 팀원 모두의 통일된 이해와 빠짐없는 시나리오를 완성하자.

**Comment by kimalec** [comment]
#234 의 알림 시나리오 도 필요합니다.

**Comment by kimalec** [comment]
#100 기상 경보에 대한 처리도 필요합니다.

**Comment by joljel** [comment]
![img_4205](https://cloud.githubusercontent.com/assets/14917457/10748402/231db724-7ca3-11e5-8354-dfc43c3e88dd.JPG)

**Comment by joljel** [comment]
![img_4205](https://cloud.githubusercontent.com/assets/14917457/10748417/42068e5e-7ca3-11e5-9524-57ba6e296a70.JPG)

**Comment by kimalec** [comment]
:+1:  멋짐. 이제 툴로다가 ㅋㅋ 위에 코멘트 두개 있어요. 혹시 못 봤을까봐서

**Comment by joljel** [comment]
네 일단 일요일에 정리한 상황만 급히 스케치 했습니다. 툴은...괜찮은 툴을...계속 찾고있습니다...

**Comment by joljel** [comment]
![flow copy](https://cloud.githubusercontent.com/assets/14917457/10780719/f8c40c1c-7d83-11e5-902f-d4e4596cb2cd.jpg)

**Comment by kimalec** [comment]
:+1:  먼가 멋져 보임 +_+

**Comment by kimalec** [comment]
기상 속보/경보는 상단에 간략하게 나오고, 클릭하면 full screen이나 큰 팝업창으로 상세 설명하는게 어떨까 싶으네요.  속보/경보가 생각보다 자주 발생은 합니다. ㅋ

**Comment by joljel** [comment]
![flow20151108 copy](https://cloud.githubusercontent.com/assets/14917457/11024134/2a7799ca-86cd-11e5-8bed-763941109708.jpg)

**Comment by kimalec** [comment]
제공되는 데이터에 따라, 영역을  현재날씨, 하루(주간)날씨, 차트 3가지 영역으로 구분할 필요가 있음.

시간별날씨
<img width="300" alt="2015-11-22 11 23 19" src="https://cloud.githubusercontent.com/assets/6895272/11321653/8a811844-910b-11e5-9245-d5291749ae01.png">

일별날씨
<img width="300" alt="2015-11-22 11 23 30" src="https://cloud.githubusercontent.com/assets/6895272/11321655/98315c38-910b-11e5-9c82-716c42c4058a.png">

오븐 주소 https://goo.gl/00lCE8

**Comment by kimalec** [comment]
#412 #421 #504 관한 내용 만들어야 함.

**Comment by kimalec** [comment]
진행하지 않음.
