### ISSUE TITLE
Android용 Widget 제작.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#241]
Android에서 사용할 기본 Widget.

**Comment by kimalec** [comment]
http://developer.android.com/intl/ko/guide/practices/ui_guidelines/widget_design.html

**Comment by kkkiiikkii** [comment]
![default](https://cloud.githubusercontent.com/assets/12652131/10867306/3a5b3c3c-809e-11e5-8f96-ea070ddfd1cb.jpg)
![default](https://cloud.githubusercontent.com/assets/12652131/10867309/3a9fe594-809e-11e5-84ed-a7231345a0c1.png)
![default](https://cloud.githubusercontent.com/assets/12652131/10867308/3a9edc4e-809e-11e5-9c23-63a20501408a.png)

**Comment by KimSeungBum** [comment]
![default](https://cloud.githubusercontent.com/assets/15318248/10874317/85591642-8165-11e5-815d-ebcd3e9cbe8b.png)

이미지 자르는 것 요청 드려요 ~
최저 최고 쪽만 자르면 될 것 같아요 
온도 아이콘으 있다고 하셨고 ,, 날씨 아이콘도 이미 있고

그리고 
sky 숫자 값 별 매칭 아이콘 소스 알려주세요 ~

**Comment by kimalec** [comment]
https://github.com/WizardFactory/TodayWeather/blob/master/client/www/js/services.js 120line

parseSkyState function 참고하세요,

**Comment by kkkiiikkii** [comment]
![default](https://cloud.githubusercontent.com/assets/12652131/10875460/f113df56-8175-11e5-995c-02c6d1ef0495.png)
![default](https://cloud.githubusercontent.com/assets/12652131/10875462/f117d5e8-8175-11e5-9d87-d2b45b350562.png)
![default](https://cloud.githubusercontent.com/assets/12652131/10875463/f1197632-8175-11e5-8b19-d2019150df99.png)
![default](https://cloud.githubusercontent.com/assets/12652131/10875464/f12d2510-8175-11e5-9e1b-32c947d687ca.png)

**Comment by KimSeungBum** [comment]
감사합니다. ^^

**Comment by KimSeungBum** [comment]
온도 default 값 처리에 대하서 검토 필요.
현재 서버에서 오는 json 데이터에서 온도 등 default 값이 0으로 옴.
실제로 온도는 0이 될 수 있으므로 존재하지 않도 값으로 default값 정의 필요

**Comment by kimalec** [comment]
![kakaotalk_20151104_120155756](https://cloud.githubusercontent.com/assets/6895272/10928506/580b5f0a-82ec-11e5-8734-fc8611f0f112.jpg)

@kimalec 과 논의한대로 위젯 크기보다는 컨텐츠에 맞추는 형태로 진행할 예정임.

**Comment by KimSeungBum** [comment]
![sample](https://cloud.githubusercontent.com/assets/15318248/11015593/865d5d28-85a7-11e5-8145-89b54142a4f6.jpg)

추가된 파일

1. src/net/wizardfactory/todaywether/widget 이하 모든 파일 
	+ Data
		- WeatherData.java : 오늘 / 어제 위젯에서 표시하는 한개 component에 대한 날씨 데이터 
		- WidgetData.java : widget에 그리기 위한 데이터 구성을 갖고 있음.
	+ JsonElement
		- AddressElement.java : geocoder 서버에서 얻어온 데이터 파싱 및 서버에 보내는 형태로 맞게 주소 구성
		- WeatherCurrentElement.java :  server에서 얻어온 날씨 정보 중 Current 부분 데이터
		- WeatherElement.java : server에서 얻은 날씨 정보 중 current, shorts, shortest만 갖고있음. 데이터 파싱 수행
		- WeatherShortElement.java : server에서 얻어온 날씨 정보 중 short에 대한 데이터
		- WeatherShortestElement.java : server에서 얻어온 날씨 정보 중 shortest에 대한 데이터
	+ Provider
		- W2x1WidgetProvider.java : 2x1 위젯에 대한 provider 내용
		// 만약 추가로 widget에 추가 된다면 해당 디렉토리에 provider을 추가하면 된다.
	- GetHttpsServerAsync : https 서버 젒고 처리하는 async class
	- WidgetMenuActivity : 위젯 메뉴구성을 위해서 따로 activity 만듬(메뉴 구성 변경 시 수정 필요). 모든 위젯 공통사용 가능.
	- ⁯WidgetUpdateService : background 에서 위젯 갱신에 대한 모든 동작을 관장함. 위젯 갱신이 필요하면 해당 service 호출 하면ㄷ ㅚㅁ.
2. res/drawable-xhdpi 이하 모든 파일(원래 있던 icon.png 제외)
3. res/layout : 디렉토리 부터 만들어서 추가함
	- w2x1_widget_layout.xml : 2x1 위젯에 대한 화면 구성을 갖고있는 xml
	- widget_menu.xml : WidgetMenuActivity 의 화면에 대한 구성
4. res/xml
	- w2x1_widget_provider.xml : widget에 대한 기본 환경 정보 기술
	// 현재 내부의 minWidth/Height 를 72/40으로 했는데 이건 테스트 폰에 맞춘 것이다. 원래는 보통 146/72로 주어야 하는데 폰마다 다른듯하여 확인 필요.

기본 샘플 위젯 추가 pull request는 요청중 .

변경된 파일

1. res/values
	- strings.xml :  이하 부분 내용 추가
2. /AdnroidManifest.xml : 파일 비교가 필요한 어쩔수 없이 중간중간 추가됨
	: 위경도 수집하기 위해서 추가 
     <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" /> 
     <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> 
	
	: 추가된 activity와 service를 위해서 
     <activity android:name="net.wizardfactory.todayweather.widget.WidgetMenuActivity" android:theme="@android:style/Theme.Translucent"/> 
     <receiver android:label="@string/widget_name" android:name=".widget.Provider.W2x1WidgetProvider"> 
             <intent-filter> 
                 <action android:name="android.appwidget.action.APPWIDGET_UPDATE" /> 
             </intent-filter> 
             <meta-data android:name="android.appwidget.provider" android:resource="@xml/w2x1_widget_provider" /> 
      </receiver> 
      <service android:name="net.wizardfactory.todayweather.widget.WidgetUpdateService" />
	
	: 버전이 안맞아서 조정
      <uses-sdk android:minSdkVersion="14" android:targetSdkVersion="22" />

**Comment by kimalec** [comment]
#298 에서 적용되었음.
