### ISSUE TITLE
apple watch app 제작

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#243]
간단한 기본 Watch App 제작하기. 
https://developer.apple.com/watch/human-interface-guidelines/resources/

**Comment by kkkiiikkii** [comment]
![default](https://cloud.githubusercontent.com/assets/12652131/10867301/16b0ee08-809e-11e5-990f-74577ba51932.jpg)
![default](https://cloud.githubusercontent.com/assets/12652131/10867300/16b0f4e8-809e-11e5-80ee-b0f6bef0d68b.png)
![default](https://cloud.githubusercontent.com/assets/12652131/10867299/16b04eb2-809e-11e5-9039-8c1ef0f7a613.png)

**Comment by neoqmin** [comment]
#### apple watch plugin 적용
1. [cordova-plugin-apple-watch](https://github.com/leecrossley/cordova-plugin-apple-watch) 플러그인에서 플러그인 추가 설치
2. xcode 상에서 wormhole 사용 시 발생되는 error에 대해서 Target Membership 추가
3. 개발자 등록된 app id를 프로젝트에 등록

#### UI관련
1. Group을 사용하여 구현 가능

**Comment by neoqmin** [comment]
<img width="139" alt="2015-11-04 4 38 53" src="https://cloud.githubusercontent.com/assets/11567505/10932246/9dbb22e4-8312-11e5-8c89-fd4317ea9479.png">

**Comment by neoqmin** [comment]
#### Product Run 실행 시 아래의 경고 창 발생
```
the operation couldn’t be completed.
(launchserviceserror error 0.)
```

**Comment by neoqmin** [comment]
#### watchapp 시작 시 해당 구간에서 중지 됨
TodayWeather/Plugins/MMWormholeFileTransiting.m
```c
- (void)checkAppGroupCapabilities {
    NSAssert([self.fileManager containerURLForSecurityApplicationGroupIdentifier:self.applicationGroupIdentifier] != nil, @"App Group Capabilities may not be correctly configured for your project, or your appGroupIdentifier may not match your project settings. Check Project->Capabilities->App Groups. Three checkmarks should be displayed in the steps section, and the value passed in for your appGroupIdentifier should match the setting in your project file.");
}
```

**Comment by neoqmin** [comment]
#### Cordova 앱에서 데이터 전송 불가

MMWormhole의 TransitingType이 MMWormholeTransitingTypeSessionContext임

아래와 같이 WCSession에 대한 Delegate 추가 필요

http://stackoverflow.com/questions/27025526/passing-data-to-apple-watch-app

**Comment by neoqmin** [comment]
![image](https://cloud.githubusercontent.com/assets/11567505/11029533/012db386-870b-11e5-841d-cb681f7f08fb.png)

데이터 공유 버전 완료

**Comment by neoqmin** [comment]
최신 소스에 맞게 새로 작업했습니다.

#### app.js 및 controller.js 수정
- cityData.dayTable에서 forEach문이 먹지않아 for문으로 작업했습니다.
- 파일내의 setUserDefaults 함수 정의과 호출로 applewatch와 데이터 공유가 가능합니다.

**Comment by neoqmin** [comment]
#### apple-watch app의 정상적인 실행을 위해서는 아래의 추가 작업이 필요합니다.
1. ionic build ios에 의해서 생성된 xcode 프로젝트에서 File/New/Target를 선택합니다.
2. WatchKit App for watchOS1을 선택합니다. WatchKit App을 선택할 경우 정상적으로 실행되지 않습니다(시뮬레이터는 실행됩니다.). 아래의 에러코드 발생

 ```
ld: framwork not found AVFoundation
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
3. 생성된 프로젝트의 Version이 모두 동일해야 합니다.
4. 모든 프로젝트의 Capabilities/App Groups에서 그룹을 추가해야 합니다.
5. repository에 포함된 applewatch 폴더 하위의 watch app과 extension 폴더를 platforms/ios에 복사합니다.

**Comment by neoqmin** [comment]
#### 구현 내용

현재는 iPhone의 TodayWeather 메인 페이지가 로딩될 때 공유 데이터를 갱신합니다.

해당 부분은 controller.js에 있습니다.

다시 쿼리할 필요가 없기 때문에 바로 시계화면에 표시될 수 있습니다.
(응답시간이 짧아야될 것 같아 이렇게 작업했습니다.)

하지만, 앱을 실행하여 메인페이지의 로딩을 하지 않았다면, 최신 데이터가 아닐 수 있습니다.
(마지막 쿼리한 지역의 날씨)

**Comment by kimalec** [comment]
store 등록시에 profile 문제가 발생

http://stackoverflow.com/questions/29553794/watchkit-extension-provisioning-profile

http://stackoverflow.com/questions/29544427/no-matching-provisioning-profiles-found-for-watchkit-extension-when-submitting-t

**Comment by kimalec** [comment]
#364 업로드 에러에 대한 이슈 검토중.
