### ISSUE TITLE
동네별예보정보 가져오는 로직 구현

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#25]
server side에서 동네별 X,Y좌료를 이용하여 동네예보정보조회 서비스 가져오는 로직 구현.
* 전체 동네는 약 3480개.
* 각 동네별로 모두 조회 및 저장해야한다.
* 3시간에 한번씩 업데이트 해야함.
* error발생시 예외 처리 및 retry에 대한 로직 주의해서 구현 해야함.

**Comment by pokers** [comment]
**구현 사항 정리**
* 하나의 class내에서 모든 처리.
* 입력 인자
  * class생성시 : x,y좌료등 request할때의 필수 데이터가 포함되어 있는 **리스트**
  * data request 할때 : url, key, date, time, 완료시 호출될 callback 함수.
* event driven방식으로 구현
  * weather data request를 동네별로 해야 하기 때문에 한번에 3천개 이상의 get request가 발생한다.
  * 일단 get request는 for loop로 싱글 process로 호출 (추후 필요하다면 multi process를 사용하게 수정)
  * get의 성공/실패시 event를 보냄.
  * event를 받으면 결과를 event를 보낸쪽의 list index를 확인하고 결과를 저장할 리스트의 해당 indexdp 성공/실패 flag를 저장.
  * 모든 get request가 완료 되었는지는 event의 개수로 알수 있음.
  * 모든 get request가 완료 되면 실패한 get request에 대해서 retry count만큼 재시도.
  * 모든 try가 완료 되면 호출시 입력 인자로 받은 callback함수에 결과를 저장한 리스트를 입력인자로 넣어서 호출.

![collect_data_sequence](https://cloud.githubusercontent.com/assets/10987524/8955080/d47d6d18-3624-11e5-9141-dfcd28f26688.jpg)

**Comment by pokers** [comment]
for문을 실행하고 event로 결과를 받는 위의 로직대로 실행 할 경우 1000개의 동네 기준으로 3314ms의 시간 소요됨.
결국 3482개의 동네가 있기 때문에 약 11초정도면 모든 정보를 받을 수 있을것으로 생각됨.(일일 트패픽 제한 때문에 전체 실행은 하지 못함.)
error가 없을 경우 이고 timeout등의 변수가 있을 경우 시간이 증가할 수 있음.
따라서, 하나의 request당 timeout를 정의 하고 timeout시간 내에 응답이 없으면 취소하고 다시 request하는것이 좋을 것으로 생각됨.

**Comment by kimalec** [comment]
request npm 이 보면 30sec정도면 time out을 발생시키는 것으로 보여요. (서버의 socket time out value에 따르는 것일 수도 있지만..) 직접 강제로 끊어버리는 것보다는 시스템이 끊어버리면 후 대응 하는게 어떨꺼 싶으네요.

**Comment by pokers** [comment]
* 남은 작업
  * 하나의 동네별예보정보의 페이지가 다수일 경우 recursive 하게 모든 페이지를 다 가져오도록 수정 필요.
  * method 이름 수정 필요 : 동네 예보, 중기예보등 다수의 예보 정보를 가져오는 method다 추가 될 예정.

**Comment by pokers** [comment]
동네별예보정보 구현이 마무리되어 close처리합니다.
통합 작업시 발생하는 이슈는 새이슈 발행후 처리 예정입니다.
