### ISSUE TITLE
KMA 생활지수 중에 동상, 열, 동파, 확산 지수 추가 저장

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#256]
#205 이어서 KMA 생활지수 중에 동상, 열, 동파, 확산 지수 추가 저장하기

**Comment by kimalec** [comment]
Service extension시에 해도 됨.

**Comment by kimalec** [comment]
식중독지수, 자외선지수, 대기확산지수는 계산할 수 없고, 부패,불쾌,열,동상가능,동파가능은 계산이 가능하므로 체감온도처럼 직접 계산하도록 변경 예정.

**Comment by kimalec** [comment]
불쾌지수의 경우 아래에서 자바스크립트도 되어 있는 계산식이 있을 겁니다. 참고하셔서, current와 short에 추가 해주세요.
http://www.kma.go.kr/HELP/basic/help_01_05.jsp

**Comment by neoqmin** [comment]
lifeIndexKmaController.js에 아래 두 함수를 추가했습니다.

getDiscomfortIndex : 불쾌지수를 가져오는 함수
convertStringFromDiscomfortIndex : 불쾌지수에 대한 스트링을 가져오는 함수

**Comment by kimalec** [comment]
계산을 getCurrent,와 getShort 에서 하는데, short의 경우 getShortRss에서 한 번더 overwrite하기 때문에 getLifeIndexKma 안에서 하는게 어떨지 봐주세요.

**Comment by kimalec** [comment]
부패지수는 없어질 예정이라고 함.
