### ISSUE TITLE
KMA 에서 보건기상 지수 가지고 오기.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#257]
#205 에 이어 KMA 보건 기상지수에서 감기지수 저장하기.

**Comment by kimalec** [comment]
#538 연결이슈.

**Comment by kimalec** [comment]
보건기상지수에서 주요 지수는 감기가능지수, 뇌졸중가능지수, 꽃가루농도위험지수임.
뇌졸중가능지수는 이름이 편치 않은 관계로 표시하는 건 기본 off 할 예정임.

**Comment by kimalec** [comment]
요청주소  http://203.247.66.146/iros/RetrieveWhoIndexService/getInflWhoList

[보건기상지수조회서비스.pdf](https://github.com/WizardFactory/TodayWeather/files/315977/default.pdf)

**Comment by neoqmin** [comment]
반환받은 areaNo 데이터 중 아래의 데이터가 기존 towns에 존재하지 않는 데이터입니다.

1171064700
2617064500
2635052500
2671025600
2826053900
2824573000
3020054800
3611054000
4111366200
4111366400
4113162500
4113554500
4119052000
4119051000
4119053000
4119056000
4119054000
4119057000
4119058000
4119059000
4119055000
4119065000
4119061000
4119066000
4119060000
4119068000
4119064000
4119062000
4119067000
4119069000
4119070000
4119072000
4119071000
4119075000
4119076000
4119078000
4119079000
4119063000
4119073000
4119074000
4119080000
4119077000
4119085000
4119081000
4119082000
4119086000
4119084000
4119083000
4145058500
4161037000
4182034500
4571025600
4783025300
4790043000
4790042000
4793039000
4793040000
