### ISSUE TITLE
current 데이터를 저장하여 지난 날씨에 활용하기.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#259]
current 데이터를 저장하여 지난 날씨에 활용하기.
1시간 실제 날씨를 가지고, 지난 3시간 날씨, 하루 날씨 만들기.

**Comment by kimalec** [comment]
1시간 실제 날씨 가지고, 지난 3시간 날씨 만드는 경우에는 온도경우 평균값은 필요없고, 날씨 상태만 필요한데, 이거는 client에 필터링 하는게 좋을꺼 같네요.

차라리 지난 실제날씨와 예보를 분리해서 받아서 처리하는게 좋을지도 모르겠습니다.

주간날씨용 하루날씨는 서버에서 묶어주던지... API상으로는 둘다 있는게 좋을꺼 같습니다만.. 당장은 어떻게 할찌 고민 좀 되네요.

**Comment by kimalec** [comment]
#261 과 연관되어 오후에 논의한 사항은 단기는 실황+(단기를 1시간 단위로 분리) 해서 전송,

단기는 그저께 0시부터, 모레 24시까지 지만 RSS에서 가지고 오는 단기가 합쳐지기 전까지는 예보된 값만 전달.

중기는 실황 + 단기 + 중기로 과거 8일전부터 미래10일까지.

**Comment by kimalec** [comment]
과거는 단기, 중기 데이타 생성용으로 두번 사용되고, 단기도 중기 데이터 생성할때 재사용되기 때문에 그런 상황을 위해서, routing class를 만들어서 instance 생성하여 결과 만들어서 전달하는 형태로 수정이 필요함.

**Comment by kimalec** [comment]
로드한 데이터는 req에 붙여서 재사용하는 것도 방법임.
약간 허술하게 mid과거 구성함. short구성에서 오늘 최대/최소값이 만들어지면 돌아는 갈 것으로 보임.

**Comment by kimalec** [comment]
0,3,6,9,12,15,18,21시에 current를 받기 전까지 데이타 공백이 발생됨.
kma homepage에는 정상적으로 데이터가 나오지만, api로 받을수 있는게 40분부터임.

**Comment by pokers** [comment]
수정 완료
