### ISSUE TITLE
과거시점의 중기 예보 중 최고, 최저 온도를 과거 실제 데이터로 대체

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#264]
과거시점의 중기 예보 데이터는 과거 시점에서의 예보 데이터이므로 실제 온도와는 차이가 있다.
과거 시점의 current데이터를 모으면 해당 날짜의 최고, 최저 온도를 알수 있기 때문에 실제 데이터로 대체하는 내용 구현 필요.

**Comment by kimalec** [comment]
#307 적용되면 진행.

**Comment by kimalec** [comment]
디비에 저장된 데이터를 꺼내어 client에 보낼때(routing단계), 적용되도록 검토 부탁드립니다.

**Comment by pokers** [comment]
과거 정보는 current정보를 취합하여 보내주도록 수정됨
