### ISSUE TITLE
기본 ionic tab template으로 android에서 하단에 tab이 위치하도록 변경

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#27]
ios는 하단에 tab이 위치하지만 동일한 template 임에도 android는 상단에 tab이 위치함

**Comment by kimalec** [comment]
크롬의 Toggle device mode를 사용하여, android, ios 같이 디버깅이 가능함.

![2015-08-05 00 32 02](https://cloud.githubusercontent.com/assets/6895272/9064860/80200bec-3b09-11e5-8742-aaeb8d817193.png)

**Comment by kimalec** [comment]
ion-tabs element 에서 class값이 tabs-bottom(or tabs-top)인 것에 따라, div tab-nav tabs의 위치가 결정되는 것으로 보임.

참고
http://mcgivery.com/structure-of-an-ionic-app/
https://blog.nraboy.com/2014/12/understanding-tabs-ionic-framework/

**Comment by kimalec** [comment]
http://ionicframework.com/docs/components/#striped-style-tab

Add tabs-striped to an element above the tabs classname for Android style tabs.
Optionally, also add tabs-top to position the tab at the top

**Comment by skywlrl** [comment]
[Tab을 Bottom에 위치하는 방법]
* http://stackoverflow.com/questions/27874855/how-to-place-ionic-tabs-at-the-bottom-of-the-screen
* ionicConfigProvider 참고 : http://ionicframework.com/docs/api/provider/%24ionicConfigProvider/
```
MyApp.config(['$ionicConfigProvider', function($ionicConfigProvider) {
    $ionicConfigProvider.tabs.position('bottom'); // other values: top
}]);
```
