### ISSUE TITLE
intro 동영상 개선 작업.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#279]
#139 에 이어서 2차 개선작업 진행

**Comment by joljel** [comment]
![city](https://cloud.githubusercontent.com/assets/14917457/10930660/ae5761d0-8303-11e5-9131-c79e6cdca217.png)
![e1](https://cloud.githubusercontent.com/assets/14917457/10930661/ae5d2818-8303-11e5-967e-913d67dfb0c2.png)
<img width="1019" alt="pl" src="https://cloud.githubusercontent.com/assets/14917457/10930662/ae605b6e-8303-11e5-9b73-384faaa4f5e1.png">
![11111](https://cloud.githubusercontent.com/assets/14917457/10930659/ae55ed6e-8303-11e5-9045-414dab8dd5a3.jpg)
일단 처음에 제작된 영상에서 소스가 교체되어야 하는부분은 4가지임
(기본적으로 위와 같은 이미지로 바뀐 ui로 캡쳐해주시면 감사하겠습니다.)
추가로 설정 화면, 디테일날씨 등도 요청드립니다.

**Comment by joljel** [comment]
애플왓치 제품사진

시간(그래프 긴데이터)
주간(그래프 긴 데이터)
생활지수(데이터 포함)
지역(이쁘게 고치신다음)

마지막 화면

**Comment by kimalec** [comment]
그래프 긴 데이터 시간
<img width="1241" alt="2015-11-09 6 22 38" src="https://cloud.githubusercontent.com/assets/6895272/11030238/2311cdde-8710-11e5-9d6f-12f813e043cc.png">
그래프 긴 데이터 주간
<img width="938" alt="2015-11-09 6 31 01" src="https://cloud.githubusercontent.com/assets/6895272/11030237/2311738e-8710-11e5-9956-902a1c0a5d95.png">
생활지수
<img width="359" alt="2015-11-09 6 38 39" src="https://cloud.githubusercontent.com/assets/6895272/11030405/2b63eec6-8711-11e5-9be4-a3e8d29beab6.png">

**Comment by kimalec** [comment]
추가 필요한 화면 - 크롬 확장 화면, tv app 화면

**Comment by kimalec** [comment]
저장된 도시리스트
<img width="360" alt="2015-11-10 7 56 50" src="https://cloud.githubusercontent.com/assets/6895272/11049388/3778068c-8781-11e5-9155-3e216f796e29.png">
도서검색
<img width="359" alt="2015-11-10 7 59 21" src="https://cloud.githubusercontent.com/assets/6895272/11049395/42086178-8781-11e5-867f-a198c397da20.png">
선택한 도시 시간별날씨
<img width="360" alt="2015-11-10 7 59 37" src="https://cloud.githubusercontent.com/assets/6895272/11049408/58b8aedc-8781-11e5-98e4-26cbfb6c76ab.png">
도시 삭제
<img width="359" alt="2015-11-10 7 57 16" src="https://cloud.githubusercontent.com/assets/6895272/11049413/64ece006-8781-11e5-85e7-92efbb2e1b7c.png">

**Comment by kimalec** [comment]
이야기했던 스크린샷임
<img width="625" alt="2015-11-12 00 01 27" src="https://cloud.githubusercontent.com/assets/6895272/11094012/b853a1e4-88d0-11e5-8d3b-7573aefce007.png">

**Comment by kimalec** [comment]
수정본
https://www.youtube.com/watch?v=q46Pptv9i04
