### ISSUE TITLE
Application workflow and UI design

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#3]
Application workflow and UI design

**Comment by kimalec** [comment]
![2015-06-14 15 20 20](https://cloud.githubusercontent.com/assets/6895272/8147561/9a8aed2a-12ab-11e5-8157-1c3b73ee2bab.png)

**Comment by kkkiiikkii** [comment]
![1](https://cloud.githubusercontent.com/assets/12652131/8636975/cb5e0dd4-28b7-11e5-940c-a14783545f92.PNG)
![2](https://cloud.githubusercontent.com/assets/12652131/8636976/cb5ee4e8-28b7-11e5-8503-aa9ef87e2b42.PNG)

**Comment by kkkiiikkii** [comment]
되게 크게 올라감

**Comment by kkkiiikkii** [comment]
![3](https://cloud.githubusercontent.com/assets/12652131/8636979/e422074e-28b7-11e5-86be-5a13f0b5efb7.JPG)
![4](https://cloud.githubusercontent.com/assets/12652131/8636978/e421d382-28b7-11e5-9352-60c1ef4bae12.JPG)

**Comment by kkkiiikkii** [comment]
![0717 2](https://cloud.githubusercontent.com/assets/12652131/8764751/667fd7b0-2e27-11e5-9a50-f053d9195a10.jpg)

**Comment by kkkiiikkii** [comment]
![default](https://cloud.githubusercontent.com/assets/12652131/8764753/77d186d0-2e27-11e5-84e4-4d526421d49a.jpg)

**Comment by kimalec** [comment]
주요이벤트(비,눈,우박..) 에 대한 변경 알림.
![default](https://cloud.githubusercontent.com/assets/6895272/8865780/2eb4d12a-31ef-11e5-92a2-459c85d76970.JPG)

현대카드 웨더의 카카오스토리 공유 모양
![default](https://cloud.githubusercontent.com/assets/6895272/8865807/a4bce826-31ef-11e5-8dd4-06ca208c240e.JPG)

광고제거 시나리오
![default](https://cloud.githubusercontent.com/assets/6895272/8865815/cc41111a-31ef-11e5-9f96-becb315c926a.JPG)

별이되어라 카카오톡 공유 모양
![default](https://cloud.githubusercontent.com/assets/6895272/8865900/ef6ea50c-31f0-11e5-9483-e83e0a228bf5.JPG)
![default](https://cloud.githubusercontent.com/assets/6895272/8865901/f1c1b434-31f0-11e5-83ce-bb2606dacc39.JPG)

처음접속시 가이드 시나리오
![default](https://cloud.githubusercontent.com/assets/6895272/8865908/ffa79ffa-31f0-11e5-9334-605b3b26ddeb.JPG)

아이폰위젯 날씨 위젯들
![default](https://cloud.githubusercontent.com/assets/6895272/8865912/0b97a0d0-31f1-11e5-8ba6-9fb1228ff889.JPG)
![default](https://cloud.githubusercontent.com/assets/6895272/8865913/0f1c011a-31f1-11e5-837c-cd53ee25a117.JPG)

애플와치알림
![default](https://cloud.githubusercontent.com/assets/6895272/8865930/4ea86ddc-31f1-11e5-99a2-54cb241f6429.JPG)
![default](https://cloud.githubusercontent.com/assets/6895272/8865932/53d51bb6-31f1-11e5-9a9a-7b1cfc356255.JPG)

**Comment by kimalec** [comment]
[[무료 다운로드]20종 고해상도 그룬지 백그라운드 이미지 팩](http://www.designlog.org/2512580) 이런 백그라운드 이미지쓰면 좀 고급져 보이지 않을까요?

**Comment by kimalec** [comment]
https://www.behance.net/gallery/27650255/App-Concept-Design-For-Drop-a-Truck - 딱 습도 느낌.

**Comment by kkkiiikkii** [comment]
![1-01](https://cloud.githubusercontent.com/assets/12652131/9024802/f96dc142-391f-11e5-90a3-2c97bf1bbca1.jpg)

**Comment by kkkiiikkii** [comment]
<img width="900" alt="2015-08-02 2 16 22" src="https://cloud.githubusercontent.com/assets/12652131/9024819/f9f9f8c8-3920-11e5-9555-59d769a7a4a9.png">

**Comment by kimalec** [comment]
UI 좌표정보
![____________________________________](https://cloud.githubusercontent.com/assets/6895272/9219215/1c761a6c-4114-11e5-8e18-d2fe2fafac3a.jpg)

**Comment by kimalec** [comment]
아래와 같이 최고/최저 부분은 색깔을 다르게 하는건 어떨까요?
<img width="141" alt="2015-09-10 07 38 29" src="https://cloud.githubusercontent.com/assets/6895272/9776025/213f8dee-578f-11e5-80ce-2696e95d8d68.png">

**Comment by kimalec** [comment]
이런 그라데이션 효과를 배경으로 해볼만하지 않을까요?

![default](https://cloud.githubusercontent.com/assets/6895272/10035788/0b687f0e-61d9-11e5-9ef9-7481b7af32c2.JPG)
