### ISSUE TITLE
www/img 폴더에 SnowWithLightning.png 파일 없음

### ISSUE THREAD

**Issue by neoqmin** [WizardFactory/TodayWeather#323]
applewatch 앱에 이미지 파일을 복사하는중 파일이 없음을 확인했습니다.

SnowWithLightning-Big.png 파일은 존재하지만, SnowWithLightning.png 파일이 없습니다.

**Comment by kimalec** [comment]
실제로 눈오면서 번개가 치는 경우가 있나 싶었는데, 가능은 하네요 ㅋ

https://www.youtube.com/watch?v=nefLipXk36o

**Comment by kimalec** [comment]
#410 에서 같이 진행.
