### ISSUE TITLE
ram mode에서 현재위치의 일별날씨 그래프가 과거부터, 오늘, 내일까지 최대/최소 온도가, undefined임.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#333]
서버로부터 데이터는 전달 받은거 같은데, 일부 데이터가 undefined됨.

https://d2ibo8bwl7ifj5.cloudfront.net/town/%EA%B2%BD%EA%B8%B0%EB%8F%84/%EC%84%B1%EB%82%A8%EC%8B%9C%EB%B6%84%EB%8B%B9%EA%B5%AC/%EC%88%98%EB%82%B41%EB%8F%99

<img width="345" alt="2015-11-12 11 42 11" src="https://cloud.githubusercontent.com/assets/6895272/11109328/c0acb2e2-8932-11e5-8c26-1ee7e7efb151.png">
<img width="175" alt="2015-11-12 11 42 18" src="https://cloud.githubusercontent.com/assets/6895272/11109329/c0f5aa38-8932-11e5-85fc-0c3bfad844c8.png">

**Comment by kimalec** [comment]
실제로 전달되는 데이터, 20151105부터, 20151113일까지 tmx, tmn데이터가 없음.
```js
"dailyData": [{
    "date": "20151105",
    "wfAm": "구름많음",
    "wfPm": "구름많음"
}, {
    "date": "20151106",
    "wfAm": "구름많음",
    "wfPm": "구름많음"
}, {
    "date": "20151107",
    "wfAm": "흐리고 비",
    "wfPm": "흐리고 비"
}, {
    "date": "20151108",
    "wfAm": "흐리고 비",
    "wfPm": "흐리고 비"
}, {
    "date": "20151109",
    "wfAm": "흐리고 비",
    "wfPm": "구름많음"
}, {
    "date": "20151110",
    "wfAm": "구름조금",
    "wfPm": "구름조금"
}, {
    "date": "20151111",
    "wfAm": "구름조금",
    "wfPm": "구름많음"
}, {
    "date": "20151112",
    "wfAm": "구름많음",
    "wfPm": "구름많음"
}, {
    "date": "20151113",
    "wfAm": "구름많음",
    "wfPm": "구름많음"
}
```

**Comment by kimalec** [comment]
아래 조건문에서 tmx가 null인 경우 true 이니 조심해야 함.
```js
if (shortForecast.t3h > dayInfo.tmx) {
```

**Comment by pokers** [comment]
DB 모드로 동작 전환 됨. 해당 내용은 db 모드에서 발생시 다른 이슈 발행 필요.
