### ISSUE TITLE
대림2동, 신공덕동, 사당1동 에러 수정

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#358]
서울특별시/영등포구/대림2동
서울특별시/마포구/신공덕동
서울특별시/동작구/사당1동

두 동에 대하여 요청이 오지만 서버 town list에 업어서 제대로 데이터를 전달하지 못함.

**Comment by kimalec** [comment]
아까 이야기 했던 주소임.

**Comment by pokers** [comment]
현재 github 소스 기준 위 주소들이 오청올때 google api를 통해서 정상적으로 mx, my를 가져오고 매칭 되는 동네 좌료를 찾음.
좌표 변환 및 short, shortest, current데이터는 정상적으로 쿼리 하지만 아직 mid등 다른 데이터에대한 처리가 되어 있지 않고, DB사용시에도 대응되어 있지 않기 때문에 문제 발생하는 것으로 보여짐.
추후 DB 기능 완료후 다시 확인 필요.

**Comment by kimalec** [comment]
convertGeocode is not defined 나는 곳 두군데 추가

경상남도/창원시성산구/가음정동
경상남도/창원시성산구/대방동

**Comment by kimalec** [comment]
위와 같이 동을 못 찾는 경우에 구 단위의 데이터를 찾아서 전달하는 방법으로 임시조치가 가능할 것으로 보임.

**Comment by kimalec** [comment]
town/서울특별시/광진구/구의3동 

base.csv에는 구의제3동으로 등록되어 있음. 지금 base.csv에는 읍면동에서 '제'라고 붙는 것이 많음.

**Comment by kimalec** [comment]
/town/경상남도/창원시의창구/팔용동
/town/광주광역시/광산구/산정동
/town/경상남도/창원시의창구/명서동
/town/경기도/용인시기흥구/서천동
/town/경기도/부천시소사구/소사본1동
/town/경기도/부천시소사구/소사본동
/town/경기도/여주군/가남면 -> 여주시/가남읍으로 변경되었지만, 구글API에는 반영되지 않아 군,면으로 나오고 있음.
/town/경기도/수원시영통구/망포동
/town/서울특별시/강남구/자곡동
/town/경기도/안산시단원구/원시동
/town/경기도/성남시분당구/수내동
/town/강원도/강릉시/노암동
/town/부산광역시/강서구/성북동
/town/경상남도/거제시옥포2동/undefined -> 파싱오류인듯, 0.6.3 정상동작함.

**Comment by kimalec** [comment]
/town/강원도/강릉시/노암동		
/town/강원도/원주시원인동/undefined		
/town/경기도/군포시수리동/undefined		
/town/경기도/성남시수정구/금토동	추가	
/town/경기도/성남시수정구/오야동	추가	
/town/경기도/성남시중원구/여수동	추가	
/town/경기도/안산시단원구/원시동		
/town/경기도/여주군/강천면	여주군->여주시	
/town/경기도/용인시기흥구/서천동		
/town/경기도/이천시/설성면.kr		
/town/경기도/파주시운정2동/undefined		
/town/경기도/하남시망월동/undefined	추가	
/town/경기도/하남시풍산동/undefined		
/town/경상남도/거제시능포동/undefined		
/town/경상남도/거제시옥포2동/undefined		
/town/경상남도/진주시/강남동	동작확인필요	
/town/경상남도/창원시의창구/명서동	동작확인필요	500 Error
/town/경상남도/창원시의창구/팔용동	팔룡동->팔용동	500 Error
/town/부산광역시/동래구/낙민동	추가	
/town/서울특별시/강서구/방화2동		500 Error
/town/서울특별시/구로구/구로3동		500 Error
/town/서울특별시/구로구/구로4동		500 Error
/town/서울특별시/동작구/사당1동		500 Error
/town/서울특별시/동작구/사당동	추가	
/town/서울특별시/마포구/신공덕동	추가	
/town/서울특별시/서대문구/홍은2동		500 Error
/town/서울특별시/서대문구/홍제1동		500 Error
/town/서울특별시/서대문구/홍제2동		500 Error
/town/서울특별시/성동구/행당1동		500 Error
/town/서울특별시/성북구/월곡1동		500 Error
/town/서울특별시/영등포구/대림2동		500 Error
/town/서울특별시/영등포구/여의도동	추가	여의동으로 인식
/town/전라남도/무안군/삼향읍	면->읍	500 Error
/town/충청남도/연기군/남면	연기군->태안군	
town/경기도/성남시중원구/여수동	추가

**Comment by kimalec** [comment]
0.6.4 수정후 결과
```
서울특별시/영등포구/대림2동	
서울특별시/마포구/신공덕동	공덕동으로 표시됨
서울특별시/동작구/사당1동	
/town/경상남도/창원시성산구/가음정동	
/town/경상남도/창원시성산구/대방동	사파동으로 표시됨
/town/경상남도/창원시성산구/중앙동	
/town/경상남도/창원시성산구/반송동	
/town/경상남도/창원시마산합포구/가포동	
/town/경상남도/창원시의창구/용지동	
/town/경상남도/창원시마산합포구/산호동	
town/서울특별시/광진구/구의3동	
/town/경상남도/창원시의창구/팔용동	팔룡동으로 표시
/town/광주광역시/광산구/산정동	하남동으로 표시
/town/경상남도/창원시의창구/명서동	명곡동으로 표시
/town/경기도/용인시기흥구/서천동	서농동으로 표시
/town/경기도/부천시소사구/소사본1동	소사본3동으로 표시
/town/경기도/부천시소사구/소사본동	
/town/경기도/여주군/가남읍	여흥동으로 표시
/town/경기도/수원시영통구/망포동	태장동으로 표시
/town/서울특별시/강남구/자곡동	세곡동
/town/경기도/안산시단원구/원시동	초지동
/town/경기도/성남시분당구/수내동	수내1동
/town/강원도/강릉시/노암동	강남동
/town/부산광역시/강서구/성북동	가덕도동
/town/경상남도/거제시옥포2동/	
/town/강원도/원주시원인동/undefined	
/town/경기도/군포시수리동/undefined	
/town/경기도/성남시수정구/금토동	시흥동
/town/경기도/성남시수정구/오야동	신촌동
/town/경기도/성남시중원구/여수동	도촌동
/town/경기도/여주군/강천면	
/town/경기도/용인시기흥구/서천동	서농동
/town/경기도/이천시/설성면.kr	
/town/경기도/파주시운정2동/undefined	
/town/경기도/하남시망월동/undefined	미사2동
/town/경기도/하남시풍산동/undefined	
/town/경상남도/거제시능포동/undefined	
/town/경상남도/거제시옥포2동/undefined	
/town/경상남도/진주시/강남동	천전동
/town/경상남도/창원시의창구/명서동	명곡동
/town/경상남도/창원시의창구/팔용동	팔룡동
/town/부산광역시/동래구/낙민동	수민동
/town/서울특별시/강서구/방화2동	
/town/서울특별시/구로구/구로3동	
/town/서울특별시/구로구/구로4동	
/town/서울특별시/동작구/사당1동	
/town/서울특별시/동작구/사당동	
/town/서울특별시/서대문구/홍은2동	
/town/서울특별시/서대문구/홍제1동	
/town/서울특별시/서대문구/홍제2동	
/town/서울특별시/성동구/행당1동	
/town/서울특별시/성북구/월곡1동	
/town/서울특별시/영등포구/여의도동	여의동
/town/전라남도/무안군/삼향읍	
/town/충청남도/연기군/남면	부여군/남면
```

**Comment by kimalec** [comment]
12/6~12/8사이에 5XX는 없었음.
