### ISSUE TITLE
초단기 예보 설명이 맞지 않는 문제.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#368]
초단기예보는 각 30분 마다, 바로 1~2시간 앞이나, 1~3시간 앞의 정보를 전달 한다고 되어 있지만, 실제로 전달되는 데이타는 2시간 후의 정보 하나만 전달해주고 있다. 
실제 kma.go.kr에 가보면 2시간, 혹은 3시간 앞의 정보를 보여주고 있다.

** 문서 설명 **
발표시간 - 초단기
00:30 - 01,02
01:30 - 02,03
02:30 - 03,04,05

** 홈페이지 정보 **
<img width="500" alt="2015-11-28 18 27 19" src="https://cloud.githubusercontent.com/assets/6895272/11451144/fafce2fa-95fd-11e5-99ae-252d08d6d0d1.png">

** 실제 받는 데이터 **
http://newsky2.kma.go.kr/service/SecndSrtpdFrcstInfoService/ForecastTimeData?base_date=20151128&base_time=1530&nx=62&ny=125&serviceKey=KEY&_type=json&pageNo=1
```javascript
{
    "response": {
        "header": {
            "resultCode": "0000",
            "resultMsg": "OK"
        },
        "body": {
            "items": {
                "item": [{
                    "baseDate": 20151128,
                    "baseTime": 1530,
                    "category": "LGT",
                    "fcstDate": 20151128,
                    "fcstTime": 1730,
                    "fcstValue": 0,
                    "nx": 62,
                    "ny": 125
                }, {
                    "baseDate": 20151128,
                    "baseTime": 1530,
                    "category": "PTY",
                    "fcstDate": 20151128,
                    "fcstTime": 1730,
                    "fcstValue": 0,
                    "nx": 62,
                    "ny": 125
                }, {
                    "baseDate": 20151128,
                    "baseTime": 1530,
                    "category": "RN1",
                    "fcstDate": 20151128,
                    "fcstTime": 1730,
                    "fcstValue": 0,
                    "nx": 62,
                    "ny": 125
                }, {
                    "baseDate": 20151128,
                    "baseTime": 1530,
                    "category": "SKY",
                    "fcstDate": 20151128,
                    "fcstTime": 1730,
                    "fcstValue": 4,
                    "nx": 62,
                    "ny": 125
                }]
            },
            "numOfRows": 10,
            "pageNo": 1,
            "totalCount": 4
        }
    }
```

**Comment by kimalec** [comment]
초단기는 웹페이지 크롤링해서 적용하는 것도 고려해봐야 할 듯 함.

**Comment by kimalec** [comment]
#375 신동네예보에서 제대로 제공하고 있음. routing시에 current와 short에 업데이트 필요. 

예:) 실황은 8시 데이터를 8시 40분에 제공하기 때문에 사용자가 보는 8시 날씨 상태는 7시 40분에 제공하는 초단기예보의 하늘 상태를 쓰는 것이 더 적합하다.

**Comment by pokers** [comment]
이거 결국 최근에 받은 shortest의 sky를 client가 요청하는 시점의 short, current에 적용하면 되는거죠?
예를 들어 
1. 서버에 12:30분에 shortest를 받은 데이터있고, short, current데이터도 최신 상태.
2. client가 1시20에 데이터를 요청 했을때
3. short의 현재 시간은 12:00이고 , current의 현재 시간은 1:00이다.
4. short데이터의 12:00 데이터의 sky 정보에 shortest의 sky 정보를 넣는다.
5. current데이터의 1:00 데이터의 shy 정보에 shortest의 sky 정보를 넣는다.

**Comment by kimalec** [comment]
5번은 맞고, short 12시는 과거 current가 들어가 할꺼 같아요. 
shortest의 3시데이터가 있다면 15시의 sky 정보에 shortest sky 정보를 넣어서 갱신하구요.

**Comment by pokers** [comment]
정리. 클라이언트를 위해서 short, current데이터를 빌드 할 때에 각각의 데이터가 가지는 시간과 일치하는 shortest데이터 element가 있다면 shortest의 sky데이터로 갱신한다.
