### ISSUE TITLE
시도, 시군구  요청에 경우에도, 정상적인 데이터 전송.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#382]
읍면동 뿐만 아니라, 시/도, 시/군/구 요청의 경우에도 정상적으로 데이터 전달.
지금도 데이터가 전달되지만, current/short/mid 모두가 전달되는 것은 아님.

town/경상남도/
town/경상남도/창원시마산합포구

#381 와 관련 있음.

**Comment by pokers** [comment]
충청북도/세종특별자치시의 lat, lon은 lat=36.8, lon=127.7
이를 mx,my로 변환하면 mx=73, my=110 가 나오는데.
해당 좌표는 현재 town 리스트에 없기 때문에 error 발생한다.
