### ISSUE TITLE
weather api 조사

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#4]
Weather api 사용법, 가격 조사.

조건
가능한 세계날씨를 저장하고 있어야 한다. 그러기 위해서 데이터를 기상관측소로 저장하고, 각 지역은 계산하는 형태로 구해야 함. 
api 제공업체에서 저장 못하게 하는 경우가 있음. (skplanet)

**Comment by kimalec** [comment]
[동네예보정보조회서비스](https://www.data.go.kr/subMain.jsp#/cHVici91c2UvcHJpL0lyb3NPcGVuQXBpRGV0YWlsL29wZW5BcGlMaXN0UGFnZSRAXjAxMm0yMSRAXnB1YmxpY0RhdGFQaz0xNTAwMDA5OSRAXmJybUNkPU9DMDAxMyRAXm1haW5GbGFnPXRydWU=)
공공데이터에서 제공하는 것으로 특별한 제약은 없을듯함.

[wunderground](http://www.wunderground.com/weather/api/d/pricing.html?MR=1)
yahoo날씨에서 사용하고 있음.

[http://openweathermap.org/API](http://openweathermap.org/price)
40,000개 이상의 기상 관측소의 데이터 기반으로 업데이트 된 70,000도시의 현재 날씨 정보를 제공한다. 

[Weather Planet](https://developers.skplanetx.com/apidoc/kor/weather/information/)
현재날씨(시간별) - 수집된 기상관측 정보를 격자단위로 분석.처리하여 1시간 단위로 현재날씨 정보를 제공한다.
초단기예보 - 1시간 간격으로 매일 24회, 5Km 격자 단위로 4시간까지의 초단기예보 정보를 제공한다.
단기예보 - 3시간 간격으로 매일 8회(2, 5, 8, 11, 14, 17, 20, 23시), 5Km 격자 단위로 단기예보 정보를 제공하며, 예보시간은 발표시간+4시간부터 최대 67시간(3일)까지 제공한다.
중기예보 - 12시간 간격으로 매일 2회(6시, 18시), 주요 시도 단위로 중기예보 정보를 제공하며, 예보시간은 일단위로 +3일부터 +10일까지 제공한다.(+2일 예보는 ’14년 6월까지만 제공)

참고: http://www.apistore.co.kr/api/apiList.do

**Comment by kimalec** [comment]
공공데이터(data.go.kr)에서 참고해야 할 api

기상청
생활기상지수조회
산업기상지수 조회
보건기상지수
동네예보정보조회서비스
예보구역정보조회
중기예보정보조회서비스

한국환경공단
대기오염통계 서비스 
대기오염정보 조회 서비스 
측정소정보 조회 서비스 
오존황사 발생정보조회 서비스

**Comment by pokers** [comment]
* 동네 예보 정보 조회 서비스
 * spec DOC : https://www.data.go.kr/subMain.jsp#/L3B1YnIvcG90L215cC9Jcm9zTXlQYWdlL29wZW5EZXZHdWlkZVBhZ2UkQF4wMTIkQF5wdWJsaWNEYXRhRGV0YWlsUGs9dWRkaTphZjkxNDdlOS1hYzlhLTQ1MjktOTBlMC05NGFjNDI3ZjlkYTckQF5tYWluRmxhZz10cnVl
 * doc 문서의 제일 아랫부분에 x,y좌료 <-> 위도,경도 변환 프로그램예제가 첨부되어 있음. (C언어)
 * xlsx 파일의 내용을 보면 동네별 위도,경도 좌표가 나와있다.

위도 ,경도 좌표를 위의 프로그램으로 x,y좌표로 변환가능할듯...
