### ISSUE TITLE
단기예보 RSS 데이터 사용하는 부분 검토 및 오류 수정.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#408]
단기예보 RSS 데이터 사용하는 부분 검토 및 오류 수정.
아래 코멘트에 관련한 작업으로, 확인된 사항으로는, 예보 시간 값에 오류가 있음.
(0시, 3시, 6, 9... ) 식이어여야 하는데, 2시, 4시 형태로 보였음.

https://github.com/WizardFactory/TodayWeather/issues/187#issuecomment-150773914

참고로 KMA REST API를 사용하는 것이 아니라, RSS를 통하여 가지고 오는 데이터임.

**Comment by kimalec** [comment]
RSS데이터에 시간정보가 1 4 7 10 13 16 19 이렇게 되 있어서 RSS머지할때 문제가 생기는듯.

TownRss.prototype.calculateTime() 요기에서 시간 계산을 잘못하고 있을 것으로 예상됨.

**Comment by neoqmin** [comment]
출력 결과
[queryDFS.jsp.xml](https://github.com/WizardFactory/TodayWeather/files/60903/queryDFS.jsp.xml.txt)

RSS 데이터의 시간 정보는 kma 홈페이지와 동일하게 3시간 단위로 표시된(18, 21,...)

결과 xml 파일의 <hour>18</hour>값을 계산 없이 날짜에 붙여서 사용하면 해결될 것 같음.

**Comment by neoqmin** [comment]
windows에서 timezone 문제로 정상적인 시간 출력이 안됨

이런 증상이 원인인지는 확실하지 않음

하지만, windows에서 아래의 코드를 수정하고, 시간이 정상적으로 출력됨을 확인함
```javascript
var _userOffset = now.getTimezoneOffset() * 60 * 1000;

now.setTime(now.getTime() + (offset * 60 * 60 * 1000) + _userOffset);
```
201512142100, 201512150000

**Comment by kimalec** [comment]
시간을 UTC 기준으로 처리해야 할겁니다. 

TodayWeather/server/lib/lifeIndexKmaRequester.js
```js
 l.nextTime.setUTCDate(l.nextTime.getUTCDate()+1);
```

**Comment by neoqmin** [comment]
![openshift timezone](https://cloud.githubusercontent.com/assets/11567505/11801437/3b412172-a329-11e5-9fcf-13a4d433aab3.jpg)

openshift에서 calculateTime으로 18을 더한값이 13이 됩니다.
