### ISSUE TITLE
가이드 화면 개선

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#409]
변경된 시나리오따라 가이드화면 만들기

가이드 화면을 설명 + 스크린 화면으로 구성하여, app store에 등록하는 스크린샷 화면과, 가이드 화면 양쪽에 사용하자.

guide를 template로 분리하여 적용하고, 설정->도움말을 선택하면 다시 볼 수 있게 하자.

**Comment by kimalec** [comment]
사용자 모니터링(오늘날씨를 사용해보지 않은 사람에게 link 전달하여 사용하는 것을 관찰)

user1 (어제날씨라는 앱과 몇몇 날씨앱을 찾아봤으나, 맘에 드는 것이 없이 네이버날씨를 사용하고 있음)
구름동이 뭐지 하고 당황함.
forecast 버튼을 눌러봄. (forecast tab이 active 되어 있어서 눌러봤다고 함)
리로드 버튼을 찾지 못하여, 도시 검색으로 가서 도시 추가 먼저 하였음.
어제보다 몇도 높음 글을 인지하지 못하고, 어제보다 상대온도를 알려달라고 하였음.
차트에 관심이 없었음.
좌/우 스왑으로 도시 변경을 발견 못했음.

user2 (직관적인 디자인을 좋아함.)
구름동? 이라고 말함.
forecast 버튼을 눌러봄
리로드 버튼을 누름.
차트를 누르다가 일별날씨로 넘어갔음.
도시검색시에 대구만 검색하고, 키보드 띄워져 있는 상태에서 스크롤을 시도함.
대구 달서구 로 검색시도함.
동단위로 검색하라고 이야기 해준 후에 제대로 검색하였음.
일별날씨 화면이 좋다고, 그 화면이 메인이면 좋겠다고 했음.
시간별날씨 그래프에서는 여백에 색깔이 있어서 차이임을 확실히 인지 할 수 있다면 좋겠다고함.

**Comment by kimalec** [comment]
https://forum.ionicframework.com/t/best-way-to-add-a-ion-view-to-ion-tabs-without-having-a-tab/

**Comment by kkkiiikkii** [comment]
[가이드 화면 기기별 모음.zip](https://github.com/WizardFactory/TodayWeather/files/201146/default.zip)

**Comment by kkkiiikkii** [comment]
[가이드 화면 기기별 모음2.zip](https://github.com/WizardFactory/TodayWeather/files/201154/2.zip)

**Comment by kkkiiikkii** [comment]
[가이드 화면 기기별 모음2.zip](https://github.com/WizardFactory/TodayWeather/files/201174/2.zip)

**Comment by kkkiiikkii** [comment]
[가이드 화면 기기별 모음 JPG.zip](https://github.com/WizardFactory/TodayWeather/files/201219/JPG.zip)

**Comment by kimalec** [comment]
첨부파일 열어보면, "가이드 화면만 따로" 라는 이미지 활용하면 됩니다. 만약 핸드폰 프레임만 따로 있는게 편하면 재요청 해주세요.

**Comment by skywlrl** [comment]
[Skip, Close 처리 구성안]
* Skip 버튼 + '>' 버튼 
* '<' 버튼 + Close 버튼 : 마지막 페이지인 경우
* ![image](https://cloud.githubusercontent.com/assets/8368939/14231783/e4650956-f9ca-11e5-831d-856ae15128d3.png)

**Comment by kimalec** [comment]
기존에 tab-forecast.html과 ForecastCtrl에 있는 guide code도 제거 부탁드려요.

**Comment by skywlrl** [comment]
"가이드 화면만 따로" 이미지 수정 요청
 - 폰 이미지 하단이 잘린 이미지 & 배경색 변경

**Comment by kimalec** [comment]
아래 페이지도 디바이스 하단 짜르거나, 그림자 없애는 게 좋을 듯 함.
<img width="333" alt="2016-04-11 10 54 44" src="https://cloud.githubusercontent.com/assets/6895272/14414877/e133b20a-ffd3-11e5-8e6c-65d959942b22.png">

**Comment by kimalec** [comment]
가이드 나오는 동안 광고 off해야함.

**Comment by kimalec** [comment]
탭 왔다갔다 반복하다보면, 언제부턴가 android back로 나가지 못하는 경우가 발생함.

**Comment by kkkiiikkii** [comment]
![5 5 -05](https://cloud.githubusercontent.com/assets/12652131/14584632/ac9173e6-048a-11e6-87c1-88a705dbc51f.png)

**Comment by kimalec** [comment]
Util.showAd를 true로 초기화해야 함.

**Comment by kimalec** [comment]
#783 에서 변경사항 적용하고, showAd관련 초기화해서 동작 확인 예정.

**Comment by kimalec** [comment]
#807 에서 관련 부분 수정하였음.
