### ISSUE TITLE
날씨 상태별 아이콘 확장.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#410]
#209 UI 2.0 개선의 일환으로 KMA에 제공하는 데이터에 맞게 하늘상태를 표현하게 함.
날씨 상태별 아이콘 확장.

하늘 상태 : 맑음, 구름 조금, 구름 많음, 흐림
강수 형태 : 없음, 비, 눈, 비/눈
번개 : 없음, 있음.

**Comment by kimalec** [comment]
<img width="360" alt="2015-12-20 13 43 50" src="https://cloud.githubusercontent.com/assets/6895272/11916570/cba51ac6-a71f-11e5-8d2c-852f36d882b2.png">

**Comment by kimalec** [comment]
날씨 아이콘 설명
http://www.kma.go.kr/weather/icon_info.html
<img width="320" src="https://cloud.githubusercontent.com/assets/6895272/11944654/0d23a0dc-a88b-11e5-895f-109471e14644.PNG">

강수 아이콘
http://www.kma.go.kr/popup/20120626_kma_icon.jsp
<img width="480" src="https://cloud.githubusercontent.com/assets/6895272/11944705/562541f0-a88b-11e5-8460-bcdc28d19d6b.PNG">

**Comment by kkkiiikkii** [comment]
<img width="1361" alt="2 0 1" src="https://cloud.githubusercontent.com/assets/12652131/12375498/70609948-bd08-11e5-81e0-9452c54f890b.png">
<img width="1375" alt="2 0 2" src="https://cloud.githubusercontent.com/assets/12652131/12375499/7061ed02-bd08-11e5-8ba5-b1b151bca384.png">

**Comment by kkkiiikkii** [comment]
날씨 아이콘 2.0 압축
[날씨 아이콘 2.0 뉴버전.zip](https://github.com/WizardFactory/TodayWeather/files/93184/2.0.zip)

**Comment by kimalec** [comment]
"맑고 눈" 이라는 상태가 있네요.

**Comment by kimalec** [comment]
날씨 아이콘 회색 버전 필요.

**Comment by kimalec** [comment]
파일 포멧을 SVG로 만드는거 해봐주세요.

**Comment by kkkiiikkii** [comment]
[sun.svg.zip](https://github.com/WizardFactory/TodayWeather/files/190736/sun.svg.zip)

**Comment by kkkiiikkii** [comment]
[160327_날씨아이콘2.0(회색).zip](https://github.com/WizardFactory/TodayWeather/files/190740/160327_.2.0.zip)

**Comment by kkkiiikkii** [comment]
[160327_날씨아이콘2.0 SVG(회색).zip](https://github.com/WizardFactory/TodayWeather/files/190754/160327_.2.0.SVG.zip)

**Comment by kimalec** [comment]
png icon은 최대 크기 48로 한다치면 192x192이어야 하고, 현재 메인 아이콘은 72px정도 이며, 이정로일때 288x288정도여야 할 것으로 생각됨.

**Comment by kkkiiikkii** [comment]
[가이드 화면만 따로(5.5형).zip](https://github.com/WizardFactory/TodayWeather/files/211672/5.5.zip)

**Comment by kkkiiikkii** [comment]
[날씨 아이콘_288*288(흰색).zip](https://github.com/WizardFactory/TodayWeather/files/222466/_288.288.zip)

**Comment by kkkiiikkii** [comment]
[날씨 아이콘_288*288(회색).zip](https://github.com/WizardFactory/TodayWeather/files/222467/_288.288.zip)

**Comment by kimalec** [comment]
SunLightning, SunSmallCloudLightning, SunBigCloudLightning, MoonLightning, MoonSmallCloudLightning, MoonBigCloudLightning, CloudLightning 없음.

**Comment by kimalec** [comment]
날씨아이콘 폰트
[twicon.zip](https://github.com/WizardFactory/TodayWeather/files/222676/twicon.zip)

참고
http://www.sitepoint.com/create-an-icon-font-illustrator-icomoon/

**Comment by kkkiiikkii** [comment]
[구름번개(회색).zip](https://github.com/WizardFactory/TodayWeather/files/244074/default.zip)
[구름번개(흰색).zip](https://github.com/WizardFactory/TodayWeather/files/244073/default.zip)

**Comment by kkkiiikkii** [comment]
[알람설정 가이드 화면.zip](https://github.com/WizardFactory/TodayWeather/files/276171/default.zip)

**Comment by kimalec** [comment]
아이패드, 아이패드 프로도 부탁해.

**Comment by kimalec** [comment]
시간,날씨, 온도 일렬 정렬 vs KMA style 정렬
<img width="240" alt="2016-05-22 18 32 09" src="https://cloud.githubusercontent.com/assets/6895272/15525438/509b0cfc-2265-11e6-9d2c-3b324c1712f9.png"> <img width="240" alt="2016-05-22 18 33 40" src="https://cloud.githubusercontent.com/assets/6895272/15525439/50d35d8c-2265-11e6-858e-e1eca6daa950.png">

**Comment by kkkiiikkii** [comment]
[알람설정 가이드 화면 추가.zip](https://github.com/WizardFactory/TodayWeather/files/287690/default.zip)

**Comment by kimalec** [comment]
KMA Style의 이점.
시간 사이이기 때문에 강수량을 표시할때, 의미가 명확해짐 (3시~6시 8.1mm)
시간 사이이기 때문에 일출/일몰을 날씨 아이콘을 빼고, 일출/일몰아이콘 그리고 아래에 시간 넣을 수 있음.

**Comment by kkkiiikkii** [comment]
[흰색 아이콘 수정.zip](https://github.com/WizardFactory/TodayWeather/files/322064/default.zip)

**Comment by kkkiiikkii** [comment]
[칼라아이콘.zip](https://github.com/WizardFactory/TodayWeather/files/322066/default.zip)

**Comment by kimalec** [comment]
https://material.google.com/style/icons.html#icons-system-icons

**Comment by kimalec** [comment]
wind(바람 방향), humidity(습도), pm10, temp, ultrv, umbrella 들 SVG로도 전달해주세요.

**Comment by kkkiiikkii** [comment]
[160623 칼라아이콘 PNG.zip](https://github.com/WizardFactory/TodayWeather/files/329797/160623.PNG.zip)

**Comment by kkkiiikkii** [comment]
[160623 칼라아이콘 SVG.zip](https://github.com/WizardFactory/TodayWeather/files/329798/160623.SVG.zip)

**Comment by kimalec** [comment]
개인의견 : 아이콘이 좀 더 컸으면 좋겠음. 해 색깔과, 달 색깔을 좀 더 조정했으면 좋겠음.

**Comment by kkkiiikkii** [comment]
[160623_weathericon_color_SVG.zip](https://github.com/WizardFactory/TodayWeather/files/333373/160623_weathericon_color_SVG.zip)
[160623_weathericon_color_PNG.zip](https://github.com/WizardFactory/TodayWeather/files/333374/160623_weathericon_color_PNG.zip)

**Comment by kkkiiikkii** [comment]
[160623_weathericon_color_SVG2.zip](https://github.com/WizardFactory/TodayWeather/files/333397/160623_weathericon_color_SVG2.zip)
[160623_weathericon_color_PNG2.zip](https://github.com/WizardFactory/TodayWeather/files/333398/160623_weathericon_color_PNG2.zip)

**Comment by kkkiiikkii** [comment]
[160626_가이드화면 수정.zip](https://github.com/WizardFactory/TodayWeather/files/333459/160626_.zip)

**Comment by kkkiiikkii** [comment]
[160626_가이드 화면 PNG(5.5형 1242*2208)수정.zip](https://github.com/WizardFactory/TodayWeather/files/333468/160626_.PNG.5.5.1242.2208.zip)

**Comment by kimalec** [comment]
아래 이미지 새로 만들어야 함.
그래픽 이미지 
기본 언어 – 한국어(대한민국) – ko-KR
가로세로 1024x500
JPG 또는 24비트 PNG(알파 없음)

![2016-06-26 23 37 29](https://cloud.githubusercontent.com/assets/6895272/16362962/0ef67222-3bf7-11e6-953c-77fca09181a0.png)

**Comment by kkkiiikkii** [comment]
![160703_ -01](https://cloud.githubusercontent.com/assets/12652131/16544048/cd8b9774-4130-11e6-9934-3ef87786aadd.jpg)
![160703_ -01](https://cloud.githubusercontent.com/assets/12652131/16544047/ccf41214-4130-11e6-84d5-8f5b01047f0d.png)

**Comment by kkkiiikkii** [comment]
[160703_weathericon_color.zip](https://github.com/WizardFactory/TodayWeather/files/344893/160703_weathericon_color.zip)

**Comment by kimalec** [comment]
1번과 4번 이미지 대처할 도시검색(리스트)와 설정
[v090_iphone_citylist_settings.zip](https://github.com/WizardFactory/TodayWeather/files/344899/v090_iphone_citylist_settings.zip)

**Comment by kkkiiikkii** [comment]
![160703_ -01](https://cloud.githubusercontent.com/assets/12652131/16544156/5dbfba24-4135-11e6-99c5-6dd99ca552cf.jpg)
![160703_ -01](https://cloud.githubusercontent.com/assets/12652131/16544157/5de61714-4135-11e6-9b44-3066bcf8e6eb.png)

**Comment by kkkiiikkii** [comment]
[160726_가이드 화면 수정.zip](https://github.com/WizardFactory/TodayWeather/files/386078/160726_.zip)
[160726_가이드 화면 PNG(5.5형 1242*2208)수정.zip](https://github.com/WizardFactory/TodayWeather/files/386079/160726_.PNG.5.5.1242.2208.zip)
