### ISSUE TITLE
left/right swipe로 도시 변경시에 효과 필요.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#425]
left/right swipe로 도시 변경시에 효과가 없어서 변경된 것에 대한 감지가 어려움.

**Comment by skywlrl** [comment]
http://ionicframework.com/docs/api/directive/ionSlideBox/

**Comment by kimalec** [comment]
swipe를 통하여 전체 화면으로 애니메이션이 들어갈려면 미리 load해두어야 하는거 아닐까요? 지금 초기 시작 타임이 길어서 최대한 줄여야 하는데, 기존상태에서 스와이프 대신에  '<','>' 버튼만 넣는건 어떨까요?

**Comment by kimalec** [comment]
#747 에서 아이콘 추가에 대한 이슈 발행했음.

**Comment by kimalec** [comment]
Native transitions

It is now possible to use native transitions within Ionic applications. I created ionic-native-transitions, a plugin that helps you configuring Telerik’s native transition Cordova plugin.

쓰기는 쉬운듯한데, 셋업이 잘 될지 모르겠음. 일차 시도 실패 

http://julienrenaux.fr/2015/10/07/native-transitions-for-ionic-framework-made-easier/

**Comment by skywlrl** [comment]
ionic-native-transitions의 경우에는 페이지 이동시에만 동작 가능함(enter, leaving 이벤트로 처리됨). 도시명 부분만 ion-slide-box로 처리해서 swipe 효과를 줄 수 있을 듯

**Comment by kimalec** [comment]
어제 새로운 사람에게 깔아주고 관찰했는데, 도시가 하나밖에 추가 하지 않았음에도 좌우 화살표가 있으니 눌러보거나 swipe를 해보네요.

**Comment by kimalec** [comment]
한개만 있는 경우 화살표 안나오게 했음.

**Comment by kimalec** [comment]
추가 개선은 다음에 스케줄 잡아서 진행.

**Comment by kimalec** [comment]
도시 변경이 자주하는 것이 아니므로 left right swipe는 도시 변경보다는 다른 용도가 좋을듯함(그림 변경,탭 이동)
