### ISSUE TITLE
Route - short 데이터 array의 날짜 순서가 섞이는 문제.

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#429]
short array의 날짜 순서가 일정하지 않은 경우가 있음

**Comment by kimalec** [comment]
#463 과 중복이슈이거나, #463 수정과 함께 수정되었을 수 있음.

**Comment by pokers** [comment]
날짜 베이스로 리스트로 만들어서 전송되는 데이터를 넣어 주기 때문에 해당 문제 수정됨.
