### ISSUE TITLE
UI 2.0 시간별/요일별 화면 구현

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#448]
#209 에 논의된 시간별 화면 구현

![151220_ _ -01](https://cloud.githubusercontent.com/assets/12652131/11916506/e883d09a-a71c-11e5-8ed6-040b2bb72f77.jpg)
![151220_ _ -02](https://cloud.githubusercontent.com/assets/12652131/11916504/e87407be-a71c-11e5-9eac-f0400fcad01b.jpg)
![151220_ _ -03](https://cloud.githubusercontent.com/assets/12652131/11916505/e874a296-a71c-11e5-9769-ac602925509b.jpg)

**Comment by kimalec** [comment]
material design framework에 맞추어 올리는 중.

**Comment by skywlrl** [comment]
UI 2.0의 차트 디자인 적용 코드
[chart.zip](https://github.com/WizardFactory/TodayWeather/files/170948/chart.zip)

**Comment by kimalec** [comment]
요일별에서 온도표시하기 위한 영역 보장 필요. 

현 디자인에서 확인해야 할 사항 -23 이라는 세자리 숫자에서 표시가 좋지 않을 수 있음.

**Comment by kimalec** [comment]
배경색을 #03A9F4; (light-blue 500)으로 적용한 경우임.

<img width="359" alt="2016-03-15 12 05 40" src="https://cloud.githubusercontent.com/assets/6895272/13766590/8482f256-eaa6-11e5-96eb-c147be1e67cb.png">

**Comment by kimalec** [comment]
메인 화면 크기 대략 조정, z1으로 조금 높임.
카드 배경색을 #81D4FA (light blue 200)으로 설정
메인 화면에 애니메이션 추가 하려면 이정도 넓이 되어야 할 것으로 보임.

<img width="362" alt="2016-03-15 12 28 21" src="https://cloud.githubusercontent.com/assets/6895272/13766996/f1fd7f92-eaa9-11e5-8f10-522dc2d8ca5a.png">

**Comment by kimalec** [comment]
온도 표시 영역에 대한 보장이 필요함.
그리는 비용(trigle, 영역보장)에 비해 기존보다 좋은지 모르겠음. 단 배경이 원안대로 흰색일 경우 확인 필요함.

<img width="386" alt="2016-03-15 16 15 30" src="https://cloud.githubusercontent.com/assets/6895272/13770281/318c3b66-eac9-11e5-8eb7-ed2b0707e21e.png">

**Comment by kimalec** [comment]
메인화면이 너무 크면 resize 효과시에 변화가 너무 클 수 있다.

요일별날씨 - 박스형과 라인형(기존화면) - 라인형은 새로운 시간별날씨와는 안 어울리는 것 같음.

**Comment by kimalec** [comment]
영역 분리를 위한 구분 선은 시간 중간에 쓰는 것이 합당할듯.
날짜 분리를 두가지 색으로 번갈아가면서 배경색에 의미를 주는 방법도 있음.
![2016-03-20 11 54 18](https://cloud.githubusercontent.com/assets/6895272/13902616/85c15a3c-ee92-11e5-9ec8-eb40d950c47e.png)

**Comment by kimalec** [comment]
일별 배경색은 Light Blue 200(81D4FA), Light Blue 100(B3E5FC) 두가지로 하고, POP는 500(03A9F4)으로 함.

**Comment by kimalec** [comment]
light-blue 100과 200은 너무 갭이 큼. blue-100, light-blue-100이 형식이 더 괜찮아 보였음.
또한 박스를 채우니 너무 꽉 차여 있는 느낌이 강함.

<img width="320" alt="2016-03-22 20 18 24" src="https://cloud.githubusercontent.com/assets/6895272/13949923/457c0c12-f06b-11e5-9422-615a426c4c9d.png">

**Comment by kimalec** [comment]
메인화면을 글자, 이미지 크기는 박스의 리사이즈 크기에 따라 변하게 적용 필요.

**Comment by kimalec** [comment]
어제, 오늘 탭 추가
<img width="383" alt="2016-04-08 09 56 32" src="https://cloud.githubusercontent.com/assets/6895272/14371242/a4efe8f0-fd70-11e5-87d8-273413652fe8.png">
위의 내용을 아래와 같은 형태로 추가.

어제, 오늘, 내일
날씨, 날씨, 날씨
최고, 최고, 최고
최저, 최저, 최저
먼지, 먼지, 먼지

하단에 풀어쓰기
일강수량, 자외선, 각종지수

**Comment by kimalec** [comment]
UI 1.5로 마무리 했고, 새로운 디자인 구상되면 새로 진행.
