### ISSUE TITLE
DB gather - 단시간에 다량의 save가 호출 되었을때 application 및 db connection이 죽는 현상.

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#450]
* 문제 1
  * 현재 current, short등 데이터 하나 받을때 마다 db 리스트에 넣고 save를 하는데, 이때 전체 동네개수인 1600개 이상을 한번에 실행 할 경우 application이 죽는다(openshift 환경)
  * 한번에 500개 정도의 동네를 실행 했을 때는 죽지 않는다.
  * --> save횟수를 줄이거나 delay를 넣거나..등 개선방법을 찾아야함.
* 문제 2
  * 잦은 save함수 호출 후 mongolab와의 connection이 끊기는 현상이 있다.
  * --> 너무 많은 save를 한번에 호출하는 것은 피하도록 해야 한다. 또, connection이 끊길 경우 retry하도록 해야 한다.

**Comment by pokers** [comment]
current데이터를 받고 DB 저장하는 시기에 openshift의 모든 동작이 느려진다. 예를 들어 log보거나 ssh접속했을때 반응속도가 매우매우 느리다..

**Comment by pokers** [comment]
todayweatherDb에서 db저장 하는 시기에 다른 application인 todayweather1, todayweather2의 동작이 느려지거나 방해를 받는지 확인이 필요하다.

**Comment by kimalec** [comment]
이번에 shortest에서 retry도 실패하는 경우에 save하고, 실패한 애들을 모아서 재실행하는데  retry하는 것을 제거하고 새로 들어간것만 사용하면 save를 분산하는 효과가 있을 것으로 보임.

current, shortest를 동시에 하지 않고, async를 사용하면 차례로 하게 하는 것도 분산하는 방법 중에 하나일듯한데 데이터 다 모으는데 시간이 더 오래 걸릴 것으로 보임.

**Comment by pokers** [comment]
async를 이용해서 current의 각각의 element가 모두 완료 되었을때 한방에 save하는 것도 테스트 해볼필요가 있음.
작은단위로 여러번 save하는게 좋다고는 하지만 어떤 환경이냐에 따라 다르기때문에 테스트 후 더 좋은 퍼포먼스를 보여주는 방법으로 수정 필요.

**Comment by pokers** [comment]
current, short를 request, save하는 부분을 async waterfall를 사용해서 순차적으로 다운받는 경우 application이 죽지 않는것을 확인 함.

**Comment by pokers** [comment]
openshift에서 application을 생성 후 초기 2일 정도는 문제 없었으나 이후 데이터 받은 후 저장 할 때 application이 죽는 현상 재현됨.
openshift의 성능 문제인지 mongoose문제인지는 모르겠으나 다른 방법을 모색해야 함.

**Comment by pokers** [comment]
* action item
 * data들을 저장할때 async.mapseries를 사용해서 하나씩 순차 저장 하게 수정해서 성능 확인.
 * current db를 100~500 개 단위로 쪼개서 collection을 만든 다음 async.waterfall를 이용해 각각 하나씩 저장하게 수정후 성능 확인 필요.

**Comment by kimalec** [comment]
저렇게 분리해야 할 정도면 gather는 AWS Beanstalk를 써보거나 하는 것도 나쁘지 않을 꺼 같습니다. 구현상에 필요한 것들 끝나는 대로 beanstalk으로도 돌려보겠습니다.

**Comment by pokers** [comment]
현재 async.mapSeries로 하나씩 저장하게 했을때 죽거나 느려지는 현상 없음.
속도는 async를 안쓸때랑 크게 차이 없음.
--> 일단 2~3일 지켜 봐야 한다. 기존에도 초기에는 문제 없었으나 시간이 지날수록 속도가 느려지거나 application이 죽는현상이 나타났음.

**Comment by pokers** [comment]
데이터 req를 나눠서 처리
current, short등이 동에 gather하지 않도록 수정.
DB저장시 async이용하여 하나씩 순차 저장하게 수정.
서버 이전(openshiftf를 사용하지 않음)
