### ISSUE TITLE
하나의 application에서 두개의 mongo DB에 접속하기

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#461]
mongoLab의 DB size제한때문에 두개의 DB에 연결해서 사용해야 한다.

**Comment by pokers** [comment]
connect()를 두번하면 Error: Trying to open unclosed connection 발생.

**Comment by pokers** [comment]
첫번째 DB connection은 mongoose.connect() method를 사용하고,
두번째 current 전용 DB connection은 mongoose.createConnection()을 사용하니 해결됨.
(ref site : http://stackoverflow.com/questions/15712226/mongoose-trying-to-open-unclosed-connection)

**Comment by kimalec** [comment]
currents, mid forecasts, midlands, midseas, mid temps, shortest, shorts, towns 각 최신 한벌씩 가지고 있을 때, DB size는 48MB로 실황을 1시간단위로 8일 저장하고, 생활지수 등 최신한벌은 유지 가능할 것으로 보임.

**Comment by pokers** [comment]
@kimalec : 위와 같이 했을때 마진값 알려주세요.

**Comment by kimalec** [comment]
디스크상으로 48MB+192MB = 240MB정도이고 생활지수랑 대기질은 모바일에서 직접 가지고 가고 있으니 추후 검토하면 될꺼 같습니다.

**Comment by pokers** [comment]
동시에 두개의 mongo DB에 접속 가능 및 확인 완료.
추후 필요하다면 해당 내용 적용해서 충분한 테스트 후 적용해야 함.
이후 작업이 필요할 경우 다시 오픈하여 처리
