### ISSUE TITLE
TownRss(shortRSS)의 loadList, mainTask가 callback 받도록 개선.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#477]
TownRss(shortRSS)의 loadList, mainTask가 callback 받도록 개선하여, controllerManager.task에서 종료되는 것을 알도록 개선하자.

**Comment by neoqmin** [comment]
##### mainTask 내에 여러번의 비동기 호출(getData)이 존재

- 비동기 호출은 무시(완료 확인 안함)하고, setTimeout을 이용하여 콜백을 호출할 예정

**Comment by kimalec** [comment]
setTimeOut은 지금도 하고 있어서 그렇게 하기 보다는 아까 알려준 부분 참고해서 검토해주세요.

async.map같은 걸로 처리도 가능해요.

**Comment by kimalec** [comment]
short rss 전체 수집하는데 3분이상 걸리면, 다른 데이터 수집에 문제가 됨.
