### ISSUE TITLE
사용자 사용패턴 분석할 수 있는 토대 마련.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#489]
google analytics, ionic analytics, 광고 플랫폼 제공 분석 툴기반으로 사용패턴을 분석할수 있는 토대를 마련하자.

**Comment by kimalec** [comment]
지금은 ionic analytics가 있지만, google analytics도 같이 사용하여 검토해보자.

**Comment by kimalec** [comment]
https://youtu.be/sXFjYKNjxuo?list=PL6OeXcmhVzfSsbqs0hAfOnRuSFulsfopX - 지속 가능한 모바일 앱/게임 사업 ( 구글 애널리틱스를 통한 분석 소개)

**Comment by kimalec** [comment]
https://blog.nraboy.com/2014/06/using-google-analytics-ionicframework/

**Comment by kimalec** [comment]
http://www.itworld.co.kr/news/98199 - '아는 만큼 보인다' 구글 애널리틱스 주요 기능 대해부

**Comment by kimalec** [comment]
http://confluence.wizardfactory.net/pages/viewpage.action?pageId=13926426 - 서비스 사용량을 app store, play store, admob, cloud front, ionic.io 내용 표로 넣었습니다. 애널리틱스 연결하면 애널리틱스 지표도 여기에 넣을 생각입니다.

**Comment by skywlrl** [comment]
* AngularJs에서 구글 애널리틱스를 이용하면 One Page Application이라서 이탈율이 크고 접속시간이 기록되지 못함 -> 이벤트를 사용하여 접속 상태를 계속 알려줘야 함
* AngularJs를 위한 구글 애널리틱스가 있어 검토 필요 -> Route로 페이지 이동 시 기록이 되는 옵션이 있음
 - https://github.com/revolunet/angular-google-analytics

**Comment by kimalec** [comment]
이탈율 : 사용자가 세션에서 페이지와 상호작용하지 않고 사이트를 떠난 단일 페이지 세션의 비율
https://support.google.com/analytics/answer/1009409?hl=ko

**Comment by skywlrl** [comment]
1. www.google-analytics.com/analytics.js을 직접 로드해서 사용하는 경우
 - Android에서 Tracking이 되지 않음
2. google-analytics-plugin으로 추가하기
 - android 빌드 에러 발생함(아래 경로에 해당되는 문제와 동일 현상)
 - https://github.com/danwilson/google-analytics-plugin/issues/123#issuecomment-151145095

**Comment by kimalec** [comment]
google play services 없애고 빌드하니 "window.analytics.startTrackerWithId('UA-XXXX-YY')"에서 에러 안나고 잘 넘어갔습니다.

```
ionic plugin remove cordova-plugin-googleplayservices
```

googleplayservices는 admob때문에 달았는데, 유료 버전의 경우 playservices를 사용하지 않고, playservices 를 설치했다가 지워서 그런지 광고도 제대로 나오는 것 같습니다.

dependency가 걸린 code의 github에 가보면 필요없어진것도 같습니다.

THIS PLUGIN IS DEPRECATED!!! Plugins should use framework tags instead.
E.g.: <framework src="com.google.android.gms:play-services-plus:+" /> <framework src="com.google.android.gms:play-services-identity:+" />>

https://github.com/MobileChromeApps/google-play-services

빌드할때 좀 귀찮게 컴파일해서 동작한다면 우선 대충 가도 될꺼 같습니다.

**Comment by skywlrl** [comment]
* plugin으로 된 google-analytics-plugin은 native app으로 동작해서 googleplayservices와 충돌하는 문제로 사용하지 않고 plugin이 아닌 js로 웹페이지로 동작하는 방법을 찾음
- https://github.com/ggendre/GALocalStorage

**Comment by skywlrl** [comment]
릴리즈 시에 index.html에 ga_storage._setAccount('[GOOGLE_ANALYTICS_KEY]'); 코드에서 GOOGLE_ANALYTICS_KEY 키를 변경해야 함

**Comment by kimalec** [comment]
코드 적용하여 동작확인되었음.

**Comment by skywlrl** [comment]
[cordova-plugin-google-analytics로 대체 작업]
- Admob plugin 변경 후 아래와 같은 에러 발생함
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#com.google.android.gms.version@value value=(8115000) from AndroidManifest.xml:35:66-89
        is also present at [com.google.android.gms:play-services-basement:8.4.0] AndroidManifest.xml:23:13-66 value=(@integer/google_play_services_version).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:35:9-92 to override.
