### ISSUE TITLE
실황 수집에 10분정도 걸리는데, 개선 필요.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#492]
기존의 동시 request 갯수를 400개로 늘리고, HTTP GET timeout를 10초에서 3초로 변경해도 큰 차이가 없음. 그전에는 11분정도 걸렸음. HTTP GET timeout를 3초했더니, short, shortest가지고 올때 timeout이 많이 발생함.
```bash
info: start tasks counts 2 Thu Jan 07 2016 20:41:37 GMT+0000 (UTC)
info: C> +++ GET CURRENT INFO :  date=20160108, time=0500
info: C> srcList length= 1630
info: TOWN_CURRENT data receive completed :  1630
info: TOWN_CURRENT data receive completed :  1230
info: TOWN_CURRENT data receive completed :  830
info: TOWN_CURRENT data receive completed :  430
info: TOWN_CURRENT data receive completed :  30
info: received All  TOWN_CURRENT  of  date=20160108, time=0500
info: C> save OK
info: Finished Current Thu Jan 07 2016 20:50:45 GMT+0000 (UTC)
```

**Comment by pokers** [comment]
현재 openshift기준으로 데이터 req하는 시간을 더이상 줄이기는 힘든 상황.
결국 데이터 처리하는데 걸리는 시간과 데이터 받는데 소요되는 시간을 확인해서 데이터 처리하는데에 걸리는 시간을 줄일수 있는 방법을 찾아 볼필요가 있음.

**Comment by kimalec** [comment]
save가 오래 걸리는 것일수 있음. 확인 필요

**Comment by pokers** [comment]
* 시간 체크 요약
 * 환경 : 10회 평균, openshift, RSS데이터 1630개(실황데이터는 key를 소모하기때문에 rss데이터를 이용),
mongolab
 * 데이터 req+parse : 평균 6분 소요.
 * 데이터 save : 평균 2분 미만 소요.
* 결론
 * req+parse와 save하는 시간을 따로 계산했을 때, req+parse 하는 시간이 오래 걸림.
 * mapSeies로 하나씩 save했을 때 1630개의 데이터저장하는데 2분 미만이면 오래 크게 오래 걸린다고 생각하기 힘들다.
 * 실제 실황데이터가 아닌 RSS데이터를 사용했기 때문에 req+parse에 걸리는 시간의 오차는 있을 수 있음
 * rss의 short데이터를 이용했기 때문에 save 하는데 소요되는 시간은 오차가 크지 않을거라 예상됨.
~~~~~~~~
Sun Jan 10 2016 03:39:29 GMT-0500 (EST): Node server started on 127.8.75.129:8080 ...
info: RSS> coord count :  1630
info: RSS> start to get RSS : Sun Jan 10 2016 03:39:30 GMT-0500 (EST)

info: RSS> receive completed : Sun Jan 10 2016 03:54:21 GMT-0500 (EST)

info: RSS > save completed : Sun Jan 10 2016 03:56:15 GMT-0500 (EST)
~~~~~~~~

**Comment by kimalec** [comment]
new relic을 적용했지만, gather에서는 자체적으로 돌아서 그런지 상태별 보는 방법이 없는건지 모르는건지.. 아직 잘 파악이 안되네요.

https://rpm.newrelic.com/accounts/1208777

**Comment by kimalec** [comment]
SHORT의 경우 5분정도 걸림.

```
info: Finished Shortest Sun Jan 24 2016 15:04:51 GMT+0000 (UTC)
info: S> +++ GET SHORT INFO :  date=20160124, time=2300
info: Finished Short Sun Jan 24 2016 15:09:50 GMT+0000 (UTC)

info: start tasks counts 1 Sun Jan 24 2016 17:31:32 GMT+0000 (UTC)
info: S> +++ GET SHORT INFO :  date=20160125, time=0200
info: Finished Short Sun Jan 24 2016 17:36:32 GMT+0000 (UTC)
```

**Comment by kimalec** [comment]
beanstalk에서는 2분만에 socket에러 발생해서 조사가 필요함.

```
info: Start shortest
info: + gather > request | Time[ 2016-01-26T01:43:44.380Z ]
info: ST> +++ GET SHORTEST INFO :  date=20160126, time=1030
info: Finished shortest Tue Jan 26 2016 01:45:44 GMT+0000 (UTC)
error:  Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketOnEnd (_http_client.js:300:23)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by kimalec** [comment]
node.js http server timeout이 있음.

https://nodejs.org/api/http.html#http_server_settimeout_msecs_callback

**Comment by kimalec** [comment]
Reminder가 가장 많이 걸리고 있고, save에 대한 시간 정보가 없음.

<img width="982" alt="2016-01-26 15 40 06" src="https://cloud.githubusercontent.com/assets/6895272/12574018/38d2e4bc-c443-11e5-85f2-3372e2cfda6e.png">

**Comment by kimalec** [comment]
동네예보자료가 아니라 **지상관측자료 도시별 현재날씨** 를 사용하는 경우가 있음.

예전에 API가 존재했고, 지금 일부에서도 사용되고 있는 것으로 보임.
http://203.247.66.146/contents/api_spec_kma1.html

도시별 현재날씨는 사용하면, 정시에 바로 이용 가능함. 동네날씨정보는 40분이후부터 받아 볼 수 있음.
http://www.kma.go.kr/weather/observation/currentweather.jsp

측정소별로는 분단위 온도도 가능하고, 일극값이라고 하여 하루 최고/최저온도, 일강우량도 가져올 수 있음.
http://www.kma.go.kr/cgi-bin/aws/nph-aws_txt_min?MINDB_01M

**Comment by kimalec** [comment]
한번에 가지고 올 수 있는 제한을 해지하고나서 3분정도 걸림.
