### ISSUE TITLE
현재온도로 체감온도 계산하기. 

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#493]
KMA 생활지수에서 제공하는 체감온도는 예보만 오기 때문에, 현재 온도 기준으로 체감온도를 계산할 필요가 있다.

**Comment by pokers** [comment]
체감온도를 계산하는 공식
- 현재 기온과 현제 풍속을 이용하여 체감온도를 계산하는 공식이 있음.
- client에 적용하면 간단하게 끝날것으로 예상되나 테스트 및 확인은 해봐야 함.
- http://terms.naver.com/entry.nhn?docId=1825975&cid=42897&categoryId=42897

**Comment by kimalec** [comment]
기상청 지수 설명에 있는 체감온도 산출 코드
```js
function getNewWCT(Tdum,Wdum) {
			var T = Tdum;
			var W = Wdum*3.6;
			var result = 0.0;
			if ( W > 4.8 ) {
					W = Math.pow(W,0.16);
					result = 13.12 + 0.6215 * T - 11.37 * W + 0.3965 * W * T;
					if(result > T) {
						result = T;
					}
			}
			else {
				result = T;
			}
			return result;
		}
```

**Comment by kimalec** [comment]
체감온도가 실온도와 동일하면 summary에서 빼고, 상세날씨에는 동일해도, 주의, 관심 등 레벨이 있는 경우에 표시되게 수정 필요.
