### ISSUE TITLE
[Backend] yeoman, mean js, mean io에 대한 조사 필요.

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#5]
각각의 방식에 대한 장,단점.
이를 토대로 server side node js에서 only express를 사용할 것인지, 
아니면 위의 세가지 scaffolding중 하나를 사용할 것인지 정해야 한다.

**Comment by kimalec** [comment]
frontend와 backend code repo 어떻게 할지도 같이 검토해봐주세요.

**Comment by pokers** [comment]
* **yeoman**
 * scaffolding을 위한 도구 (http://yeoman.io/)
 * command line tool에서 "yo" 명령어로 사용할 수 있음.
 * yo
   * 일종의 scaffolding을 위한 generator를 실행해주는 command tool로 생각하면 됨.
    * npm 처럼 yo cmd로 사용자가 원하는 scaffolding을 해주는 generator 실행하면 해당 프로젝트의 기본 scaffolding이 생성됨.
 * generator
   * 일종의 linux에서 환경설정 등을 위해 서용하는 script 파일이라고 생각하면 됨.
    * yo 가 해당 generator를 읽어 들여서 scaffolding를 만들어냄.
    * 매우 많은 종류의 generator가 있어서(1000개 이상이라고...) 원하는 스타일의 프로젝트를 검색해서 찾아서 사용하면 됨. (nodejs, angularJS 종류는 엄청나게 많음..)
  * 장점
    * 설치 및 실행이 용의하다. 실제로 meanjs를 설치 및 실행 했는데 초기 page가 나오게 하는데 5분 걸림.
    * 왠만한 종류의 project에 해당하는 generator는 검색해서 찾을 수 있기 때문에 힘들이지 않고 base구성이 가능하다.
    * 원한다면 내가 원하는 것들만 골라서 scaffolding 구성할 수 있다. 예를 들어 mean stack구성 할때 angularJS의 cookies를 뺀다거나...
    * 잘 organize 되어 있는 generator를 사용하면 설치 중 y/n 선택으로 원하는 구성만 scaffolding할 수 있다.
    * 유명하다보니 meanjs team에서 만든 generator가 있을 정도... (meanjs를 직접 사용할 필요가 있을까 하는 의구심이 든다...)
   * 단점
     * 무겁다. 단지 scaffolding만 했을 뿐인데 엄청 많은 파일, 코드 등이 포함되어 있다. 장점이 될수도 있지만 불필요한 것들이 많다면...
     * 익숙하지 않은 프로젝트라면 시작할때 scaffolding되어 있는 파일 및 구조 파악하는데도 쉽지 않을듯...

 yeoman의 homepage에서 설명을 읽어보고 meanjs scaffolding를 구성해 봤을는데 전반적으로 괜찮은 느낌이였는데 과연 우리 프로젝트에서 이렇게 까지 많은 base기능들을 넣을 필요가 있을까 하는 생각이 든다...

**Comment by pokers** [comment]
* **mean js**
 * mean stack를 위한 scaffonding를 제공.
 * yeoman으로 설치하기를 권장하고 있음.
 * http://meanjs.org/docs.html 에 생성되는 폴더, 폴더 설명, tool 사용법 등 상세한 설명이 있음.
 * 장점
    * 개발에 필요한 왠만한 base를 다 포함하고 있어서 개발 시작할 때 빠르게 시작할 수 있다.
    * yeoman으로 간편하게 필요한 config를 선택할 수 있음.
    * website에 자세한 설명이 있기 때문에 구조에 대한 이해가 쉽다.
 * 단점
    * 역시 무겁다. 과연 이 많은 파일들이 필요로 할까 싶은생각이...
 
yeoman에서 언급한 것과 같이 사용시 yeoman을 이용해서 간단하게 설치, 설정, 실행까지 논스톱으로 가능함.

**Comment by pokers** [comment]
* **mean io**
 * npm으로 mean-cli를 설치 후 mean 명령어로 scaffolding 설치.
 * http://learn.mean.io/ ㅅ에 생성 폴더, 설정, 설명 등 상세 설명.
 * 장점
    * mean js와 크게 다를 것들은 없다. 어느것을 선택해도 기본적인 내용들을 다 포함한다.
    * 최근 업데이트가 2015년 7월로 꾸준히 업데이트 및 유지가 되고 있다.
 * 단점
    * 위에 언급한 mean js와 같이 무겁다.

결국 scaffolding 에 대한 내용은 **귀찮으면 mean js혹은 io를 선택** 하면 될것 같다.
조금더 나아가 **필요한 것들만을 원한다면 yeoman의 generator를 검색해서 나의 프로젝트에 가장 잘 맞는 generator를 찾아서 설치** 하는 것이 좋다.
**베트스케이스는 yeoman에서 generator 생성 방법을 익힌 후 내가 필요한 package만을 포함 시켜서 설치하는 것** 이 좋지만, generator 생성 방법을 공부해야하는....

**Comment by pokers** [comment]
* Source repo 구성
 * hithub의 몇몇 프로젝트를 살펴보니 대부분 root folder에 server, client 두개의 folder를 생성후 각각의 폴더 내에 소스를 구성했다. 
 * 그외 간단한 프로젝트들은 ionic scaffolding를 기반으로 root의 js파일에 서버를 구현한 걸로 보여진다.
 * 참고 
    * https://github.com/jjhargreaves/Ionic-app-with-NodeJs-backend 
    * https://github.com/yslim/ionic_uglify

**Comment by pokers** [comment]
* Ionic+Nodejs
 * https://github.com/wnovido/myTwilioApp
 * https://github.com/thomaspawlik/mobileui
ionic의 구조를 잘 모르기 때문에 어떤방향이 좋을지 모르겠다...

meanio의 구조는 커도 너무 큰것 같음.(default로 설치했는데 어마어마한 폴더 구조가 등장함...)
지금 개인적인 생각으로는 webstorm의 node+express project를 생성해서 하는것도 나쁘지 않다고 생각됨.
**일단 초기 try는 yeoman을 사용해서 meanjs의 generator를 사용할 생각!!**
p.s 반대의견 언제든지 환영합니다~

**Comment by kimalec** [comment]
저도 express generator + jwt + moongoose 정도도 괜찮을듯함

**Comment by pokers** [comment]
* mean js
 * backend 에서는 아래 그림의 폴더 들을 주로 사용하게 될것.
    * controllers : express application controller 가 있는 곳.
    * models : mongoose model 이 있는 곳
    * routes : server의 route table을 설정하는 곳.
    * 나머지 폴더는 말그대로 test, views. views의 경우 404 error와 같은 페이지 렌더링을 위해 존재.
 * 결국 routes에다가 우리가 원하는 page를 route시켜 주고 controllers 폴더에다가 해당 페이지 특정 동작을 하는 놈을 끼워 넣으면 되는듯..
 * 시작점은 root의 server.js 파일 이고, config폴더 안의 init.js 에서 config를 읽어 들이는 등의 작업을 하는 듯...
 * server task(예를 들어 주기적으로 기상정보를 가져오는 작업을 하는 task 같은거...js에서는 뭐라고 부르나...`ㅡ`?)는 server.js에서 주기적으로 혹은 scheduler를 사용해서 돌아가게 하면 될듯하고....해당 동작을 하는 js파일은 controllers에 폴더 하나 뚫어서 넣으면 될듯하다..
 * **일요일에 전체 리뷰 필요함!!!!!!!**

![default](https://cloud.githubusercontent.com/assets/10987524/8742573/b5b37058-2ca1-11e5-8bb2-e98979b257ca.jpg)
