### ISSUE TITLE
날씨 공유 기능

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#527]
사용자들이 현재날씨를 공유할 수 있게 하자.

**Comment by skywlrl** [comment]
[카카오톡 링크 API]
* https://developers.kakao.com/docs/js
* API 키를 생성할 때 웹서버 주소가 필요하나, ionic의 경우 file://로 실행되어 등록이 안됨
* 서버를 통해서 처리하거나 Native SDK를 Plugin 형태로 지원해서 사용해야 함

**Comment by skywlrl** [comment]
**[화면의 특정 부분을 Capture 해서 이미지로 공유하는 방법]** -> 차후에 재검토
* https://jsfiddle.net/8ypxW/3/ 와 같이 jquery로 html2canvas을 이용하여 canvas에 그린 후 이미지로 저장해서 보내야 함 -> jquery를 사용하지 않고 directive로 처리해야 할 것 같음
* $cordovaCapture을 이용하여 현재 화면 전체를 캡쳐할 수 있음

**[날씨 정보를 텍스트+이모티콘으로 표시]**
* 플랫폼 별 이모티콘 정보 : http://unicode.org/emoji/charts/full-emoji-list.html#26ab

**Comment by kimalec** [comment]
crosswalk 에서 message + '\u{1F31E}\n'; 에 대하여 syntax error가 발생함.
아래 설명에 따라 "\ud83c\udf1e" 로 변경함.
http://www.charbase.com/1f31e-unicode-sun-with-face
