### ISSUE TITLE
cloudfront cache clear

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#568]
gather server에서 데이터가 갱신되면, cloudfront에 cache clear 를 요청하여 cache때문에 데이터 갱신이 안되는 문제를 해결하자.

http://stackoverflow.com/questions/22021651/amazon-s3-and-cloudfront-cache-how-to-clear-cache-or-synchronize-their-cache

**Comment by pokers** [comment]
사용전에 AWS에서 access key, secret key를 발급해야 하고, cloudfront의 distribution id를 알아야한다.
region, api version은 default값을 사용할 수 있다.

**Comment by kimalec** [comment]
아직은 key 발급 안 받아서 동작 안하는거죠? 

invalidate 시기는 좀 더 정교하게, 조정해야 할 것 같습니다.
또한 실제 데이터 업데이트가 있는 경우에 대해서만 clear하도록 하는거죠.

**Comment by pokers** [comment]
invalidate 는 고민해봤는데 
invalidate하는데에만 10분정도가 소요되기 때문에(AWS에도 10분~12분 소요된다고 나와있음)
너무 자주하면 오히려 문제가 발생할수 있다고 생각되네요.
50분에 넣은 이유는 current data가 완료되는 시점이 45분 전후이기 때문에 일단 50분에 넣었고
current data기준으로 invalidate하는것이 좋을것 같아서 했는데 조금 더 정교하게 할 필요는 있다고 생각해요.

key발급은 내계정이 아니기 때문에 발급 받을 수 가없어요.
발급받아서 keydata에 넣어주세요

**Comment by kimalec** [comment]
invalidate 하고자 하는 목적이 지금 cache time 이 5분정도로 되어 있는데, 이걸 1일 정도로도 두고, 업데이트 할때 마다 하고자 했는데, 갯수 상으로는 1시간에 한번정도 할 수 있고 10~12분정도 소요된다고 하니 적용 방법을 고민 좀 해봐야 할꺼 같아요. 

지금 데이터 업데이트 타임이 크게 두번으로 나뉠거 같아요.  1분대(중기, RSS)에 하는 경우와 30분대(최단기, 단기, 실황) 두 타임으로 압축해도 2*24*30 = 1440 이군요.
 
10~12분 정도 소요되는게 글로벌이라서, cloudfront는 국내로 한정하거나 좀 좋아지지 않을까 싶습니다만, 글로벌 서비스하게 되면 동일한 문제를 만나긴 하겠네요.

**Comment by kimalec** [comment]
https://www.cloudflare.com/plans/  cloudflare라고 저렴한  CDN이 있는데,  cache clear도 지원하는듯함.

**Comment by kimalec** [comment]
CloudFront에 아래와 같은 옵션이 있음.

**Object Caching**
Select Use Origin Cache Headers if your origin server is adding a Cache-Control header to control how long your objects stay in the CloudFront cache. Select Customize to specify a minimum time that objects stay in the CloudFront cache regardless of Cache-Control headers.

**Comment by kimalec** [comment]
Minimum TTL 셋업이후에 hit가 나오고 있음.

<img width="1018" alt="2016-04-04 21 33 20" src="https://cloud.githubusercontent.com/assets/6895272/14271875/63a63442-fb38-11e5-9157-32ac1f37a5b9.png">

**Comment by kimalec** [comment]
성능에 관련된 부분으로 추후 더 필요시에 진행.

**Comment by kimalec** [comment]
cache timeout 5분 현행 유지.
