### ISSUE TITLE
API 미동작시에 대응할 crawler 제작.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#594]
API 미동작하는 경우에도 provider의 web page는 정상동작하기 때문에 crawler를 사용하여 데이터를 수집하자.

https://github.com/ktty1220/cheerio-httpcli
www.kma.go.kr/weather/process/index-dfs-ajax.jsp.01.jsp?requestPointCode=1117053000

순서 
에러 발생시에 mx,my에 해당하는 areaNo를 구해서 요청한다.
가지고 온 정보들을 기존  DB에 맞추어 저장한다.
pastGather에서 crawler로 가지고 온 경우에는 API를 통해 다시 가지도 오도록 한다.   crawler로 가지고 경우에 파악할 수 있어한다.

**Comment by kimalec** [comment]
api 수신 totalcount가 0인 경우에 crawler 동작 시킬껀데 좀 더 상셍한 시나리오 필요.

**Comment by kimalec** [comment]
아래 두개 url의 경우 WSD 값이 없음.

```
http://newsky2.kma.go.kr/service/SecndSrtpdFrcstInfoService2/ForecastGrib?serviceKey=ZHnG%2BY4Lm4ro7irtG1atoYPJTVgSPFz5iZbHQYFTEXJfCCrdcF1caV1UK%2FQH5fMqbA%2B%2FpL9Cy%2BSYVi%2BAqzG8bw%3D%3D&base_date=20160214&base_time=2100&nx=71&ny=140&pageNo=1&numOfRows=999
http://newsky2.kma.go.kr/service/SecndSrtpdFrcstInfoService2/ForecastGrib?serviceKey=ZHnG%2BY4Lm4ro7irtG1atoYPJTVgSPFz5iZbHQYFTEXJfCCrdcF1caV1UK%2FQH5fMqbA%2B%2FpL9Cy%2BSYVi%2BAqzG8bw%3D%3D&base_date=20160214&base_time=2100&nx=106&ny=94&pageNo=1&numOfRows=999
```

**Comment by kimalec** [comment]
current 보정을 위한 시간별 데이터(60분간격)은 도시관측자료를 사용 도시관측자료가 없는 지역은 AWS의 60분간격에서 가지고 올 수 있음.

문제점 : AWS와 가까운 경우, 정보 확장을 위해서 도시관측자료도 같이 써야 하는데, 이 경우 적정거리를 고려해야 함.
무조건 가장 가까운 하나를 쓰는 것도 방법이긴 함.

도시관측자료 : http://www.kma.go.kr/weather/observation/currentweather.jsp?tm=2016.3.22.16:00&type=t99&mode=0&auto_man=m&stn=108

**Comment by kimalec** [comment]
https://scotch.io/tutorials/scraping-the-web-with-node-js
https://github.com/sylvinus/node-crawler
http://leejoon0.github.io/crawler,%20scraping/2014/05/23/web-crawler--web-scraping-on-nodejs/
http://www.sitepoint.com/web-crawling-node-phantomjs-horseman/

**Comment by kimalec** [comment]
cheerio의 경우 jquery와 유사해서 jquery문법을 좀 알아야 함.
kma는 enckr로 되어 있어, utf8로 변환이 필요함.

**Comment by kimalec** [comment]
도시별 현재날씨에서 도시가 보이지 않은 경우도 있음.
경주시보이다가 정시에 데이터가 늦게 생성되어서 이름만 있다가 항목에서 사라졌음.
경주시 링크를 타고 들어가서, 보면 시간이 좀 지나면 데이터가 만들어졌으나, 전체항목에서는 여전히 보이지 않음.

**Comment by kimalec** [comment]
정해진 시간에 도시별 날씨를 가지고, 10분이나 정해진 시간 이후에 db에서 갱신된 날짜보고 갱신되지 않은 지역에 대하여 업데이트 하는 형태로 구성.

AWS(지역별상세관측자료)정보와 시도별 현재날씨 정보를 한 collection안에 넣는게 좋을지 분리할지 결정해야 함.

near로 적정거리에서 가지고오 city항목에서 최소 한 데이터를 뽑는 형태로 해도 될꺼 같은데.. 검토 필요.

AWS parser가 만들어지면, mobile에서 최신 관측자료를 server 통해서 가지고 오게 할 예정임.(몇분이내의 강수, 기온, 습도, 풍속을 제공할 수 있음.)

**Comment by kimalec** [comment]
AWS는 692개 정도이며 동시에 geo location 정보를 가지고 올 수 없음. 
추후에는 문제가 되지 않지만 초반에 문제가 있음.

**Comment by kimalec** [comment]
"제주특별자치도제주시우도면 서광리"의 경우 DAUM api에는 없고, google api로만 결과 받을 수 있는데, 가끔 error로 lat, lon이 없는데도, err없이 넘어오는 경우가 있음.

**Comment by kimalec** [comment]
aws에서 도시별 날씨를 제공하는 주요 station이 있는데, 동마다 근처 30개까지 해도, 도시별날씨가 포함되지 않는 경우가 있음.

find를 두개 분리해서 진행해서 merge하는 형태로 변경 예정.

**Comment by kimalec** [comment]
```js
$('.table_develop3 thead #table_header2 th').each(function () {
```
아래 html이 getCityWeather의 시작부분입니다. 위의 코드가 매치되는 부분임. 

<img width="819" alt="2016-04-05 09 29 32" src="https://cloud.githubusercontent.com/assets/6895272/14267995/12d28542-fb11-11e5-84bc-715f7523c4b2.png">

**Comment by pokers** [comment]
잘 아시겠지만 crawler 소스코드의 특성상  처음 만들었던 사람외의 다른 사람이 유지&보수가 쉽지 않은 것 중 하나라고 알고 있습니다.
훗날 본인의 편의를 위해서라도 가급적이면 코드에 많은 주석을 넣어주시면 감사하겠네요^^

**Comment by kimalec** [comment]
네 저도 잘 모르는 부분이라 업데이트하면서 주석 많이 넣도록할께요

**Comment by kimalec** [comment]
crawler가 들어가면서 오늘 최고, 최저 온도 재조정이 필요함.

<img width='240' src='https://cloud.githubusercontent.com/assets/6895272/14305574/b8f66b54-fbf8-11e5-9086-2d075ab6d091.png'>

**Comment by kimalec** [comment]
scraper로 일극값(최대,최저 온도, 일 강수량)도 가지고 올 수 있지만, 일단 필요한 경우에 진행하기로 하고 이슈 닫음
