### ISSUE TITLE
pull-to-refresh

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#61]
데이터 가져오고 지역 찾기를 위한, pull-to-refresh 

http://ionicframework.com/docs/api/directive/ionRefresher/
http://devdactic.com/pull-to-refresh-ionic/

**Comment by kimalec** [comment]
디자인 부터 나와야 해서 먼저 @kkkiiikkii 로 할당합니다.

**Comment by kimalec** [comment]
#50 에서 status bar를 살리면 pull to refresh를 하면 끊어지는 느낌이 남.

**Comment by kimalec** [comment]
동작 자체는 쓸 수 있는데, custom하기가 쉽지 않은 듯 함
```html
<ion-refresher
                pulling-text="업데이트 중입니다."
                on-refresh="doRefresh()">
        </ion-refresher>
```

```js
        $scope.doRefresh = function() {
            $http.get('/new-items')
                .success(function(newItems) {
                    $scope.items = newItems;
                })
                .finally(function() {
                    // Stop the ion-refresher from spinning
                    $scope.$broadcast('scroll.refreshComplete');
                });
        };
```

**Comment by kimalec** [comment]
#68 에 의해서 overflow-scroll="true" 와 ion-refresher가 같이 들어가면, div scroll의 size가 변경됨.

<img width="808" alt="2015-08-30 13 56 22" src="https://cloud.githubusercontent.com/assets/6895272/9565752/9a4ac38a-4f1e-11e5-835d-912522205cb7.png">

**Comment by kimalec** [comment]
데이터 업데이트 배경 및 아이콘
<img width="360" alt="default" src="https://cloud.githubusercontent.com/assets/6895272/9566070/d2f4725c-4f2e-11e5-83d0-d3e5638500e5.png">

데이터 업데이트용 아이콘
![update icon-01](https://cloud.githubusercontent.com/assets/6895272/9566071/e902c846-4f2e-11e5-9bac-dc60b2d301bc.png)

**Comment by skywlrl** [comment]
데이터 영역을 좌우로 스크롤 할 때에 pull-to-refresh가 동작하는 문제가 있음
-> 위 아래로 특정 크기 이상 드래그 할 때만 동작하도록 수정 필요함

**Comment by kimalec** [comment]
design 부분은 #98 에서 적용하고 본 이슈는 close합니다.
