### ISSUE TITLE
다국어 지원

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#613]
다국어 지원에 필요한 사항 조사

**Comment by kimalec** [comment]
http://www.oneskyapp.com/ - Translation Made Easy for Apps, Games & Websites
https://www.icanlocalize.com/site/ - Translating websites, iPhone & Android and software is what we do best starting at $0.09 per word

**Comment by kimalec** [comment]
https://crowdin.com/ - Localization Management Platform for mobile apps, web, desktop software and related assets.

**Comment by kimalec** [comment]
https://brunch.co.kr/@anitooni/2 - 기본 중의 기본 - 다국어

**Comment by kimalec** [comment]
http://ngcordova.com/docs/plugins/globalization/

**Comment by kimalec** [comment]
https://www.icanlocalize.com/site/tutorials/iphone-applications-localization-guide/

**Comment by kimalec** [comment]
http://robferguson.org/2015/07/22/internationalisation-i18n-and-localisation-l10n-for-ionic-apps/
https://angular-translate.github.io/docs/#/guide/09_language-negotiation
http://www.lingoes.net/en/translator/langcode.htm

**Comment by kimalec** [comment]
https://www.raymondcamden.com/2015/10/14/adding-localization-to-your-ionic-application-with-ibm-bluemix

**Comment by kimalec** [comment]
en, ja, de, zh-ch, zh-tw, ko 지원 예정.
local branch : 613-multi-languages

**Comment by kimalec** [comment]
#667 내용도 변경해야 함.

**Comment by kimalec** [comment]
summary, description 부분은 서버에 디비로 저장하고, 새로운 글이 나올 경우 왓슨 및 번역 API를 사용해서 추가 및 클라이언트에 전달해주고, 추후 보정해서 디비에 저장하는 형태로 해야 할듯함.

**Comment by kimalec** [comment]
초기에는 설정상에 언어 변경을 지원하지 않음.

**Comment by kimalec** [comment]
Particle Pollution (PM) - Particle pollution, also called particulate matter or PM
Fine dust VS Particulate matter 중에 많이 쓰는 단어 알아야 함.

**Comment by kimalec** [comment]
최종 사용자 언어를 기반으로 객체를 캐싱하도록 CloudFront 구성
CloudFront에서 요청에 지정된 언어에 따라 여러 버전의 객체를 캐싱하려는 경우, Accept-Language 헤더의 언어를 포함하도록 애플리케이션을 프로그래밍하고 Accept-Language 헤더를 오리진에 전달하도록 CloudFront를 구성합니다.
https://docs.aws.amazon.com/ko_kr/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-language

**Comment by kimalec** [comment]
https://github.com/alexei/sprintf.js - JavaScript sprintf implementation for the browser and node.js

**Comment by kimalec** [comment]
다국어와 단위가 같이 변경되기 때문에 summary를 서버에서 만드는데 무리가 있어 보임.

**Comment by kimalec** [comment]
client summary 수정
push notification 언어, 단위 고려

**Comment by kimalec** [comment]
server api 변경해야 할 사항
추가 : fromToday, dayOfWeek,
변경 : dustForecast의 PM10Grade, PM25Grade, O3Grade를 pm10Grade, pm25Grade, o3Grade로 변경, grade값을 실시간과 동일하게 맞추기. makeSummary 기준값 조정.
고려사항 : 서버측도 push notification때문에 language, units에 대하여 고려해야 함. grade값은 지역별 혹은 설정에 따라 변경될 수 있음.

**Comment by kimalec** [comment]
국내에서 영어를 사용할때는 사용자 표시에 위치정보와 api query용 한글주소가 필요함.

**Comment by kimalec** [comment]
국내에서 영어 사용을 지원하기 위해서 표시되는 이름은 영어로 되어야함. 현재위치에 대한 위치 검색후, 영어나 다른언어 이름을 위해서 google에 query해야함. 얻은 주소 중에 types가 postal_code인 주소정보에서 두번째 값을 사용.
주소와 실제 표시 이름을 분리한것은 #635 에서 진행했음.
합쳐서 진행이 필요함.

**Comment by kimalec** [comment]
- [ ] 서버에서 kma제공 weatherType 정보를 추가해서 제공
- [ ] 현재위치를 제외한 나머지 영어 적용
- [ ] #635 내용 합침(다만 자동완성을 국내 주소에 한함.)
- [ ] 현재위치까지 다국어로 제공.

**Comment by kimalec** [comment]
http://theeye.pe.kr/archives/2240 - 구글플레이가 제공하는 APK 번역 서비스 이용 후기

**Comment by skywlrl** [comment]
* $translate.instant : sync로 string 가져올 수 있음
http://stackoverflow.com/questions/20540877/correct-use-for-angular-translate-in-controllers
* 서버에서 숫자로 된 type이 아니라 'LOC_xxx'로 전달하면 클라이언트에서 값 변환없이 그대로 View에서 사용 가능함

**Comment by kimalec** [comment]
lang.json을 strings.xml로 변환하기 (총 가격확인하기위해 변경)

예제
```xml
<?xml version='1.0' encoding='utf-8'?>
<resources>
 <string name="app_name">오늘날씨</string>
</resources>
```
LOC_XXX에서 LOC_빼고 소문자 + _ 로 변경하여 <string name>에 추가함.

**Comment by kimalec** [comment]
번역할 단어 816단어
독일어 122.40, 영어 81.60, 일본어 122,40, 중국어 간체 130.56, 중국어 번체 130.56 -> 587.52불

**Comment by kimalec** [comment]
일본어, 영어, 중국어(간체) 번역 요청함.

**Comment by kimalec** [comment]
controllers 에서 showAlert부분 다시 체크해야 함.
translate 하는 부분에서 초기값과 에러값 수정

**Comment by kimalec** [comment]
**Localization management platform**
https://poeditor.com - 최대 1000 strings까지 무료, 프로젝트 갯수와 contributor 수는 제한 없음, strings, json 별로 프로젝트를 분리하거나, 통일해서 하나로 쓰던지해야 함.
oneskyapp.com - 스토어 설명 및 각 파일별로 따로 관리 가능함.

oneskyapp.com으로 시작해볼 예정임.

**Comment by kimalec** [comment]
applyWeatherData에서 chartShortHeight, shortTable를 setTimeout을 이용하여 비동기로 적용하는데, 처음 실행시에 차트와 상세 정보가 표시가 안됨. setTimeout를 빼야 정상동작하는듯함.

**Comment by kimalec** [comment]
ng-bind-html을 제거하고,  applyWeatherData에서 layout에 관한 값을 먼저 설정하고, async로 실제 데이터를 넣는 형태로 수정 중 -> tab 이동시에 반응을 빠르게 하기 위함.

**Comment by kimalec** [comment]
- [ ] Android 언어별 위젯 스크린샷
- [ ] Android, iOS 언어별 앱 스크린샷

**Comment by kimalec** [comment]
다국어 지원
- [ ] android 일본어는 깨짐, 중국어 간체, 번체 영어로 나옴

**Comment by kimalec** [comment]
- [ ] android 중국어 간체, 번체 전환안됨.

**Comment by kimalec** [comment]
FBStart로 www.transifex.com 를 6개월간 사용할수 있음, 잘 만들어진 느낌이 들지만 가격또한 비쌈.
