### ISSUE TITLE
앱아이콘 안드로이드를 위해 끝부분 살짝 라운드 처리.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#629]
앱아이콘 안드로이드를 위해 끝부분 살짝 라운드 처리.
아래 아이콘 참조
<img width="147" alt="2016-03-06 18 46 29" src="https://cloud.githubusercontent.com/assets/6895272/13553407/d7bba58a-e3cb-11e5-9b85-7cde666ea5af.png">

**Comment by kkkiiikkii** [comment]
![160327_ -01](https://cloud.githubusercontent.com/assets/12652131/14063349/17542b62-f408-11e5-982f-d3000115730f.png)
