### ISSUE TITLE
위치 정보 사용 요청 문구 개선

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#63]
아래와 같이 지역정보에 대한 문의 문구 개선이 필요.

![ios simulator screen shot 2015 8 24 10 06 39](https://cloud.githubusercontent.com/assets/6895272/9431209/a616e6d4-4a47-11e5-8d09-12d02ccaf69a.png)

**Comment by skywlrl** [comment]
* 동일한 질문
http://stackoverflow.com/questions/1673579/location-permission-alert-on-iphone-with-phonegap
* config.xml에 Geolocation 설정이 플랫폼마다 필요함
 - http://docs.phonegap.com/en/3.0.0/cordova_geolocation_geolocation.md.html#The%20Command-line%0AInterface
 - ios의 경우
<feature name="Geolocation">
    <param name="ios-package" value="CDVLocation" />
</feature>

**Comment by kimalec** [comment]
참고 자료

http://iswwwup.com/t/728bbb82007f/ios-location-permission-alert-on-iphone-with-phonegap-and-ionic.html 

http://www.raymondcamden.com/2015/05/18/tracking-and-notifying-geolocation-status-with-ionic

**Comment by kimalec** [comment]
지인에게 문의해서 아래와 같은 경우인 것으로 확인함.

geolocation불러오는것을
```js
$ionicPlatform.ready(function (){})
```
안에서 불러오시면 될거에요
geolocation을 디바이스가 앱을 완전히 로딩하기전에 불러오면 저렇게 뜨는것 같아요

controller.js에서 확인용으로 timeout으로 1초 후에 getCurrentPostion하도록 하니 메세지 없이 동작하는 것 확인하였음.
