### ISSUE TITLE
지역 검색 개선.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#635]
지금은 client에 있는 town.js를 통해서만 검색하는데, 다국어 지원, 외국 지역 검색 지원 등을 위해 개선이 필요함.

**Comment by kimalec** [comment]
geo data for locations and the world tree structure are taken from GeoNames - genomes.org

**Comment by kimalec** [comment]
http://www.geonames.org/ - The GeoNames geographical database covers all countries and contains over eight million placenames that are available for download free of charge.

#200

**Comment by kimalec** [comment]
이 부분은 서버 연계랑 normalize 하는 부분이 있으니, 조사하신거 내용 정리해주시면 제가 받아서 진행하겠습니다.

**Comment by skywlrl** [comment]
* google map api
 - https://developers.google.com/maps/documentation/javascript/places-autocomplete?hl=ko#place_autocomplete_service
 - 결과 값이 5개만 전달됨
* daum local api
 - https://developers.daum.net/services/apis/local/v1/search/keyword.format
 - 다국어 지원시 처리 방안 필요함
* daum 지도의 검색어 입력에 사용되는 api
 - http://sugloc.search.daum.net/localplace?q=rk%E3%84%B1%E3%84%B4&mod=json&code=utf_in_out&callback=santa.$5.dataModel.forceLoadComplete
 - 공개된 daum api가 아님
 - 지역 외에 다른 데이터도 전달되는데 구분할 수 없음

**Comment by skywlrl** [comment]
테스트 코드 PR로 올려놨습니다.

**Comment by kimalec** [comment]
위치정보 normalize도 같이 진행해야 함.
국내와 해외도 구분해야 함.

**Comment by kimalec** [comment]
#903 이 잘 동작함. 
추가로 필요한 작업
구글로고 추가
town.js제거
한국어외 다른 언어로 질의시에 처리 방법 모색.

**Comment by kimalec** [comment]
한국의 경우에도 다른 언어로 질의 한 경우에도 동일하게 동작해야 함.
현재 mobile과 server간에 한국어 address로 질의하는 것이 동작하지 못함.
mobile에서 다시 한국어 주소를 가지고 와서 전달이 가능하나 아무래도 지연이 큼.

**Comment by kimalec** [comment]
google에서 처리된 address는 국가가 들어 있음.
필요시에 국가를 전달할 수 있음. 다만 common api로 사용하기 위해서는 이런 제약을 풀어야 할 것임.

한국에서 뉴욕날씨를 요청할 수 있음. client에서 현지 시간을 올려주는 것은 의미가 없음.
시간 정보가 없는 경우 최신데이터를 그대로 전달해주는 형태가 필요함.

**Comment by kimalec** [comment]
어떠한 언어로 검색해도, 국내와, 해외를 구분하여 국내의 경우 기존 API, 해외의 경우 새로운 API로 요청하게 수정하였음.

다만 국내에서 현재위치에 대한 주소를 가지고 오는 성능을 개선하기 위해서, geo location 정보를 가지고 mCoord 계산하여 국내인지 아닌지 구분하는게 좋을 듯함.

**Comment by kimalec** [comment]
구글API를 사용하는 경우 세종특별자치시가 나오지 않음.
DAUMAPI와 같이 사용하거나, 추가 조치가 필요할듯함.
추후 테마날씨의 경우에도 검색을 지원하기 위해서는 여러 소스를 활용한 자동완성 형태야 할 듯함.

**Comment by kimalec** [comment]
- [ ] 구글API로 주소를 가지고 온 경우, 위치 정보가 이상한듯함.(잠실본동인데, 미세먼지 측정소가 중구로 나옴.)

**Comment by kimalec** [comment]
towns.js와 google에서 주소 받는 것 했음. 다음API까지 붙여볼 예정임.

![2016-10-12 16 43 41](https://cloud.githubusercontent.com/assets/6895272/19301566/13808438-909b-11e6-9a67-285bfa25e41a.png)

**Comment by kimalec** [comment]
http://postcode.map.daum.net/guide#sample 이 잘되는데, 쓸려면 분석해서 뜯어야 할듯함.
키워드로 장소 검색의 경우 매끄럽지는 않지만, 동작은 함.
https://developers.daum.net/services/apis/local/v1/search/keyword.format

**Comment by kimalec** [comment]
**google**
특정 국가로 검색 제한
componentRestrictions 옵션을 사용하여 특정 국가로 자동완성 검색을 제한합니다. 다음 코드는 프랑스 내의 도시로 결과를 제한합니다.
```js
var input = document.getElementById('searchTextField');
var options = {
  types: ['(cities)'],
  componentRestrictions: {country: 'fr'}
};
autocomplete = new google.maps.places.Autocomplete(input, options);
```
https://developers.google.com/maps/documentation/javascript/places-autocomplete?hl=ko

**Comment by kimalec** [comment]
아래와 같이 요청시에 'forEach' of undefined 에러가 발생함.
http://localhost:3000/ww/010000/current?gcode=37.378739,127.113239

```
info: WW>  [{"address":{"country":"","city":"","zipcode":null,"postcode":null},"geocode":{"lat":37.378739,"lon":127.113239},"__v":0}]
info: WW> load geocode, count: 1
info: index[0]lon:(127.113239), lat:(37.378739) | lon:(127.113239), lat:(37.378739)
info: WW> matched by geocode
info: WW> get MET data
info: WW> get OWM data
error: gWU> There is no WU Forecast data for  lat=37.378739, lon=127.113239
error: gWU> There is no WU Current data for  lat=37.378739, lon=127.113239
info: WW> get WU data
info: WW> get DSF data
info: WW> Finish to make weather data
info: MG WuC> curDate 
TypeError: Cannot read property 'forEach' of undefined
    at self.mergeWuCurrentData (/Users/aleckim/WebstormProjects/TodayWeather/server/controllers/worldWeather/controllerWorldWeather.js:404:17)
    at Layer.handle (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/express/lib/router/layer.js:95:5)
    at Layer.wrappedLayerHandleRequest [as handle_request] (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/newrelic/lib/instrumentation/express.js:373:32)
    at next (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/express/lib/router/route.js:131:13)
    at cleanup (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/newrelic/lib/instrumentation/express.js:400:18)
    at self.mergeWuForecastData (/Users/aleckim/WebstormProjects/TodayWeather/server/controllers/worldWeather/controllerWorldWeather.js:392:9)
    at Layer.handle (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/express/lib/router/layer.js:95:5)
    at Layer.wrappedLayerHandleRequest [as handle_request] (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/newrelic/lib/instrumentation/express.js:373:32)
    at next (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/express/lib/router/route.js:131:13)
    at cleanup (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/newrelic/lib/instrumentation/express.js:400:18)
    at /Users/aleckim/WebstormProjects/TodayWeather/server/controllers/worldWeather/controllerWorldWeather.js:288:13
    at /Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/async/lib/async.js:52:16
    at /Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/async/lib/async.js:1209:30
    at /Users/aleckim/WebstormProjects/TodayWeather/server/controllers/worldWeather/controllerWorldWeather.js:276:25
    at /Users/aleckim/WebstormProjects/TodayWeather/server/controllers/worldWeather/controllerWorldWeather.js:989:13
    at Query.<anonymous> (/Users/aleckim/WebstormProjects/TodayWeather/server/node_modules/mongoose/lib/model.js:3343:16)
```

**Comment by kimalec** [comment]
현재위치 -> 주소(구글)
    country가 KR일 경우, city name 설정, DAUM에서 주소 다시 구함.
    country가 KR이 아닌 경우, city name설정
검색
  result에 first property가 있는 경우 국내. city name 설정
  result.address 인 경우 google에서 geo code와 country를 구함
    country가 KR인 경우 city name 설정, DAUM에서 다시 주소 구함.(현 주소가 한국어 아닐 수 있음)
    country가 KR이 아닌 경우, city name설정

**Comment by kimalec** [comment]
google 주소 검색에서 city.name 만들기
  단어를 분리하고, 사용자가 입력한 워드가 포함된 단어를 선택, 없는 경우에는 마지막 단어 사용.

**Comment by kimalec** [comment]
현재위치 -> 주소 구함(from 구글) -> city name 설정 -> country가 KR이면 DAUM에서 주소 갱신.
검색
searchResult(towns에서 검색된 결과)
searchResult2(google에서 검색된 결과)
그중에 선택한 result에 first property가 있는 경우(towns에서 고름) -> city name 설정.
선택한 result에 address property가 있는 경우(구글검색에서 선택한 경우) -> google에서 geo code와 country를 구함 -> country가 KR이면 DAUM에서 주소 갱신.

**Comment by kimalec** [comment]
http://okihouse.tistory.com/entry/Redis-Spring-boot-Auto-Complete-구현추천단어검색 - redis를 사용한 추천단어 검색으로 추후 우리가 내장하고 있는 데이터를 전달할때 유용할듯함.
