### ISSUE TITLE
습도 지수 만들기

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#645]
15℃에서는 70%, 18~20℃에서는 60%, 21~23℃에서는 50%, 24℃ 이상일 때는 40%가 적당한 습도다.

<img width="540" alt="2016-03-31 20 42 27" src="https://cloud.githubusercontent.com/assets/6895272/14174710/25aad46e-f781-11e5-82a9-1e067c049782.png">

습도에 관해서 매우건조, 약간건조, 건조, 적정, 습함, 매우습함 단계를 만들어보자.

관련 자료 조사 필요함.

related : #570

**Comment by neoqmin** [comment]
습도 지수와 관련된 그래프를 찾아 링크를 첨부합니다.
https://harizanov.com/2015/03/diy-internet-connected-smart-humidifier/

**Comment by kimalec** [comment]
[상대습도와 절대습도의 상관관계](https://www.google.co.kr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiY6KOy3-rLAhXBFJQKHc_rB9MQFgglMAA&url=http%3A%2F%2Fwww.ppm.co.kr%2Fbbs%2Fupload%2Finput%2FBoard_tech03_51_1.docx&usg=AFQjCNGhyws_mv59aos1s-Q4h8JMEw-fMg&sig2=VJTtsE0sjtn8UZWWyOSO7A&bvm=bv.118353311,d.dGo)

**Comment by neoqmin** [comment]
누군가 저희와 같은 고민을 하고, 지식인에 질문을 남겼군요.

아래는 기상청의 답변이 포함된 질문 내용입니다.

http://kin.naver.com/qna/detail.nhn?d1id=11&dirId=1117&docId=208465053&qb=6rG07KGwLCDsirXtlagsIOunpOyasOqxtOyhsCwg66ek7Jqw7Iq17ZWo&enc=utf8&section=kin&rank=1&search_sort=0&spq=0&pid=SY04MspySDlssuVYR6Gsssssss4-184733&sid=prQ10CBcqSo6xYPey8ihag%3D%3D

**Comment by neoqmin** [comment]
이미 계산되어진 상대습도를 추가적인 계산없이 단순히 범위를 나누어 단계를 구분하면 될 것 같습니다.

**Comment by kimalec** [comment]
- [ ] 습도의 상태 표시앱들을 주시해서 어떻게 표시하는지 확인하자.

**Comment by kimalec** [comment]
현앱에서 진행하지 않음.
