### ISSUE TITLE
주기적인 DB Backup

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#696]
MongoDB의 주기적인 Backup을 시도하자.

**Comment by kimalec** [comment]
https://docs.mongodb.org/manual/core/backups/

https://gist.github.com/lazarofl/4961746

**Comment by kimalec** [comment]
VM내에서 한시간씩 백업하고(24개 유지), 하루에 한번씩 최종본을 S3에 압축해서 저장하면 좋겠에요.

**Comment by pokers** [comment]
mongodb를 S3에 백업하는 npm 이 있다.

https://www.npmjs.com/package/mongo-backup-to-s3

**Comment by pokers** [comment]
Script를 사용하거나 js를 사용해서 backup가능. 둘다 장단점은 있음.

script 사용시 로컬에 DB를 dump한 다음 압축해서 S3에 저장하기 때문에 size측면에서 유리

js의 source코드 사용시 DB에서 S3로 direct stream upload를 하기 때문에 압축을 할 수가 없다. 다만 로컬에 저장 후 압축 하는 일이 없기 때문에 심플하게 동작.

**Comment by pokers** [comment]
Backup 파일 개수 관리는 아래 설명된 설정을 이용해서 3일이 지난 파일들은 자동 삭제되게 rule을 생성한다.
지난 일자의 파일들은 서비스시 이미 소용없는 데이터로서 삭제해도 무관.

1. Bucket --> properties --> lifecycle 에서 rule 생성.
2. creation된 이후 특정 날짜가 지나면 삭제 되도록 rule 설정.

**Comment by kimalec** [comment]
crontab에 script가 좋을 듯 mondodump를 쓰면 콜력센별로도 복원이 가능해서 추후 필요시 currents만 복원 가능

**Comment by pokers** [comment]
js 이용해도 mongodump를 이용해서 file 저장 없이 S3로 바로 업로드하게 되어 있음.

문제는 script혹은 js에서 돌릴경우 이게 시스템 자원을 얼마나 잡아먹는지 모르겠고,
script의경우 local에 한번 copy한 다음 압축 및 upload를 하는데
local에 카피 되는 동작시 문제될것이 있는지 파악이 필요함.
(예를들어 DB size가 200 MB인 경우 이를 local에 가져와서 압축을 하기 때문에 local에 충분한 여유공간이 항상 확보 되어 있어야함. local에서 압축을 할때 시스템을 자원을 사용하게 되는데 이때도 문제될 소지가 있는지 확인 필요.)

**Comment by pokers** [comment]
crontab를 이용해서 S3에 2시간마다 한번씩 backup
