### ISSUE TITLE
ionic menu drawing 방법 조사

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#7]
[ionic 관련 정보]
http://ionicframework.com/
http://ngcordova.com/

[Mac에서 Android Studio 설치 방법]
http://s2junn.tistory.com/85

**Comment by kimalec** [comment]
ionic site도 잘 나와 있네요
http://www.ionicframework.com/docs/guide/

**Comment by skywlrl** [comment]
[Upgrade Node.js via NPM]
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
[HOW TO SET UP ADB (ANDROID DEBUG BRIDGE) IN MAC OSX]
http://esausilva.com/2010/10/02/how-to-set-up-adb-android-debug-bridge-in-mac-osx/
[안드로이드 개발 WiFi 를 이용한 디바이스 디버깅]
http://mookiedata.tistory.com/54

**Comment by skywlrl** [comment]
필요한 작업은 이슈로 생성하여 진행.
