### ISSUE TITLE
하늘시, 구름동 없애기. 

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#700]
사용자 의견에 따라 하늘시, 구름동 예제화면을 없애고 현재위치 추가 혹은 도시 검색 추가 하도록 하자.

처음 시작하는 경우에만 도시검색으로 보내고, 도시검색에는 "현재위치 리스트에 추가"를 넣자.

위젯은 현재위치정보만 나오게 해두었기 때문에, 같이 수정되어야 함.

**Comment by kimalec** [comment]
위젯과 ionic 간의 즐겨찾기 리스트 공유 방법이 필요함.

**Comment by kimalec** [comment]
android의 경우, 파일로 공유, sql lite를 사용하는 방법이 있는듯하고,  iOS에서는 파일로는 불가능한듯함. sqlite(coreData)로는 가능해 보임.  데이터가 심플해서 더 간단하게 하는 방법도 있을 듯한데 찾는게 더 일이 될 수 있음.

https://www.thepolyglotdeveloper.com/2014/11/use-sqlite-instead-local-storage-ionic-framework/
http://www.glimsoft.com/06/28/ios-8-today-extension-tutorial/
http://www.tutorialspoint.com/android/android_sqlite_database.htm
http://soooprmx.com/wp/archives/2277
https://www.invasivecode.com/weblog/sharing-data-between-apps-and-their-extenstions/
http://stackoverflow.com/questions/25407428/how-to-access-coredata-model-in-today-extension-ios

**Comment by kimalec** [comment]
시나리오 제안 
현재위치 검색과, 현재위치 사용을 분리해서 현재위치 검색은 도시검색에 넣어서 현재위치를 찾아서 즐겨찾기 추가해주고, 지금과 같이 현재위치를 사용하고자 한다면 설정에서 현재위치 사용을 on 해주어 사용할 수 있게 하자.

**Comment by kimalec** [comment]
https://github.com/WizardFactory/ionic-timepicker - ionpopup 사용해서 만들어진 time picker 예요 
popup 창 만들 때, 참고하세요.

**Comment by skywlrl** [comment]
가이드 화면 -> Close/Skip 버튼 클릭 -> Popup ->
1. 현재 위치 검색 선택 -> 예보 화면으로 이동
2. 도시 검색 선택 -> 도시 검색 화면으로 이동

[도시 로딩 시점 변경]
- 도시 별로 데이터 로드 시간 저장(이미 데이터가 로드된 경우는 재요청하지 않음, 로드한 지 10분이 경과된 경우 timeout 처리)
1. 예보 화면으로 이동 시 현재 도시만 가져오기.
2. 도시 검색 화면으로 이동 시 모든 도시에 대해서 데이터 로드하기.

**Comment by kimalec** [comment]
test

ios 동작확인
premium 사용자로 업데이트 확인
현재위치 없는 경우 동작확인
도시 이동 확인
공유하기 확인 -> 날씨탭이 아닌경우에 링크만 주는데 맞는지..

**Comment by kimalec** [comment]
$ionicPlatform.ready 전에 현재위치 정보를 요청하면 첨부된 이미지처럼 실행할때마다, 권한 승인 요청화면이 나옴.
<img width="386" alt="2016-05-30 12 22 07" src="https://cloud.githubusercontent.com/assets/6895272/15638993/5d9299f2-2661-11e6-8c6b-3a09543b3161.png">

init()함수에 있는 loadWeatherData()를 ready callback으로 쌀 예정임.
```js
applyWeatherData();
$ionicPlatform.ready(function() {
  loadWeatherData();
});
```

**Comment by kimalec** [comment]
ios에서 동작이 너무 빨라서 spinner가 아예 보이지 않는 상황이 발생하는듯합니다. 
spinner가 나오지 않으면 오동작하는 것으로 보이니 검토해봐주세요.

**Comment by kimalec** [comment]
로딩바 안뜨는 건 ionic version 1.3.x로 넘어가면서 괜찮아 보임. 추가검토한후 close할 예정.

**Comment by kimalec** [comment]
로딩바 안뜨는건 1.3.1 업데이트로 괜찮은지 확인하였음.
