### ISSUE TITLE
short rss 저장중에 에러가 발생하는 경우가 있음.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#738]
info: Start shortrss
info: + gather > request | Time[ 2016-04-06T03:02:55.316Z ]
info: RSS> start rss!1
error: fail to save
unknown log level: err
error: fail to save
unknown log level: err
error: fail to save
unknown log level: err
error: fail to save
unknown log level: err
error: fail to save
unknown log level: err
info: rss: finished !!1721
info: RSS:res.send()
info: Finished shortrss Wed Apr 06 2016 03:04:51 GMT+0000 (UTC)

**Comment by pokers** [comment]
retry 때문에 발생하는 걸로 보이지지 않음.
get fail 후 retry를 하게되면 아래 로그가 찍혀야 하는데 보이지 않음.
> log.error('failed to get short rss (%d)', index);

예상되는 문제는 아래 코드에서 예전에 데이터의 빠른 처리를위해 save를 걸고 save완료 후 callback를 콜하지 않고 save로 진입 동시에 다음 데이터를 처리하기 위해 callback를 바로 호출하는데 이것 때문에 발생하는걸로 보여짐
>
            dbShortList.save(function(err){
                if(err){
                    log.warn(err);
                    log.error('short rss fail to save');
                }
            });
        });

        if(cb) {
            cb();
        }

**Comment by pokers** [comment]
- mongoose의 error를 trace해보면 아래와 같이 version error가 발생

> error!! :  { [VersionError: No matching document found for id "568459a8131b0ab53a77cd7a"]
  message: 'No matching document found for id "568459a8131b0ab53a77cd7a"',
  name: 'VersionError' } function VersionError(doc) {
  MongooseError.call(this, 'No matching document found for id "' + doc._id +
    '"');
  this.name = 'VersionError';
}

- 위 error에 대해 검색해보면 아래 링크에서 보는것과 같이 우리와 동일한 error가 있어서 분석 및 수정한 내용이 있음. 요약하면 save() 여러개가 한번에 들어오면서 unlock후 save하기 직전에 다른 save요청에 의해서 version이 바뀌기 때문에 발생하는 현상.
  : http://stackoverflow.com/questions/17499089/versionerror-no-matching-document-found-error-on-node-js-mongoose
- mongoose의 versioning 설명 page
  : http://aaronheckmann.blogspot.kr/2012/06/mongoose-v3-part-1-versioning.html

- mongoose의 manual대로 versioning을 false했지만 여전히 문제 발생.
  : 이유는 기존에 저장된 데이터들이 versioning을 가지고 있기 때문인듯…
  : 기존 로컬 db의 데이터를 다 지우고 versioning 을 false한 후 데이터를 받으면 위의 error가 발생하지 않는다

- 수정 방향은 두가지가 있는데 각각의 장단점이 있다.

1. versioning을 false로 할 경우
   1. 기존 db의 데이터를 한번 지워야 한다.
   2. 우리 시스템 상으로 크게 문제가 될것 같지는 않으나 versioning 체크를 하지 않기 때문에 최신이 아닌 데이터로 over write될수 있다. (현재 세시간 주기라서 크게 문제될건 없을듯…) 
2. 현재 async.map로 돌면서 데이터를 읽고쓰는데 이것을 mapSeries로 수정해야한다.
   1. 기존보다 시간이 더 오래 걸릴 가능성이 있음.

**Comment by kimalec** [comment]
동일한 document(지역)에 대하여 업데이트 요청이 두번 발생하는지 확인이 필요해 보임

**Comment by pokers** [comment]
mCoord를 가져올때 "mCoord"에 대해서 distinct를 사용하고 있으나 동일한 mx, my값이 전달 되고 있음.

이유는 기본적으로 저장될때 {my:--, mx:--} 형태로 저장되어 있는데, 
동일한 좌표의 값을 보면 하나는 {my:--, mx:--}형태로 저장되어 있고, 또하나는 {mx:--, my:--} 형태로 x, y 좌표가 반대로 저장되어 있음.
distinct는 x,y가 반대일때에는 다른걸로 인식하고 있는듯?( 검색해볼 필요 있음)

현재 DB의 좌표를 for문으로 돌면서 mx, my를 수동으로 비교했을때 350개 정도 동일좌표 검색됨.
 : DB의 total 좌표 개수 : 2319 
 : 동일좌표 삭제후 좌표 개수: 1952

--> 동일좌표 삭제된 좌표 리스트를 이용해서 gather한 결과 fail 되는 경우 없어짐.
동일 좌표 리스트 첨부.

[동일좌표 리스트.txt](https://github.com/WizardFactory/TodayWeather/files/969836/default.txt)
