### ISSUE TITLE
공공데이터서비스에 사례 등록(일일 트레픽 제한 늘리기위함)

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#74]
공공데이터서비스 사이트에 사용등록 사례를 올려야 일일 트레픽 제한이 1000에서 1000000으로 증가한다.
현제 하루 약 22600번의 request를 해야 하기 때문에 서비스 시작시점에 등록이 필요함.

**Comment by kimalec** [comment]
wizardfactory account로 사례등록하였음.

https://www.data.go.kr/subMain.jsp#/L3B1Ym4vbGFiL2V4bS9Jcm9zVXNlRXhhbS9vcGVuTXlEZXRhaWxQYWdlJEBeMDgyTTAwMDAxMzNeTTAwMDAzMjIkQF5wcmN1c2VDYXNlU249MTAwMTgxNw==

**Comment by kimalec** [comment]
중기, 동네 예보에 대한 api 사용 승인은 났고, 활용사례 등록은 아직 업데이트 되지 않고 있음.

**Comment by kimalec** [comment]
개발계정에서 운영계정으로 신청했음.

**Comment by kimalec** [comment]
활용신청 승인나서 트래픽수 늘렸음.
