### ISSUE TITLE
App loading시에 현재 시간으로 view point 조정.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#76]
app loading시에 차트에서 현재시간이 왼쪽 두번째 오게 조정.

**Comment by kimalec** [comment]
약간 꼼수 같지만, controller에서 timeout을 사용하여 이동시킨다. 
```js
        $timeout(function () {
            $ionicScrollDelegate.$getByHandle('chart').scrollTo(535, 0, false);
        }, 0);
```

참고: http://forum.ionicframework.com/t/scroll-position-on-back/291/9

**Comment by kimalec** [comment]
차트 영역은 현재시간 기준으로 과거 16개, 미래 16개를 가지오고, 보이는 것은 과거 8개, 미래 16개

get current time
(currentTime/3)*3 -> current position
start from yesterday same hour to same hour on the day after tomorrow
if 0 o'clock, display "yesterday", "today", "tomorrow", "2(date)"

**Comment by skywlrl** [comment]
로딩 화면에 7개 데이터가 보이는데 우측 글자가 잘려서 보입니다. Reopen 합니다.
![2015-09-01-00-43-33](https://cloud.githubusercontent.com/assets/8368939/9582816/a2b1e754-5042-11e5-8d32-a899fb7a2052.png)
