### ISSUE TITLE
Android widget 개선.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#763]
#700 이 들어가고, "현재위치 사용" on/off에 대한 기능이 들어가면서 위젯도 도시리스트에서 선택가능하게 개선이 필요함.

#423 에 추가 작업.

**Comment by kimalec** [comment]
위젯과, 앱간의 도시목록을 공유할 수 있는 방법이 필요함.
iOS위젯의 경우에는 한 도시 지정밖에 안되는 것으로 보임. (여러도시 선택 불가)
일반적으로 인덱스 첫번째나, 라스트뷰의 도시를 보여줌.

**Comment by seankim2** [comment]
![storyboard](https://cloud.githubusercontent.com/assets/8072056/15507058/f995e464-2204-11e6-8b42-dcc71b46704d.png)
* GUI를 입히기 전 필요한 데이터테스트를 위한 스토리보드 구성

**Comment by kimalec** [comment]
참고
https://developer.android.com/reference/android/appwidget/AppWidgetProvider.html
http://arabiannight.tistory.com/category/Android/widget
http://itmir.tistory.com/551
https://android.googlesource.com/platform/development/+/master/samples/WeatherListWidget/src/com/example/android/weatherlistwidget/WeatherWidgetProvider.java

**Comment by kimalec** [comment]
App widget 추가시에 configuration screen를 선택하면 configure activity가 만들어짐.
위젯에서 이미지가 가장 하단에 오게 되면, 삼성, LG모두 꽉찬 모양으로 보여줄 수 있음.

해결해야 할 문제
configure activity를 menu activity에서 띄우는걸 못하고 있음.
configure를 다른 widget에 붙이면 동작은 하는데, 업데이트 전에는 configure 원래 widget의 모양이 나옴.
도시목록을 버튼으로 리스트업하니 이쁘지 않음.

구현해야할 사항.
configure activity에서 도시목록 가지고 오기.
WidgetUpdateService 개선하기.

**Comment by kimalec** [comment]
sqlite 를 사용하지 않고, http://ngcordova.com/docs/plugins/preferences/ 를 사용하면, 아래와 같은 native 기능을 사용하므로, 유용할 듯함.

Native execution on iOS / OSX using NSUserDefaults
Native execution on Android using android.content.SharedPreferences

**Comment by kimalec** [comment]
app-preferences를 사용하여, cityList를 webapp에서 저장하고 widget configure에서 읽는 것 확인하였음.

**Comment by kimalec** [comment]
widget configure에서 back button이나, home button누르면 zombi가 되어버리는 문제.
cancel button이나, back button은 delete되도록 해결하였으나, home button은 해결 안됨.

참고
https://developer.android.com/reference/android/appwidget/AppWidgetManager.html?hl=ko
https://code.google.com/p/android/issues/detail?id=2539

**Comment by kimalec** [comment]
문제2. 다시 configure activity를 띄우는 방법을 모르겠음.
문제3. 앱이 살아 있는 경우에 menuactivity에서 업데이트하면 메인앱이 사라지지 않음.

**Comment by skywlrl** [comment]
문제4. 앱이 한 번도 실행되지 않은 경우에는 도시 리스트가 하나도 나오지 않음. 설명 문구 필요함

**Comment by kimalec** [comment]
#916 수정사항 테스트 해보니, 들어는 가는데, 업데이트 버튼으로 업데이트를 한번 하니 두개가 동일 해져버리네요.
검토는 안했고, 우선 증상만 코멘트 남깁니다.

**Comment by skywlrl** [comment]
이상하네요 제가 더 추가한게 있는건지 확인 다시 해볼게요

**Comment by kimalec** [comment]
한글 문자열 수정해야 함.
1x1 제거해야 함.
