### ISSUE TITLE
사용자 의견 보내기 할때, 기본 디바이스 정보 추가하기.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#771]
사용자 의견 보내기 할때, 기본 디바이스 정보를 추가하여, 디버깅 및 요구사항 반영을 용이하도록 개선하자.

**Comment by kimalec** [comment]
http://hjzzin.tistory.com/117 - mailto 의 여러 속성

**Comment by kimalec** [comment]
https://github.com/katzer/cordova-plugin-email-composer/tree/f4fcee88c47c7ac642cceb27d3d8b31edd26a8f6 - The plugin provides access to the standard interface that manages the editing and sending an email message

**Comment by kimalec** [comment]
sound같은 경우에는 처음 스케줄에 등록될때, 다운받아서 저장한다.

**Comment by kimalec** [comment]
http://ngcordova.com/docs/plugins/emailComposer/

**Comment by kimalec** [comment]
https://www.thepolyglotdeveloper.com/2016/05/send-emails-ionic-2-mobile-app-via-rackspace-mailgun-api/ - 사용자가 email client 셋업하지 않아도 메일을 보낼 수 있음.

**Comment by skywlrl** [comment]
왓챠앱
![image](https://cloud.githubusercontent.com/assets/8368939/19415548/528dfe56-93ae-11e6-942a-5e1d02731dfe.png)

**Comment by kimalec** [comment]
7분운동 예시
<img width="320" alt="2016-10-16 14 38 55" src="https://cloud.githubusercontent.com/assets/6895272/19415551/6af523fc-93ae-11e6-8fed-35f895d034e6.png">
