### ISSUE TITLE
불쾌지수 아이콘 필요.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#772]
체감온도의 상반되는 불쾌지수에 대한 아이콘 필요.

**Comment by kimalec** [comment]
http://www.kma.go.kr/HELP/basic/help_01_05.jsp

**Comment by kimalec** [comment]
화난 모습 아이콘

![angry](https://cloud.githubusercontent.com/assets/6895272/14587496/3197e21e-04ef-11e6-9c88-370773c76f27.png)

**Comment by kkkiiikkii** [comment]
저모양 써도 될거 같아요
