### ISSUE TITLE
차트의 디자인 시안 적용 작업

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#78]

**Comment by skywlrl** [comment]
요청 사항 : 아래 값의 가이드 필요함
- 선 두께
- 원의 반지름 길이
- 온도의 폰트 크기

**Comment by kimalec** [comment]
정확한 값이 뽑기가 어려워서 아래와 같은 방법으로 먼저 맞추고, 최종적으로 디자이너와 함께 조정합시다.

아래 이미지를 www/img에 sreen-dash.png로 복사하고
https://cloud.githubusercontent.com/assets/6895272/9566086/9888e4e4-4f2f-11e5-8702-791fe21308f1.png

ionic.app.scss를 아래와 같이 수정하면, 뒷 배경에 png가 나옵니다.
```js
.main-content {
  width: 100%;
  height: 100%;
//  background-color: #22a1db;
  color: black;
}
.scroll-content {
  background: url("../img/screen-dash.png");
  background-size: cover;
}
```
<img width="353" alt="2015-09-01 00 41 40" src="https://cloud.githubusercontent.com/assets/6895272/9582714/f0f2527e-5041-11e5-9231-8bbc326236c0.png">

**Comment by skywlrl** [comment]
**[d3.svg.line()의 interpolate 종류]**
* https://www.dashingd3js.com/svg-paths-and-d3js
* cardinal에서 monotone으로 변경

**[실행화면]**
<img width="372" alt="2015-09-05 2 20 01" src="https://cloud.githubusercontent.com/assets/8368939/9697855/150d5b68-53da-11e5-85c8-8df5f56aeec9.png">
<img width="371" alt="2015-09-05 2 20 52" src="https://cloud.githubusercontent.com/assets/8368939/9697856/1573cda8-53da-11e5-967e-03bc649e52b3.png">
