### ISSUE TITLE
상세날씨 탭 제거하고, 어제오늘->미세먼지탭추가->없이 시간별,일별 두가지로 변경.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#786]
어제, 오늘, 내일 정보를 정리한 탭 구현.

#448 에서 코멘트 된 사항 적용.

**Comment by kimalec** [comment]
어제, 오늘, 내일
날씨, 날씨, 날씨
최고, 최고, 최고
최저, 최저, 최저
먼지, 먼지, 먼지

하단에 풀어쓰기
일강수량, 자외선, 각종지수

**Comment by kimalec** [comment]
어제 오늘 탭 먼가 약간 .. 간이 덜된 느낌이랄까 ㅠㅠ
<img width="320" src="https://cloud.githubusercontent.com/assets/6895272/15379368/7e4b1c90-1da7-11e6-9a1f-891c26c94735.png">

**Comment by kimalec** [comment]
탭 순서 변경 필요. 
어제오늘 -> 시간별 -> 요일별 or 시간별 -> 어제오늘 -> 요일별.
하단에 탭별로 summary?
main summary가 변화가 적고, 너무 포괄적인 느낌이 있음.

**Comment by kimalec** [comment]
시간단위 상세 날씨 정보는 시간별 날씨 하단에 들어가고,
어제오늘 탭은 제거, 요일별 날씨에서 오늘, 내일 날씨 정보 그리고 지난주말 이번 주말 비교 추가 시나리오 도 괜찮을듯함.

**Comment by kimalec** [comment]
어제오늘탭보다, 미세먼지 탭을 추가해봤음.
시간별탭 하단에 현시간 상세날씨, 요일별탭에 하단 오늘,내일의 하루 날씨, 미세먼지 탭 하단에 미세먼지예보와 현시간 대기질 정보를 넣었음.
![2016-05-21 12 49 48](https://cloud.githubusercontent.com/assets/6895272/15446203/cddd8354-1f52-11e6-84c7-93824d9de7e4.png)

**Comment by kimalec** [comment]
어제오늘 탭은 주말용 차트와 함께, 요일별 차트의 한 종류로 들어가는게 좋을듯 함.
요일별 차트에서 All, Weekend, YTT(이것도 필요없을 수 있음) 그러나, 주말만 뽑아서 비교해주는 것은 좋을듯함.

**Comment by kimalec** [comment]
팀 의견 4(미세먼지):2(기존방식)
미세먼지 탭 적용해볼 예정. -> 사용해보고 개선 필요하면 좀 더 조정할 것임.

**Comment by kimalec** [comment]
#813 top main box resize는 적용하지 않고, 음역정도 적용하여 스크롤시에 분리 느낌만 살릴 예정임.

**Comment by skywlrl** [comment]
![image](https://cloud.githubusercontent.com/assets/8368939/15803235/d548fcaa-2b0e-11e6-9bf4-c7c3b04c2324.png)

**Comment by kimalec** [comment]
vertical, horizional 모두 사용할때, ios에서 원활하지 않음. 처음로딩할때와, 시간별,요일별날씨 이동시에 그래프가 다 나오지 않는 경우가 있음.

참고
아래의 코드는 터치 이벤트를 상위 scroll로 넘기는 기능임.
http://codepen.io/rajeshwarpatlolla/pen/xGWBja

**Comment by kimalec** [comment]
<img width="220" src="https://cloud.githubusercontent.com/assets/6895272/15953552/12c4fa38-2f07-11e6-8600-30543b21cc9f.png"><img width="220" src="https://cloud.githubusercontent.com/assets/6895272/15953553/1594f88a-2f07-11e6-846b-4ba104d3fedb.png"><img width="220" src="https://cloud.githubusercontent.com/assets/6895272/15953556/18495b66-2f07-11e6-97c4-473b9927b927.png">

관련하여 남은 작업
FrontEnd
특정 경우에 빨간점이 작게 나와야 하는데 크게 나오는 경우 있음.
3,6,9등 정시에는 온도 글자색 변경.
chart에서 scope.watch제거.
오존 예보는 미세먼지와 예보 타임이 달라서 재조정 필요, 또한 없는 경우에 필드를 없애야 함. (오존예보는 매년 4월15일~10월15일까지 발표.)
android 4.4에서 UI 다르게 그려지는 문제 수정 필요.
코드정리
성능검토

BackEnd
6시간단위의 강수량을 3시간단위로 쪼개기
서버에서 평균 바람세기 구해서 전달
과거 비올확률 정보추가

확장 시나리오 (milestone 7)
시간별날씨
풍량,풍속 표시
해뜨는 시간, 해지는 시간 표시 (시간 사이에 날씨 아이콘이 들어가기 때문에 여기에 해뜨는 시간, 지는시간 + 아이콘 추가 가능)
요일별날씨
요일별날씨에서 주말만 표시, 모두 표시, 어제오늘내일표시

**Comment by kimalec** [comment]
과거 비올확률 정보추가 -> client로 전달할 short를 재사용하기 때문에 mid에 merge할 시기에는 모레부터 밖에 없음.
이 부분을 지원하기 위해서는 데이터 자르는 시기를 후반으로 변경하거나, DB에서 데이터를 다시 가지고 와야 함. - 중요하지 않으므로 당장 진행하지 않음.

**Comment by kimalec** [comment]
날씨 예보 탭 전환할때, 클릭 이벤트가 두 번 불리는 문제 -> ng-click을 상위 div에 붙이니 문제가 해결됨, div 전환 click event가 맞물리면서 문제가 발생하는듯함. 
short에서 mid로 전환시에 날씨아이콘이 찌그러지는 증상 -> 일별날씨에 업데이트시에는 정상으로 표시됨.

**Comment by kimalec** [comment]
날씨 예보 탭 전환할때, 클릭 이벤트가 두 번 불리는 문제 -> ng-click을 상위 div에 붙이니 문제가 해결됨, div 전환 click event가 맞물리면서 문제가 발생하는듯함 -> 빈도가 줄었지만 여전히 발생함.

**Comment by kimalec** [comment]
남은 이슈 
Chart에서 현재위치에 가늘게 라인이 남음.
iphone4, G2등 낮은 버전에서 동작 튜닝해야함.

**Comment by kimalec** [comment]
이슈 두가지.
한시간이상 지난후에 앱 실행해서 업데이트하면, 데이터 갱신이 안됨.
데이터 갱신이 되어도, Chart에 제대로 반영이 안됨.

**Comment by kimalec** [comment]
3,6,8,12, 15, 18, 24는 박스가 앞으로 쳐야 함.
