### ISSUE TITLE
data 전송 시 gzip 적용

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#90]
server, client간의 데이터 전송시 gzip 적용.

**Comment by kimalec** [comment]
지금은 cloudfront가 중간에서 https로 전송해주고 있는 상황이라 필요없음.
물론 추후 TW-server와 cloudfront간에 딜레이를 줄이기 위해 검토해볼 필요가 있을지도 모르나, 현재 큰 이슈가 아님.

cloudfront에서 http/2를 지원하는 것이 좋은데, CDN에서 http/2 적용하는 것은 몇가지 이슈가 있는듯함.

현 issue close하고, 추후 필요시 논의
