### ISSUE TITLE
CDN 설정하기

### ISSUE THREAD

**Issue by pokers** [WizardFactory/TodayWeather#91]
openshift의 서버 위치가 US -east이기 때문에 AWS의 cloudfront서비스를 사용할 필요가 있다.

**Comment by pokers** [comment]
* AWS - CloudFront 기본 설정 완료.
  * http://d2ibo8bwl7ifj5.cloudfront.net/ 
  * 위 주소가 origin 서버인 http://todayweather-wizardfactory.rhcloud.com/town 로 연결 및 캐싱됨.

**Comment by kimalec** [comment]
다된거 같은데 추가로 해야 할게 없다면 close해주세요.
