### ISSUE TITLE
설정에 가이드 가는 경우, 현재위치 선택창 제거.

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#926]
설정에서 가이드를 들어가는 경우에도 나올때도, 도시 검색방법을 물어보는데, 설정에서 들어가는 경우에는 묻지 않도록 개선 필요.

**Comment by skywlrl** [comment]
재현 안됨.
가이드 버전이 localStorage에 저장된 상태이면 Popup이 뜨지 않도록 되어 있음.
다시 발생하는 경우에 reopen 하도록 함

**Comment by kimalec** [comment]
맥부기 애플(Apple OS) 개발자 모임 에서 한 사용자가 다시 버그 리포트 하였음.

설정 -> 가이드 보기이동시 도시 선택이 무조건 뜨게 되어있네요
