### ISSUE TITLE
사용자 분석

### ISSUE THREAD

**Issue by skywlrl** [WizardFactory/TodayWeather#958]
설치수에 비해 유지율이 낮은 원인 파악하기
- 에러 상황에 대한 GA 이벤트 추가
- Reload 시 로딩 시간 체크

**Comment by kimalec** [comment]
https://milooy.wordpress.com/2015/05/20/google-analytics-with-utm-parameter/ - UTM Parameter를 달아 링크 유입 분석하기

**Comment by skywlrl** [comment]
**[trackEvent]**
1. app / ua / _ua
2. app / version / _version
4. app / user / new, returning / city count
5. app / status / resume, pause
6. app / account / free, premium (load, update)
7. action / tab / reload, share
8. action / click / open market, send mail
9. data / get / position, native position, daum address, google address, shorten address(city index) / time
10. alarm / set, cancel / address / index
11. city / disable / true, false / 0
12. city / add, delete / address / index
13. category error / …

**[trackView]**
1. toState.name

**[trackTiming]**
1. data / time / get / position, native position, daum address, google address, weather info
2. category error / …

**Comment by kimalec** [comment]
Util.ga.setAllowIDFACollection(true); 부분이 안드로이드에서 에러 나는듯합니다.
iOS용 IDFA와 google용 AAID를 구분해서 사용해야 하나 보네요.

**Comment by skywlrl** [comment]
아래와 같이 위젯 copy를 하면서 android 폴더 안에 설치되어 있는 ga plugin이 복사되어 버전 차이에 의해 API가 없어 에러가 발생하고 있습니다. android 폴더에 있는 ga plugin을 최신으로 업데이트 해주시면 됩니다.
> cp -a ../android platforms/;ionic build android

**Comment by kimalec** [comment]
- [ ] 네트워크 에러 상태 표시 추가 해야 함
