### ISSUE TITLE
딥링크 및 동적링크 만들기

### ISSUE THREAD

**Issue by kimalec** [WizardFactory/TodayWeather#987]
firebase 동적링크는 앱설치 되어 있지 않으면 다운로드페이지로 가고, 설치되어 있으면 딥링크로 간다고함.
좀 더 상세한 내용 확인필요.

http://googledevkr.blogspot.kr/2016/06/introducing-firebase-dynamic-links.html

ionic에서 deeplinking만들기.
http://blog.ionic.io/deeplinking-in-ionic-apps/

추가 필요해보이는 사항.
외부링크로 위치정보나, 도시정보가 날라왔을 때, 날씨를 보여줄 수 있는 시나리오 필요.

**Comment by kimalec** [comment]
동적링크를 생성하기 위해서는 딥링크 먼저 만들어야 함.

**Comment by kimalec** [comment]
아이튠즈는 출처 에서 캠페인용 링크를 생성가능함.

**Comment by skywlrl** [comment]
**[Deep Link 추가 방법]**
- ionic-native 설치

```
$ bower install ionic-native
또는 
bower.json에 "ionic-native": "~1.3.10" 추가
```
- ionic-plugin-deeplinks 설치
```
$ cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=todayweather --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=todayweather.com
```
- index.html에 추가
```
<script src="lib/ionic-native/ionic.native.min.js"></script>
```
- app에서 Deeplink route 추가
```
angular.module('starter', [
    ...,
    'ionic.native'
])
    .run(function($ionicPlatform, Util, $rootScope, $location, WeatherInfo, $state) {
        $ionicPlatform.ready(function() {
            IonicDeeplink.route({
                '/': {
                    target: 'tab.forecast',
                    parent: 'tab.forecast'
                }
            }, function(match) {
                    $state.go(match.$route.parent, match.$args);
            }, function(nomatch) {
                console.warn('No match', nomatch);
            });
```

**Comment by skywlrl** [comment]
[Deep Link 테스트 방법]
- App에서 링크 이동
 1. `cordova.InAppBrowser.open("todayweather://", "_system");` -> App 실행 상태에서 forecast로 이동됨
 2. `cordova.InAppBrowser.open("https://todayweather.com/", "_system");` -> 연결 가능한 App & 브라우저 Apps 선택 팝업 뜸
- Chrome 브라우저를 이용한 html 페이지에서 링크 이동
 1. `<a href="intent://todayweather.com/;scheme=https;package=net.wizardfactory.todayweather;end"> test </a>` -> 이동 안 됨
 2. `<a href="intent://#Intent;scheme=todayweather;package=net.wizardfactory.todayweather;end;">example://gizmos</a>` -> App 실행됨
- QR 코드로 링크 이동
 1. https://firebase.google.com/docs/app-indexing/android/test#---
 2. HTTP URL testing tool에서 `(URL) https://todayweather.com/, (App ID) net.wizardfactory.todayweather` 입력하면 QR 코드 생성됨
 3. QR 코드 리더기로 인식하여 Chrome 앱에서 열어 링크 선택 시 App 실행됨("todayweather://"는 이동 안 됨)

**Comment by skywlrl** [comment]
ionic-plugin-deeplinks 대신 cordova-universal-links-plugin도 지원함
- ionic-native 필요없는 것 같음
- https://github.com/nordnet/cordova-universal-links-plugin

**Comment by kimalec** [comment]
팁링크 생성되면 아래와 같이 넣을 수 있네요.
![2016-09-28 10 06 18](https://cloud.githubusercontent.com/assets/6895272/18897232/4c1a1090-8563-11e6-860d-f50f9601acd8.png)

**Comment by kimalec** [comment]
- [ ] loadcities를 deviceready전에 할 수 있는지 확인하기. @kimalec

**Comment by kimalec** [comment]
loadcities 에 따른 device ready의 속도차이 거의 없었음.
A7모델로 두번 했으며, 다른 모델에서도 추가로 해볼 예정임.
loadcities를 ready전 호출
```
10-18 12:14:54.399 10308-10308/net.wizardfactory.todayweather I/WebViewFactory: Loading com.google.android.webview version 53.0.2785.124 (code 278512400)
10-18 12:14:58.239 10308-10308/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
```
10-18 12:16:46.719 14312-14312/net.wizardfactory.todayweather W/System: ClassLoader referenced unknown path: /data/app/net.wizardfactory.todayweather-1/lib/arm
10-18 12:16:50.889 14312-14312/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
loadCities를 deviceready후 호출
```
10-18 12:20:33.329 19583-19583/net.wizardfactory.todayweather W/System: ClassLoader referenced unknown path: /data/app/net.wizardfactory.todayweather-2/lib/arm
10-18 12:20:37.509 19583-19583/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
```
10-18 12:22:51.459 25675-25675/net.wizardfactory.todayweather W/System: ClassLoader referenced unknown path: /data/app/net.wizardfactory.todayweather-1/lib/arm
10-18 12:22:55.629 25675-25675/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```

**Comment by kimalec** [comment]
SS S3
loadCities in deviceready
```
10-18 12:35:38.015 13176-13176/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-18 12:35:42.690 13176-13176/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
```
10-18 12:38:00.255 16002-16002/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-18 12:38:04.755 16002-16002/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
loadCities out device ready
```
10-18 12:40:36.235 17380-17380/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-18 12:40:42.885 17380-17380/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```
```
10-18 12:43:29.050 19980-19980/net.wizardfactory.todayweather I/dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
10-18 12:43:36.210 19980-19980/net.wizardfactory.todayweather I/chromium: [INFO:CONSOLE(21)] "device ready!!", source: file:///android_asset/www/js/app.js (21)
```

**Comment by kimalec** [comment]
loadCities는 밖으로 빼도 되요. 딥링크 추가하시면서 빼주세요.

**Comment by kimalec** [comment]
삼성 S3기준
deviceready내에서 loadCities를 하면 10회동안 5초 넘어선 적이 없으며, 대부분 4.5초에 종료됨.
loadCities를 deviceready전에 하면 4번에 2번이 5초를 넘어섬.

[loadCities_out_deviceready.log.zip](https://github.com/WizardFactory/TodayWeather/files/535331/loadCities_out_deviceready.log.zip)

5초를 넘더라도, 타임아웃 에러가 발생하지는 않지만  **loadCities를 deviceready전에 실행하는건 위험해보입니다.**
https://github.com/WizardFactory/TodayWeather/issues/1130#issuecomment-250384075

**Comment by skywlrl** [comment]
https://forum.ionicframework.com/t/best-way-to-show-first-view-dynamically-when-starting-app/16423/9

**Comment by kimalec** [comment]
http://stackoverflow.com/questions/27300583/how-to-deviceready-in-right-way-in-ionic-application

**Comment by skywlrl** [comment]
[소모임 앱에서 딥 링크 사용 예제]
http://open.friendscube.com/g/a3176646-0704-11e6-bae7-22000aac80141
